### ISSUE TITLE
Add check format compatibility button in deck editor

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#4244] opened 2017-12-14 00:18 UTC
It's will be good to have "check format compatibility" button in deck editor. Like "import" dialog:
 - combobox with formats list to check (see format list in match settings);
 - "check" button to start checking process;
 - memo field with results (show OK message or list of all wrong cards);
 - optional: move wrong cards to sideboard column (no need to search it manually);

Window example:
![shot_171214_041737](https://user-images.githubusercontent.com/8344157/33969269-c138bff6-e085-11e7-8606-4311e06d7cb7.png)

**Comment by Zerrisx** [comment] 2020-07-01 19:26
Duplicate of #4784 - marking this as the duplicate, since that seems to have work actively being done on it.

**Closed by Zerrisx** 2020-07-01 19:26 UTC
Labels: GUI, enhancement
