### ISSUE TITLE
Azor Lawbringer ETB effect when brought into play during opponents turn

### ISSUE THREAD

**Issue by Rewyn** [magefree/mage#5139] opened 2018-07-10 19:43 UTC
Azor Lawbringer already prevents other from casting instants or sorceries the turn he comes into play, instead starting at the next turn.
Example: Used Living Death, while I had a Diluvian Primordial and an opponent had Azor Lawbringer in his grave, preventing me from casting any spells off of Diluvian Primordial.
I was, however, able to cast instants and sorceries my actual next turn just fine.
Edit: Welp, should've searched for open issues first. My bad.

**Comment by Zerrisx** [comment] 2020-07-10 16:47
Duplicate of #4570

**Closed by Zerrisx** 2020-07-10 16:47 UTC
