### ISSUE TITLE
Adriana, Captain of the Guard not triggering

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10170] opened 2023-04-04 04:06 UTC
As per the screenshot: melee is not triggering at all.

![image](https://user-images.githubusercontent.com/82664393/229684568-d5736ef7-68d9-4a51-a206-2e1646ef7961.png)

**Comment by Grath** [comment] 2023-04-04 04:21
Duplicate of #9848 (also the screenshot clearly shows it IS triggering, but it's not actually pumping creatures.)

**Closed by Grath** 2023-04-04 04:21 UTC
