### ISSUE TITLE
Bottom Scroll Bar Issue

### ISSUE THREAD

**Issue by rromoli** [magefree/mage#6081] opened 2019-12-09 13:47 UTC
Hi, I'm using xmage 1.4.40v1a and I get a graphical issue related to the scroll
bar on the bottom of the hand cards area. I run debian buster and the screen
resolution in 1399x768. I read about this problem in a post for a previous
version but the solution is not applicable to the current version of xmage 
(https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=13632#p162924).

Hope you can help me

**Comment by JayDi85** [comment] 2019-12-09 14:14
Try to change window size (there are bugs with missing scrollbar in some window sizes). If not help then try to change hand and card sizes in preferences (make it small).

**Comment by rromoli** [comment] 2019-12-10 09:17
I can't resize the window in vertical because xmage do not let me do this; I have already changed the size of each element as small as possible but the bottom scrollbar is still hide

**Comment by JayDi85** [comment] 2019-12-10 09:38
There are bugs from 786 to 831 window's height in Windows systems (missing horizontal scrollbar). But works fine from 767 to 785.

Here example of my settings (look at hand size):
![shot_191210_133111](https://user-images.githubusercontent.com/8344157/70517091-7bb54680-1b51-11ea-8cf1-dea8ff79f77d.png)
![shot_191210_132957](https://user-images.githubusercontent.com/8344157/70517102-7f48cd80-1b51-11ea-8a76-eda386861cff.png)

Try that settings. If not helps then try that lifehack to change hand size under minimum:
1. Use [that instructions](https://github.com/magefree/mage/issues/4461#issuecomment-361108597) to find and edit xmage settings;
2. Find `gui/Card/Hand/Size` setting and change it to 5 or any other size (10 is minimum value from GUI dialog):
![shot_191210_133400](https://user-images.githubusercontent.com/8344157/70517606-3cd3c080-1b52-11ea-9339-fc5bc32275cd.png)
3. Test it:
![shot_191210_133455](https://user-images.githubusercontent.com/8344157/70517625-45c49200-1b52-11ea-90b0-ac5478219978.png)

**Comment by rromoli** [comment] 2019-12-10 11:29
I lowered the hand size so I can see al the cards in may hand but I still don't see the scrolbar.. I there a way to change the dimension of the window such as the card size?

**Comment by JayDi85** [comment] 2019-12-10 12:10
Nope, it's depends on window height only (game panel height). You can try only that:
a. Make window mode, increase window size more than your resolution;
b. Increase virtual screen resolution;
c. Use window manager with non caption/borderless/full screen mode for applications.

**Comment by rromoli** [comment] 2019-12-10 13:25
I will try using `wmctrl` as a workaround and I will let you to know. Is there a way to make this bug will be fixed in a following version?

**Comment by JayDi85** [comment] 2019-12-10 13:29
Maybe. I'm working on bug fix, but it's not easy (new resolution limit do not help).

**Comment by Zerrisx** [comment] 2020-07-14 05:39
Duplicate of #5605

**Closed by Zerrisx** 2020-07-14 05:39 UTC
Labels: GUI
