### ISSUE TITLE
AI: Sword of Fire and Ice inflicts damage to own creatures

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#6341] opened 2020-03-11 13:14 UTC
Only opponent creatures should be targeted by the damaging effect.

**Comment by luziferius** [comment] 2020-03-15 14:56
> Only opponent creatures should be targeted by the damaging effect.

Unless the own creatures have beneficial Enrage triggers and preferably don’t die on damage resolution.

**Comment by Zerrisx** [comment] 2020-07-14 16:13
Duplicate of #6838

**Closed by Zerrisx** 2020-07-14 16:13 UTC
Labels: AI
