### ISSUE TITLE
Sakashima throws an exception when enters targeting SpellStutter Sprite

### ISSUE THREAD

**Issue by Alexsandr0x** [magefree/mage#2937] opened 2017-03-06 19:30 UTC
I was playing Modern when this happened:
PlayerA has Spellstutter Sprite in play.
PlayerB casts Sakashima Impostor targeting SpellStutter.

The game shows an error.
I was able to replicate this in an unit test in [this link](https://github.com/Alexsandr0x/mage/blob/sakashima-bug/Mage.Tests/src/test/java/org/mage/test/cards/abilities/other/SakashimaTheImpostorTest.java#L13).

I'am not familiar with Xmage code but I think the effect is trying to get a target spell, even this doesn't exist in stack. So maybe after Sakashima copy the player could target a spell? or just ignore the Spellstutter effect?

I tried with Spell Queller (since this card has a similiar ability) but the exception doesn't appear.

StackTrace:
```
java.lang.NullPointerException
	at mage.cards.s.SpellstutterSpriteCounterTargetEffect.apply(SpellstutterSprite.java:129)
	at mage.abilities.AbilityImpl.resolve(AbilityImpl.java:186)
	at mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:101)
	at mage.game.stack.StackAbility.resolve(StackAbility.java:107)
	at mage.game.GameImpl.resolve(GameImpl.java:1340)
	at mage.game.GameImpl.playPriority(GameImpl.java:1291)
	at mage.game.turn.Step.priority(Step.java:87)
	at mage.game.turn.Phase.playStep(Phase.java:210)
	at mage.game.turn.Phase.play(Phase.java:115)
	at mage.game.turn.Turn.play(Turn.java:152)
	at mage.game.GameImpl.playTurn(GameImpl.java:820)
	at mage.game.GameImpl.play(GameImpl.java:729)
	at mage.game.GameImpl.start(GameImpl.java:693)
	at org.mage.test.serverside.base.impl.CardTestPlayerAPIImpl.execute(CardTestPlayerAPIImpl.java:185)
	at org.mage.test.cards.abilities.other.SakashimaTheImpostorTest.copySpellStutterTest(SakashimaTheImpostorTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
FATAL [2017-03-06 16:35 [53:622]] GameImpl[main]: Game exception 
```

**Comment by drmDev** [comment] 2017-03-06 19:45
Looking at the `apply` overriden code for Spellstutter Sprite compared to SpellQueller...

SpellstutterSprite.java:
```
        int numberFaeries = game.getState().getBattlefield().countAll(SpellstutterSprite.filter, source.getControllerId(), game);
        StackObject stackObject = game.getStack().getStackObject(source.getFirstTarget());
        if (stackObject.getConvertedManaCost() <= numberFaeries) {
            if (game.getStack().counter(source.getFirstTarget(), source.getSourceId(), game)) {
                return true;
            }
        }
        return false;
```

SpellQueller.java
```
        Player controller = game.getPlayer(source.getControllerId());
        MageObject sourceObject = source.getSourceObject(game);
        if (controller != null && sourceObject != null) {
            Spell spell = game.getStack().getSpell(getTargetPointer().getFirst(game, source));
            if (spell != null) {
                UUID exileId = CardUtil.getExileZoneId(game, source.getSourceId(), source.getSourceObjectZoneChangeCounter());
                return controller.moveCardsToExile(spell, source, game, true, exileId, sourceObject.getIdName());
            }
            return true;
        }
        return false;
```

I would add in some of the same checks as SpellQueller does and change how the spell is retrieved then see if the issue is still occurring. Should resolve the issue. Otherwise it's in SpellstutterSprite `adjustTargets` override. 

Also, put up your Unit Test and changes made in a PR so we can review and merge them in. Thanks for your contributions!

**Comment by drmDev** [comment] 2017-03-07 21:10
resolved with your commit!

**Closed by drmDev** 2017-03-07 21:10 UTC
Labels: bug
