### ISSUE TITLE
Exile window cannot be closed

### ISSUE THREAD

**Issue by kohldampfer** [magefree/mage#4155] opened 2017-11-10 00:01 UTC
During the game, my AI opponent exiles a creature from my battlefield with [Path to exile](https://magiccards.info/cma/en/19.html). A new small windows opens, where I can see, which card the my opponent exiled this way (see the picture).

![xmage-exile-window](https://user-images.githubusercontent.com/20419801/32635859-51181868-c5b2-11e7-9843-c422520c763e.png)

Now, I cannot close this window anymore. Even if I clicked on **Done** after the exile part. So this window lies now somewhere on my screen. The best thing I can do now is minimizing this window and move it anywhere. For me this solution is not the best one. I think it would be good, if this window can be closed after the whole exile part is over.

**Comment by JayDi85** [comment] 2017-11-11 23:46
I think error in that code lines (devs forgot to add `this.setClosable(true);`):
https://github.com/magefree/mage/blob/cf831eea2873aee7ee4bcdb0ef2cf4213bf5220b/Mage.Client/src/main/java/mage/client/dialog/CardInfoWindowDialog.java#L108-L110

I can't test that now. Maybe other devs can.

**Comment by JayDi85** [comment] 2017-11-12 00:47
Found another bug with that window: all exiled cards from both players collected in one window, but it must collected in different like graveyard do.

**Comment by JayDi85** [comment] 2017-11-24 15:08
Duplicate of #1115

**Closed by JayDi85** 2017-11-24 15:08 UTC
