### ISSUE TITLE
Voting / Kick / Admin tools needed 

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#6858] opened 2020-07-18 20:26 UTC
Below is a screenshot of a player who would pass priority after whole minutes have passed, his turn and the two players before me seemed to go completely lag free, but as soon as I attacked him on my turn then the passing of priority became whole minutes, (my start of combat to his 1st main took approximately 45 mins of that players timer) you can see the time disparity in the below screenshot, we all refused to leave as we assumed from the context of the game that he was doing it deliberately:
![image](https://user-images.githubusercontent.com/64497504/87861218-21c4fc80-c93c-11ea-8adc-64581e40e1eb.png)

**Comment by JayDi85** [comment] 2020-07-18 20:35
Users vote system feature: #6329

**Comment by Zerrisx** [comment] 2020-07-29 17:35
Duplicate of #6329

**Closed by Zerrisx** 2020-07-29 17:35 UTC
