### ISSUE TITLE
Players leaving the game at certain times can lock up the game

### ISSUE THREAD

**Issue by ngenisis** [magefree/mage#1597] opened 2016-03-06 04:15 UTC
Sometimes when a player concedes or loses connection while another player is in the process of casting or resolving a spell affecting that player or his or her permanents, it will lock up the client. For example, I cast Force of Will targeting a player's spell. While it was asking me if I wanted to cast it using its alternate cost, that spell's controller conceded. Instead of my Force of Will fizzling upon resolution for an illegal target, the client just locked up and didn't let anyone do anything. 

I've even had the client lock up when a spectator lost connection.

**Comment by drmDev** [comment] 2017-06-07 04:37
Unsure if problem still persisting since this was over a year ago

**Comment by Zerrisx** [comment] 2020-07-01 21:56
If this still happens, likely a duplicate of #2423

**Closed by Zerrisx** 2020-07-01 21:56 UTC
Labels: bug, not confirmed
