### ISSUE TITLE
NPE when playing Isochron Scepter with the new auto-choose targets feature

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#9256] opened 2022-07-12 04:59 UTC
```
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.51-V4-beta7 (build: 2022-07-09 15:21)
mage.target.TargetImpl.tryToAutoChoose(TargetImpl.java:665)
mage.player.human.HumanPlayer.choose(HumanPlayer.java:730)
mage.cards.i.IsochronScepterImprintEffect.apply(IsochronScepter.java:84)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:201)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:185)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:149)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1618)
mage.game.GameImpl.playPriority(GameImpl.java:1544)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```
[[Isochron Scepter]]

Happens when the ability resolves, after clicking "yes". Only happens when set to "most" and there is only a single valid target.

**Comment by Alex-Vasile** [comment] 2022-07-12 12:26
Duplicate of #9248

**Closed by Alex-Vasile** 2022-07-12 12:26 UTC
