### ISSUE TITLE
Sen Triplets still does not allow playing cards from opponents' hands

### ISSUE THREAD

**Issue by Grath** [magefree/mage#8001] opened 2021-07-11 19:21 UTC
Steps to reproduce:
1. Play Sen Triplets (in this case, from the command zone)
2. Choose an opponent
3. Click on anything from their revealed hand, several things of which are highlighted as though they should be playable.
4. Nothing happens.

**Comment by alexander-novo** [comment] 2021-07-11 19:48
Hey @Grath, a previous issue was just closed with a fix (#7116). The commit was merged into master 4 days ago and the latest beta was built on 07/08, so there's a possibility that whoever built it wasn't entirely up to date (I'm not familiar with the build process). Try waiting until the next beta release (which should be soon with all of the new AFR cards) and check to see if it's still broken.

**Comment by JayDi85** [comment] 2021-07-11 20:15
Current beta have that fixes.

**Comment by Grath** [comment] 2021-07-11 20:22
Yes, it's still bugged in the current beta. This is why I'm complaining again. You may recognize me as the person who opened #7068 that was allegedly fixed (but there's no visible difference in the behavior as far as I can tell as an end user.) I was very excited to finally be able to play that Commander deck again after ten months of the bugged behavior.

**Comment by jeffwadsworth** [comment] 2021-07-12 00:57
I can confirm that Sen Triplets does not work in the latest build.

**Comment by theelk801** [comment] 2021-07-13 02:24
not sure why this is still broken, I wrote tests for it when I fixed it

**Comment by Grath** [comment] 2021-07-13 03:45
> not sure why this is still broken, I wrote tests for it when I fixed it

Everything correctly indicates what should be playable, lands and cards you have the mana for and all that, but something about the actual act of clicking on the card from the opponent's revealed hand doesn't actually play the card. If I had to guess at this point, it might be a UI bug somehow rather than a functional one.

**Comment by jeffwadsworth** [comment] 2021-07-13 12:57
All things point to a UI issue because, as mentioned, the playable cards are highlighted, etc.  But you can't click on them to play/cast.

**Comment by JayDi85** [comment] 2021-07-13 14:16
I'll look at it.

**Comment by jeffwadsworth** [comment] 2021-07-22 02:28
It looks like the issue is in PlayerImpl.  The playable list gets populated with the "abilities", but it never fires play or cast when the cards are selected.  Who knows.

**Comment by jeffwadsworth** [comment] 2021-07-25 01:23
The fix for this was embarrassingly simple.

**Closed** 2021-07-25 01:59 UTC
Labels: bug

**Comment by JayDi85** [comment] 2021-07-25 05:42
Strange fix. If it works then original problem was in reveal effect -- it doesn't work correctly (well, xmage cleans revealed cards on each priority, so it must be refreshed by card's effect all the time). Opponents hand's cards must be revealed all the time, so game must see it in revealed list, not from hand (hand visible to owner only). I'll look at it later.

**Comment by jeffwadsworth** [comment] 2021-07-25 12:41
Regardless of reveal, the hand zone was missing from the check in getPlayable().

**Comment by JayDi85** [comment] 2021-07-25 17:51
Cause you can't play cards from oppoent's hand without reveal or move to public/own zone.

**Comment by jeffwadsworth** [comment] 2021-07-25 20:04
Let me get this straight.  Are you saying that the code is not supposed to check the zone for the “PlayFromNotYourOwnHand” effect?  A revealed card is not automatically playable.  Perhaps you have a specific example?

**Comment by JayDi85** [comment] 2021-07-26 02:39
I mean mtg rules doesn't allows to play card without reveal it to you. All "play from non hand" use cases instructs player to reveal/move/put/etc card before play. You can't see opponent's hand in normal use cases (without control), so you can't activate card in that hand.

**Comment by JayDi85** [comment] 2021-08-20 11:57
Related bug that was discovered after turning on the opponent hand check -- suspend ability was able to activate from the opponent's hand (fixed in 9fa487e60aaf8dad14d2b0c715033651f671bf3f).
