### ISSUE TITLE
game error trying to create token in beta released today

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#9568] opened 2022-09-24 23:34 UTC
YI try to cast my commander [[Ghired, Conclave Exile]] and got this error

![image](https://user-images.githubusercontent.com/4504719/192122203-d748ff23-7ba3-407b-af1c-624fbb3d2cee.png)

```
Game exception occurred: java.lang.ClassCastException: mage.game.permanent.PermanentToken cannot be cast to mage.game.permanent.token.Token
Server version: 1.4.52-V1-beta4 (build: 2022-09-24 06:33)
mage.watchers.common.CreatedTokenWatcher.watch(CreatedTokenWatcher.java:34)
mage.watchers.Watchers.watch(Watchers.java:34)
mage.game.GameState.handleEvent(GameState.java:817)
mage.game.GameState.handleSimultaneousEvent(GameState.java:792)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:226)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:185)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:149)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1634)
mage.game.GameImpl.playPriority(GameImpl.java:1560)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1055)
mage.game.GameImpl.play(GameImpl.java:965)
mage.game.GameImpl.start(GameImpl.java:941)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

```

**Comment by copperfield42** [comment] 2022-09-24 23:39
furthermore, it also crash on AI turn playing the [[The Locust God]] trying to create its token
![image](https://user-images.githubusercontent.com/4504719/192122341-2fe0031b-f710-4b43-ae90-e0239802820b.png)

```
Game exception occurred: java.lang.ClassCastException: mage.game.permanent.PermanentToken cannot be cast to mage.game.permanent.token.Token
Server version: 1.4.52-V1-beta4 (build: 2022-09-24 06:33)
mage.watchers.common.CreatedTokenWatcher.watch(CreatedTokenWatcher.java:34)
mage.watchers.Watchers.watch(Watchers.java:34)
mage.game.GameState.handleEvent(GameState.java:817)
mage.game.GameState.handleSimultaneousEvent(GameState.java:792)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:226)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:185)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:149)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1634)
mage.game.GameImpl.playPriority(GameImpl.java:1560)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1055)
mage.game.GameImpl.play(GameImpl.java:965)
mage.game.GameImpl.start(GameImpl.java:941)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

```

**Comment by awjackson** [comment] 2022-09-25 00:26
Duplicate of #9562

**Closed by awjackson** 2022-09-25 00:26 UTC
Labels: duplicate
