### ISSUE TITLE
I think I cast Astral Cornucopia and accidentally payed for it with Tamiyo, Field Researcher's Emblem

### ISSUE THREAD

**Issue by aemilstark** [magefree/mage#7015] opened 2020-08-27 19:15 UTC
I think I cast Astral Cornucopia and accidentally payed for it with Tamiyo, Field Researcher's Emblem

> Game exception occurred: java.util.ConcurrentModificationException
> Server version: 1.4.45V0 (build: 2020-08-22 22:18)
> java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
> java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
> java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
> java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
> java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
> java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
> java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
> mage.abilities.AbilitiesImpl.containsKey(AbilitiesImpl.java:275)
> mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:372)
> mage.abilities.effects.common.continuous.GainAbilityControlledEffect.apply(GainAbilityControlledEffect.java:115)
> mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:102)
> mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1044)
> mage.game.GameState.applyEffects(GameState.java:595)
> mage.game.GameImpl.applyEffects(GameImpl.java:1534)
> mage.players.PlayerImpl.moveCards(PlayerImpl.java:4082)
> mage.players.PlayerImpl.moveCards(PlayerImpl.java:4026)
> mage.game.stack.Spell.resolve(Spell.java:296)
> mage.game.GameImpl.resolve(GameImpl.java:1408)
> mage.game.GameImpl.playPriority(GameImpl.java:1355)
> mage.game.turn.Step.priority(Step.java:61)
> mage.game.turn.Phase.playStep(Phase.java:184)
> mage.game.turn.Phase.play(Phase.java:89)
> mage.game.turn.Turn.play(Turn.java:126)
> mage.game.GameImpl.playTurn(GameImpl.java:877)
> mage.game.GameImpl.play(GameImpl.java:791)
> mage.game.GameImpl.start(GameImpl.java:776)
> mage.server.game.GameWorker.call(GameWorker.java:34)
> java.util.concurrent.FutureTask.run(FutureTask.java:266)
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> java.lang.Thread.run(Thread.java:748)

**Comment by LevelX2** [comment] 2020-12-28 14:27
Duplicate of #7170.

**Closed** 2020-12-28 14:27 UTC
