### ISSUE TITLE
Server's Error: Offset Out of Bounds

### ISSUE THREAD

**Issue by abrahamdrinkin** [magefree/mage#9023] opened 2022-05-28 15:28 UTC
Ever since the beta updated with the first half of New Capenna cards, I've been noticing the error message Server Error Offset Out of Bounds. This happens when I, search my library, crack a treasure, tap a land and have to choose between 5 colors of mana, or name something when prompted (Cavern of Souls, choose a creature type), or choose a color with Carpet of Flowers. When it comes to choosing a name or color of many among 5 options, the game seems to crash and I cannot progress forward. Despite having the error pop up when I search my library, I am able to progress forward in the game, with the other issues, its a dead stop until the game times out. Anyone have any answers?

**Comment by JayDi85** [comment] 2022-05-28 16:12
Try to increase max memory limits for server and client in the launcher (move over memory stats on main menu to see details and instructions -- apply it for both server and client options).

**Comment by Alex-Vasile** [comment] 2022-05-28 17:59
Duplicate of #8836.

**Comment by Alex-Vasile** [comment] 2022-07-07 12:42
Closing duplicate, keep an eye on linked issue.

**Closed by Alex-Vasile** 2022-07-07 12:42 UTC

**Comment by Alex-Vasile** [comment] 2022-07-17 00:41
@abrahamdrinkin When you were having these issues, were you playing against the AI?

**Comment by abrahamdrinkin** [comment] 2022-07-17 00:56
@Alex-Vasile yes. The only mode I play is where I have experienced this issue, in 4 player free for all with me against 3 other AI.

**Comment by Alex-Vasile** [comment] 2022-07-17 01:01
> @Alex-Vasile yes. The only mode I play is where I have experienced this issue, in 4 player free for all with me against 3 other AI.

Do you happen to remember if any of them was playing Edgar Markov?

**Comment by abrahamdrinkin** [comment] 2022-07-17 01:07
> > @Alex-Vasile yes. The only mode I play is where I have experienced this issue, in 4 player free for all with me against 3 other AI.
> 
> Do you happen to remember if any of them was playing Edgar Markov?

@Alex-Vasile yes! That is one of the decks I use for the AI. As well as, Atraxa, Ur Dragon, Syr Gwyn, and Esika. I have used Maelstrom Wanderer but I do not let the AI use Wanderer.

**Comment by Alex-Vasile** [comment] 2022-07-17 01:32
> > > @Alex-Vasile yes. The only mode I play is where I have experienced this issue, in 4 player free for all with me against 3 other AI.
> > 
> > 
> > Do you happen to remember if any of them was playing Edgar Markov?
> 
> @Alex-Vasile yes! That is one of the decks I use for the AI. As well as, Atraxa, Ur Dragon, Syr Gwyn, and Esika. I have used Maelstrom Wanderer but I do not let the AI use Wanderer.

Perfect! Then I fixed this in 420b6f1a74590b5126a5525fdb86d8e4f70916dd. Wait for the next beta update to fix the issue.

**Comment by abrahamdrinkin** [comment] 2022-07-17 01:42
> > > > @Alex-Vasile yes. The only mode I play is where I have experienced this issue, in 4 player free for all with me against 3 other AI.
> > > 
> > > 
> > > Do you happen to remember if any of them was playing Edgar Markov?
> > 
> > 
> > @Alex-Vasile yes! That is one of the decks I use for the AI. As well as, Atraxa, Ur Dragon, Syr Gwyn, and Esika. I have used Maelstrom Wanderer but I do not let the AI use Wanderer.
> 
> Perfect! Then I fixed this in [420b6f1](https://github.com/magefree/mage/commit/420b6f1a74590b5126a5525fdb86d8e4f70916dd). Wait for the next beta update to fix the issue.

@Alex-Vasile You’re a god amongst men. Thank you for your time in this. I’ve never finally contributed but now I feel compelled. It’s a drop in the ocean compared to all the goings on around the world, but truly, I thank you.

**Comment by Alex-Vasile** [comment] 2022-07-17 02:07
> > > > > @Alex-Vasile yes. The only mode I play is where I have experienced this issue, in 4 player free for all with me against 3 other AI.
> > > > 
> > > > 
> > > > Do you happen to remember if any of them was playing Edgar Markov?
> > > 
> > > 
> > > @Alex-Vasile yes! That is one of the decks I use for the AI. As well as, Atraxa, Ur Dragon, Syr Gwyn, and Esika. I have used Maelstrom Wanderer but I do not let the AI use Wanderer.
> > 
> > 
> > Perfect! Then I fixed this in [420b6f1](https://github.com/magefree/mage/commit/420b6f1a74590b5126a5525fdb86d8e4f70916dd). Wait for the next beta update to fix the issue.
> 
> @Alex-Vasile You’re a god amongst men. Thank you for your time in this. I’ve never finally contributed but now I feel compelled. It’s a drop in the ocean compared to all the goings on around the world, but truly, I thank you.

Thank you for the kind words!

As for contributing, there are many ways to contribute. Even playing and reporting every bug you find, no matter how small, is of great help. As well as things you find annoying (e.g. #8879)
