### ISSUE TITLE
Deck Editor 1.4.52-V5 error, cannot add and/or save decks

### ISSUE THREAD

**Issue by mtuc878** [magefree/mage#11112] opened 2023-09-05 04:29 UTC
Hello!

Would like to ask for some help figuring out my issue, please.

Since the latest update I am having some issues with the Deck Editor. I will list the things that I have noticed:

- Deck Editor does not open on the first click (loading symbol appears), but opens on the 2nd click
- Cannot add cards to a new or loaded deck
- Appears to be able to remove cards, but saving the deck does not actually save. Reloading deck does not show changes made.
- None of the buttons in the bottom left of the card database (add/remove from main/side) work.
- Double clicking cards does not do the action selected

Upon starting the jar launcher:

`WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.`

Initial error log upon clicking Deck Editor for the first time:
```
FATAL 2023-09-05 00:20:42,227 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at mage.client.deckeditor.table.MageCardComparator.compare(MageCardComparator.java:82)
	at mage.client.deckeditor.table.MageCardComparator.compare(MageCardComparator.java:15)
	at java.util.TimSort.binarySort(TimSort.java:296)
	at java.util.TimSort.sort(TimSort.java:239)
	at java.util.Arrays.sort(Arrays.java:1512)
	at java.util.ArrayList.sort(ArrayList.java:1462)
	at mage.client.deckeditor.table.TableModel.sort(TableModel.java:413)
	at mage.client.deckeditor.table.TableModel.loadCards(TableModel.java:182)
	at mage.client.deckeditor.CardSelector.filterCards(CardSelector.java:496)
	at mage.client.deckeditor.CardSelector.loadCards(CardSelector.java:227)
	at mage.client.deckeditor.DeckEditorPanel.showDeckEditor(DeckEditorPanel.java:253)
	at mage.client.deckeditor.DeckEditorPane.show(DeckEditorPane.java:57)
	at mage.client.MageFrame.showDeckEditor(MageFrame.java:1231)
	at mage.client.MageFrame.btnDeckEditorActionPerformed(MageFrame.java:1057)
	at mage.client.MageFrame.access$900(MageFrame.java:86)
	at mage.client.MageFrame$8.actionPerformed(MageFrame.java:942)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I have attempted to delete the XMage folder where I installed from the .jar package and then reinstall, no change.

**Comment by xenohedron** [comment] 2023-09-14 04:09
See #11157 for root cause. Workaround applied in 4a53ca5 so will be fixed in next release.

**Closed by xenohedron** 2023-09-14 04:09 UTC
Labels: bug, support
