### ISSUE TITLE
Issue with countering copies of a spell

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#1159] opened 2015-07-29 00:00 UTC
I cast Tendrils of Agony with storm = 3. In response to the Storm trigger, my opponent counters the original spell with a Counterspell. After the 3 copies are put on the stack, my opponent casts Force of Will targeting one of the copies. The Force resolves correctly according to the chat, but the copy stays on the stack and will end up resolving normally.

There were 2 Rest in Peace on the battlefield, which may cause issue with replacement effects.

**Comment by emerald000** [comment] 2016-02-08 03:04
The issue also occurred with Replicate on a Gigadrowse with nothing relevant on the battlefield. Opponent casts a Dispel on a copy, which resolves and does nothing. Chat said it was countered but the copy stayed on the stack.

I also remember a similar thing happening with a Hive Mind copy, but I am not 100% sure.

**Comment by drmDev** [comment] 2016-07-25 11:25
Is this issue still occurring? There was a commit a little while ago that should have addressed countering copies of spells:
https://github.com/magefree/mage/commit/95b2d76ab1b25b1a1c5cd7b96661253c8e1c953f

**Comment by drmDev** [comment] 2016-07-30 01:30
will test

**Comment by goesta** [comment] 2017-03-03 22:29
@drmDev can we close this?

**Comment by drmDev** [comment] 2017-03-03 22:32
Sorry I haven't been active on this project for a while. Last I recall this one was difficult to test due to issues with the testing API handling targeting differently than in game behavior.

**Comment by JRHerlehy** [comment] 2017-03-04 08:25
Last I remember trying to look into this (within the last 2 months) there was still issues with say a flusterstorm each targeting a different copy of tendrils not countering more than the original spell.

**Comment by Zerrisx** [comment] 2020-05-18 00:46
Cannot reproduce; this appears to be fixed.

**Closed** 2020-06-11 21:26 UTC
Labels: bug, not confirmed
