### ISSUE TITLE
Omenkeel bug in Commander games

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7503] opened 2021-02-04 20:53 UTC
omenkeel triggers twice when it hits an opponent, exiling 6 cards instead of 3.

**Comment by weirddan455** [comment] 2021-02-04 23:29
Not able to reproduce this.  I'm only seeing 3 exiled cards.  Omenkeel does trigger " Whenever a Vehicle you control deals combat damage to a player", not just off itself.  Was there another vehicle attacking?

**Comment by ignitaxiom** [comment] 2021-02-04 23:37
just onemkeel. i'll try it again


________________________________

**Comment by ignitaxiom** [comment] 2021-02-04 23:49
all of the mdfc commanders seem to trigger twice

**Comment by weirddan455** [comment] 2021-02-05 00:01
Oh, you didn't mention it was in commander.  Probably related to #7501

**Comment by JayDi85** [comment] 2021-02-06 06:52
Fixed by ac98a3a31ae96372302a71f9dc737ae5e4522c07

**Closed by JayDi85** 2021-02-06 06:52 UTC
Labels: bug
