### ISSUE TITLE
Errors going to time during tournament

### ISSUE THREAD

**Issue by Xlblaze** [magefree/mage#1927] opened 2016-05-07 19:32 UTC
Player wins 1st round of draft as opps time runs out, 
This is the last game playing so the winners next round starts
But his skips are still set cant be cancled and dont stop work play can not do anything only conceed
and the players timer starts the point it ended last game in this case 2:00 minutes

**Comment by Zerrisx** [comment] 2020-05-18 21:41
Duplicate of #683

**Closed** 2020-06-24 20:14 UTC
