### ISSUE TITLE
Vengeful Ancestor Goad Error

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#9024] opened 2022-05-28 16:17 UTC
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.51-V4-beta4 (build: 2022-05-27 05:58)
mage.designations.InitiativeDamageTriggeredAbility.checkTrigger(Initiative.java:64)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:94)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:55)
mage.game.GameState.handleEvent(GameState.java:819)
mage.game.GameState.handleSimultaneousEvent(GameState.java:792)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:226)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:185)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:149)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1646)
mage.game.GameImpl.playPriority(GameImpl.java:1572)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1070)
mage.game.GameImpl.play(GameImpl.java:980)
mage.game.GameImpl.start(GameImpl.java:956)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Alex-Vasile** [comment] 2022-05-29 17:45
[[Vengeful Ancestor]]

**Comment by Alex-Vasile** [comment] 2022-05-29 18:16
Duplicate of #9010

**Closed by Alex-Vasile** 2022-05-29 18:16 UTC
Labels: bug
