### ISSUE TITLE
Vindictive Lich issue

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#3895] opened 2017-08-28 18:13 UTC
From Discord:
"Vindictive Live (C17) after it died in combat, it gave me the option to chose which effects i want and which effect target which player, but nothing happend after i selected it.
so noone throw cards away, noone lost life and noone had to sacrifice a creature"

**Comment by Zzooouhh** [comment] 2017-12-12 14:38
I should note that this happened to me in a game where Vindictive Lich died and I had two opponents. Maybe it fizzles on less than three opponents?

**Comment by Zerrisx** [comment] 2020-06-28 18:49
Duplicate of #4742

**Closed by Zerrisx** 2020-06-28 18:49 UTC
