### ISSUE TITLE
The AI destroys its own permanents with Beast Within

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#5775] opened 2019-05-02 02:48 UTC
For the majority of games when the AI uses Beast Within, it will use it to destroy its own land, even if I or any other player has any other permanent that would be more advantageous for the AI to destroy.

In a similar fashion, it uses Song of the Dryads on its own cards.

**Comment by Zerrisx** [comment] 2020-07-14 16:12
Duplicate of #6838

**Closed by Zerrisx** 2020-07-14 16:12 UTC
Labels: AI
