### ISSUE TITLE
Gadrak, the Crown-Scourge can attack when I control only one artifact

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#6743] opened 2020-06-29 01:09 UTC
![Capture](https://user-images.githubusercontent.com/16656302/85963414-9501d100-b983-11ea-9f79-879a85976903.PNG)

At no point in this game have I controlled more than a single artifact. I currently control 1.

**Comment by Zerrisx** [comment] 2020-06-29 01:31
Duplicate of #6646

**Closed** 2020-06-29 13:02 UTC
