### ISSUE TITLE
Card Rules Bug: Living death + Syr Konrad

### ISSUE THREAD

**Issue by mrf1shie** [magefree/mage#6385] opened 2020-03-30 14:47 UTC
Currently, casting living death with syr konrad in the graveyard will trigger his 'whenever a creature leaves your graveyard' ability. This should not work as he will enter from exile with the rest of the graveyard and not see creatures leaving the graveyard.

**Comment by Zerrisx** [comment] 2020-07-15 19:45
...Weirdly, I can't reproduce this with Living Death... but I *can* reproduce it with Living End, which should have the exact same effect.

**Comment by mrf1shie** [comment] 2020-07-15 20:29
Thanks for looking into this, can definitely confirm it was living death when I reported the bug though. Super weird that it's seemingly fixed itself with death but not end.

**Comment by Zerrisx** [comment] 2020-07-15 20:33
I think it might be related to rollbacks and/or what other abilities are on the stack at the time.  Definitely seems a little more that a simple bug - but I reproduced it with only about five minutes of effort, so hopefully we can track it down and fix it.

**Comment by mrf1shie** [comment] 2020-07-15 20:38
If it helps the initial bug was in a 4 player commander game.

**Comment by 18ths** [comment] 2020-07-16 10:05
Actually the bug and explanation for it is quite simple - Living Death interaction was fixed by d8fb962030febe3834810702d120943ce1ff69ca but Living End copy-pasted effect was somehow omitted in this commit. So the solution to it would be extracting Living Death effect to common code, remove duplicated Living End effect and use common one. I'll try to fix this in a few hours, as I don't have access to the code right now.

**Closed** 2020-07-16 14:58 UTC
Labels: bug
