### ISSUE TITLE
Tawnos does not copy all aspects of creatures spells with X in mana cost 

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#9767] opened 2022-11-20 21:06 UTC
![image](https://user-images.githubusercontent.com/63882410/202926149-f8ac6089-fba7-49c1-a810-955925981ff4.png)

**Comment by jeffwadsworth** [comment] 2022-11-23 16:48
[[Tawnos, the Toymaker]]

**Comment by Grath** [comment] 2023-05-13 16:18
Gonna mark this as a duplicate of #9697 now to keep the info in one issue, since the issue is with all copying of X-cost permanent spells.

**Closed by Grath** 2023-05-13 16:18 UTC
