### ISSUE TITLE
Torpor Orb doesn't prevent Eminence

### ISSUE THREAD

**Issue by zeflap** [magefree/mage#4074] opened 2017-09-30 02:34 UTC
as above, Edgar still makes vampires, Inalla gets to double up on Wizards, etc.

**Comment by theelk801** [comment] 2017-09-30 03:06
Just tested this and it worked fine with Inalla. It wouldn't affect the other three anyway since none of them are abilities that trigger off a creature entering.

**Comment by Zerrisx** [comment] 2020-07-01 17:25
Edgar also isn't affected; he triggers on cast not on ETB.  Closing this as not a bug.

**Closed by Zerrisx** 2020-07-01 17:25 UTC
Labels: bug, not confirmed
