### ISSUE TITLE
AI enhancement request: More actively/aggressively blocking, also understanding of deathtouch when blocking.

### ISSUE THREAD

**Issue by Grath** [magefree/mage#8498] opened 2021-12-03 19:11 UTC
The AI is very conservative about blocking, I was just able to swing past a cloud of deathtouch blockers from [[Hornet Queen]] for lethal damage because I had some 20/20 creatures, the AI doesn't understand deathtouch, and it only blocks when it knows it can kill an attacker with a blocker. The AI also routinely doesn't block large attackers, even when not chump blocking causes them to lose.

**Comment by JayDi85** [comment] 2021-12-03 19:25
Related chump block issue #4485

**Comment by Alex-Vasile** [comment] 2022-09-19 18:49
Deathtouch part of the issue is covered by #6697.

I am closing this as a duplicate since all parts of it are already covered by other issues

**Closed by Alex-Vasile** 2022-09-19 18:49 UTC
Labels: enhancement, AI

**Comment by jeffwadsworth** [comment] 2023-01-26 22:57
Working on revamping the AI combat.  I will put up a video in this spot with progress soon.  Works fine, but I would like to enhance the SimulatedPlayer2 "player" to allow for the checking of activated abilities like regeneration.  Right now, the SimulatedPlayer2 only checks for triggered/continuous effects for score resolution til the end of a turn.  The AI will now block with multiple creatures if advantageous and culls results from any end of turn effects like Sengir Vampire, etc.  If anyone has experience with SimulatedPlayer2, let me know.
