### ISSUE TITLE
[OGW] Deceiver of Form and Vehicles

### ISSUE THREAD

**Issue by IntrinsicNerd** [magefree/mage#9294] opened 2022-07-20 04:10 UTC
Playing against a bot in commander, they have Deceiver of Form out, and it throws an exception when the next card is a vehicle. Here is the error:
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.50-V2 (build: 2022-07-19 05:39)
mage.cards.d.DeceiverOfFormEffect.apply(DeceiverOfForm.java:96)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:201)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:185)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:149)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1618)
mage.game.GameImpl.playPriority(GameImpl.java:1544)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

As well, I built from source as to have the newest list of cards in case that is important

**Comment by Alex-Vasile** [comment] 2022-09-27 18:31
[[Deceiver of Form]]

**Comment by xenohedron** [comment] 2023-07-10 10:47
Can't reproduce. Presumably this is actually a duplicate of #9501 and likewise fixed.

**Closed by xenohedron** 2023-07-10 10:47 UTC
Labels: bug
