### ISSUE TITLE
Incorrect interaction when playing a land after playing Life // Death

### ISSUE THREAD

**Issue by jsiegelman1** [magefree/mage#4442] opened 2018-01-25 05:17 UTC
1. Cast Life
2. Play a land
3. The land is a 1/1 with summoning sickness
The land should not be a creature.

**Comment by BenDawes** [comment] 2018-01-26 19:53
Reproduced; also affects other BecomesCreatureAllEffect like Dragonshift and Jolrael, Empress of Beasts. The problem is that the affected set is calculated at apply time instead of init-time:

https://github.com/magefree/mage/blob/00755356502810ccab90198c39fdc0e0cd2e1a7f/Mage/src/main/java/mage/abilities/effects/common/continuous/BecomesCreatureAllEffect.java#L74

**Comment by BenDawes** [comment] 2018-01-26 23:21
In fact BecomesCreatureAllEffect seems very buggy entirely, I'm seeing no effect from cards that have it as a SimpleStaticEffect

**Comment by BenDawes** [comment] 2018-01-27 11:53
https://github.com/magefree/mage/pull/4450

**Comment by BenDawes** [comment] 2018-01-30 09:52
Above PR merged, please close @JayDi85

**Closed** 2018-01-30 10:03 UTC
Labels: bug, cards
