### ISSUE TITLE
World Shaper and Korvold, Fae-Cursed King issue

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7313] opened 2020-12-29 17:57 UTC
I sac the world shaper to the  Korvold with the undying and this happens

Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.47V1 (build: 2020-12-28 22:25)
java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
mage.abilities.AbilitiesImpl.containsKey(AbilitiesImpl.java:275)
mage.game.permanent.PermanentImpl.addAbility(PermanentImpl.java:373)
mage.abilities.effects.common.continuous.GainAbilityControlledEffect.apply(GainAbilityControlledEffect.java:115)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:102)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1058)
mage.game.GameState.applyEffects(GameState.java:599)
mage.game.GameImpl.applyEffects(GameImpl.java:1562)
mage.game.GameImpl.playPriority(GameImpl.java:1363)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:127)
mage.game.GameImpl.playTurn(GameImpl.java:897)
mage.game.GameImpl.play(GameImpl.java:809)
mage.game.GameImpl.start(GameImpl.java:794)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/64045003/103303916-34585d00-49d5-11eb-8e10-efa03a72c9f5.png">

**Comment by jeffwadsworth** [comment] 2020-12-30 15:02
What was being used for the "gain ability controller" effect?

**Comment by catman123456** [comment] 2020-12-30 15:09
> 
> 
> What was being used for the "gain ability controller" effect?

I believe is has to do with the Korvold trigger. I can sac the worldshaper without the Korvold trigger to Mikaeus, the Unhallowed and its fine.

**Comment by jeffwadsworth** [comment] 2020-12-30 15:53
I tested the trigger and it worked fine.  The error has a "GainAbilityControlledEffect" in it.  Do you recall what was using that?

**Comment by catman123456** [comment] 2020-12-30 16:04
Nope

**Comment by jeffwadsworth** [comment] 2021-01-01 06:30
#7170

**Comment by jeffwadsworth** [comment] 2021-01-01 06:35
It may be Mikaeus, the Unhallowed causing the bug.  I will check it out soon.

**Comment by JayDi85** [comment] 2021-02-13 11:50
Duplicate of #7170

**Closed by JayDi85** 2021-02-13 11:50 UTC
