### ISSUE TITLE
ClassCastException in CardView to PermanentView

### ISSUE THREAD

**Issue by Francogdlp** [magefree/mage#12777] opened 2024-09-01 18:02 UTC
Error type: General error - ClassCastException
Client version: 1.4.53-V1 (build: 2024-08-16 15:36)

mage.view.CardView cannot be cast to mage.view.PermanentView

Stack trace:
org.mage.card.arcane.CardPanel.getOriginalPermanent(CardPanel.java:838)
mage.client.game.BattlefieldPanel.update(BattlefieldPanel.java:185)
mage.client.game.PlayAreaPanel.update(PlayAreaPanel.java:515)
mage.client.game.GamePanel.updateGame(GamePanel.java:1155)
mage.client.game.GamePanel.updateGame(GamePanel.java:1056)
mage.client.game.GamePanel.updateGame(GamePanel.java:1044)
mage.client.game.GamePanel.inform(GamePanel.java:2046)
mage.client.remote.CallbackClientImpl.lambda$onCallback$2(CallbackClientImpl.java:414)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
mage.client.dialog.MageDialog.startModal(MageDialog.java:209)
and other 176 lines

**Comment by xenohedron** [comment] 2024-09-17 01:46
duplicate of #12524

**Closed by xenohedron** 2024-09-17 01:46 UTC
Labels: bug
