### ISSUE TITLE
AI: Saskia the Unyielding can choose its controller in Commander Free For All

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#5810] opened 2019-05-23 17:19 UTC
This shouldn't happen.
![2019-05-23 (2)](https://user-images.githubusercontent.com/17330088/58272872-7af7c700-7d5d-11e9-98f5-0f6850f6f6a6.png)

**Comment by Zerrisx** [comment] 2020-07-14 16:13
Duplicate of #6838

**Closed by Zerrisx** 2020-07-14 16:13 UTC
Labels: AI
