### ISSUE TITLE
No draw Mighty Servant of Leuk-o

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9808] opened 2022-12-15 19:08 UTC
Crewed Mighty Servant of Leuk-o with Ethersworn Canonist and activated creature Mishra's Factory.  It did not gain the "when crewed by exactly 2 creatures" ability.
![image](https://user-images.githubusercontent.com/82664393/207946375-d329f9e0-a81f-4851-926e-cd796f981899.png)

**Comment by xenohedron** [comment] 2023-06-04 22:35
Duplicate of #9324

**Closed by xenohedron** 2023-06-04 22:35 UTC
