### ISSUE TITLE
Remove gray background image

### ISSUE THREAD

**Issue by RedStoner** [magefree/mage#3152] opened 2017-04-18 10:20 UTC
In the background folder, there is a gray background. this thing should go/not be pushed EVERY update. All in game text on screen is white, and the background is grey, making it incredibly painful to read the screen's text. After an update, if i forget to change it I am forced to condede whatever game i was just put into with the terrible background, because i will be unable to read the screen the rest of the match.
I have gone through and tried replacing it, deleting it, and making it read only and changing it to somthing else. Seems though xmage really wants me to have the thing. if i replace it, xmage puts it back, delete it.... xmage returns it.. make it read only..... xmage wont install. big issues here.
solution: make the backgrounds folder install only if the directory does not exist  prior to installation. or simply find a better background than gray.

**Comment by magenoxx** [comment] 2017-04-18 16:50
Hi,
Gray image is not default so I think it is stored somewhere in your preferences.
Default images are:
- gradient blue for non-play windows (e.g. login/tournaments)
- brown with Dragon for games

Try to change preferences by:
- Preferences -> Images -> User default image/ Use default battlefield image

Also: what OS do you play on?
On Windows all preferences are stored here:
HKEY_CURRENT_USER\Software\JavaSoft\Prefs\mage\client
Key Names: 
- background/Image
- background/Image/Default (false/true)
- battlefield/Image
- battlefield/Image/Default (false/true)

You may share these values so we are probably able to help you.

**Comment by RedStoner** [comment] 2017-04-18 19:50
I understand that the gray bg is not default. I have custom background in my folder that i am using, and i do have the setting turned on to use all images in bg folder. 
The main issue here is, that the gray bg gets installed every single update. I am hoping that this could be changed so that it is not forced onto the client's every time xmage updates. 
if not bgFolder { install backgrounds} else do nothing    simple enough fix.

**Comment by magenoxx** [comment] 2017-04-18 22:04
so do you mean that you remove gray background and then it gets back with upgrade.
if so, could you then use external folder with your background images, and point preferences to it

**Comment by RedStoner** [comment] 2017-04-18 23:32
I am unable to find a way to point background images to a folder. It only allows you to pick a single one. I set it to a single one in a custom bg folder, then selected pick at random and even still, it only pulls from default bg folder. screenshot of background related options : https://gyazo.com/5639b82d391b0bb39c67c613944dbe96
My goal is to have a folder with multiple bg's in them in which xmage pulls from without the grey background being injected into the folder with every update.

**Comment by spjspj** [comment] 2017-04-18 23:57
Can you take a screen shot of the Xmage client that shows what the problem with the background is?  I don't think that https://gyazo.com/5639b82d391b0bb39c67c613944dbe96 shows the actual problem?

**Comment by RedStoner** [comment] 2017-04-19 00:21
would be easy for you to replicate. just set your background to grey and try to read the text that shows up above the done button between resolutions. starting at that for an hour long game puts serious strain on the eyes. so i remove the grey background and use custom ones to add more flavor other than the dragon bg. to mix it up, i tell it to pull a random image, using the option available. works great, untill an update, then the grey image is in there again. 
I am simply asking if it's possible to do one of the following:
 1. Make it so the grey background is not added to the client if the background folder already exists. It seems between updates the folder never gets removed, as all my backgrounds remain.
 2. Allow a folder to be selected to pick the background images to pull from when using the "select random battlefield image" option
 3. put the grey background in an "assets" folder and use it as a default when the user does not have a valid background selected.

**Comment by spjspj** [comment] 2017-04-19 00:23
Upload an image of what you see as the problem.  I don't follow instructions particularly well ;)

**Comment by RedStoner** [comment] 2017-04-19 00:33
quick responce. Cannot give screenshot at the moment. I have deleted the grey background already. and it seems xmage does not want to reupdate for me. it cannot contact server. 
But Simply. Reading White text on a grey background hurts alot.

**Comment by magenoxx** [comment] 2017-04-19 08:06
Ok, the issue is clear now (no need for screenshot). I'll try to reproduce it.

**Comment by RedStoner** [comment] 2018-05-06 18:08
is this still being worked on?

**Comment by JayDi85** [comment] 2018-05-06 18:56
@RedStoner can you explain the problem? Is that actual for current version? 

I can't find/reproduce your default background path. Current version show up empty paths:
![shot_180506_225540](https://user-images.githubusercontent.com/8344157/39676740-aad139e8-5180-11e8-9a44-9bcf1738b750.png)

**Comment by RedStoner** [comment] 2018-05-07 17:14
I really dont under stand why this is so confusing. The issue is the grey background makes white text near impossible to read. Im asking for the grey background to not be downloaded EVERY SINGLE UPDATE. If background folder exists, dont download the backgrounds.

**Comment by JayDi85** [comment] 2018-05-07 17:57
Finally find that are you talking about: "random background" function use standard "background" game folder. It's have weird gray image file by default -- need to delete that file.

Fixed via c44127e238f6fa438cc65951b27e77cf62668c2d

**Closed by JayDi85** 2018-05-07 17:57 UTC
Labels: GUI, enhancement
