### ISSUE TITLE
Ghired, Conclave Exile bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7426] opened 2021-01-22 03:15 UTC
on the 2nd match of  a commander game and Ghired, Conclave Exile commander tax is not cleared.
<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/64045003/105441232-1bd70d80-5c36-11eb-9eb1-47e553a4bb14.png">

**Comment by Alex-Vasile** [comment] 2022-09-28 02:39
Duplicate of #7311

**Closed by Alex-Vasile** 2022-09-28 02:39 UTC
