### ISSUE TITLE
4k monitor causes extremely small UI

### ISSUE THREAD

**Issue by Lobster-Emperor** [magefree/mage#8738] opened 2022-03-02 22:57 UTC
Launching the game on a 4k monitor, or moving the game to a 4k monitor, causes the UI to shrink heavily, even when moving it back to a 1080p monitor. The biggest victim is the buttons, which all become extremely small, even on a 1080p monitor (see below image).

![small buttons](https://user-images.githubusercontent.com/100809072/156463455-2198844e-9904-443d-9434-38c181e62afe.png)

Starting the game on a 4k monitor at all causes it to permanently have the buttons shrink with no observable fix, as the issue persists even through restarts. The only temporary solution is to disable the 4k monitor, launch the game on the 1080p monitor, and then re-enable the 4k monitor which causes the buttons to have an acceptable size (see below image).

![large buttons](https://user-images.githubusercontent.com/100809072/156463646-e6c89411-50d7-4376-9578-dfb5ba96c02d.png)

I personally think a good fix would be to have an option to set the size of buttons in the Preferences menu. But even just ensuring that the buttons stay at an acceptable size when launching on a 4k monitor or moving between different resolution monitors.

**Comment by Alex-Vasile** [comment] 2022-09-28 02:57
Duplicate of #969 

See that Issue for potential workaround. Situation will get better when the launcher update is eventually released since you'll be able to use system java through the launcher.

**Closed by Alex-Vasile** 2022-09-28 02:58 UTC
Labels: GUI
