### ISSUE TITLE
Can't attack unless payment bug in regards to AI

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#2964] opened 2017-03-13 01:31 UTC
Simple test with Sphere of Safety.  The AI will freeze up with any payment restriction in regards to attacking.

**Comment by drmDev** [comment] 2017-03-26 16:12
Probably related to https://github.com/magefree/mage/issues/3012 . Sphere of Safety and a couple other similar cards would cause NRE due to a bug resolved in a recent commit mentioned in that issue.

**Comment by drmDev** [comment] 2017-04-22 05:24
Players still reporting this is an issue vs AI specifically. Works fine in non-AI games.

**Comment by Zerrisx** [comment] 2020-06-27 04:08
Cannot reproduce; this appears to be fixed.

**Closed by Zerrisx** 2020-06-27 04:08 UTC
Labels: AI, bug
