### ISSUE TITLE
Powerstones don't tap for mana with spells that have been made artifacts by mycosynth lattice

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#11459] opened 2023-11-24 17:42 UTC
![61caf9ca8f8a08a3ec3b7f7d354384ca (1)](https://github.com/magefree/mage/assets/63882410/fccf9555-b085-4b90-9271-7f7debc857d1)

**Comment by JayDi85** [comment] 2023-11-24 18:03
Fixed in #11447, will be available with next update.

**Closed by JayDi85** 2023-11-24 18:03 UTC

**Comment by ssk97** [comment] 2023-11-25 00:16
This is actually not a bug - Mycosynth Lattice makes all cards/spells colorless, but only permanents become artifacts.

**Comment by dashosa** [comment] 2023-11-26 05:21
Thank you for letting me know. Makes sense. Cheers
