### ISSUE TITLE
Errors after running Run Client

### ISSUE THREAD

**Issue by drowinternet** [magefree/mage#6395] opened 2020-04-05 07:59 UTC
The client doesn't seem to launch and I get 42 errors. I'm using VSC. The error are all from the New Features Dialog in Mage.client\...\client\dialog and include:

The import javafx cannot be resolved
JFXPanel cannot be resolved to type
Webview cannot be resolved to type 

ect

I've also tried Run Client in IntelliJ and the terminal seems to hang when it tries to load symbols. VSC seems to be able to load symbols but stops at:

at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

I'm trying to implement card from Ikoria but don't want to do a pull request without testing first.

Thank you,

**Comment by Elandril** [comment] 2020-04-16 13:24
Are you by any change using OpenJDK? JavaFX is not part of OpenJDK as it was split into a separate project (OpenJFX) some years back. Therefore OpenJDK 8 to 13 do not offer it, but for 14 they are considering/working on re-integrating it.

You need to use the Oracle JDK 1.8 to get JavaFX support, as there are no versions for OpenJDK. There are two alternative JDKs that I know of that bundle JavaFX 8: [Azul Zulu](https://www.azul.com/downloads/zulu-community/) and [BellSoft Liberica](https://bell-sw.com/java8), but I have not tested either of these.

There are some details about this in the [OpenJDK FAQs](https://adoptopenjdk.net/faq.html#openjfxfaq) and some people who manually added the JavaFX jar, but I would not recommend that course of action.

**Comment by JayDi85** [comment] 2020-04-16 14:47
Client must works fine without JavaFX on system (e.g. with OpenJDK). It's can be another problem like:
1. Auto-login freeze ([fix](https://github.com/magefree/mage/issues/4461#issuecomment-361108597));
2. Broken symbols files (fix: delete `\xmage\mage-client\plugins\images\symbols` folder and restart client).

**Comment by allentiak** [comment] 2020-05-05 23:52
The client **cannot** be built without JavaFX. The WhatsNew class uses it.
See #6197.

**Comment by Zerrisx** [comment] 2020-07-15 19:04
I'm pretty sure this is a straight duplicate of #6197.

**Closed** 2020-07-29 17:32 UTC
