### ISSUE TITLE
An issue about Council of the Absolute

### ISSUE THREAD

**Issue by seedds** [magefree/mage#227] opened 2013-05-25 13:25 UTC
According to Wizards FAQ (http://www.wizards.com/magic/magazine/article.aspx?x=mtg/faq/dgm) :

You can name either half of a split card, but not both. If you name half of a split card, your opponents can cast the other half. (This is a recent rules change.) If that split card has fuse, your opponents can’t cast that card as a fused split card.

Right now, I'm choosing both the names.

**Comment by Zerrisx** [comment] 2020-05-17 19:55
Duplicate of #6549

**Comment by JayDi85** [comment] 2020-06-10 06:02
Fixed via b38ac2f575c3da161f98ac3fdc2048c9fc446169

**Closed by JayDi85** 2020-06-10 06:02 UTC
Labels: bug
