### ISSUE TITLE
Sealed Elimination / Swiss not working?  Stuck at overview page

### ISSUE THREAD

**Issue by PhilistineAu** [magefree/mage#4842] opened 2018-04-22 00:39 UTC
Hi,
A few times now I have played Sealed Swiss and Sealed Elimination with a friend on the xmageplayersmtg.ddns.net server.  In all but one of those games, I am able to select the packs (e.g. 6 Theros), he joins, we start and build our decks and then click submit.  However, once we have both submitted, most of the time only one of us joins the game.  The other is left stuck at the overview screen.  If you click "watch" in the overview screen, nothing happens.  I've tried the same with the AI and it seems to work.

We now build our decks, save them and then use "new match" to battle it out.  However, it would be nice if sealed worked.  Any suggestions?

Last question - I have no idea how Xmage differs on Sealed Elimination, Sealed Swiss and both of those in cube.  Could someone let me know what each of these is / how they are applied in Xmage?

Thank you!!!

**Comment by LevelX2** [comment] 2018-04-25 07:36
No idea, why most of the time not both of you are able to connect to the same tournament.
Are you both connecting from the same local network to the xmage server?
Does this also sometimes happen, if only one is connection a tournament (and your friend or you are not online at that time)?

https://en.wikipedia.org/wiki/Swiss-system_tournament
Elimination means : You lose a match = you're out

**Comment by Khyrberos** [comment] 2018-10-10 06:53
This happened to me just a few minutes ago.  I don't know what my opponent saw (I believe it said "Dueling" so he was in the game?), but I was stuck at the Tournament 'info' screen, and pressing 'Watch' didn't change anything (ultimately he left).

**Comment by Zerrisx** [comment] 2020-07-07 20:39
Duplicate of #5555

**Closed by Zerrisx** 2020-07-07 20:39 UTC
Labels: question, server
