### ISSUE TITLE
Cascade effect bug

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#4673] opened 2018-03-28 15:25 UTC
From the forum: Remanding a Tarmogyf that was cast from cascade of a Blood Braid Elf. Tarmogyf properly went back into my opponents hand after casting Remand, however the Tarmogyf was unable to be interacted with/casted for the remainder of the game.

**Comment by Zerrisx** [comment] 2020-07-07 18:26
Duplicate of #4600

**Closed by Zerrisx** 2020-07-07 18:26 UTC
Labels: bug
