### ISSUE TITLE
Body Double Gisela, Blade of Goodnight issue

### ISSUE THREAD

**Issue by lazypidgey** [magefree/mage#6378] opened 2020-03-27 18:32 UTC
Playing a game of commander where the following interaction occured. My opponent had a Body Double enter as a copy of Gisela, Blade of Goldnight that was in my graveyard. Later, an Ixadron enters, flipping all creatures facedown making them 2/2's. However the Body Double still had all of Gisela's abilities, (flying, first strike, controller takes half damage, opponents take 2x damage). No other creature kept their abilities. I don't know what caused this but I'm assuming it has something to do with Body Double

**Comment by Zerrisx** [comment] 2020-07-15 18:45
Duplicate of #3583

**Closed by Zerrisx** 2020-07-15 18:45 UTC
