### ISSUE TITLE
XMage UI sometimes freezes displaying an extremely tall subwindow especially when stacking triggers

### ISSUE THREAD

**Issue by draxdyn** [magefree/mage#1841] opened 2016-04-11 14:05 UTC
Sometimes, usually when triggers have to be stacked, XMage displays a subwindow which is solid grey and apparantly taller than the xmage window itself it is contained in, so that the subwindow titlebar and bottom border are hidden and only the left and right borders and grey interior are visible, which occupy the full height of the containing XMage window.

Once this happens, the UI seems to stop responding to everything except for resizing either the main XMage window (which causes a relayout as normal) or resizing the subwindow (only the left/right position can be altered since the top and bottom parts are not visible), forcing the user to quit XMage and the active game.

**Comment by Zerrisx** [comment] 2020-07-15 20:53
If this is a duplicate, can we mention what it's a duplicate of?

**Comment by JayDi85** [comment] 2020-07-15 21:27
It can be related to bad performance on slow HDD with antivirus (xmage freezes on new cards puts to battlefield/stack -- it's try to load new images from HDD but it slow). Solution: use SDD or puts images folder to antivirus's ignore list.

**Closed by JayDi85** 2020-07-15 21:27 UTC
Labels: bug, duplicate
