### ISSUE TITLE
Price of fame is still bugged

### ISSUE THREAD

**Issue by rexelallan** [magefree/mage#6737] opened 2020-06-27 21:02 UTC
![image](https://user-images.githubusercontent.com/42716000/85932204-920fcd80-b8fc-11ea-8c44-038b6447a1ed.png)

**Comment by LevelX2** [comment] 2020-06-27 21:59
Duplicate of #6698.

**Comment by rexelallan** [comment] 2020-06-27 22:09
They said it was fixed, but no it was not. Dont tag as duplicate this is new issue since bug is not yet fixed as they claimed to be

**Comment by Zerrisx** [comment] 2020-06-27 22:55
The fix is only on beta servers right now. If you're on the release server, it'll still be bugged until the next patch. What client/server were you using?

**Comment by rexelallan** [comment] 2020-06-27 23:14
I see. Im using the live server and not beta. Thanks!

**Comment by Zerrisx** [comment] 2020-06-27 23:28
No worries!  Yeah, we typically mark things fixed as soon as the fix goes into beta, but it can take a few weeks to make it to live.

**Closed by Zerrisx** 2020-06-27 23:28 UTC
Labels: bug, duplicate
