### ISSUE TITLE
ClassCastException in CardView to PermanentView

### ISSUE THREAD

**Issue by RFCKOlive** [magefree/mage#12884] opened 2024-09-16 17:54 UTC
Error type: General error - ClassCastException
Client version: 1.4.54-V2 (build: 2024-09-09 11:29)

mage.view.CardView cannot be cast to mage.view.PermanentView

Stack trace:
org.mage.card.arcane.CardPanel.getOriginalPermanent(CardPanel.java:838)
mage.client.game.BattlefieldPanel.update(BattlefieldPanel.java:185)
mage.client.game.PlayAreaPanel.update(PlayAreaPanel.java:515)
mage.client.game.GamePanel.updateGame(GamePanel.java:1155)
mage.client.remote.CallbackClientImpl.lambda$onCallback$2(CallbackClientImpl.java:391)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
java.awt.EventQueue.access$500(EventQueue.java:97)
java.awt.EventQueue$3.run(EventQueue.java:709)
java.awt.EventQueue$3.run(EventQueue.java:703)
and other 9 lines

**Comment by xenohedron** [comment] 2024-09-17 01:46
duplicate of #12524

**Closed by xenohedron** 2024-09-17 01:46 UTC
Labels: bug
