### ISSUE TITLE
Unable to cast card

### ISSUE THREAD

**Issue by ChillKloete** [magefree/mage#8568] opened 2022-01-20 21:50 UTC
I encountered a bug concerning the card "Timely Ward". It is an enchantment that says: "You may cast this spell as though it had flash if it targets a commander."

I was not able to cast it at instant speed, though my commander was on the field and there was nothing else preventing me to cast it. Casting other instants was possible.

**Comment by jeffwadsworth** [comment] 2022-01-20 22:52
[[Timely Ward]]

**Comment by awjackson** [comment] 2022-09-11 01:01
Duplicate of #7326

**Closed by awjackson** 2022-09-11 01:01 UTC
