### ISSUE TITLE
Some mana abilities with undo/cancel can be used to spy information

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1224] opened 2015-08-25 14:57 UTC
"Chromatic Sphere - Fixed Chromatic Sphere being undoable to spy for next card to draw."
Still undoable.
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=17549&p=184613#p184613

LevelX: The undo button can be deactivated if used not for casting a spell. But if you used the Sphere during a spell casting the cancel button for this spell casting can't be removed because the way xmage handles spell casting (maybe you have not enough mana and then you would be locked without the cancel button). So no real solution to solve this problem yet. The spell canceling has not to undo the usage of Chromatic Sphere, what's not possible yet.
Probably there is a complete redesign of spell casting neccessary to solve this.

**Comment by Zerrisx** [comment] 2020-07-29 14:27
Duplicate of #2382.

Keeping the other one as the master, since it's got more detail and includes this case.

**Closed by Zerrisx** 2020-07-29 14:27 UTC
Labels: bug
