### ISSUE TITLE
Cavern of Souls

### ISSUE THREAD

**Issue by synergize** [magefree/mage#869] opened 2015-03-31 23:15 UTC
I played Cavern naming Golem. Next turn I tap to played Platinum Angel using the Cavern to tap for colorless. Opponent tried countering it and it disallowed him stating I paid color mana to cast the Angel.

**Comment by LevelX2** [comment] 2015-03-31 23:24
Duplicate of #798

**Closed by LevelX2** 2015-03-31 23:24 UTC
Labels: bug, duplicate
