### ISSUE TITLE
Kira, Great Glass-Spinner triggers twice

### ISSUE THREAD

**Issue by derflippi** [magefree/mage#3041] opened 2017-03-30 16:46 UTC
Kira, Great Glass-Spinner will trigger twice if a player targets kira with an ability, and then with a spell.

The correct behavior would be to not trigger again for the spell, as "it's already been the target of a spell OR ability".

Edit:
The ability was Liliana, the Last Hope's +1 ability with "Up to one target creature" 
The spell was Kolaghan's Command, targetting Kira with 2 damage and a player for discard.

**Comment by ingmargoudt** [comment] 2017-03-30 17:51
Looking at the implementation of Kira, Great Glass-Spinner, I can imagine that this occurs. Test will be created and if needed card will be fixed in next release

**Comment by ingmargoudt** [comment] 2017-03-30 23:06
I made a test for this with an Ugin, the Spirit Dragon (+2 ability) and a Shock, but I could not reproduce this, I will make a test with Liliana the Last Hope and Kolaghans Command as well.

**Comment by stravant** [comment] 2017-04-01 02:51
Investigating further, Kira's implementation is pretty buggy. It has a bunch of extra ".isCreature()" checks in it's implementation that shouldn't be there. Kira's Abilities don't actually care about whether the targeted things are creatures, "this creature" in the ability text really just means "this object". The "FilterCreaturePermanent("creatures")" part on the granting ability is actually the only reference that there should be to creatures at all in the entire implementation.

**Comment by ingmargoudt** [comment] 2017-04-01 12:14
To me the implementation of Kira looks Ok. I can see 2 isCreature calls, one could argue that one of them is redundant. If you have the idea that Kira also triggers on noncreatures, then i suggest to make a unit test for that

**Comment by stravant** [comment] 2017-04-01 23:28
> If you have the idea that Kira also triggers on noncreatures

It doesn't trigger on non-creatures, but it *shouldn't* trigger when you target a creature that has already been targeted earlier in the turn while it wasn't a creature yet. For instance, if you target a non-animated manland, and then it becomes animated, it will currently trigger when it becomes target even though it shouldn't.

That's why there shouldn't be an isCreature check in the Watcher either.

**Comment by jeffwadsworth** [comment] 2017-04-18 21:21
Tested this and it works for me.  Any reason to keep this open?

**Comment by LevelX2** [comment] 2017-04-18 22:17
I only fixed the problem described by stravant. Not the original issue.

**Comment by jeffwadsworth** [comment] 2017-04-19 21:31
From my understanding:
The initial issue was it triggering twice.  It no longer does that and works correctly in this frame.
The other issue raised was concerning it being targeted as a non-creature and targeted as a creature (man-land) later in the turn.  This works also.  Tested with Treetop Village and Twiddle.
Is there something else that was not working?

**Comment by jeffwadsworth** [comment] 2017-04-19 21:36
This works in both the initial case (triggering twice) and the other case (man-land targeted, animated, and targeted again).  Is there something else that needs to be tested here?

**Comment by jeffwadsworth** [comment] 2017-04-20 20:45
This appears to work now in all situations described above.

**Closed** 2017-04-21 09:57 UTC
Labels: bug
