### ISSUE TITLE
[BUG] - Savior of Ollenbock

### ISSUE THREAD

**Issue by brotendomtg** [magefree/mage#9937] opened 2023-02-01 00:25 UTC
Had a game today where Savior of Ollenbock trained but couldn't target/select a creature on the battlefield. There weren't any creatures in graveyards, so I'm not sure if that would have worked. 

![Screenshot 2023-01-31 155641](https://user-images.githubusercontent.com/114497501/215914715-28e099f8-05a7-45b7-bdbd-6e3ec9fb9184.png)

**Comment by PurpleCrowbar** [comment] 2023-02-06 14:56
Duplicate of #9561

**Closed by PurpleCrowbar** 2023-02-06 14:56 UTC
