### ISSUE TITLE
BUG: Haunting Voyage not returning all creatures of a type from graveyard when foretold

### ISSUE THREAD

**Issue by Biohazard31415** [magefree/mage#11904] opened 2024-03-03 23:54 UTC
As stated in the title, Haunting Voyage only returns two creatures of a type from graveyard regardless of whether it was cast foretold for 5BB or from hand for 4BB. When foretold it should return all creatures of a type from graveyard to field.

**Comment by xenohedron** [comment] 2024-03-19 03:18
duplicate of #8419

**Closed by xenohedron** 2024-03-19 03:18 UTC
