### ISSUE TITLE
Server's error: offset out of bounds (too much memory usage by server)

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9052] opened 2022-06-01 23:41 UTC
In XMage Beta Version 1.4.51-dev, May 27: Trying to cast Herald's Horn from hand results in "server's error: offset out of bounds" popup.  Even if I click OK, I cannot select a creature type or proceed.  Rollback and no cast was required.

**Comment by LegionedintheDamned** [comment] 2022-06-01 23:45
Edit: error continued to pop up on any choices after that, whether it be a number for 'X' or for stack order.  May be related to server options instead.

**Comment by LegionedintheDamned** [comment] 2022-06-01 23:48
Edit 2: https://www.reddit.com/r/XMage/comments/uvojxm/server_out_of_bounds/
Appears to be a wider spread problem.

**Comment by LegionedintheDamned** [comment] 2022-06-01 23:53
Expanded search in this forum: server -Xmx8G is what I have implemented.  Client java is -Xmx4G.

**Comment by LegionedintheDamned** [comment] 2022-06-01 23:56
Edit 3: playing zombie deck with Toxic Deluge in the deck.  Never saw the card though.  After full reboot of server and client, played same deck again, same error occurred, no choice cards (i.e. 'X') or stack choices were used.

**Comment by LegionedintheDamned** [comment] 2022-06-02 01:53
Edit 4: adjusted both server and client java options to match exactly vanilla boot options.  Most games were fine, however: when Urza's Incubator came up (same deck) it caused the same game hang up.
-Server's error: offset out of bounds
-Unable to select or enter creature type
-Pushing 'OK' does nothing, error pops up again

**Comment by JayDi85** [comment] 2022-06-02 04:46
1. Can you confirm that increase memory limits can fix it for you? 
2. Is it starting from last beta or it was before with same deck/cards (in old beta or release)?

**Comment by Alex-Vasile** [comment] 2022-06-02 13:23
Duplicate of #8836, #9023?

**Comment by LegionedintheDamned** [comment] 2022-06-02 19:15
> 

1. Memory limit increase did not fix it.  Current server java options reads: "-Xms10G -Xmx10G -XX:MaxPermSize=384m".

Testing just now, during lunch, same deck (blue/black, commander, zombie tribal, Wilhelt the Rotcleaver, Toxic Deluge in deck).  _Game 1_: I was able to cast Herald's Horn, Reflections of Littjara, Cover of Darkness without the failure, but did see it in edit 4 last night.  
_Game 2_: I did get the error at the end of my second test game, without casting any of the 'choose' spells.
_Game 3_: Played Cavern of Souls, error instantly popped up (turn 3).  Unable to play land, or choose creature type.  Game hang up.  Server not rebooted or retried during 3 test games.

2. I have not tested beta servers properly prior to now.  This was my first time experimenting with it as a server.  So I cannot confirm if it was prior to now.

**Comment by LegionedintheDamned** [comment] 2022-06-03 02:59
Edit 5: was able to repeat error in a different deck, game 1 of the server boot.  Commander, 3 player, mono-white angels, Giada Font of Hope general.  Cast Bloodline Pretender, exact same error, exact same scenario (choose creature type).

**Comment by LegionedintheDamned** [comment] 2022-06-06 01:08
Update 6: confirmed again today - it is any pop-up window.  Choosing a creature type, choosing 'X', even cases where you choose which resolves first.  I cannot isolate the events leading up to it, this time it was the first game after server bootup.

**Comment by Alex-Vasile** [comment] 2022-06-06 01:30
When you test on a local server and see this error occurs. What is in the console for both that client and the server?

I've been trying to reproduce it, and now that I'll looking at it it's refusing to replicate.

**Comment by LegionedintheDamned** [comment] 2022-06-06 03:04
![Example of error](https://user-images.githubusercontent.com/82664393/172087380-df6177f2-faf1-4e85-af2d-caba9fdee0e4.png)

**Client error:**
_FATAL 2022-06-05 21:02:03,519 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.IllegalArgumentException: offset out of bounds
	at sun.util.locale.provider.RuleBasedBreakIterator.checkOffset(RuleBasedBreakIterator.java:759)
	at sun.util.locale.provider.RuleBasedBreakIterator.preceding(RuleBasedBreakIterator.java:819)
	at javax.swing.text.GlyphView.getBreakSpot(GlyphView.java:799)
	at javax.swing.text.GlyphView.getBreakWeight(GlyphView.java:724)
	at javax.swing.text.html.InlineView.getBreakWeight(InlineView.java:150)
	at javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:733)
	at javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:233)
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:717)
	at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:157)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
	at javax.swing.text.html.ParagraphView.getMinimumSpan(ParagraphView.java:270)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
	at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:343)
	at javax.swing.text.BoxView.layout(BoxView.java:708)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:912)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1333)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1513)
	at java.awt.Container.doLayout(Container.java:1502)
	at java.awt.Container.validateTree(Container.java:1698)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validate(Container.java:1633)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)_
This is repeated over and over and over again, continuously.

Server no error:
_INFO  2022-06-05 20:57:59,069 MATCH started [Game] 5d7866bc-aeb1-46f6-b2d8-7bc588fd9638(Legioned)                        =>[CALL main-50] TableController.lambda$startMatch$7 
INFO  2022-06-05 20:57:59,137 GAME started 9426d8f6-2cb2-4291-a991-b7faf594d5aa [Game] Legioned - Computer 4 - Computer 2 - Computer 3 =>[CALL main-50] TableController.startGame_

**Comment by LegionedintheDamned** [comment] 2022-06-14 02:14
Any suggestions?  Essentially makes BETA untestable, so I can't record card errors.  Seems based on the last post I made, perhaps it is a client error?

**Comment by LegionedintheDamned** [comment] 2022-06-18 20:01
Confirmed yesterday that I am still having the same client error post update.  Can anyone post their client java settings, so I can try other ones?

**Comment by JayDi85** [comment] 2022-06-19 03:01
@LegionedintheDamned try again -- can you connect to beta now?

**Comment by LegionedintheDamned** [comment] 2022-06-19 19:20
@JayDi85 I was successful in connecting to normal Beta, and running and hosting my own Beta server.  No issues with booting, joining, hosting a game, or any of that.

The issue is only when playing a game, in the Commander format, with 3 x AIs.  Today I am getting the "Server's erorr: offset out of bounds" on any pop-up when I have to choose 2 or more stack trigger orders.  I can select "OK" and continue despite this.

I cannot select if it is a 'choose' text (i.e. choose X, choose creature type, choose colour) - it freezes all the way, and while I can stop the pop-up, I have to rollback to stop the message - I cannot proceed at all while the pop-up is present and a dialog box with choose is present.

**Server Console**: nothing out of the ordinary.
**Client Console**: _FATAL 2022-06-19 13:08:10,276 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.IllegalArgumentException: offset out of bounds
	at sun.util.locale.provider.RuleBasedBreakIterator.checkOffset(RuleBasedBreakIterator.java:759)
	at sun.util.locale.provider.RuleBasedBreakIterator.preceding(RuleBasedBreakIterator.java:819)
	at javax.swing.text.GlyphView.getBreakSpot(GlyphView.java:799)
	at javax.swing.text.GlyphView.getBreakWeight(GlyphView.java:724)
	at javax.swing.text.html.InlineView.getBreakWeight(InlineView.java:150)
	at javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:733)
	at javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:233)
	at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:717)
	at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:157)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
	at javax.swing.text.html.ParagraphView.getMinimumSpan(ParagraphView.java:270)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568)
	at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378)
	at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903)
	at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146)
	at javax.swing.text.BoxView.checkRequests(BoxView.java:935)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:343)
	at javax.swing.text.BoxView.layout(BoxView.java:708)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:912)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1333)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1513)
	at java.awt.Container.doLayout(Container.java:1502)
	at java.awt.Container.validateTree(Container.java:1698)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validate(Container.java:1633)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)_
	
The client console error repeats once every second, over and over repeatedly.

**Comment by Alex-Vasile** [comment] 2022-07-07 12:43
Closing duplicate, keep an eye on #8836.

**Closed by Alex-Vasile** 2022-07-07 12:43 UTC

**Comment by Alex-Vasile** [comment] 2022-07-17 00:38
> ![Example of error](https://user-images.githubusercontent.com/82664393/172087380-df6177f2-faf1-4e85-af2d-caba9fdee0e4.png)
> 
> **Client error:** _FATAL 2022-06-05 21:02:03,519 MAGE Client UI error =>[AWT-EventQueue-0] EDTExceptionHandler.handle java.lang.IllegalArgumentException: offset out of bounds at sun.util.locale.provider.RuleBasedBreakIterator.checkOffset(RuleBasedBreakIterator.java:759) at sun.util.locale.provider.RuleBasedBreakIterator.preceding(RuleBasedBreakIterator.java:819) at javax.swing.text.GlyphView.getBreakSpot(GlyphView.java:799) at javax.swing.text.GlyphView.getBreakWeight(GlyphView.java:724) at javax.swing.text.html.InlineView.getBreakWeight(InlineView.java:150) at javax.swing.text.FlowView$LogicalView.getPreferredSpan(FlowView.java:733) at javax.swing.text.FlowView.calculateMinorAxisRequirements(FlowView.java:233) at javax.swing.text.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:717) at javax.swing.text.html.ParagraphView.calculateMinorAxisRequirements(ParagraphView.java:157) at javax.swing.text.BoxView.checkRequests(BoxView.java:935) at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568) at javax.swing.text.html.ParagraphView.getMinimumSpan(ParagraphView.java:270) at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903) at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146) at javax.swing.text.BoxView.checkRequests(BoxView.java:935) at javax.swing.text.BoxView.getMinimumSpan(BoxView.java:568) at javax.swing.text.html.BlockView.getMinimumSpan(BlockView.java:378) at javax.swing.text.BoxView.calculateMinorAxisRequirements(BoxView.java:903) at javax.swing.text.html.BlockView.calculateMinorAxisRequirements(BlockView.java:146) at javax.swing.text.BoxView.checkRequests(BoxView.java:935) at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:343) at javax.swing.text.BoxView.layout(BoxView.java:708) at javax.swing.text.BoxView.setSize(BoxView.java:397) at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722) at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:912) at javax.swing.JComponent.getPreferredSize(JComponent.java:1662) at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1333) at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791) at java.awt.Container.layout(Container.java:1513) at java.awt.Container.doLayout(Container.java:1502) at java.awt.Container.validateTree(Container.java:1698) at java.awt.Container.validateTree(Container.java:1707) at java.awt.Container.validateTree(Container.java:1707) at java.awt.Container.validateTree(Container.java:1707) at java.awt.Container.validate(Container.java:1633) at javax.swing.RepaintManager$3.run(RepaintManager.java:711) at javax.swing.RepaintManager$3.run(RepaintManager.java:709) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708) at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731) at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311) at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) at java.awt.EventQueue.access$500(EventQueue.java:97) at java.awt.EventQueue$3.run(EventQueue.java:709) at java.awt.EventQueue$3.run(EventQueue.java:703) at java.security.AccessController.doPrivileged(Native Method) at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74) at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)_ This is repeated over and over and over again, continuously.
> 
> Server no error: _INFO 2022-06-05 20:57:59,069 MATCH started [Game] 5d7866bc-aeb1-46f6-b2d8-7bc588fd9638(Legioned) =>[CALL main-50] TableController.lambda$startMatch$7 INFO 2022-06-05 20:57:59,137 GAME started 9426d8f6-2cb2-4291-a991-b7faf594d5aa [Game] Legioned - Computer 4 - Computer 2 - Computer 3 =>[CALL main-50] TableController.startGame_
> 
> Client java options: -Xms6G -Xmx6G -XX:MaxPermSize=384m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled

What was Computer 2 (top left) playing here? Was it Edgar Markov by any chance?

**Comment by LegionedintheDamned** [comment] 2022-07-17 18:33
Yes, it was.  It is worth noting that I just haven't had time to start looking at the beta again to see if I could stop getting the error.  My plan is to reinstall XMage when I try again.

**Comment by Alex-Vasile** [comment] 2022-07-17 18:39
> Yes, it was. It is worth noting that I just haven't had time to start looking at the beta again to see if I could stop getting the error. My plan is to reinstall XMage when I try again.

Perfect. Then this issue is solved by 420b6f1a74590b5126a5525fdb86d8e4f70916dd and you'll find it fixed in the *next* beta .
