### ISSUE TITLE
Armament Corps text wrong but card works

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#9151] opened 2022-06-23 21:44 UTC
[[Armament Corps]] asks if you want to deal damage when it should ask to give counters. The card works though: it gives counters as it should.
![Nimetön](https://user-images.githubusercontent.com/22531697/175407658-dc5e481b-f7b7-46b6-a526-636a2075af12.png)
.

**Comment by PurpleCrowbar** [comment] 2022-06-24 17:33
Duplicate of #8069

**Closed by PurpleCrowbar** 2022-06-24 17:33 UTC
