### ISSUE TITLE
Can't activate card abilities on Linux

### ISSUE THREAD

**Issue by troyready** [magefree/mage#675] opened 2015-01-15 02:04 UTC
I'm not sure if this is related to #584 -- when activating abilities (or casting cards like Mox Opal or Ornithopter), no activation option is appearing my Ubuntu 14.04 system. On my Windows system, a black box appears on the battlefield showing me the option to cast or cancel, but nothing appears at all on the Linux one.

*edit: changed issue from specifically referencing 0 mana spells to all activated ability boxes.

**Comment by LevelX2** [comment] 2015-02-02 10:15
I' ptretty sure this is a duplicate of #584 as you already mentioned. So I close this one.
If you see other aspects, add a note to the #584 issue.

**Closed by LevelX2** 2015-02-02 10:15 UTC
Labels: bug, duplicate
