### ISSUE TITLE
Warren warleader miscoded

### ISSUE THREAD

**Issue by ovenmittromney** [magefree/mage#12757] opened 2024-08-30 10:33 UTC
Warren warleader from Bloomburrow is coded wrong
It's activating both modes instead of presenting a choice when you attack.
https://scryfall.com/card/blb/38/warren-warleader

**Comment by PurpleCrowbar** [comment] 2024-08-30 13:08
Duplicate of #12696, fixed by ec46db6

**Closed by PurpleCrowbar** 2024-08-30 13:08 UTC
