### ISSUE TITLE
Eater of virtue not exiling

### ISSUE THREAD

**Issue by radiasian** [magefree/mage#8821] opened 2022-04-07 23:23 UTC
My opponent controlled a bloodsoaked champion with an eater of virtue equipped. I used Erebos' Intervention to give the champion -1/-1, where it died but ended up in the graveyard instead of being exiled by the eater.

**Comment by awjackson** [comment] 2022-04-08 03:48
Duplicate of #8697

**Closed by awjackson** 2022-04-08 03:48 UTC
