### ISSUE TITLE
BUG Leonardo Da Vinci's second ability is not working

### ISSUE THREAD

**Issue by Notshauna** [magefree/mage#12895] opened 2024-09-21 02:39 UTC
Leonardo Da Vinci's second activated ability is sending an error as soon as it's activated. I've copied it below.

Error type: SERVER - game error
Client version: 1.4.54-V2 (build: 2024-09-09 11:29)

Game error occurred: 

java.lang.ClassCastException: mage.game.permanent.PermanentToken cannot be cast to mage.players.Player
Server version: 1.4.54-V2 (build: 2024-09-09 11:29)
Stack trace:
mage.constants.TargetController$PlayerPredicate.apply(TargetController.java:111)
mage.constants.TargetController$PlayerPredicate.apply(TargetController.java:101)
mage.filter.FilterPermanent.lambda$match$0(FilterPermanent.java:60)
java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
mage.filter.FilterPermanent.match(FilterPermanent.java:60)
mage.game.permanent.Battlefield.lambda$getActivePermanents$10(Battlefield.java:249)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
java.util.Iterator.forEachRemaining(Iterator.java:116)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
mage.game.permanent.Battlefield.getActivePermanents(Battlefield.java:250)
mage.abilities.effects.common.continuous.BoostControlledEffect.init(BoostControlledEffect.java:80)
mage.game.GameImpl.addEffect(GameImpl.java:1948)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:238)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:209)
mage.game.stack.StackAbility.resolve(StackAbility.java:85)
mage.game.GameImpl.resolve(GameImpl.java:1803)
mage.game.GameImpl.playPriority(GameImpl.java:1726)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:205)
mage.game.turn.Phase.play(Phase.java:91)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1150)
mage.game.GameImpl.play(GameImpl.java:1057)
mage.game.GameImpl.start(GameImpl.java:1033)
mage.server.game.GameWorker.call(GameWorker.java:35)
mage.server.game.GameWorker.call(GameWorker.java:16)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Notshauna** [comment] 2024-09-21 02:41
[[Leonardo da Vinci]]

**Comment by Grath** [comment] 2024-09-21 03:42
Duplicate of #12774 and will be fixed after the next update.

**Closed by Grath** 2024-09-21 03:42 UTC
