### ISSUE TITLE
Ancient Imperiosaur Convoke bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#10250] opened 2023-04-21 22:24 UTC
[[Ancient Imperiosaur]] Convoke doesn't give the +1/+1 counters 

![image](https://user-images.githubusercontent.com/64045003/233743374-1de18840-0037-4570-a858-e5956e7313f5.png)

**Comment by PurpleCrowbar** [comment] 2023-04-22 01:54
Duplicate of #10237

**Closed by PurpleCrowbar** 2023-04-22 01:54 UTC
