### ISSUE TITLE
Mirrorwing Dragon interaction with Silverfur Partisan issues

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2175] opened 2016-08-16 21:47 UTC
from reddit:

New to Xmage, so there's a small chance I did something wrong, but I think this is a bug. Had a Silverfur Partisan and two wolf tokens out, along with a Mirrorwing Dragon. When I cast Expedite on the dragon, it copies onto all of my other creatures, so I should get three more wolf tokens. However, this did not happen.

**Comment by drmDev** [comment] 2016-08-16 21:47
Probably cannot create a test for this with the framework targetting issues.

**Comment by niewidoczna** [comment] 2017-01-06 12:53
I tried it with both a Zada, Hedron Grinder and a Mirrorwing Dragon in the same game. They should work similarly, but only targeting Zada creates copies of a spell that make a Silverfur Partisan's ability trigger. On the other hand, Mirrorwing Dragon's ability allowed me to select the order in which the copies for different targets are placed on the stack (this order is important, for example, with a spell like Confront the Unknown) while Zada's ability did not.

**Comment by Zerrisx** [comment] 2020-06-26 01:42
Duplicate of #5727

**Closed by Zerrisx** 2020-06-26 01:42 UTC
Labels: bug
