### ISSUE TITLE
Flying creatures can't be blocked by flying creatures?

### ISSUE THREAD

**Issue by Tech0verlord** [magefree/mage#2259] opened 2016-09-13 04:52 UTC
So in the latest official build, I was practicing against a bot using my Commander deck. The bot is using an older version of my current deck, so I know what is in it, but for some reason, when it attacks with a flying creature, I can't block using any of my flying creatures. I get a message saying that this creature can't be blocked. In the attached pictures, I've attempted to block both an Emeria Shepherd and an Angel token, both with flying, with a Knight of Obligation that I gave flying to, and an Assault Griffin, which innately has flying. The first picture has what Knight of Obligation has equipped/enchanted with, if it matters.
<img width="960" alt="1" src="https://cloud.githubusercontent.com/assets/2433224/18461824/699c0868-794b-11e6-882e-bf71fae128ff.png">
<img width="960" alt="2" src="https://cloud.githubusercontent.com/assets/2433224/18461823/699473f0-794b-11e6-89c7-b2619e61bd3e.png">

**Comment by Tech0verlord** [comment] 2016-09-13 05:00
So I dragged the game on and got Guardian of the Gateless, a flier with the ability to block any number of creatures, and it wasn't able to block any of my opponents 7-ish fliers.

**Comment by stravant** [comment] 2016-09-13 05:14
Try with a simpler test case? I've definitely blocked multiple fliers with fliers since the update, so at the very least, the problem isn't simply the fliers themselves not working, but some other card interaction.

**Comment by Dilnu** [comment] 2016-09-13 10:59
In the first picture in this bug, it says Knight of Obligation is equipped with Skyblinder Staff, maybe there's a bug with that card for some reason?

**Comment by Tech0verlord** [comment] 2016-09-13 18:29
I assume it's skyblinder, seeing as it only happened after he came out. Seems like skyblinder is affecting all creatures from both players

**Comment by Dilnu** [comment] 2016-09-13 22:54
Alright, I figured out what was causing this issue I'll have a fix submitted shortly once I finish writing a test for it.

**Comment by Dilnu** [comment] 2016-09-14 00:53
Fixed by https://github.com/magefree/mage/pull/2266

**Closed by Dilnu** 2016-09-14 00:53 UTC
