### ISSUE TITLE
Problem with image/button rendering in Xmage in general

### ISSUE THREAD

**Issue by ThePal93** [magefree/mage#2508] opened 2016-10-27 16:37 UTC
[https://i.gyazo.com/2254dcbb085e3e36f40e826f24f98037.gif](url)
This happens often, normally after 10-40 min of me using the software, Java and Xmage's fully updated to the current date. Any help? (27th Sep 2016)

**Comment by Sertion** [comment] 2016-10-29 21:49
This is possibly a duplicate of #1514.

**Comment by iRoxor** [comment] 2016-11-04 09:07
Yeah, that's definitely the same bug with Java itself.

A quick fix is to unlock your taskbar and move it to any side of the screen and back to its original position and it will temporarily return the game back to normal for a short while.

**Comment by drmDev** [comment] 2017-03-07 15:40
This is a duplicate of #1514 the parent ticket on this issue so will be closed. Information added to main ticket.

**Closed by drmDev** 2017-03-07 15:40 UTC
