### ISSUE TITLE
Couldn't unmount zip files net.java.truevfs.kernel.spec.FsSyncException: zip:file:/E:/mage-full_1.4.54-dev_2024-09-09_11-34/xmage/mage-client/plugins/images/WC02.zip!/ - FsSyncException

### ISSUE THREAD

**Issue by Jerry70S** [magefree/mage#12855] opened 2024-09-12 18:04 UTC
Error type: Couldn't unmount zip files net.java.truevfs.kernel.spec.FsSyncException: zip:file:/E:/mage-full_1.4.54-dev_2024-09-09_11-34/xmage/mage-client/plugins/images/WC02.zip!/ - FsSyncException
Client version: 1.4.54-V2 (build: 2024-09-09 11:29)

zip:file:/E:/mage-full_1.4.54-dev_2024-09-09_11-34/xmage/mage-client/plugins/images/WC02.zip!/

Stack trace:
net.java.truevfs.kernel.impl.TargetArchiveController.close(TargetArchiveController.java:434)
net.java.truevfs.kernel.impl.TargetArchiveController.sync(TargetArchiveController.java:327)
net.java.truevfs.kernel.impl.ResourceController.sync(ResourceController.java:95)
net.java.truevfs.kernel.impl.CacheController.sync(CacheController.java:128)
net.java.truevfs.kernel.impl.SyncController.doSync(SyncController.java:263)
net.java.truevfs.kernel.impl.SyncController.sync(SyncController.java:243)
net.java.truevfs.kernel.impl.LockController$10.call(LockController.java:212)
net.java.truevfs.kernel.impl.LockController$10.call(LockController.java:208)
net.java.truevfs.kernel.impl.LockingStrategy$4.call(LockingStrategy.java:142)
net.java.truevfs.kernel.impl.LockController.sync(LockController.java:208)
and other 13 lines
Root caused by:
sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
java.nio.file.Files.newByteChannel(Files.java:361)
java.nio.file.Files.newByteChannel(Files.java:407)
java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
java.nio.file.Files.newInputStream(Files.java:152)
net.java.truevfs.driver.file.FileInputSocket.stream(FileInputSocket.java:45)
net.java.truecommons.cio.IoSockets$InputAdapter.stream(IoSockets.java:61)
and other 37 lines

**Comment by xenohedron** [comment] 2024-09-15 20:36
duplicate of #12833

**Closed by xenohedron** 2024-09-15 20:36 UTC
