### ISSUE TITLE
Suspend + Trinisphere incorrect interaction

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4996] opened 2018-06-02 13:00 UTC
After running out of time counters, suspend forces the owner of its card to cast the card without paying its mana cost if able. Certain effects like Trinisphere force a mana cost to be paid even in this scenario, and per the rules, if there is enough mana in the mana pool at this point to pay the cost, it must be paid. However, currently the caster may decline to pay the cost even if there is enough mana available in his pool.

**Comment by Zerrisx** [comment] 2020-07-08 01:42
This is no longer the rule, if it was before.  The caster may choose not to pay the tax, in which case the spell should stay in exile.  This seems to be the current behavior, so closing this as not a bug.

**Closed by Zerrisx** 2020-07-08 01:42 UTC

**Comment by emerald000** [comment] 2020-07-08 01:50
This is still the rule. If there is an additional cost to the cast the spell, you must pay it if able. You don't have to activate mana abilities if you don't want to, but if you have mana in your pool you must use it.

**Comment by Zerrisx** [comment] 2020-07-08 02:10
Per https://pucatrade.com/articles/2015/judgecorner3:

> Bonus Fact 3: Last corner case of the day: when a card is suspended, it is exiled with a certain amount of Time Counters and one of them is removed at the beginning of the owner's upkeep. When the last is removed, you're forced to cast the card without paying its mana cost, if able. Does that mean that if Trinisphere is on the battlefield I'm forced to tap my lands even if I don't want to? (Maybe because I want to save my mana for another spell). The rules come in our support here as well, and tell us that **activating mana abilities is not mandatory under any circumstance, even if paying a cost often can be.** So, in this case, you can choose to cast it and pay 3 by tapping your lands, or you can choose to leave your suspended card in exile for the rest of the game. However, if you were to find yourself with mana floating around (Perhaps because of Braid of Fire), you have use it to cast the suspended card, if it's enough.

And currently, if you have *floating* mana, the game will eat it, so that's being handled correctly.

**Comment by Zerrisx** [comment] 2020-07-08 02:14
It won't give you a choice on *which* floating mana it eats - looks like it's going in WUBERG order and grabs the first three it sees - but the odds you have multiple colors of floating mana in your upkeep *and* want to float it through the trinisphere cost seems to low that I honestly don't care enough to write up an issue for it.
