### ISSUE TITLE
CLB new mana gate lands

### ISSUE THREAD

**Issue by Devilboon** [magefree/mage#9382] opened 2022-08-18 04:57 UTC
It might speed up the game when lands like Cliffgate, Seagate etc. will automatically tap for the asked mana instead of asking the player which to choose. For example, when I play a spell that has a white mana symbol to pay and my Seagate can tap for either Blue or White then the Seagate could automatically choose white.

**Comment by Alex-Vasile** [comment] 2022-08-18 14:18
Duplicate of #9258

**Closed by Alex-Vasile** 2022-08-18 14:18 UTC
