### ISSUE TITLE
Can't cast cards from hand that were bounced after Etali cheated them in

### ISSUE THREAD

**Issue by jfreitas25** [magefree/mage#4647] opened 2018-03-22 01:48 UTC
Order of play:

1. Opponent cheats permanents using Etali
2. I used Cyclonic Rift on all his stuff
3. Any permanents that had been cheated in can no longer be cast from hand

All those permanents always have the purple "castable" border around them, even if you don't actually have enough mana to cast them.

**Comment by zeflap** [comment] 2018-03-31 15:20
Happened to me as well, the cards bring up a cast dialog that does nothing, instead of just prompting you to pay the mana cost and then resolving as usual.

**Comment by Zerrisx** [comment] 2020-07-07 18:18
Duplicate of #4600

**Closed by Zerrisx** 2020-07-07 18:18 UTC
Labels: cards
