### ISSUE TITLE
adding a condition on that only 100 mana is added with a combo.

### ISSUE THREAD

**Issue by PhyrexianHorror** [magefree/mage#8837] opened 2022-04-12 10:23 UTC
Hi, I hope you have a great day and that I am doing this right ^^ Browsed here for it but couldn't really find it.... My idea was for example with Grim Monolith or Basalt Monolith and PowerArtifact to have when its enchanted to either of them to obtain another 3rd ability that (lets say after the 4th. time) allows to also tap to add 100 colorless mana to the manapool. Now I am suggesting 4th, because the opponent might want to react to untapping or tapping it in one of the first few times. If he does not the player gets another ability from basalt monolith "unlocked" to add 100 mana to his or her manapool. Is something like this doable? I feel like clicking so many times is really frustrating for all players. Thank you very much :)

**Comment by sumsarz** [comment] 2022-04-16 17:54
Try recording a macro instead.

**Comment by Alex-Vasile** [comment] 2022-09-28 02:18
Duplicate of #2147.

**Closed by Alex-Vasile** 2022-09-28 02:18 UTC
