### ISSUE TITLE
[BUG] - Jegantha, The Wellspring

### ISSUE THREAD

**Issue by smolpp69** [magefree/mage#9819] opened 2022-12-19 21:08 UTC
[[Jegantha, The Wellspring]] doesn't float mana properly. When you tap Jegantha to add to mana pool, you can't always select that mana to use on spells (yes I'm accounting for the symbol restriction). Been using Jegantha in a Nivmizzit deck and it's an absolute nightmare to get it to work. Sometimes depending on the order you tap, it works, but most of the time the mana gets stuck in your pool and you can't use it on anything at all, so you sit there clicking like an idiot until you ultimately pass turn, losing all your mana and looking like a doofus, so I've heard.

**Comment by jeffwadsworth** [comment] 2022-12-19 23:21
https://github.com/magefree/mage/issues/8844

**Comment by xenohedron** [comment] 2023-06-17 04:46
Duplicate of #9796

**Closed by xenohedron** 2023-06-17 04:46 UTC
