### ISSUE TITLE
Umezawa's Jitte Bug

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#9129] opened 2022-06-19 04:40 UTC
- If a creature equipped with Umezawa's Jitte dies in combat, often time the Jitte will not receive counters.

**Comment by jeffwadsworth** [comment] 2022-06-20 16:10
[[Umezawa's Jitte]]

**Comment by jeffwadsworth** [comment] 2022-06-22 20:43
By the time "DamagedPermanentBatchEvent" or "DamagedPlayerBatchEvent" fires, the equipment or aura has already detached from the permanent, thus the check fails if the permanent leaves the battlefield, etc.  Other events, like "DamagedPermanentEvent" still allow for an accurate check of the equipment or aura still being attached to the permanent.

**Comment by Alex-Vasile** [comment] 2022-07-13 12:51
> By the time "DamagedPermanentBatchEvent" or "DamagedPlayerBatchEvent" fires, the equipment or aura has already detached from the permanent, thus the check fails if the permanent leaves the battlefield, etc. Other events, like "DamagedPermanentEvent" still allow for an accurate check of the equipment or aura still being attached to the permanent.

Is that difference supposed to occur?
Also why is `DealsCombatDamageEquippedTriggeredAbility` using `DamagedPermanentBatchEvent` instead of `DamagedPermanentEvent`?

**Comment by jeffwadsworth** [comment] 2022-07-13 16:23
If you do a search on the Discord channel, you will find references to it.  In order not to break anything, I left it alone.  Of course, the batch allows for one trigger fire versus many.

**Comment by Alex-Vasile** [comment] 2022-07-13 21:15
> > Also why is `DealsCombatDamageEquippedTriggeredAbility` using `DamagedPermanentBatchEvent` instead of `DamagedPermanentEvent`?
> 
> 
> 
> Suppose a creature with a "when this deals damage" ability (either its own ability or added by an aura or equipment) is double blocked, and deals damage to both of its blockers. Or the creature has trample and it deals damage both to its blocker and to the player it is attacking. According to the rules of Magic, each of these is a single instance of "dealing damage" and the creature's ability only triggers once, not once for each creature or player it dealt damage to. The "batch" events are how xmage handles this.

Right. I understood that part from  other cards with the distinction between "whenever a" and "whenever one or more".

I guess I was asking why does the Jitte specifically use the batch rather than non-batch. But the reply above covers it.

**Comment by Alex-Vasile** [comment] 2022-07-13 21:40
> If you do a search on the Discord channel, you will find references to it.  In order not to break anything, I left it alone.  Of course, the batch allows for one trigger fire versus many.

Thanks for the reply about the batch.

I couldn't find anything on discord. What is the rationale for having the batch events trigger afterwards?

**Comment by jeffwadsworth** [comment] 2022-07-13 21:55
It is just coded that way and needs to be fixed to align with the non-batch events.  We can assume that some other cards have the same issue.

**Comment by stevedavidmusic** [comment] 2022-07-13 21:57
> We can assume that some other cards have the same issue.

Eater of Virtue is still buggy, sometimes it doesn't exile the creature when it dies, perhaps the two are related?

**Comment by Alex-Vasile** [comment] 2022-07-18 14:43
Duplicate of #8555

**Comment by Chewbaklava** [comment] 2022-09-30 20:25
Any updates on progress?

**Closed** 2022-10-07 15:36 UTC
Labels: bug
