### ISSUE TITLE
Conduit of Ruin: Can't play card with higher converted mana cost than total mana. Reduced cost is only applied to card that there is already enough mana for.

### ISSUE THREAD

**Issue by dougr-code** [magefree/mage#6869] opened 2020-07-21 01:54 UTC
When conduit of ruin is out it will not allow cards with a converted mana cost great than total mana to be played. For example, if I have 13 mana and an Emrakul in my hand, I can't play it. However, if I go to play another card I do see its cost reduced by the correct amount of 2. If you include the double mana from the temples and all scions there is 13 mana in the image below.

![ManaShort](https://user-images.githubusercontent.com/64867335/88003768-7aba9f00-caba-11ea-8b4d-5d29a9ec38f1.PNG)

![ManaShort2](https://user-images.githubusercontent.com/64867335/88003778-7db58f80-caba-11ea-9c71-9e7d060711b6.PNG)

**Comment by Zerrisx** [comment] 2020-07-21 13:47
Duplicate of #6698, almost certainly.

**Comment by dougr-code** [comment] 2020-07-27 19:40
Much appreciated.

**Comment by Zerrisx** [comment] 2020-07-29 04:31
Fixed in beta by c1ac2ac; will be in next release..

**Closed by Zerrisx** 2020-07-29 04:31 UTC
