### ISSUE TITLE
Emrakul, the promised end bug

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2355] opened 2016-09-21 13:15 UTC
Hello,

When you take control of your opponent's turn, there are times when neither player gets priority, so no spell can be cast. Is this a known issue?

It usually fixes itself when several rollbacks are done.

**Comment by drmDev** [comment] 2017-03-07 16:33
I haven't been able to duplicate this issue but I hear about these cases sometimes.

**Comment by Zerrisx** [comment] 2020-06-26 01:10
Duplicate of #2088

**Closed by Zerrisx** 2020-06-26 01:10 UTC
Labels: bug, not confirmed
