### ISSUE TITLE
Disconnect bug

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7413] opened 2021-01-19 06:00 UTC
Sometimes when I cast terastodon xmage freezes and disconnects  
<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/64045003/104993582-0fae3e80-59f1-11eb-9fe4-c524004e61bd.png">

<img width="1920" alt="Untitled" src="https://user-images.githubusercontent.com/64045003/104993938-a549ce00-59f1-11eb-8333-00d0e9905056.png">

**Comment by Alex-Vasile** [comment] 2022-09-27 19:17
Based on the wording of [[Terastodon]] and you playing against AI, I think this is a duplicate of #9539.

**Closed by Alex-Vasile** 2022-09-27 19:17 UTC
