### ISSUE TITLE
Won't let me play Once Upon A Time as the First Spell Cast for free

### ISSUE THREAD

**Issue by Belli482** [magefree/mage#7684] opened 2021-03-20 22:24 UTC
![image](https://user-images.githubusercontent.com/78760053/111887136-43292d00-8990-11eb-98c9-678f7499257f.png)

**Comment by theelk801** [comment] 2021-03-20 23:41
was this during a match?

**Comment by Alex-Vasile** [comment] 2022-09-27 19:13
Duplicate of #6954

**Closed by Alex-Vasile** 2022-09-27 19:13 UTC
