### ISSUE TITLE
Unable to use cards obtained from Recollect BUG

### ISSUE THREAD

**Issue by EllNubNub** [magefree/mage#4639] opened 2018-03-19 12:22 UTC
replayed this card a few times during a match and was unable to cast any of the cards i got back with it. i was however able to use other cards that cast something from my hand for free to cast them. the cards i got back were either enchantments or instants.

**Comment by LevelX2** [comment] 2018-03-20 22:13
Recollect alone works correctly in my tests.
 
So how are the cards moved to graveyard? Any other cards involved?

**Comment by EllNubNub** [comment] 2018-03-21 02:12
hmm. well if it worked for you im not sure what was going on. but the cards went through multiple bouncing back to hand and destruction/discarding effects and some of them were cast using a cascade effect if that matters (the cards i got back with recollect that were uncastable). 

Cards used to bounce my own permanents: 
[Devastation Tide](http://gatherer.wizards.com/Pages/Card/Details.aspx?name=devastation+tide)
[Baral's Expertise](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423696)

Some of the cards unable to cast were [mana crypt](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=420603), [Memory plunder](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=433110), [Psychic Intrusion](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=373695), i think a [cyclonic rift](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=425860) and an [eternal witness](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=430326). i do also remember that one of those cards i listed, the mana crypt was only bounced back to my hand using devastation tide and i was unable to cast it. The rest i am sure i got back with Recollect and was unable to cast them again without using a card like baral's expertise to cast one of them.
Cascade effects:
[Yidris, Maelstrom Wielder](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=420667) - this was the main one
[Demonic Dread](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=185062)
[Shardless Agent](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423529)
[Violent Outburst](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=185056)
[Bloodvraid Elf](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423509)
[Kathari Remnant](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423523)
[Deny Reality](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423510)
[Bituminous Blast](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423508)
[Etherium-Horn Sorcerer](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=433103)
[Maelstrom Wanderer](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=423526)

**Comment by Zerrisx** [comment] 2020-07-07 18:18
Duplicate of #4600

**Closed by Zerrisx** 2020-07-07 18:18 UTC
Labels: cards
