### ISSUE TITLE
Issue with ETB triggers

### ISSUE THREAD

**Issue by Mercsetronics** [magefree/mage#11052] opened 2023-08-28 14:16 UTC
Dear Team!

Since the last update, 9 out of 10 times, whenever I cast a creature with its evoke cost, the window "choose which triggered ability goes on the stack first" does not appear.
If I try to relaunch the client, without disconnecting, I can rejoin my game, the window appears, but there are not abilities (or anything) in the window.
I cannot click anywere, I cannot text, cannot change window, forcing me to quit the match.

Previously I barely had any quit games, now I have doubled it due to this issue, as well as lost 100 places in rankings :(

I have tried to update Java, force update the client, but nothing seems to be working,

If you could propose me a solution, I would be greatful.

Thank you for your time!

**Comment by xenohedron** [comment] 2023-08-28 15:42
Sounds like #8851. It's real annoying, hard to reproduce consistently but still breaks games every so often. Hasn't yet been investigated and I'm not sure really where to start. I doubt it is specific to recent update though.

**Comment by JayDi85** [comment] 2023-08-28 17:54
There are possible bugs with player's priority lost on broken continues/replacement effect. Maybe `/fix` command in the chat can help, but it useless in most use cases.

Game engine support only one choose dialog per player. If some broken effect try to ask a player in the middle of game cycle then it will broke original dialog. Examples: 
* continues or cost reduction effect try to call choose dialog on `apply` method;
* another effect try to call choose dialog in `applies` method instead `apply`;

So try to find another active/buggy card. It's can be a real reason.

**Comment by Mercsetronics** [comment] 2023-08-29 06:41
When this occurs I cannot use the chat or click anywhere in fact. 
Seems like the issue happens 100% when I cast Fury with evoke, 90% when I cast Grief with evoke.
The issue just happened again, I tried the cold restart of client about 12 times, but does not resolves the issue.

**Comment by Mercsetronics** [comment] 2023-08-29 09:13
Now the issue happened with Kroxa as well.

**Comment by Susucre** [comment] 2023-08-29 11:05
Is that all in the same deck?
Can you link it, there might be a card inside that makes the issue reproducible.

**Comment by Mercsetronics** [comment] 2023-08-29 11:10
How can I link my deck on Xmage here?

**Comment by Susucre** [comment] 2023-08-29 11:12
Just paste or drag on drop the .dck file. github takes care of upload and linking it.

**Comment by Mercsetronics** [comment] 2023-08-29 11:17
For some reason it does not allow me, it says it is unsupported.

Also, same happened to a player: "11:45: Ogoun Badagris: Rich: sorry... game was asking me to choose order to stack triggered abilities, but it completely froze up the client. I couldn't do anything, couldn't even type a response"

**Comment by Mercsetronics** [comment] 2023-08-29 11:17
3 [ARB:46] Terminate
3 [ONE:248] Blackcleave Cliffs
4 [RNA:245] Blood Crypt
2 [THS:107] Thoughtseize
2 [KTK:239] Polluted Delta
4 [KTK:230] Bloodstained Mire
4 [MH2:397] Dauthi Voidwalker
4 [MH2:311] Grief
4 [MH2:126] Fury
3 [AFR:103] Feign Death
3 [VOW:134] Undying Malice
2 [SLU:1] Marsh Flats
4 [MH2:138] Ragavan, Nimble Pilferer
1 [UNF:238] Mountain
2 [UNF:237] Swamp
1 [AFR:258] Hive of the Eye Tyrant
4 [NEO:141] Fable of the Mirror-Breaker
4 [LTR:103] Orcish Bowmasters
2 [USG:132] Duress
2 [HA5:20] Kolaghan's Command
2 [3ED:162] Lightning Bolt
1 [THB:221] Kroxa, Titan of Death's Hunger
SB: 2 [5DN:118] Engineered Explosives
SB: 2 [NEO:221] Hidetsugu Consumes All
SB: 2 [2X2:94] Surgical Extraction
SB: 1 [VOW:124] Path of Peril
SB: 2 [TSR:326] Leyline of the Void
SB: 1 [BRO:128] Brotherhood's End
SB: 2 [MH2:102] Tourach, Dread Cantor
SB: 1 [DMU:331] Sheoldred, the Apocalypse
SB: 2 [9ED:176] Blood Moon

**Comment by Susucre** [comment] 2023-08-29 11:32
Yeah I could not reproduce, cast all three around 10 times with no problem.
This might be a network code issue or a server under heavy charge issue, that I am not able to replicate locally.

**Comment by Mercsetronics** [comment] 2023-08-29 12:27
That is unfortunate. If that helps, I have never faced this issue before, only since I have updated to the current version

**Comment by JayDi85** [comment] 2023-08-29 12:42
@Mercsetronics as a last chance -- you can reset xmage settings to default by delete all values in `HKEY_CURRENT_USER\Software\JavaSoft\Prefs\mage\client` (see [here for example](https://github.com/magefree/mage/issues/4461#issuecomment-361108597)). But be careful -- you will lost all changed hot keys, new game settings, saved password, images paths, etc.

**Comment by Mercsetronics** [comment] 2023-08-30 06:44
I tried @JayDi85 recommendation, but the problem still persist, even though a bit less frequently

**Comment by Mercsetronics** [comment] 2023-08-30 12:01
Tried deleting and reinstalling the whole thing, first game and it still does not work

**Comment by Mercsetronics** [comment] 2023-09-03 19:54
After the update, it still does not work

**Comment by Mercsetronics** [comment] 2023-09-04 12:27
Tried a clean install once again, removing that value from regedit, but still does not work

**Comment by Mercsetronics** [comment] 2023-09-04 14:13
Is there a way to reposition the window somehow, once it is supposed to appear?

**Comment by JayDi85** [comment] 2023-09-05 02:05
@Mercsetronics did you member when it all starting? Is it works fine before August 25?

**Comment by xenohedron** [comment] 2023-09-05 02:26
Over the past week or so, there's definitely been an uptick in reports (on Discord) of game getting stuck when asking to order triggers. It still sounds like #8851, and I know we experienced it a few times back in July and earlier (specifically on Patagia Viper at least twice). I am not sure what recent adjustment could have increased the frequency of this issue. Seems like it happens with quite a few different cards/effects.

**Comment by Mercsetronics** [comment] 2023-09-11 08:09
@JayDi85 prior to the release 2 weeks ago, it was working fine. Then around the 27 of August, after the update it stopped working.

**Comment by JayDi85** [comment] 2023-09-18 10:48
@Mercsetronics if you catch that bug then collapse and expand app's window (change window size) to call game update -- it will show choose triggers dialog again.

**Comment by Mercsetronics** [comment] 2023-09-21 11:20
@JayDi85 I tried what you have mentioned, it fixes the freeze, but the dialog window does not appear still

**Comment by Mercsetronics** [comment] 2023-09-21 11:23
I tried again the above, the window appears if I click on any cards in my hand, thank you!!

**Comment by JayDi85** [comment] 2023-09-21 14:48
fixed by #11189

**Closed by JayDi85** 2023-09-21 14:48 UTC
Labels: support
