### ISSUE TITLE
UI bug in Prowl Cost

### ISSUE THREAD

**Issue by skaspels** [magefree/mage#12051] opened 2024-04-02 14:39 UTC
I have been using [[hunting velociraptor]] in a dinosaur deck. It happens that when I have done damage to opponent so that I can cast dinosaurs for prowl cost, the UI prevents me from playing the dinosaurs. Screenshot attached:
![prwol dino error](https://github.com/magefree/mage/assets/154446328/ef5d43ab-586f-44ea-ac70-558cc7ce9388)
notice that the UI tells me that prowl is activated, and that I have mana to cast the dinosaur's prowl cost; but the UI does not let me activate the prowl ability to cast the creature.
I discovered that if I have enough open mana to cast the creature naturally, THEN the UI allows me to cast it for the alternative prowl cost, but that if I don't have the mana up to cast the creature naturally, the UI will never let me select the creature to cast it for its alternative cost.

**Comment by xenohedron** [comment] 2024-04-02 14:57
Duplicate of #11714

**Closed** 2024-04-02 14:58 UTC
Labels: bug
