### ISSUE TITLE
Unable to pay for / play spells

### ISSUE THREAD

**Issue by ianelletson** [magefree/mage#2172] opened 2016-08-16 20:31 UTC
Casting and paying for spells causes lands to repeatedly tap and untap, the mana is added once to my pool but doesn't empty. Occasionally, I seem to be able to play the spell but it doesn't appear if it's a permanent and I can't interact with it. This happened immediately after updating to the newest version (as of last night, 2016-08-15).

**Comment by drmDev** [comment] 2017-03-07 16:41
Is this issue still occurring? game log?

**Comment by Zerrisx** [comment] 2020-06-26 01:29
Three years later and no further reports of this, I'm closing as not a bug/not reproducible/latency/fixed.  Whatever the case, it doesn't seem to be an ongoing issue for users.

**Closed by Zerrisx** 2020-06-26 01:29 UTC
Labels: not confirmed
