### ISSUE TITLE
[NCC] Caldaia Guardian draws card on death when it's not supposed to in certain scenarios.

### ISSUE THREAD

**Issue by stevedavidmusic** [magefree/mage#9592] opened 2022-09-29 03:39 UTC
Ran into an issue where Caldaia Guardian drew a card when recurring it / sacrificing it on the same turn with Recurring Nightmare. It wasn't blitzed that turn obviously because it ETB'd via Recurring Nightmare, but it's important to note that it was blitzed earlier in the game. 

I tested the same scenario where said Caldaia Guardian WASN'T blitzed earlier in the game, and it didn't draw a card in later turns when it was recurred / sacrificed to Recurring Nightmare. I also tested where two different Caldaia Guardians, one that was blitzed and one that wasn't blitzed and recurred / sacrificed them with Recurring Nightmare. The one that was blitzed in a previous turn drew a card on death, the one that wasn't blitzed previously did NOT draw a card on death.

<img width="1276" alt="Caldaia Guardian Bug" src="https://user-images.githubusercontent.com/45299811/192933399-666745c8-7571-4cec-89f4-600e970e799f.png">

**Comment by stevedavidmusic** [comment] 2022-09-29 03:42
Ran into an issue where Caldaia Guardian drew a card when recurring it / sacrificing it on the same turn with Recurring Nightmare. It wasn't blitzed that turn obviously because it ETB'd via Recurring Nightmare, but it's important to note that it was blitzed earlier in the game. 

I tested the same scenario where said Caldaia Guardian WASN'T blitzed, and it didn't draw a card when it was recurred / sacrificed to Recurring Nightmare. I also tested where two different Caldaia Guardians, one that was blitzed and one that wasn't blitzed and recurred / sacrificed them with Recurring Nightmare. The one that was blitzed in a previous turn drew a card on death, the one that wasn't blitzed previously did NOT draw a card on death.

<img width="1276" alt="Caldaia Guardian Bug" src="https://user-images.githubusercontent.com/45299811/192933399-666745c8-7571-4cec-89f4-600e970e799f.png">

**Comment by Alex-Vasile** [comment] 2022-09-29 04:18
[[Caldaia Guardians]], [[Recurring Nightmare]]

**Comment by Alex-Vasile** [comment] 2022-09-29 04:19
[[Caldaia Guardian]]

**Comment by awjackson** [comment] 2022-09-29 12:42
Duplicate of #8885

**Closed by awjackson** 2022-09-29 12:42 UTC
Labels: bug, duplicate
