### ISSUE TITLE
about:create a tournament, if the submitted time is inconsistent (about 1-2 minutes), it will easily cause the game to be lost and cannot match.

### ISSUE THREAD

**Issue by siyiye** [magefree/mage#5447] opened 2018-11-29 02:42 UTC
example:
create a tournament, if the submitted time is inconsistent (about 1-2 minutes), it will easily cause the game to be lost and cannot match.

Now only the decks are formed, and the public channel is ordered to click and submit together - can you guarantee the time of the group (15 minutes for example), i can submit it at any time?

**Comment by Zerrisx** [comment] 2020-07-02 21:28
Pretty sure this is a duplicate of #5555.  If it's not, can you provide additional clarification?

**Closed by Zerrisx** 2020-07-02 21:28 UTC
