### ISSUE TITLE
Game froze claiming to wait for player 4 while player 3's clock was ticking.

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#4606] opened 2018-03-12 04:03 UTC
This happened in a FFA 4-player multiplayer game on the first round.
Game log attached.
[game-34d2da09-10b0-40bf-90dc-c266094c2df4.json.zip](https://github.com/magefree/mage/files/1801374/game-34d2da09-10b0-40bf-90dc-c266094c2df4.json.zip)

**Comment by spjspj** [comment] 2018-03-12 05:21
There is now the /game chat command that should let you know current stats about the game.

**Comment by Zerrisx** [comment] 2020-07-02 21:16
Duplicate of #4534

**Closed by Zerrisx** 2020-07-02 21:16 UTC
