### ISSUE TITLE
Screen elements jump and draw randomly over game screen (graphic card driver issue)

### ISSUE THREAD

**Issue by ianelletson** [magefree/mage#1514] opened 2016-02-03 04:48 UTC
![image](https://cloud.githubusercontent.com/assets/1207114/12773245/303d452e-c9ff-11e5-9a41-57bf8709f305.png)

Seems to happen when I play any deck that sees another player's hand or cares about the exile zone e.g. Storm and Bx Eldrazi.

I'm running Windows 10. Let me know if I can provide anything more to help.

**Comment by ianelletson** [comment] 2016-02-04 06:22
I was using dual monitors but I tried with just one monitor and the error persisted. It happens frequently (but not 100% of the time) when viewing a pop-up zone of cards.

**Comment by LevelX2** [comment] 2016-02-04 08:28
I can remember some user having problems like that related to size and usage of background image and used screen resolution.

I would first try to switch off background image of xmage and check if that has any influence.

I guess graphics card driver is up-to-date?

**Comment by ianelletson** [comment] 2016-02-04 17:15
My GTX 970 drivers are up to date. I will try to switch off the background image and report back if that is a workaround.

**Comment by ianelletson** [comment] 2016-02-09 19:26
Not to jinx it but turning off the background image (in the options) has seemed to mostly fix the problem. However, the background image still exists while I play.

**Comment by ianelletson** [comment] 2016-02-13 01:16
The issue came back again yesterday. Seemed to come up the same way.

**Comment by maalsol** [comment] 2016-03-01 23:59
I'm experiencing this whenever I cast Ancient Strrings.

**Comment by CplCuddles** [comment] 2016-03-04 13:05
I'm having this same problem, It seems to be random. If someone finds a way to fix it, tell me pls.

**Comment by LevelX2** [comment] 2016-03-04 14:27
Please all people that encounter that problem should post operating system, version of OS, used screen resolution and used graphics card type.
Maybe we get some relations that help us to identify the problem.

**Comment by ianelletson** [comment] 2016-03-04 14:56
My resolution is 1920x1080 and 1080x1920 for my secondary

**Comment by CplCuddles** [comment] 2016-03-04 20:18
Here are my specs.
![computer](https://cloud.githubusercontent.com/assets/17643961/13539089/d58d4e76-e213-11e5-8731-6c13c3f1d679.png)

**Comment by rkfg** [comment] 2016-03-04 20:24
@CplCuddles do you also have two displays?

**Comment by CplCuddles** [comment] 2016-03-04 20:25
@rkfg I do not.

**Comment by CplCuddles** [comment] 2016-03-04 20:38
Here is a vid of it happening, if that helps.
https://www.youtube.com/watch?v=EcK5JCI_FIQ

**Comment by LevelX2** [comment] 2016-03-05 08:04
Can you check if using the 3D setting for Java like shown here does help you?

https://www.youtube.com/watch?v=UWu3dyXlbAM

**Comment by CplCuddles** [comment] 2016-03-05 09:53
I don't have a selector as he did, I'm not running my integrated graphics at all, so it is irrelevant.

**Comment by rkfg** [comment] 2016-03-05 10:09
On a side note, this text glitches occur to me on Linux as well when I use SNA acceleration (it's on by default), after switching to UXA it's all good.

However, I'm of little help as I don't have windows installed anywhere. It would help to know the exact graphics driver version, just "up to date" isn't enough. There are beta drivers, you may try it. Certainly doesn't look like a game problem but could be related to JVM internals and/or drivers. For example, on Java 8 and Intel GPU I have a tiled image in the card preview panel (on the battlefield) and launcher, tiles are about 128x128 pixels I guess... On another PC with NVIDIA GPU it's all right on the same config. The game uses its own bundled Java so I don't think it's worth a report as it's an artificial environment.

**Comment by CplCuddles** [comment] 2016-03-05 10:23
The game I'm currently in it started when the "Permanent - Exile" window popped up. Which I can't seem to close either.

**Comment by rkfg** [comment] 2016-03-05 10:25
Is that related to the issue? This exile window can only be minimized, it doesn't have a close button.

**Comment by CplCuddles** [comment] 2016-03-05 10:39
It starts happening about half the time when that exile window pops up, if that would be considered related.

**Comment by maalsol** [comment] 2016-03-07 20:08
I think this issue is related to JVM. I encountered the same behavior while using a java-based P2P app yesterday, which is not related at all with XMage.

**Comment by CplCuddles** [comment] 2016-03-08 07:57
Well, I'd love to know how to fix it. It really have begun to irritate me quite badly. It happens almost every single game.

**Comment by LevelX2** [comment] 2016-03-08 08:51
> Well, I'd love to know how to fix it. It really have begun to irritate me quite badly. It happens almost every single game.

Probably you have to tweak/update/downgrade/setup your graphics card driver. It's nothing that we can do by changing xmage.

**Comment by CplCuddles** [comment] 2016-03-08 10:41
tweak/update/downgrade/setup is quite a broad spectrum of possibilities. I switched it to run from the newest java update (I think.)

**Comment by CplCuddles** [comment] 2016-03-08 11:39
Running a different java type did not help.

**Comment by rkfg** [comment] 2016-03-08 11:48
So what's your exact videodriver version? Did you try beta version of it or downgrading it?

**Comment by CplCuddles** [comment] 2016-03-09 00:38
My current driver is 362.00, I updated last night. I will play with it and see if I encounter the problem again.

**Comment by rkfg** [comment] 2016-03-09 00:42
There's also 364.51, released just yesterday. Give it a try if 362.00 doesn't help.

**Comment by CplCuddles** [comment] 2016-03-09 03:05
It did end up happening again, I updated to 364.51. Testing now.

**Comment by eternalnami** [comment] 2016-03-14 07:03
It happened to me, 1080p dual monitor.  980ti, running driver 364.51.  All zones are default other than making chat smaller via the in match slider bar.

**Comment by LevelX2** [comment] 2016-04-16 14:24
Reported:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=18463&start=45#p195492

**Comment by Okiesmokie** [comment] 2016-07-27 23:26
I very highly doubt it's a graphics card issue as I have two monitors both running off the same graphics card.  This issue only happens on my main monitor running at 1080p.  When I drag it to my second monitor that is running 1440x900, the issue does not happen at all.  It seems more like an issue with XMage adjusting to higher resolutions when certain things happen, but I have not been able to narrow down exactly what causes it to happen.

**Comment by drmDev** [comment] 2016-07-28 00:27
Interesting... thanks for letting us know. Sounds like dual monitor setups are more likely to run into this problem looking back at the discussion above.

**Comment by drmDev** [comment] 2016-08-14 14:40
From #2166 we have another report of another commonality being a dual monitor setup. How that would possibly interact so Java apps or XMage specifically causes this issue, I have no idea.

**Comment by Okiesmokie** [comment] 2016-08-14 21:27
This issue seemed to be fixed in the previous version for me.  Upon updating to 1.4.14 it has resurfaced.

**Comment by drmDev** [comment] 2016-08-14 22:10
Don't believe there was any change relevant to the UI. More likely it was coincidental the issue resurfaced now than something introduced in this new version. Though again, still not sure what the cause of the issue is in the first place.

**Comment by Okiesmokie** [comment] 2016-08-14 22:36
Yeah I went through the commits to see if I could find anything, but nothing seems relevant.  Very strange though because the bug happens nearly every single game when it is surfacing, but it didn't happen at all under the previous version.

**Comment by kester13** [comment] 2016-08-16 14:05
Nothing from this thread seems to resolve this issue. Only using one single monitor at 2560x1440 resolution. No update on graphics card driver for the past month or so. Forced to move to old laptop running OSX. No problem there.

**Comment by Navyguy330** [comment] 2016-08-16 20:14
FEB  seriously wtf people fix this shit

**Comment by fwannmacher** [comment] 2016-08-16 20:27
@Navyguy330 if it was simple to fix, believe me, we would have already fixed that. To be sincere, I think we can't even fix that because it seems to be an issue with some particular video drivers.

**Comment by ianelletson** [comment] 2016-08-16 20:28
@Navyguy330 please don't be so rude, these people are providing a great free program and are working hard on it. You are free to (constructively) contribute.

**Comment by fwannmacher** [comment] 2016-08-16 20:33
Could some one try this? https://www.youtube.com/watch?v=UWu3dyXlbAM
Just select the Java binary (jre) downloaded by the launcher.

**Comment by Fr33dan** [comment] 2016-08-16 23:32
@fwannmacher I am the person from #2166. I attempted to try what was in the video but it is not valid for my case. I am on an AMD card. I looked for equivalent settings in their drivers but could not find any.

**Comment by fwannmacher** [comment] 2016-08-17 00:27
@Fr33dan please, install the latest java version. After that, go to your xmage installation folder. You should be able to navigate the following folders xmage/mage-client/lib.

Inside the lib folder, open a cmd and run xmage using javaw -Xms256m -Xmx512m -XX:MaxPermSize=384m -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -jar .\lib\mage-client-1.4.14.jar

See if the new java version fixes the issue and post the result here :-)

**Comment by Fr33dan** [comment] 2016-08-17 02:43
I tried, it seemed like it might work for awhile, but then on my third match it started back up.

**Comment by kester13** [comment] 2016-08-17 03:36
I downloaded and installed Java 8 Update 102. Didn't start using java 8 though, since i used xmage launched using the launcher. And I had selected to use the default image. The problem seems to have gone away for now. Not sure if any actually solve this. Just been watching some matches to test, so far the tearing problem has not resurfaced.

Will update.

**Comment by kester13** [comment] 2016-08-17 04:27
Not sure if this is relevant or may have clues to the cause. From what I had observed, the tearing issue had happened quite randomly in matches. Can be in middle of the first match, or the fifth match. I found that by scrolling up and down clears the tearing for awhile, just enough for me to see the board and play some targeting spells and have a view of the board. I guess, temporarily if anyone has the same problem, perhaps scroll up and down (using the mouse wheel) to perhaps play when the tearing appears mid-game. And restart XMage application again once the tearing has surfaced.

I also noticed that the tearing problem WILL definitely appears when I scrolled (up and down) the player list on Tables. So far, it happens to me all the time. Not randomly like those in matches.

Huge thanks for the devs for the support of this great app :+1:

**Comment by Quartz99** [comment] 2016-09-06 13:21
Having the same issue, but i don't run dual monitor...

**Comment by LevelX2** [comment] 2016-09-14 17:55
Created a launcher config to use Java 8.
Would be nice if some people with that problem could check if that helps.

Set your Xmage Home to "http://xmage.de/xmage1.4.15v1J8" to update Java and check if it helps you to run xmage with Java 8. Please report if you get the same errors or if it does resolve the problem.

**Comment by LevelX2** [comment] 2016-09-14 18:33
@Quartz99 Maybe this helps
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=18680&p=197408&hilit=Software%5CJavaSoft%5CPrefs#p197408

**Comment by Navyguy330** [comment] 2016-09-14 18:36
I can try but that's not the same error in getting.

**Comment by Navyguy330** [comment] 2016-09-15 03:13
nothing has changed. tried all of these methods. and even removed java, checked the PATH variables, and reinstalled. no avail.

**Comment by LevelX2** [comment] 2016-09-15 11:53
Hasn't the graphics card some setting to act in a basic mode (e.g. without acceleration or so)?
Would be interesting to know if that has any influence. 

At least I see no approach how we can solve your problem within XMage coding.

**Comment by iRoxor** [comment] 2016-09-17 06:17
It seems that downgrading the client to the beta version (1.4.12v0) stops this problem from occurring entirely. I've played a Lantern deck, one that pretty much always causes the screen tearing effect because of how much it causes hand checking and "top card of library is face-up" actions, and had no problems at all with the beta client.

The only issue with this, however, is that I am unable to play with Eldritch Moon and newer packs as they are not coded in with such an early version of XMage.

**Comment by Roboreaper** [comment] 2016-09-29 12:16
i've had these issues as well.
they usually appears when moving the scroll bar of the GY or exile zone. but i can also force it by scrolling through the users in the game windows.

but since the UI update last week. it did not occur yet.

**Comment by LevelX2** [comment] 2016-09-29 12:52
> but since the UI update last week. it did not occur yet.

You mean the client update to 1.5.15v5?

**Comment by iRoxor** [comment] 2016-10-04 04:34
So I had stumbled upon something really interesting... and as it turns out...

It's not even XMage's fault at all. It's actually Java.

I've had this same bug occur on an entirely different game that is also coded in Java. The same screen tearing occurs whenever a pop-up window is involved (in this case with the game I was playing, it happened after trying to save/load).

There must be something wrong with the way Java handles new window pop-ups.

**Comment by drmDev** [comment] 2016-10-04 11:49
We've been pretty sure it isn't related to the code in XMage for a while now. Even if we want to conclude it's a problem with Java, it still doesn't tell the full tale. Why does it only happen for certain users and why does it suddenly happen for them when they were fine before? The real cause is still unknown - some mix of Java and users individual environment (drivers, OS, etc).

**Comment by Godless-Soldier** [comment] 2016-11-15 22:49
Screen Tearing still an Issue? Any known fixes? Xmage 1.4.18v0 still happening. I can't use the launcher so I use the Zip files. Extract and open....Launch from there. Screen tears after a couple minutes into a match.

**Comment by drmDev** [comment] 2017-03-06 19:29
From #2611 we have some stack traces when this may have occurred:

```
FATAL 2016-11-20 17:48:58,600 MAGE Client UI error                                                                       =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
    at mage.cards.repository.ExpansionRepository.getSetCodes(ExpansionRepository.java:64)
    at org.mage.card.arcane.ManaSymbols.loadImages(ManaSymbols.java:53)
    at mage.client.MageFrame.<init>(MageFrame.java:291)
    at mage.client.MageFrame$22.run(MageFrame.java:1296)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
```

and

```
FATAL 2016-11-20 17:26:32,691 MAGE Client UI error                                                                       =>[Thread-1] EDTExceptionHandler.handle 
net.java.truevfs.kernel.spec.FsSyncException: zip:file:/D:/Users/ksakw_000/Downloads/xmage/mage-client/plugins/images/OGW.thumb.zip!/
	at net.java.truevfs.kernel.impl.TargetArchiveController$$anonfun$close$2.apply(TargetArchiveController.scala:357)
	at net.java.truevfs.kernel.impl.TargetArchiveController$$anonfun$close$2.apply(TargetArchiveController.scala:349)
	at scala.Option.foreach(Option.scala:257)
	at net.java.truevfs.kernel.impl.TargetArchiveController.close(TargetArchiveController.scala:349)
	at net.java.truevfs.kernel.impl.TargetArchiveController.sync(TargetArchiveController.scala:253)
	at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$ResourceController$$super$sync(DefaultManager.scala:158)
	at net.java.truevfs.kernel.impl.ResourceController$class.sync(ResourceController.scala:70)
	at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$CacheController$$super$sync(DefaultManager.scala:158)
	at net.java.truevfs.kernel.impl.CacheController$class.sync(CacheController.scala:116)
	at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$SyncController$$super$sync(DefaultManager.scala:158)
	at net.java.truevfs.kernel.impl.SyncController$class.doSync(SyncController.scala:172)
	at net.java.truevfs.kernel.impl.SyncController$class.sync(SyncController.scala:149)
	at net.java.truevfs.kernel.impl.DefaultManager$BackController.net$java$truevfs$kernel$impl$LockController$$super$sync(DefaultManager.scala:158)
	at net.java.truevfs.kernel.impl.LockController$$anonfun$sync$1.apply$mcV$sp(LockController.scala:96)
	at net.java.truevfs.kernel.impl.LockController$$anonfun$sync$1.apply(LockController.scala:96)
	at net.java.truevfs.kernel.impl.LockController$$anonfun$sync$1.apply(LockController.scala:96)
	at net.java.truevfs.kernel.impl.LockingStrategy.apply(LockingStrategy.scala:84)
	at net.java.truevfs.kernel.impl.LockController$class.sync(LockController.scala:96)
	at net.java.truevfs.kernel.impl.DefaultManager$BackController.sync(DefaultManager.scala:158)
	at net.java.truevfs.kernel.impl.ArchiveControllerAdapter.sync(ArchiveControllerAdapter.scala:37)
	at net.java.truevfs.comp.zipdriver.AbstractKeyController.sync(AbstractKeyController.java:147)
	at net.java.truevfs.kernel.spec.FsDecoratingController.sync(FsDecoratingController.java:117)
	at net.java.truevfs.kernel.impl.FalsePositiveArchiveController.sync(FalsePositiveArchiveController.scala:157)
	at net.java.truevfs.kernel.spec.FsControllerSyncVisitor.visit(FsControllerSyncVisitor.java:49)
	at net.java.truevfs.kernel.spec.FsControllerSyncVisitor.visit(FsControllerSyncVisitor.java:22)
	at net.java.truevfs.kernel.spec.FsAbstractManager$1AssembleExceptionVisitor.visit(FsAbstractManager.java:34)
	at net.java.truevfs.kernel.spec.FsAbstractManager$1AssembleExceptionVisitor.visit(FsAbstractManager.java:30)
	at net.java.truevfs.kernel.impl.DefaultManager$$anonfun$accept$3.apply(DefaultManager.scala:95)
	at net.java.truevfs.kernel.impl.DefaultManager$$anonfun$accept$3.apply(DefaultManager.scala:95)
	at scala.collection.Iterator$class.foreach(Iterator.scala:750)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at net.java.truevfs.kernel.impl.DefaultManager.accept(DefaultManager.scala:95)
	at net.java.truevfs.kernel.spec.FsAbstractManager.sync(FsAbstractManager.java:39)
	at net.java.truevfs.kernel.impl.DefaultManager.sync(DefaultManager.scala:87)
	at net.java.truevfs.kernel.impl.DefaultManager$$anonfun$1.apply$mcV$sp(DefaultManager.scala:37)
	at net.java.truevfs.kernel.impl.ShutdownFuse$$anonfun$net$java$truevfs$kernel$impl$ShutdownFuse$$onDisarm$2.apply$mcV$sp(ShutdownFuse.scala:55)
	at net.java.truevfs.kernel.impl.ShutdownFuse.net$java$truevfs$kernel$impl$ShutdownFuse$$onCondition(ShutdownFuse.scala:61)
	at net.java.truevfs.kernel.impl.ShutdownFuse.net$java$truevfs$kernel$impl$ShutdownFuse$$onDisarm(ShutdownFuse.scala:53)
	at net.java.truevfs.kernel.impl.ShutdownFuse$$anon$1.run(ShutdownFuse.scala:29)
	Suppressed: net.java.truevfs.kernel.spec.FsSyncException: zip:file:/D:/Users/ksakw_000/Downloads/xmage/mage-client/plugins/images/KLD.thumb.zip!/
		... 41 more
	Caused by: java.nio.file.AccessDeniedException: D:\Users\ksakw_000\Downloads\xmage\mage-client\plugins\images\KLD.thumb.zip
		at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
		at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
		at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
		at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
		at java.nio.file.Files.newOutputStream(Unknown Source)
		at net.java.truevfs.driver.file.FileOutputSocket$1Stream.<init>(FileOutputSocket.java:240)
		at net.java.truevfs.driver.file.FileOutputSocket.stream(FileOutputSocket.java:254)
		at net.java.truecommons.cio.IoSockets$OutputAdapter.stream(IoSockets.java:84)
		at net.java.truecommons.io.Streams.copy(Streams.java:82)
		at net.java.truecommons.cio.IoSockets.copy(IoSockets.java:43)
		at net.java.truevfs.driver.file.FileOutputSocket.close(FileOutputSocket.java:163)
		at net.java.truevfs.driver.file.FileOutputSocket$1Stream.close(FileOutputSocket.java:248)
		at net.java.truecommons.io.DecoratingOutputStream.close(DecoratingOutputStream.java:56)
		at net.java.truevfs.comp.zip.AbstractZipOutputStream.close(AbstractZipOutputStream.java:681)
		at net.java.truevfs.comp.zipdriver.ZipOutputService.close(ZipOutputService.java:272)
		at net.java.truevfs.kernel.spec.cio.MultiplexingOutputService.close(MultiplexingOutputService.java:155)
		at net.java.truecommons.cio.DecoratingOutputService.close(DecoratingOutputService.java:32)
		at net.java.truevfs.kernel.impl.DisconnectingOutputService.net$java$truevfs$kernel$impl$CheckedCloseable$$super$close(DisconnectingOutputService.scala:28)
		at net.java.truevfs.kernel.impl.CheckedCloseable$class.close(CheckedCloseable.scala:25)
		at net.java.truevfs.kernel.impl.DisconnectingOutputService.close(DisconnectingOutputService.scala:28)
		at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply$mcV$sp(LockOutputService.scala:30)
		at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply(LockOutputService.scala:30)
		at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply(LockOutputService.scala:30)
		at net.java.truevfs.kernel.impl.LockOn$.apply(LockOn.scala:23)
		at net.java.truevfs.kernel.impl.LockAspect$$anonfun$locked$1.apply(LockAspect.scala:21)
		at net.java.truevfs.kernel.impl.LockAspect$$anonfun$locked$1.apply(LockAspect.scala:21)
		at net.java.truevfs.kernel.impl.LockOutputService.close(LockOutputService.scala:30)
		at net.java.truevfs.kernel.impl.TargetArchiveController$$anonfun$close$2.apply(TargetArchiveController.scala:351)
		... 40 more
Caused by: java.nio.file.AccessDeniedException: D:\Users\ksakw_000\Downloads\xmage\mage-client\plugins\images\OGW.thumb.zip
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
	at java.nio.file.Files.newOutputStream(Unknown Source)
	at net.java.truevfs.driver.file.FileOutputSocket$1Stream.<init>(FileOutputSocket.java:240)
	at net.java.truevfs.driver.file.FileOutputSocket.stream(FileOutputSocket.java:254)
	at net.java.truecommons.cio.IoSockets$OutputAdapter.stream(IoSockets.java:84)
	at net.java.truecommons.io.Streams.copy(Streams.java:82)
	at net.java.truecommons.cio.IoSockets.copy(IoSockets.java:43)
	at net.java.truevfs.driver.file.FileOutputSocket.close(FileOutputSocket.java:163)
	at net.java.truevfs.driver.file.FileOutputSocket$1Stream.close(FileOutputSocket.java:248)
	at net.java.truecommons.io.DecoratingOutputStream.close(DecoratingOutputStream.java:56)
	at net.java.truevfs.comp.zip.AbstractZipOutputStream.close(AbstractZipOutputStream.java:681)
	at net.java.truevfs.comp.zipdriver.ZipOutputService.close(ZipOutputService.java:272)
	at net.java.truevfs.kernel.spec.cio.MultiplexingOutputService.close(MultiplexingOutputService.java:155)
	at net.java.truecommons.cio.DecoratingOutputService.close(DecoratingOutputService.java:32)
	at net.java.truevfs.kernel.impl.DisconnectingOutputService.net$java$truevfs$kernel$impl$CheckedCloseable$$super$close(DisconnectingOutputService.scala:28)
	at net.java.truevfs.kernel.impl.CheckedCloseable$class.close(CheckedCloseable.scala:25)
	at net.java.truevfs.kernel.impl.DisconnectingOutputService.close(DisconnectingOutputService.scala:28)
	at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply$mcV$sp(LockOutputService.scala:30)
	at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply(LockOutputService.scala:30)
	at net.java.truevfs.kernel.impl.LockOutputService$$anonfun$close$1.apply(LockOutputService.scala:30)
	at net.java.truevfs.kernel.impl.LockOn$.apply(LockOn.scala:23)
	at net.java.truevfs.kernel.impl.LockAspect$$anonfun$locked$1.apply(LockAspect.scala:21)
	at net.java.truevfs.kernel.impl.LockAspect$$anonfun$locked$1.apply(LockAspect.scala:21)
	at net.java.truevfs.kernel.impl.LockOutputService.close(LockOutputService.scala:30)
	at net.java.truevfs.kernel.impl.TargetArchiveController$$anonfun$close$2.apply(TargetArchiveController.scala:351)
	... 40 more
```

**Comment by weeurey** [comment] 2017-03-15 01:08
Also having this issue, Windows 10, AMD RX480. 2 monitor setup but I disconnected one and I still have the problem. Latest driver. Has there been any fix for the issue?

**Comment by Hygaradon** [comment] 2017-04-01 22:04
I'm having this problem. I noticed, when it happens and I switch between two monitors and turning the 2nd on on or off. it fixes it temporarily. when it happens again I turn on the 2nd screen and its fixed again... very weird. But it's quite annoying to do this multiple times per match. It won't go away by itself.

Specs:
Win 7 Prof
I7-3820 @3.6GHz
16GB RAM
AMD Radeon HD5800

Xmage 1.4.22V0 (2017-03-11)

**Comment by FreshDumbledore** [comment] 2017-09-17 12:23
I solved this for me with one of this actions (all at about the same time), sorted by likeliness highest to lowest:
* Checking 'Fall back to plain image based rendering' in the XMage Graphic Options
* Updating XMage to V4
* Updating GFX Card Drivers

As a workaround if the problem occurs to you, change your display resolution to a lower one. Always fixed it temporary for me so i could go on playing (once i found it).

**Comment by racctor** [comment] 2017-09-23 20:57
is there any chance for a fix? didnt have the problem two months ago.

i tried a clean uninstall of all gpu drivers, clean uninstall of java, removing and reinstalling xMage multiple times, tried various graphic resolutions, and played around in xMage preferences. nothing helped.

running a single moitor setup
radeon 280x
windows 7 64x

**Comment by Akoras** [comment] 2017-09-26 06:15
I have the same problem on my pc, have had it forever:

Win 10 64x

AMD Radeon R7 200 Series
Driver Packaging Version
16.40.2311.1002-161121a-309377E

I do have my tv connected via HDMI and set to copy my screen but it's never  on when I play.

super annoying, I too have to play on my laptop because it is unplayabel. Problem starts always during game 1, never have been able to finish a game.

**Comment by Navyguy330** [comment] 2017-09-26 06:57
to finish all you have to do is ctrl alt del and force quit, and re open
you will usually auto reconnect to table. i have to do this maybe 5 times
every few games lol. some times 3-4 times PER GAME

**Comment by Akoras** [comment] 2017-09-26 07:02
> Navyguy330 commented
to finish all you have to do is ctrl alt del and force quit, and re open
you will usually auto reconnect to table. i have to do this maybe 5 times
every few games lol. some times 3-4 times PER GAME

I know about this "workaround" but it happens to me every minute or so...thats just not a viable option

**Comment by Navyguy330** [comment] 2017-09-26 07:19
yeah I have tried everything.  you mention using a tv as a monitor, I am
too. but hdmi to a monitor vs television these days does not seem like it
could cause that (unless some odd driver bug combo with java screen
drawing) oddly enough my OLD computer, that I use at my gf, with another tv
does not do it, but that same computer did it to me here lmao.

**Comment by majaldm** [comment] 2017-10-28 10:26
I installed XMage this week and this happened to me every single game I played.
![20171028_175010](https://user-images.githubusercontent.com/19721326/32133376-221f46e2-bc09-11e7-90d3-8243fef30e33.jpg)
![20171028_182142](https://user-images.githubusercontent.com/19721326/32133574-41a97628-bc0d-11e7-8ec2-477ccf39af69.jpg)


This are my specs, I'm using the recommended Java version
![20171028_175810](https://user-images.githubusercontent.com/19721326/32133399-ab075b66-bc09-11e7-8a64-3bef0c8708ec.jpg)


These are my settings on NVIDIA control panel (all off or minimum except shaders on):
![20171028_182510](https://user-images.githubusercontent.com/19721326/32133589-7bb233aa-bc0d-11e7-849c-230b01b07056.jpg)


Do you plan on working on this bug? Let me know if you need more information.

**Comment by drmDev** [comment] 2017-10-28 15:45
We have not been able to establish a root cause of the issue to troubleshoot it. We cannot duplicate it ourselves either. Since it is not a problem for all users, it is related to user environments at the very least. In this thread we've found some commonalities but unsure how to proceed.

If someone with development experience is having this problem, you can help contribute to XMage and run it locally through a debugger to try to provide more details on where this is happening. It's possible somewhere in the code we have to account for differences in user environments than what is already done.

**Comment by majaldm** [comment] 2017-11-03 13:21
I am an IT student, but I don't have much time right now. As additional info: I have Chinese Zhuyin input on my system (it uses phonetic symbols like this: ㄋㄧˇ ㄏㄠˇ), inputting any of those symbols as a text in XMage will immediately cause this bug to appear.

**Comment by JayDi85** [comment] 2017-11-22 13:18
It's not a graphic card issue at all. That's kind of bugs causing by windows loose his "handles" and can't to process system messages (e.g. panels and controls don't known then it must redraw, example, after change position or after remove another window over app). 

You must checking every step from start to first bug appear. It may not nulled pointer access, broken resources, broken data, wrong actions, access to non exist cards or game elements, and etc. 

**Log all actions and isolate moment of the bug's begin (less steps is better).**

**Comment by JayDi85** [comment] 2017-11-22 17:37
Please, try that test version and tell -- can it help you: [download link](https://yadi.sk/d/oLKb_rzG3PwE7n) (200 MB). Download, extract zip to somewhere and run `XMageLauncher-0.3.8.jar` from `xmage-test` folder (as your normal game).

**Comment by Navyguy330** [comment] 2018-02-24 10:23
https://prnt.sc/ij2oaf

still an issue, 2 years later lol.  its so annoying,

**Comment by JayDi85** [comment] 2018-02-24 11:07
@Navyguy330 I think it's a java 2d problem, not xmage... [You can find fixes here](https://stackoverflow.com/questions/22737535/swing-rendering-appears-broken-in-jdk-1-8-correct-in-jdk-1-7). Try one of this:
 - add launcher param to client: `-Dsun.java2d.d3d=false`;
 - [change nvidia driver settings for java apps](https://stackoverflow.com/a/40651617/1276632);
 - or other fixes from link above.

**Comment by jdavis8** [comment] 2018-02-27 22:05
This is also happening to me I found that changing the memory allocated helps some but it still tears when my memory usage goes over 30%

**Comment by jdavis8** [comment] 2018-04-05 00:28
i have this same error. it seems to be alleviated a bit when i allocate more memory to xmage but that still doesnt stop it completely from happening

**Comment by JayDi85** [comment] 2019-03-21 15:16
99% of all graphic glitches come from client errors (as example: broken images files/zips -- just delete zero size files or files from error message). Users must open client logs and research errors `xxx\xmage\mage-client\mageclient.log` (upload it to https://pastebin.com/ and create new issue with your problem).

1% of all graphic glitches come from old graphic card drivers. You must update it to latest version. If not helps then try to use `-Dsun.java2d.d3d=false` fix ([see above](https://github.com/magefree/mage/issues/1514#issuecomment-368220596)).

**Closed by JayDi85** 2019-03-21 15:16 UTC
Labels: GUI, bug
