### ISSUE TITLE
BUG - Umezawa's Jitte; No triggers when equipped creature dies in combat.

### ISSUE THREAD

**Issue by Chewbaklava** [magefree/mage#9271] opened 2022-07-14 09:10 UTC
Situation:

Umezawa's Jitte is equipped to an attacking 1/1. The attacker is blocked by defending player's 1/1. Both creatures die.

The Jitte should trigger and get +2 counters. However, this doesn't happen. Pls Fix.

<3
-Chewbaklava

**Comment by PurpleCrowbar** [comment] 2022-07-14 10:19
Duplicate of #9129

**Closed by PurpleCrowbar** 2022-07-14 10:19 UTC
