### ISSUE TITLE
Goad ability must extend CantAttackYouEffect

### ISSUE THREAD

**Issue by derlhurgoyf** [magefree/mage#5283] opened 2018-08-28 03:26 UTC
In a recent game with Grenzo, Havoc Raiser is owned and controlled by player A.
Xantcha, Sleeper Agent is owned by player B but controlled by player C. 
A attacks C and goads Xantcha.
On C's turn, Xantcha can't attack B by her own ability but must attack.
Goad says that the creature has to attack, and another player if able.
This last clause means that goaded creatures must attack and can attack the player that goaded it if no other player can be attacked.

Relevant ruling (from Besmirch):
If the creature doesn’t meet any of the above exceptions and can attack, it must attack a player other than the controller of the spell or ability that goaded it if able. It the creature can’t attack any of those players but could otherwise attack, it must attack an opposing planeswalker (controlled by any opponent) or the player that goaded it. (2016-08-23)

**Comment by JayDi85** [comment] 2019-07-05 10:33
Xantcha have "can't attack ability", so it can't attack controller after goaded (even with no other targets available):
> 8/23/2016 If, during a player’s declare attackers step, a creature that player controls that’s been goaded is tapped, is affected by a spell or ability that says it can’t attack, or hasn’t been under that player’s control continuously since the turn began (and doesn’t have haste), then it doesn’t attack. If there’s a cost associated with having a creature attack a player, its controller isn’t forced to pay that cost, so it doesn’t have to attack in that case either. 

If you have another goaded creature instead Xantcha then yes -- you must attack controller with no other targets. BUT xmage's engine is limited and do not supports targets analyse (e.g. do not support: "If the creature can’t attack any of those players but could otherwise attack, it must attack an opposing planeswalker or the player that goaded it").

P.S. `Besmirch` card was bugged and doesn't goad the target. That will be fixed with next 37v2 update.

**Comment by Zerrisx** [comment] 2020-07-14 04:40
Duplicate of #4999

**Closed by Zerrisx** 2020-07-14 04:40 UTC
Labels: bug
