### ISSUE TITLE
[CMR] Krark, the Thumbless and Rite of Replication

### ISSUE THREAD

**Issue by NekoNL** [magefree/mage#7192] opened 2020-11-19 14:55 UTC
Krark, the thumbless and a copy of him are on the field, and I cast Rite of replication kicked. The first coinflip fails and returns it to my hand, and the second coinflip wins and copies it, but does not copy the kicked part. I believe I did this before in another game and the first flip won then it would be a kicked copy.

**Comment by LevelX2** [comment] 2020-11-25 16:19
The problem is caused by the way the kicked status is handeled.
If the first flip is lost, the spell (card) on the stack is moved back to the hand.
If later the spell copy resolves,  the kicked status will be retrieved with the zoneChangeCounter of the card on the hand (increased by 1) and so the result of this is not kicked.

**Comment by JayDi85** [comment] 2020-12-15 16:10
Fixed by 4d362d7edcd08c0313e653fa0af7e988b9595dee. That fix improved ZCC processing of copied spells (now it synced with original spell or card -- it allows to keep ability's settings that depends on ZCC).

**Closed by JayDi85** 2020-12-15 16:10 UTC
Labels: bug
