### ISSUE TITLE
Color Identity sometimes gets used instead of color

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#7983] opened 2021-07-06 20:38 UTC
Also occurs for: (often the creature whose color and color identity is mixed up is a commander)
- Protection:
    - "I can't block with Jadzi, even though she's blue and [Sword of Feast and Famine] only gives protection from green and black."
    - "It was reported that Sword of Fire and Ice attached to a creature is not providing correct color protection. Example given: Memnarch."
- Bloom Tender: "Bloom Tender provides WUBRG when tapped when Sisay, Weatherlight Captain is on the battlefield.

Original problem:
![image](https://user-images.githubusercontent.com/11657716/124663684-41ac4380-de5f-11eb-8688-98c858f8a093.png)

[[Faeburrow Elder]] gets +1/+1 for each color among permanents you control. This should be *color*, not *color identity*. As shown above, Faeburrow Elder looks at color identity, not color.

**Comment by weirddan455** [comment] 2021-07-13 13:38
I'm not able to reproduce this with the cards shown.  What version are you using?  It's possible it's been fixed already.
![feaburrow](https://user-images.githubusercontent.com/8128047/125461683-09deb773-4072-4ea7-8fd8-84aabd3ba03d.jpg)

**Comment by theelk801** [comment] 2021-07-13 14:08
This bug gets reported occasionally, for some reason color and color identity get mixed up sometimes but not always. These kinds of bugs that only happen sometimes are always difficult to find.

**Comment by alexander-novo** [comment] 2021-07-13 16:56
I've noticed it happen pretty consistently while Sisay was my commander. The screenshot in #7987 also happened with a commander.

**Comment by alexander-novo** [comment] 2021-07-14 22:53
Here it is in another game I was playing where someone's command was morophon:

![image](https://user-images.githubusercontent.com/11657716/125702983-862ecc09-6c6e-4047-83d7-4f1af4a7de86.png)

If it isn't happening always, I'd bet it's a commander issue.

**Comment by alexander-novo** [comment] 2021-07-17 23:24
Here's a similar example, this time with [[Sisay, Weatherlight Captain]], which is a commander:

![image](https://user-images.githubusercontent.com/11657716/126051382-e9e754b0-1116-46ba-91f5-fe4ca2a975a6.png)

In this example, the Sisay on the left is a commander and the Sisay on the right is a [[Spark Double]] copy of Sisay. As you can see, the spark double copy gets the +5/+5 from the commander Sisay's color identity. I wonder how it would work with Sakashima, where they both stay legendary. Would the commander sisay work properly since the copy isn't a commander?

**Comment by wwwmagnottait** [comment] 2024-03-13 23:27
Same issue here in 2024! 
I use Sisay weatherlight Captain as commander on XMage (latest version updated) and bloom tender and farburrow elder ALWAYS (not occasioally…ALWAYS!) get mana of all colors with Sisay on the battlefield. Is it very frustrating coz it is like cheating :( I saw post here since 2019 regarding this issue: How is it possible that it is still not fixed after 5 years? Please try to find a fix, many thanks

**Comment by wwwmagnottait** [comment] 2024-03-14 08:45
> Same issue here in 2024! I use Sisay weatherlight Captain as commander on XMage (latest version updated) and bloom tender and farburrow elder ALWAYS (not occasioally…ALWAYS!) get mana of all colors with Sisay on the battlefield. Is it very frustrating coz it is like cheating :( I saw post here since 2019 regarding this issue: How is it possible that it is still not fixed after 5 years? Please try to find a fix, many thanks

Here u are an example of what **ALWAYS** happens on XMage matches with **Sisay Weatherlight Captain** as Commander:

![sisay1](https://github.com/magefree/mage/assets/160843375/9fb6ad9a-cd37-4a33-8b72-eb36cceeba58)
![sisay2](https://github.com/magefree/mage/assets/160843375/41c2fca7-7049-4265-ad7b-edde9b8a00eb)
![sisay3](https://github.com/magefree/mage/assets/160843375/0d1a7f1f-6f0c-4dcc-b1f6-09107f912160)

As you can see (image 1 and 3) **Sisay is considered as a 5 colors card, even when you start the game and Sisay is in the Command Zone.** Bloom Tender (image 2) can consequently procude all 5 mana colors. 

The weird thing is that **Sisay, on XMage deck editor, is correctly considered as a white only permanent** (see image below).
![sisay4](https://github.com/magefree/mage/assets/160843375/85289c4d-0c74-4c41-98ec-010d2fe21f9c)

I want to stress about the fact that **it is not a random issue**: I have it **CONSTANTLY** in **ALL** my commander matches on XMage, with Sisay. Can u please help? Many thanks for all u efforts :)

**Comment by wwwmagnottait** [comment] 2024-03-15 09:52
Hi,
**I saw that this bug haven't been assigned to anyone (since 2021!).** 
Considering that it is a **severe bug**, perduring and not resolved since more thant 3 years, is it possible at least to be assigned to a dev? Many thanks :)

**Comment by alexander-novo** [comment] 2024-03-15 12:54
@wwwmagnottait Please keep in mind that this is an open source project. The developers of this project contribute only because they wish to - it isn't their responsibility. So no one gets "assigned" to take care of issues, but that doesn't mean that no one has looked into it.

**Comment by wwwmagnottait** [comment] 2024-03-15 13:00
> @wwwmagnottait Please keep in mind that this is an open source project. The developers of this project contribute only because they wish to - it isn't their responsibility. So no one gets "assigned" to take care of issues, but that doesn't mean that no one has looked into it.

Dear Alexander, thanks for u reply!
I know it's a free open source project (a fantastic one, I add). and that no one is obliged to do it: only by seeing the other recent bug posts I noticed that they had been assigned, and I wondered why such a serious and 3 year old bug still hadn't been assigned... that's all! Any help (when and if there is any) is welcome :)

**Comment by alexander-novo** [comment] 2024-03-15 13:08
Some people will assign themselves to notify others that they shouldn't work on it, as it has already been claimed.

**Comment by wwwmagnottait** [comment] 2024-03-25 11:37
hi all :) just to inform community that, sadly, the bug it is still persistent in **all** my games with Sisay :(

**Comment by wwwmagnottait** [comment] 2024-04-26 08:57
Good morning! Updated XMage to v. 1.4.51 and the bug is still here! :-(

**Comment by alexander-novo** [comment] 2024-04-26 13:52
@wwwmagnottait This bug will continue to be in every xMage version until this issue is closed. We will all get a ping when the issue is closed, so until then, there is no need to remind us.

**Comment by JayDi85** [comment] 2024-04-26 13:57
If someone can reproduce it with 100% successful rate then it can be easy to fix.

It can be related to ai games, to object copy code, to game restart by Karn, to rollback, to concede by other player, etc. It can be related to client code too (e.g. miss or wrong field update) — btw client bug can be checked by reconnection (if you reconnected and it’s food color again then it’s gui bug).

**Comment by wwwmagnottait** [comment] 2024-04-26 14:10
> If someone can reproduce it with 100% successful rate then it can be easy to fix.
> 
> It can be related to ai games, to object copy code, to game restart by Karn, to rollback, to concede by other player, etc. It can be related to client code too (e.g. miss or wrong field update) — btw client bug can be checked by reconnection (if you reconnected and color fixed then it’s gui bug).

hi @JayDi85 ...this issue happens on 100% of my XMage games, both with AI that with other users, from the START of the game (I can immediatly see that Sisay is considered a 5 color card). In local I've also tried to disconn and reconn to server during the match with a bot, as u suggested, but the issue was still present. How can I help you? Many thanks :)

**Closed** 2024-06-07 19:46 UTC
Labels: bug

**Comment by alexander-novo** [comment] 2024-06-07 19:58
@wwwmagnottait you will be happy to know that the bug has been fixed. It existed for seven years before now.
