### ISSUE TITLE
Bug: Foretold card "Jorn, God of Winter" cannot be cast

### ISSUE THREAD

**Issue by Don-Cruz** [magefree/mage#7487] opened 2021-02-02 21:27 UTC
The card "Jorn, God of Winter" was foretold with the ability of the card "Dream Devourer".
Two turns after it was not possible to cast the card from exile, as it should work.
![grafik](https://user-images.githubusercontent.com/78379079/106664276-21711380-65a5-11eb-93bc-ae159baa80fb.png)
![grafik](https://user-images.githubusercontent.com/78379079/106664365-436a9600-65a5-11eb-8229-96e0a5924013.png)

Clicking on the option "No, play/activate ability" does nothing.
Although in the same moment the ability works with other cards, like the card "Dread Rider".

**Comment by Don-Cruz** [comment] 2021-02-02 21:35
The emblem of "Kaya the Inexorable" was active at that time.
It says: "At the beginning of your upkeep, you may cast a legendary spell from your hand/graveyard/card you own in exil, without paying its mana cost.
As "Jorn, God of Winter" is legendary, it could be cast with Kayas ability later in the upkeep.
Perhaps the two competing abilities meshed with each other.

**Comment by Don-Cruz** [comment] 2021-02-02 21:45
Jorn was foretold in the same turn. That was the reason.

**Comment by Don-Cruz** [comment] 2021-02-02 22:22
It happend again. I was not able to cast a foretold Jorn. This time it was several turns after foretelling, without Kayas Emblem.
![grafik](https://user-images.githubusercontent.com/78379079/106670570-83357b80-65ad-11eb-86bd-e3eb0faad53f.png)

**Comment by weirddan455** [comment] 2021-02-03 23:53
I can confirm this bug.  It seems to be affecting all split cards and MDFCs that have been foretold with Dream Devourer.  I took a look a look at the Foretell code and it seems this is never being used (at least "Find Usages" in IntelliJ came up empty):

https://github.com/magefree/mage/blob/7da65b38b2ae3546877816941e5d65ed25ac2824/Mage/src/main/java/mage/abilities/keyword/ForetellAbility.java#L326-L334

So when it runs the checks for split cards and MDFCs, `abilityName` is never initialized:

https://github.com/magefree/mage/blob/7da65b38b2ae3546877816941e5d65ed25ac2824/Mage/src/main/java/mage/abilities/keyword/ForetellAbility.java#L278-L289

@jeffwadsworth has been doing most (all?) of the work on Foretell.  Where is this supposed to be called from?  I checked `PlayerImpl` like the comment said but not seeing anything in there.

**Comment by JayDi85** [comment] 2021-02-04 00:06
@weirddan455 see `CardImpl->getAbilities(Game`

Foretell copy-pasted from flashback, so it must use same workaround.

**Comment by jeffwadsworth** [comment] 2021-02-04 01:20
I will check this tomorrow.  It was never tested with MDFC's.

**Comment by weirddan455** [comment] 2021-02-04 02:13
I have an idea of where to go with this now.  There's a couple things that need to be reworked.  Dream Devourer needs to check both halves of the card and apply the correct Foretell cost to both.  I'll see what I can do on this tonight.

**Comment by weirddan455** [comment] 2021-02-04 08:09
See PR #7498.  I think I've got it working save for some text issues which I can look at tomorrow.

**Comment by jeffwadsworth** [comment] 2021-02-04 14:42
> 
> 
> @weirddan455 see `CardImpl->getAbilities(Game`
> 
> Foretell copy-pasted from flashback, so it must use same workaround. Maybe.

Nope.  Not even used...only mentioned, but it never checks for other activated abilities related to them.  Like I said, split-cards and MDFC's were never tested.  I assumed that since the checking code was there for the keyword flashback, it was actually using it.

**Comment by weirddan455** [comment] 2021-02-04 22:31
Fixed in cd9c57feade1af22f2a5d1a29380c201d60ebf09

**Closed** 2021-02-04 22:33 UTC
Labels: bug
