### ISSUE TITLE
Emrakul/Mindslaver incorrect turn order

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#2470] opened 2016-10-16 01:53 UTC
[Emrakul, the Promised End](https://mtg.wtf/card/emn/6) seems to mostly work correctly now, except that APNAP order is still wrong: in XMage, the player controlling the turn gets priority first, instead of the player whose turn it is.

**Comment by Zerrisx** [comment] 2020-06-26 01:11
Duplicate of #2088

**Closed by Zerrisx** 2020-06-26 01:11 UTC
Labels: bug
