### ISSUE TITLE
Spare Dagger sacrifice damage effect doesn't trigger

### ISSUE THREAD

**Issue by BroCube** [magefree/mage#8390] opened 2021-10-17 06:32 UTC
https://gatherer.wizards.com/Pages/Card/Details.aspx?name=Spare%20Dagger
```
Equipped creature gets +1/+0 and has "Whenever this creature attacks, you may sacrifice Spare Dagger. When you do, this creature deals 1 damage to any target."
Equip 1 (1: Attach to target creature you control. Equip only as a sorcery.)
```
The request prompt to sacrifice appears, and the card goes to the graveyard, but the damage effect never appears on the stack. Tested attached to `Fynn, the Fangbearer`, `Vengeful Reaper` and `Jaspera Sentinel`.

Client: 1.4.50-V2 (build 2021-09-05 18.55) Server 1.4.50-V2 (2021-09-05 18:59)

**Comment by awjackson** [comment] 2021-10-17 11:40
Duplicate of #8264 ?

**Closed as completed** 2021-10-18 13:12 UTC
Labels: duplicate
