### ISSUE TITLE
Aether Rift Heap space error

### ISSUE THREAD

**Issue by chesse20** [magefree/mage#10179] opened 2023-04-06 19:45 UTC
Instead of reanimating a creature [[aether rift]] instead caused this error to other players not in the same match, and caused the player who cast it to have UI issues.
![image](https://user-images.githubusercontent.com/9161779/230479003-ffe76f46-a48f-49e3-900f-2b0bc308cbe3.png)

**Comment by chesse20** [comment] 2023-04-06 19:52
this was previously reported in 2019 #5868

**Comment by xenohedron** [comment] 2023-06-04 22:16
Closing as the card functionality was fixed and can't reproduce the heap space error

**Closed by xenohedron** 2023-06-04 22:16 UTC
