### ISSUE TITLE
Emrakul the promised end's ability not allowing to cast spells

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2622] opened 2016-11-22 20:42 UTC
There are instances when you get control of the other player's turn, but no player receives priority, which does not allow you to cast spells, or activate any ability. It just allows you to pass through each step. Can this be fixed?

**Comment by Muppet1** [comment] 2017-01-04 15:39
Also if you are playing the ai taking control of his turn only allows you to see its cards, it still happily plays its turn and takes another.

**Comment by drmDev** [comment] 2017-03-07 15:37
Playing vs AI with any take over turn effect has been a bug for a very long time - the AI portion of the project has long gone untouched.

Is this issue still going on vs human players? I've been able to get take over turn effects to work fine vs other human players.

**Comment by Zerrisx** [comment] 2020-06-26 01:11
Duplicate of #2088

**Closed by Zerrisx** 2020-06-26 01:11 UTC
Labels: bug, not confirmed
