### ISSUE TITLE
Alibou doesn't trigger when Esper Sentinel attacks alone

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#8424] opened 2021-10-31 16:25 UTC
[[Alibou, Ancient Witness]] and [[Esper Sentinel]]. esper sentinal is an artifact creature so I believe Alibou's scry / damage ability should trigger (message log shows it hasn't against AI in test mode):

![image](https://user-images.githubusercontent.com/64497504/139593074-00900fd7-dd49-42b8-98b1-f0f9a051e041.png)

**Comment by awjackson** [comment] 2021-10-31 16:35
Duplicate of #8228

**Closed by awjackson** 2021-10-31 16:35 UTC
Labels: duplicate
