### ISSUE TITLE
Draft match hangs in tournament panel

### ISSUE THREAD

**Issue by hitch17** [magefree/mage#5555] opened 2019-01-27 18:53 UTC
Frequently, after I complete a draft my first match won't start.  

- There have always been at least 1 bot drafting (sometimes all bots, sometimes with humans, I don't think the bot type matters)
- Killing the client and trying to rejoin occasionally works.

I'm just checking if others have experienced this issue or have some ideas about what I might start to try and debug the issue.  

<img width="1053" alt="screen shot 2019-01-27 at 10 48 20 am" src="https://user-images.githubusercontent.com/164796/51805362-26b25f80-2221-11e9-80d4-65965d41fc91.png">

Might be related to: https://github.com/magefree/mage/issues/567

**Comment by JayDi85** [comment] 2019-01-27 19:02
This is disconnection problem and must be fixed someday. 

One of the reason: if you complete the draft/sideboard but other player disconnects before game started then all freezes (your game is started by server and waiting other player, but it's want popup it to you). But it's not work if other player connected again -- it's can "lost" his waiting game and can't start.

**Comment by hitch17** [comment] 2019-01-28 17:23
Is there already an issue tracking this?  If so, happy to close this issue.

**Comment by JayDi85** [comment] 2019-01-28 17:46
Same or related issues:
* games not start: #5447, #4842, #567 
* ghost tournament/games: #5358 #3741 #3237 #5260 
* not finished tourneys: #1450

**Comment by smadigan91** [comment] 2019-02-21 17:18
Just wanted to add that I was testing playing out with friends last night and we ran into this. If the decks are all submitted within the same couple of minutes, no issues, but if someone takes a bit longer to submit (we saw 4-5+ minutes) then everyone in the tournament seems to experience this issue. Seemed to be 100% reproducible

**Comment by LevelX2** [comment] 2020-07-24 13:50
Related post in the forum:
**Xmage sealed not working?**
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=22139&sid=8fc9ad6792ab2a51524f7d3dde3855e3

**Comment by jasonywang0** [comment] 2021-07-14 22:26
Yeah, you can reproduce this issue by creating a 2 player sealed tournament and have one player submit the deck much later than the other. It's quite annoying, but here is a workaround: The player whose game did not start should open another client and connect to the server **without closing their current one**. This should cause the game panel to load after a brief time in xmage limbo--which I presume is xmage loading the board.

**Comment by Alex-Vasile** [comment] 2022-09-05 04:03
Still and issue. The following shows up in the server logs:
```
INFO  2022-09-04 16:14:11,568 GAME started 51927b0a-ae31-4736-881e-cef601dcb67e [] Alex2 - Computer 3                     =>[CALL main-60] TableController.startGame 
INFO  2022-09-04 16:14:11,569 Tourn. match started id:66709834-7044-4861-930f-8caf0e4e5091 tournId: e0e42eed-475a-4265-8be4-7425e96ffb0b =>[CALL main-60] TableController.startMatch 
INFO  2022-09-04 16:14:11,570 GAME started ae418926-34b0-4e82-b852-40b1f0ed26a0 [] null - Computer 4 - Computer 6        =>[CALL main-60] TableController.startGame 
INFO  2022-09-04 16:14:11,571 Tourn. match started id:dfc38453-14ba-478b-8298-e083625d262a tournId: e0e42eed-475a-4265-8be4-7425e96ffb0b =>[CALL main-60] TableController.startMatch 
INFO  2022-09-04 16:14:11,572 GAME started 7bba131e-7eca-4901-80d3-36ccf1b06fc7 [] null - Computer 8 - Computer 7        =>[CALL main-60] TableController.startGame 
INFO  2022-09-04 16:14:11,573 Tourn. match started id:190efb23-c5a3-4522-ad7e-3e03ac763fa0 tournId: e0e42eed-475a-4265-8be4-7425e96ffb0b =>[CALL main-60] TableController.startMatch 
INFO  2022-09-04 16:14:11,591 GAME started 0220e5a2-6279-49b0-95ad-7f390ae73aed [] Alex - Computer 5                     =>[CALL main-60] TableController.startGame 
WARN  2022-09-04 16:14:13,170 Ability without sourceId:If it would be dealt damage or destroyed, remove a shield counter from it instead. =>[pool-1-thread-1] ContinuousEffects.getControllerOfSourceId 
WARN  2022-09-04 16:14:13,170 Ability without sourceId:If a permanent with a stun counter would become untapped, remove one from it instead. =>[pool-1-thread-1] ContinuousEffects.getControllerOfSourceId 
WARN  2022-09-04 16:14:13,197 Ability without sourceId:If it would be dealt damage or destroyed, remove a shield counter from it instead. =>[pool-1-thread-1] ContinuousEffects.getControllerOfSourceId 
WARN  2022-09-04 16:14:13,197 Ability without sourceId:If a permanent with a stun counter would become untapped, remove one from it instead. =>[pool-1-thread-1] ContinuousEffects.getControllerOfSourceId 
WARN  2022-09-04 16:14:13,200 Ability without sourceId:If it would be dealt damage or destroyed, remove a shield counter from it instead. =>[GAME ae418926-34b0-4e82-b852-40b1f0ed26a0] ContinuousEffects.getControllerOfSourceId 
WARN  2022-09-04 16:14:13,200 Ability without sourceId:If a permanent with a stun counter would become untapped, remove one from it instead. =>[GAME ae418926-34b0-4e82-b852-40b1f0ed26a0] ContinuousEffects.getControllerOfSourceId 
INFO  2022-09-04 16:14:14,242 GAME started 398c2fb5-bbf2-4d79-a132-67406dfacc0d [] null - Computer 8 - Computer 7        =>[GAME 7bba131e-7eca-4901-80d3-36ccf1b06fc7] TableController.startGame 
INFO  2022-09-04 16:14:15,564 GAME started a1f998c4-f12a-43ca-9ac8-c5e1c54f893e [] null - Computer 4 - Computer 6        =>[GAME ae418926-34b0-4e82-b852-40b1f0ed26a0] TableController.startGame 
WARN  2022-09-04 16:14:21,516 SESSION LOCK - fireCallback - userId: 362b89bf-d84e-4e64-b21d-c45debd42dd5 messageId: 0    =>[pool-11-thread-1] Session.fireCallback 
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireNanos(AbstractQueuedSynchronizer.java:1245)
	at java.util.concurrent.locks.ReentrantLock.tryLock(ReentrantLock.java:442)
	at mage.server.Session.fireCallback(Session.java:376)
	at mage.server.User.lambda$fireCallback$0(User.java:232)
	at java.util.Optional.ifPresent(Optional.java:159)
	at mage.server.User.fireCallback(User.java:231)
	at mage.server.User.ccGameStarted(User.java:242)
	at mage.server.game.GameController.sendInfoAboutPlayersNotJoinedYetAndTryToFixIt(GameController.java:358)
	at mage.server.game.GameController.lambda$init$0(GameController.java:236)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO  2022-09-04 16:16:56,993 USER REMOVE - Alex2 (Disconnected)  userId: 362b89bf-d84e-4e64-b21d-c45debd42dd5 [Tourn: 1 ] =>[CALL main-133] UserManagerImpl.lambda$null$1 
```

**Comment by JayDi85** [comment] 2024-03-07 16:19
Not actual anymore after game events processing improved in #6131 and #11458. Real reason: client receiving server commands in diff order due network stability and command payload size.

**Closed by JayDi85** 2024-03-07 16:19 UTC
Labels: bug, server
