### ISSUE TITLE
Blood Moon vs. Shock lands ( Still have to pay 2 life to enter untapped, when it should not cost any life)

### ISSUE THREAD

**Issue by roverttrevlac** [magefree/mage#11805] opened 2024-02-17 01:35 UTC
This is still a big issue that has lingered since I have been on the client.

It is the most tilting, false interaction on the client that has yet to be fixed.

**Comment by PurpleCrowbar** [comment] 2024-02-17 01:44
Duplicate of #4202

**Closed by PurpleCrowbar** 2024-02-17 01:44 UTC
