### ISSUE TITLE
Define X Value (e.g. Black Sun's Zenith) or Choices don't work correct using a Linux system while XMage tray bar icon is blinking

### ISSUE THREAD

**Issue by quantumfx** [magefree/mage#584] opened 2014-09-29 17:40 UTC
Choosing X doesn't work and it always only ask you to pay BB. Used to work on previous versions. It looks like it might be a general issue for any card with casting cost X?
![screenshot from 2014-09-29 13 32 22](https://cloud.githubusercontent.com/assets/2328946/4446118/a1f73d9c-47ff-11e4-82e9-06a14154710b.png)

**Comment by troyready** [comment] 2015-02-02 17:59
FWIW, I seem to be experiencing this issue consistently regardless of the blinking state of the tray icon.

**Comment by LevelX2** [comment] 2015-02-02 22:47
Which Linux Distribution and which Desktop do you use?

**Comment by troyready** [comment] 2015-02-03 02:45
It's Ubuntu 14.04 w/ the default Unity desktop environment. I've tried launching the client app with the launcher's provided Oracle JRE & my system's build of openjdk7 but the results are the same.

What is interesting is that it functions properly when testing against AI on a local server -- it's only when I try to use the public server with another real client that the issue manifests.

**Comment by Simown** [comment] 2015-02-03 10:08
I had a look at this over the span of a few days and it looks like a generic Linux issue rather than a distribution specific one (e.g. Ubuntu). I wasn't able to get to the root of the problem, but was able to reproduce it fairly consistently. It doesn't only seem to happen Human vs Human. Maybe it's a concurrency issue or an odd quirk with Java on Linux.

**Comment by LevelX2** [comment] 2015-02-03 12:13
Just to get the problematic behaviour of the bug correctly:
1) You play a spellm with a {X} cost.
2) The small window to choose {X} opens.
3) Meanwhile the program runs further and thinks you did choose X = 0.
4) But the window is still open and it doesn't matter what you enter and confirm in the window.
5) As you push OK on the small windo it closes and your can pay the remaining costs beside X.
Is this description correct?

**Comment by troyready** [comment] 2015-02-03 15:10
The issue that I'm experiencing is a bit different - nothing appears at all when I attempt to cast spells with a {0} mama cost (e.g. Mox Opal, Ornithopter). The card is highlighted purple (indicating that it can be cast), but no feedback at all appears when clicking on it.

In an AI game or on Windows, clicking on the card properly pops up a small black box with a "Cast..." option.

**Comment by quantumfx** [comment] 2015-02-03 15:28
@LevelX2 that description is correct for the original bug reported.

**Comment by LevelX2** [comment] 2015-02-12 10:19
Related posts/infos:
http://www.reddit.com/r/XMage/comments/2vllp6/serious_bug_with_protection_effects_ubuntu_1204/

**Comment by fireshoes** [comment] 2015-02-23 16:08
Can we just update the code to take the blinking function out of the icon? The blinking starts when a player joins or leaves a table or when you open a new pack in draft (usually just if you are on a different screen when the pack opens).

**Comment by fireshoes** [comment] 2015-02-24 04:29
Re: Bug Reports 1.3.0 dev 2015-02-07
Postby aging-goblin » 23 Feb 2015, 15:12 

Confirmed on Arch Linux using DWM. All spells with X in casting cost are X=0 when the tray icon is blinking.
It would be nice to be able to disable blinking, or disable the icon entirely.

**Comment by skeet70** [comment] 2015-05-07 20:34
I've experienced the same/a similar issue with any cards that require choices. If a choice of cards (eg Ancient Stirrings) or a search is required (eg Rampant Growth), no dialog comes up and the program doesn't accept any user input. The tray icon doesn't ever seem to blink. This is on Ubuntu 14.04 LTS. 

Semi-randomly selecting the stop blinking option in the tray before the problem occurs seems to prevent it, trying to select it after lockup presents no context menu at all when clicking the tray icon.

Just thought I'd add my data to the issue. No errors or anything in the log files.

**Comment by skeet70** [comment] 2015-05-08 19:17
I'm trying to find out where this problem is coming from. For one thing, my tray icon blinks, but not when this problem occurs. Once the lockup has happened I also can't click the tray icon to tell it to stop blinking (not that it is). If my opponent quits I regain the ability to use the program again. I'm under the impression that the dialogs are being incorrectly created somehow, and you can't click anywhere until you've finished selecting things in those (hidden/non-existant) dialogs.

I can only get the client to run locally, can't get a server up, and can't connect to a remote server with the source client (even if I change the version constant to match the server's, I get NPEs when I try to connect), so I can't reproduce the issue in a version of the client that I can try debugging. Any advice?

**Comment by Nidhoegger** [comment] 2015-07-03 09:45
Patch or this issue sent to LevelX

**Comment by LevelX2** [comment] 2015-07-06 08:38
Can anyone confirm, that the problem with 1.4.1v0 or later is fixed on linux systems?

**Comment by Simown** [comment] 2015-07-06 08:48
I hasn't been an issue when I've been playing over the weekend, can't
remember if there were any {X} cost cards, however. I will test it tonight
if no one else confirms.

**Comment by Nidhoegger** [comment] 2015-07-06 11:07
Important note for testing: The bug only occured when the tray icon was flashing! So make sure the tray icon blinks while testing (best option: you open the table, after a player joins the icon starts flashing. Do not click on the icon and you will have a flashing icon the whole match!).

**Comment by skeet70** [comment] 2015-07-06 13:05
The bug wasn't related to flashing for me, but I'll try to check today if
it's fixed.

**Comment by LevelX2** [comment] 2015-07-06 13:19
> @LevelX2, didnt you mean 1.4.2v0? I fixed the bug after 1.4.1v3 release.

True that was a typo, I mean 1.4.2vo.

**Comment by Simown** [comment] 2015-07-06 20:06
I have tested it on the development environment, Linux Mint 17.1 and it seems to be working and not showing the bug that was on X cost cards before, I have not exhaustively tested it but it has been working in all of my tests so far. If this fix was in 1.4.2v0 it should be in the release. I'd be happy to close it unless anyone finds a different result.

**Comment by skeet70** [comment] 2015-07-06 21:50
Tried to test it, but I couldn't get things to work unrelated.
Had to pass proxy settings from the command line, and then the launcher (while running in java) says it can't find Java and won't let me start anything. I'll keep trying to get to the point where I can test this bug.

**Comment by troyready** [comment] 2015-09-30 01:11
This is working perfectly for me now (Ubuntu 15.04) -- everything that I'd previously reported in this issue and the main 'define x' issue appear to be resolved. Thanks for the great work!

**Closed** 2016-07-30 01:47 UTC
Labels: bug
