### ISSUE TITLE
Too many drafts die to disconnects

### ISSUE THREAD

**Issue by ogier** [magefree/mage#3741] opened 2017-07-25 19:35 UTC
Possibly related to #3237.

During user disconnects it appears that the draft table becomes unresponsive, and many drafts end during drafting due to this. I have had 3 of 7 drafts today die to this problem. There is often a user reported as disconnected in chat, and occasionally a timer ticks down next to someone's name in the Tournament screen. But even if that timer reaches zero, the player is not dropped and drafting does not proceed. If I wait in the table for many minutes (10? 15?) the draft sometimes proceeds, usually once I am the only player remaining.

This is a problem that kills the usability of XMage for drafting. It's very demoralizing to have invested time drafting and planning a deck only to have it not matter.

**Comment by ogier** [comment] 2017-07-25 20:28
Here's a log of one recent tournament. Drafting proceeded at 21:59:

> On this panel you can see the players, their state and the results of the games of the tournament. Also you can chat with the competitors of the tournament.
> 21:11: Clueless has joined (1.4.24V3)
> 21:11: tpvic has joined the tournament
> 21:11: tpvic has joined (1.4.24V3)
> 21:11: Alexx has joined the tournament
> 21:11: Alexx has joined (1.4.24V0)
> 21:24: cpius: hmm
> 21:24: cpius: Not much is happening here
> 21:24: cpius: :(
> 21:25: cpius: Stuck on 2/14
> 21:25: cpius: It looks like alex reconnected, but then didn't
> 21:25: Dandelioon3755: ll
> 21:25: cpius: ?
> 21:25: Clueless: :/
> 21:25: Clueless: why is xmage so unreliable?
> 21:25: Alexx has reconnected
> 21:25: Nina was replaced by draftbot
> 21:25: Clueless: i feel like the server shouldn't fall over any time someone DCs
> 21:25: Nina has quit the tournament
> 21:25: Nina [cleaning up]
> 21:25: tpvic: its dead
> 21:26: tpvic has quit the tournament
> 21:26: tpvic was replaced by draftbot
> 21:26: tpvic [cleaning up]
> 21:26: Dandelioon3755 has quit the tournament
> 21:26: Dandelioon3755 was replaced by draftbot
> 21:26: Dandelioon3755 [cleaning up]
> 21:26: Puzzle360 has quit the tournament
> 21:26: Puzzle360 was replaced by draftbot
> 21:26: Puzzle360 [cleaning up]
> 21:26: CaNiBuS was replaced by draftbot
> 21:26: CaNiBuS has quit the tournament
> 21:26: CaNiBuS [cleaning up]
> 21:37: Alexx has lost connection
> 21:49: Alexx [cleaning up]
> 21:54: sclipsclap has joined (1.4.24V3)
> 21:54: sclipsclap [cleaning up]
> 21:59: Alexx was replaced by draftbot
> 21:59: Alexx has quit the tournament
> 22:03: Clueless has submitted his or her tournament deck

**Comment by Zerrisx** [comment] 2020-07-14 14:47
Duplicate of #3237

**Closed by Zerrisx** 2020-07-14 14:47 UTC
Labels: bug, server
