### ISSUE TITLE
BUG / MOM: "Overloaded Mage Ring" doesn't copy all aspects of a spell

### ISSUE THREAD

**Issue by Don-Cruz** [magefree/mage#10368] opened 2023-05-13 16:15 UTC
[https://scryfall.com/card/mom/64/invasion-of-vryn-overloaded-mage-ring](url)
[https://scryfall.com/card/mom/32/progenitor-exarch](url)
<img width="242" alt="Overloaded Mage Ring" src="https://github.com/magefree/mage/assets/78379079/44475437-1268-4679-b3d1-31c1d4e378f6">
After transforming the battle "Invasion of Vryn" into "Overloaded Mage Ring" the player can copy a spell on the stack with it. The copy ability works, but it does not copy all aspects of the spell on the stack.
<img width="380" alt="Mage Ring 1" src="https://github.com/magefree/mage/assets/78379079/93974be2-b4df-4b90-8c4c-1622b7c76a75">
<img width="840" alt="Mage Ring 2" src="https://github.com/magefree/mage/assets/78379079/2c3b3361-c753-4aa9-99ef-430ede672b74">
In this example player cruz copied the spell "Progenitor Exarch", which is an X-creature-spell, by activating Overloaded Mage Ring. The spell was copied successfully but in the copy X was 0 instead of 3 like in the original spell on the stack.
The original spell created X=3 incubator-tokens, but the copy created 0 tokens.

**Comment by Grath** [comment] 2023-05-13 16:17
Duplicate of #9697 (whose name was not quite correct until now.)

**Closed by Grath** 2023-05-13 16:17 UTC
