### ISSUE TITLE
There is a bug regarding "replacement effects" and dredge

### ISSUE THREAD

**Issue by Dryspell** [magefree/mage#1152] opened 2015-07-26 18:59 UTC
Occasionally when two dredge effects are on the stack, it asks to pick order of replacement effects then even after picking the order the window pops up again. selecting any of the options closes the window and opens it again.

**Comment by Dryspell** [comment] 2015-07-26 19:26
![image](https://cloud.githubusercontent.com/assets/13140947/8895486/3934a31e-33a2-11e5-99e3-41921ff38073.png)

**Comment by Dryspell** [comment] 2015-07-26 19:26
Note that Golgari Grave Troll, Golgari Thug, and Shambling Shell are not in my deck.

**Comment by LevelX2** [comment] 2015-07-28 11:51
Duplicate of #643

**Closed by LevelX2** 2015-07-28 11:51 UTC
