### ISSUE TITLE
Custom card banlist, unban and restricted list re-explained basically full room host control

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [magefree/mage#6318] opened 2020-02-28 17:39 UTC
As a gamer and bug tester I know there are just some times when things full through the cracks que in player controlled custom banlist.

Ever play with friends or strangers that just basically abuse the system? Wish you had known ahead of time if someone was going eat your deck through unforseen satanic arts? Well if you said yes then what you want is the ability to ban certain cards before the match even gets started! 

Introducing the custom banlist. 

Using the deck editor the room leader could select a banned deck - "A deck filled with cards that are not allowed in the room." And then sets the rules like normal. 

Congratulations you now have control over your room. This means you could have house rules like no Grindstone or maybe you just want to not play with slivers or elfs now you can ban cards and never worry again about whether some little **** found a technique that breaks the fabric of reality in 3 or less turns. 

This also means since we don't have friendlists we can play with house rules while also playing the formats in MTG format list as seen here.

Also see original post
https://github.com/magefree/mage/issues/6309

Wait thats not all what about an unbanned and restricted list? We could go all the way and make rooms the most awesome place on earth for the room leader. Act now and you could also unban cards from the game like black lotus (wth was wizards thinking) or restrict cards like maybe you don't want 4 of a specific cards maybe you only allow one.

So to summurize we could have the 
* ban list - ban cards you have seen first hand are cheap as ****
* Unban list - Think wizards of the coast made a mistake on a few cards / put them back in circulation.
* Restricted list - want to limit how many copies of a card there are in a lobby? Use this - only 1-3 copies of card!

So devs what are you waiting for - act now - cause honestly these seem like a requirement in a game this size :D

**Comment by Zerrisx** [comment] 2020-07-01 19:34
Duplicate of #4256

**Closed by Zerrisx** 2020-07-01 19:34 UTC
Labels: enhancement
