### ISSUE TITLE
Nulldrifter Evoke messages misleading

### ISSUE THREAD

**Issue by Dunkoro** [magefree/mage#12683] opened 2024-08-19 12:01 UTC
When casting Nulldrifter I'm first presented first with a choice whether to cast it for 7 or with evoke for 2U (this is all fine so far)
Afterwards, when the Nulldrifter and the Draw 2 is put on the stack, I'm once more presented with a similar choice; Evoke for 2U or Cast for normal cost of... nothing.
Choosing the Evoke option prompts me to pay additional 2U, which, if not paid, makes the draw 2 not resolve.
Choosing the option of nothing results in the card working as expected.

**Comment by PurpleCrowbar** [comment] 2024-08-19 13:26
Confirmed, how bizarre. Exclusively an issue with [[Nulldrifter]] (and, thus, evoke). Another alternative cost, emerge, doesn't yield the same bugged results with on-cast triggers (tested with [[Abundant Maw]])

It seems the emerge keyword is implemented as a `SpellAbility` whereas evoke extends `AlternativeSourceCostsImpl`. It seems that a lot of alternative costs like blitz, escape, emerge, extend `SpellAbility`, with the only exceptions being Evoke, Dash, Freerunning, and Prowl, which extend `AlternativeSourceCostsImpl`. Maybe something going on there

**Comment by PurpleCrowbar** [comment] 2024-08-19 13:55
No idea, Nulldrifter has been implemented for four months so should've been available in the last release, but maybe no one noticed the bug. Most recent relevant commit that changes `EvokeAbility` appears to be 96b08ee, but can't see why that commit would break anything. This card is also the first evoke card to have an on-cast trigger so may be a longstanding issue that's only been discovered now due to this card's printing.

**Comment by Dunkoro** [comment] 2024-08-19 14:11
I'm pretty sure this wasn't there in the previous build, I've played with Nulldrifter a few times and I'm sure I'd have noticed.

**Comment by xariskaliakatsos** [comment] 2024-09-10 22:48
is there a work around for this?

**Comment by JayDi85** [comment] 2024-12-14 18:36
Fixed by 4bce1e0a9a72f829a0f94ac2c85e1ad6e7e951ee

**Closed by JayDi85** 2024-12-14 18:36 UTC
Labels: bug
