### ISSUE TITLE
Nissa, Resurgent Animist Forcing Rollback

### ISSUE THREAD

**Issue by JelloPiranha** [magefree/mage#10430] opened 2023-06-04 14:55 UTC
The trigger from Nissa, Resurgent Animist keeps forcing the turn to rollback. I'm sure the relevant info is in the crash log, but I'll explain the turn here anyway in case that helps: It was the first Landfall trigger of the turn, and there was also a Lotus Cobra trigger and a Retreat to Hagra trigger on the stack. There were still Elfs and/or Elementals in my deck, which was my first thought, but it's only the first time the ability has triggered anyway. Reordering the triggers doesn't help. I've definitely played games where Nissa's trigger works correctly and even does the "search" on subsequent triggers, but trying to add the mana is crashing this game for some reason.

"Game exception occurred: 

java.lang.NullPointerException
Server version: 1.4.52-V4-beta2 (build: 2023-05-12 14:27)
Stack trace:
mage.watchers.common.AbilityResolvedWatcher.getResolutionCount(AbilityResolvedWatcher.java:39)
mage.abilities.effects.common.IfAbilityHasResolvedXTimesEffect.apply(IfAbilityHasResolvedXTimesEffect.java:40)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:199)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:183)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:152)
mage.game.stack.StackAbility.resolve(StackAbility.java:85)
mage.game.GameImpl.resolve(GameImpl.java:1690)
mage.game.GameImpl.playPriority(GameImpl.java:1615)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:125)
mage.game.GameImpl.playTurn(GameImpl.java:1087)
mage.game.GameImpl.play(GameImpl.java:997)
mage.game.GameImpl.start(GameImpl.java:973)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)"

**Comment by SHADILLAC77** [comment] 2023-06-04 19:21
I have had the exact same problem. Below is the output provided.


java.lang.NullPointerException
Server version: 1.4.52-V4-beta2 (build: 2023-05-12 14:27)
Stack trace:
mage.watchers.common.AbilityResolvedWatcher.getResolutionCount(AbilityResolvedWatcher.java:39)
mage.abilities.effects.common.IfAbilityHasResolvedXTimesEffect.apply(IfAbilityHasResolvedXTimesEffect.java:40)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:199)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:183)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:152)
mage.game.stack.StackAbility.resolve(StackAbility.java:85)
mage.game.GameImpl.resolve(GameImpl.java:1690)
mage.game.GameImpl.playPriority(GameImpl.java:1615)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:125)
mage.game.GameImpl.playTurn(GameImpl.java:1087)
mage.game.GameImpl.play(GameImpl.java:997)
mage.game.GameImpl.start(GameImpl.java:973)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by xenohedron** [comment] 2023-06-04 19:42
Duplicate of #10424 and likewise fixed by 35ecc51 (pending next beta release)

**Closed by xenohedron** 2023-06-04 19:42 UTC
