### ISSUE TITLE
Whip of Erebos on commander in graveyard interaction issue

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3060] opened 2017-04-05 01:27 UTC
If you use Whip of Erebos to bring back a commander from your graveyard and whip's replacement effect triggers, you cannot have your commander go to the command zone. The question to move it to the command zone appears but pressing yes does nothing.

(from forums)

**Comment by jeffwadsworth** [comment] 2017-04-05 19:53
I don't play Commander, but it should be a simple check to see if the "commander" is part of any player's "commander list".  Perhaps someone that plays this variant can test.

@Override
    public boolean replaceEvent(GameEvent event, Ability source, Game game) {
        Permanent permanent = game.getPermanent(source.getFirstTarget());
        Player controller = game.getPlayer(source.getControllerId());
        if (permanent != null 
                && controller != null
                && !controller.getCommandersIds().contains(permanent.getId())) {
            controller.moveCardToExileWithInfo(permanent, null, null, source.getSourceId(), game, Zone.BATTLEFIELD, true);
        }
        return true;
    }

**Comment by emerald000** [comment] 2017-04-06 02:56
I don't think we should add Commander specific code to cards. The issue will probably be fixed by not using the old moveCardWithInfo methods but the newer one.

**Comment by jeffwadsworth** [comment] 2017-04-06 19:00
If you play Commander, perhaps you can make that change to the method and check it out.

**Comment by ssouders412** [comment] 2019-12-22 05:31
I let my commander, K'rrik, go to the grave, then brought him back with Whip of Erebos. At end of turn, I selected to have him go back to the command zone, and confirmed this selection in the game log, but he went to exile instead.

**Comment by jeffwadsworth** [comment] 2019-12-22 06:02
903.9. If a commander would be exiled from anywhere or put into its owner’s hand, graveyard, or library from anywhere, its owner may put it into the command zone instead. This replacement effect may apply more than once to the same event. This is an exception to rule 614.5.

**Comment by Zerrisx** [comment] 2020-06-27 17:00
Cannot reproduce; this appears to be fixed.

**Closed by Zerrisx** 2020-06-27 17:00 UTC
Labels: bug
