### ISSUE TITLE
Progenitor Mimic (possibly other clones?) stays on battlefield after their owner leaves/loses the gams

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#3916] opened 2017-09-01 21:18 UTC
If I understand correctly, if a clone card gets stolen with Control Magic and the like, and the owner dies, it should disappear. Recently I've had a Progenitor Mimic stick around even after the owner conceded.

**Comment by theelk801** [comment] 2017-09-01 22:52
So your opponent owned Progenitor Mimic and you had stolen it or it was your Progenitor Mimic and you copied your opponent's creature?

**Comment by Zzooouhh** [comment] 2017-09-02 02:55
The former. Also it was the original Progenitor Mimic, not its token copies that stayed.

**Comment by LevelX2** [comment] 2017-09-03 05:55
I guess this is no card specific problem but caused by errors that can happen during the player removing from the game.
Handled here: #3885

**Comment by Zerrisx** [comment] 2020-07-17 21:59
Duplicate of #4472

**Closed by Zerrisx** 2020-07-17 21:59 UTC
Labels: not confirmed
