### ISSUE TITLE
[VOW] Auras cast with disturb do not allow a target to be selected

### ISSUE THREAD

**Issue by Cytocide** [magefree/mage#8901] opened 2022-05-01 02:18 UTC
I am not sure if this is true for all disturb cards but it is at least the case for [[Dorothea, Vengeful Victim]] and [[Mirrorhall Mimic]]. When you cast the aura side from your graveyard it simply doesn't prompt you to select a target, and thus the aura just immediately exiles itself as it isn't attached to anything

**Comment by jeffwadsworth** [comment] 2022-05-01 13:53
[[Mirrorhall Mimic]]

**Comment by Alex-Vasile** [comment] 2022-05-01 14:25
Duplicate of #8572

**Closed** 2022-07-09 03:38 UTC
