### ISSUE TITLE
New Version 1.4.51-dev (2022-09-24 06-57) keeps failing on token creation

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9576] opened 2022-09-26 01:50 UTC
First game, drew due to random infinite loop.  Computer had Bitterblossom in play... that was it.

Second game, I played Breya.  Got this error message, which was repeatable every time I tried to play Breya.  Instant turn rollback.

![image](https://user-images.githubusercontent.com/82664393/192178367-d82ed0c9-4b67-4215-846a-84da423b3683.png)

Attempting third game to see.

**Comment by LegionedintheDamned** [comment] 2022-09-26 01:54
It seems to be any token.  Same error on casting Skyclave Relic with kicker.  I will restart the server, and change the decks to see if it is different.

![image](https://user-images.githubusercontent.com/82664393/192178821-6e946089-cade-428e-a35d-40e1cbad231d.png)

**Comment by LegionedintheDamned** [comment] 2022-09-26 02:00
Fourth try yielded the same.  Sacrificed Risen Executioner to Wilhelt, the Rotcleaver as his end of turn trigger.

![image](https://user-images.githubusercontent.com/82664393/192179452-8daa1cf8-d5cc-438a-882e-c3411464fabd.png)

**Comment by Grath** [comment] 2022-09-26 02:06
Duplicate of already-fixed-but-not-released #9562 - take the Idol of Oblivion (or some other thing that cares about whether or not a token was created this turn) out of your deck or play a different deck until the next release of Beta.

**Closed** 2022-09-26 02:17 UTC
