### ISSUE TITLE
Aftermath cards are lacking text

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#8229] opened 2021-09-07 04:31 UTC
This might be something that only appears as such with image mode (not mtgo rendering). But aftermath cards do not show the card text, even when hovered over. This makes drafting very hard as I have to currently look up the card text separately on scryfall.

![image](https://user-images.githubusercontent.com/46700039/132284561-8208f2f8-ccd8-4d9a-a363-47961de5d99f.png)

**Comment by awjackson** [comment] 2021-09-07 05:04
AKR, I presume? That's just what the card images on scryfall look like for that set because they're taken from Arena: https://scryfall.com/search?q=set%3Aakr+is%3Asplit

**Comment by JayDi85** [comment] 2021-09-07 06:40
You can use mouse wheel to change popup card style from image to text (popup over mouse move). BTW preferences settings contains popup settings, so you can decrease it to show card hint more quickly.

**Comment by JayDi85** [comment] 2021-09-07 06:42
I recommends to use text mode cause many cards have special card hints in the rules text so you don't need to calc permanents amount or another conditions -- xmage shows you an actual value.

**Comment by awjackson** [comment] 2022-03-12 14:22
Duplicate of #8541

**Closed by awjackson** 2022-03-12 14:22 UTC
