### ISSUE TITLE
New mode: MTGA Cascade

### ISSUE THREAD

**Issue by zeflap** [magefree/mage#5456] opened 2018-12-11 11:51 UTC
From what I can think, this seems like it'd be as simple as having the ability to have arbitrary cards as emblem forms in the command zone.

Of course, this would probably wreak havoc with assumptions.
still, here's hoping

**Comment by zeflap** [comment] 2018-12-11 11:54
And just to clarify, the "mode" is just Standard with each player having an emblem of Maelstrom Nexus.

**Comment by Zerrisx** [comment] 2020-07-14 16:42
Duplicate of #6766

**Comment by xenohedron** [comment] 2023-09-30 22:27
Functionality added in #10498

**Closed by xenohedron** 2023-09-30 22:27 UTC
Labels: enhancement
