### ISSUE TITLE
5 Color commanders like Sisay, Weatherlight Captain provide all colors for Bloom Tender.

### ISSUE THREAD

**Issue by AsterAether** [magefree/mage#8218] opened 2021-09-04 21:40 UTC
[[Bloom Tender]] provides WUBRG when tapped when [[Sisay, Weatherlight Captain]] is on the battlefield.

**Comment by alexander-novo** [comment] 2021-09-04 22:42
Same issue as #7983, #7987, #8089

**Comment by Alex-Vasile** [comment] 2022-09-27 18:46
Closing as duplicate of #7983

**Closed by Alex-Vasile** 2022-09-27 18:46 UTC
