### ISSUE TITLE
Only able cast Gift of Doom if a creature is on bf, even if I want to play as a morph

### ISSUE THREAD

**Issue by JohnPetfield** [magefree/mage#7121] opened 2020-10-09 08:39 UTC
3 lands, gift of doom in my hand and although it's highlighted I cannot play it (I should be able to play it as a face down creature):
![image](https://user-images.githubusercontent.com/64497504/95561668-f91c4280-0a12-11eb-80db-28612d6bd50f.png)

3 lands, gift of doom in hand and a creature on the board now allows me to cast Gift of Doom as a facedown creature:
![image](https://user-images.githubusercontent.com/64497504/95561796-2e289500-0a13-11eb-9e03-befb6b3ddfe3.png)

**Comment by Alex-Vasile** [comment] 2022-09-27 18:16
Duplicate of #6045, and should have been fixed?

**Comment by johnmeat** [comment] 2022-09-27 18:22
nope, tried in the beta, gift of doom in hand no creatures on the battlefield, it is highlighted as though it should be able to be cast but clicking it does nothing.

![image](https://user-images.githubusercontent.com/64497504/192606162-9a5c4451-306e-45a1-93a7-558eee070976.png)

**Comment by Alex-Vasile** [comment] 2022-09-27 18:23
Then https://github.com/magefree/mage/commit/6d21c9d3dce94bb37e243a4e1f49d524b82f3719 was not enough.

Alrighty. This is still an issue then.

**Closed** 2023-10-03 03:01 UTC
Labels: bug
