### ISSUE TITLE
Combat Celebrant can be exerted multiple times per turn with vigilance

### ISSUE THREAD

**Issue by MaygeKyatt** [magefree/mage#3345] opened 2017-05-11 02:21 UTC
If combat celebrant is given vigilance, it can be exerted repeatedly in a single turn, effectively allowing for infinite combat steps unless it's killed. However, as the card text states, it should only be exertable if it hasn't been previously exerted that turn.

**Comment by drmDev** [comment] 2017-05-11 04:25
we have tried many times to duplicate this issue but have been unable to. see https://github.com/magefree/mage/issues/3195 and the associated tests. need a log showing infinite combat steps to investigate further

**Comment by drmDev** [comment] 2017-05-11 18:02
Attempted again with Always Watching out and was unable to exert Celebrant more than once. As mentioned in the issue linked above, need a log to investigate further. Unable to duplicate still. Celebrant can still attack again in the additional combat phase, just cannot exert again in the same turn.

**Comment by MaygeKyatt** [comment] 2017-05-11 22:43
Opponent played Combat Celebrant, then next turn played Arlinn Kord and used her +1 to give Combat Celebrant vigilance. He then attacked and exerted, then in the second combat phase attacked again and was once more given the option to exert. He did so just to see if it would actually work. It did, giving him a third combat phase, during which he didn't attack because he recognized that it was a glitch. I thus don't know whether it would have allowed him to exert a third time, but I doubt it would be any different than the second time. Here's the relevant section of the log:

`<font color="#CCCC33">7:43 PM: </font><font color="#20B2AA">Mastaalucard</font><font color="White"> 
    puts </font><font color="#DAA520"><a href="#Arlinn Kord">Arlinn Kord</a></font><font color="White"> 
    [756] from stack onto the Battlefield</font>
<font color="#CCCC33">7:43 PM: </font><font color="#20B2AA">Mastaalucard</font><font color="White"> 
    activates: Until end of turn, up to one target creature gets +2/+2 and 
    gains vigilance and haste. from </font><font color="#DAA520"><a href="#Arlinn Kord">Arlinn 
    Kord</a></font><font color="White"> [756] targeting </font><font color="#FF6347"><a href="#Combat Celebrant">Combat 
    Celebrant</a></font><font color="White"> [393] </font>
<font color="#CCCC33">7:43 PM: </font><font color="#20B2AA">Mastaalucard</font><font color="White"> 
    exerted Combat Celebrant</font>
<font color="#CCCC33">7:43 PM: </font><font color="#20B2AA">Mastaalucard</font><font color="White"> 
    attacks with 1 creature</font>
<font color="#CCCC33">7:43 PM: </font><font color="White">Ability triggers: </font><font color="#FF6347"><a href="#Combat Celebrant">Combat 
    Celebrant</a></font><font color="White"> [393] - When </font><font color="#FF6347"><a href="#Combat Celebrant">Combat 
    Celebrant</a></font><font color="White"> [393] becomes exerted, untap all 
    other creature you control you control and after this phase, there is an 
    additional combat phase.</font>
<font color="#CCCC33">7:44 PM: </font><font color="White">Attacker: </font><font color="#FF6347"><a href="#Combat Celebrant">Combat 
    Celebrant</a></font><font color="White"> [393] (6/3) unblocked</font>
<font color="#CCCC33">7:44 PM: </font><font color="#20B2AA">MaygeKyatt</font><font color="White"> 
    loses 6 life</font>
<font color="#CCCC33">7:44 PM: </font><font color="#20B2AA">Mastaalucard</font><font color="White"> 
    starts an additional Combat phase</font>
<font color="#CCCC33">7:44 PM: </font><font color="#20B2AA">Mastaalucard</font><font color="White"> 
    exerted Combat Celebrant</font>
<font color="#CCCC33">7:44 PM: </font><font color="#20B2AA">Mastaalucard</font><font color="White"> 
    attacks with 1 creature</font>
<font color="#CCCC33">7:44 PM: </font><font color="White">Ability triggers: </font><font color="#FF6347"><a href="#Combat Celebrant">Combat 
    Celebrant</a></font><font color="White"> [393] - When </font><font color="#FF6347"><a href="#Combat Celebrant">Combat 
    Celebrant</a></font><font color="White"> [393] becomes exerted, untap all 
    other creature you control you control and after this phase, there is an 
    additional combat phase.</font>
<font color="#CCCC33">7:45 PM: </font><font color="White">Attacker: </font><font color="#FF6347"><a href="#Combat Celebrant">Combat 
    Celebrant</a></font><font color="White"> [393] (6/3) unblocked</font>
<font color="#CCCC33">7:45 PM: </font><font color="#20B2AA">MaygeKyatt</font><font color="White"> 
    loses 6 life</font>
<font color="#CCCC33">7:45 PM: </font><font color="#20B2AA">Mastaalucard</font><font color="White"> 
    starts an additional Combat phase</font>
<font color="#CCCC33">7:45 PM: </font><font color="#20B2AA">Mastaalucard</font><font color="White"> 
    attacks with 0 creatures</font>`

**Comment by drmDev** [comment] 2017-05-11 22:58
Still unable to duplicate. It's possible this was an issue in v4 but not an issue on the current code in master which be released in v5 (and what I'm testing against).

![celebrant-arlinn](https://cloud.githubusercontent.com/assets/11060241/25975332/b081b168-367b-11e7-9a4c-13ac5cc73f48.png)
Was never given the option to be able to exert a second time - screenshot taken at the point where I would usually be given the option to.

Does your client and server version show 1.4.23v4 as well?

**Comment by MaygeKyatt** [comment] 2017-05-11 23:24
Yes. Also, as I said, it was my opponent playing the cards, not me, so I don't know all the details.

**Comment by drmDev** [comment] 2017-05-21 16:14
unable to reproduce

**Closed by drmDev** 2017-05-21 16:14 UTC
Labels: AKH, bug, Not confirmed

**Comment by jsut** [comment] 2018-04-10 03:11
I just ran into this in a game. And this is probably going to be coming up a lot due to the success of the UR GPG deck at GP seattle on the weekend. I was not playing the celebrants, but it did say in the on screen log that his three celebrants, all of which had been exerted previously, were once again exerted.  I am suspicious that it actually did to everything right, aside from reporting that the celebrants were exerted when they couldn't have been.

Here's roughly how it went down:

- he played a celebrant.
- I lost legacy'ed the rest of them into exile, so he only had the one left anywhere
- he got GPG down
- he returned the celebrant, attacked and exerted
- on the combat phase that immediate followed, he returned a vizier of many faces, and chose to duplicate the celebrant.
- attacks again, exerting the vizier/celebrant, original celebrant untaps.
- third combat phase of the turn, he returns another vizier, and makes a third celebrant, and attacks.
- From what i recall, at this point all three celebrants ended up tapped, but the log said they were exerted.  however if the ability had actually gone off then 2 of them should have been untapped.
