### ISSUE TITLE
Game did not open after game start.

### ISSUE THREAD

**Issue by Invaine** [magefree/mage#9301] opened 2022-07-21 15:08 UTC
2 player Sealed Elimation Cube
Everything proceed like normal until deckbuilding was finished. Game started yet the window for the game did not appear to either player and clicking the watch button did nothing. The timer did indicate the match started, but the game was missing from the switch panels screen.

**Comment by Alex-Vasile** [comment] 2022-09-05 04:49
Seems like a duplicate of #5555. See comments there for hints on how to avoid and what to try if it happens.

**Closed** 2022-09-05 04:49 UTC
Labels: bug
