### ISSUE TITLE
Goblin Welder doesn't trigger dies-abilities

### ISSUE THREAD

**Issue by Jipsu** [magefree/mage#8578] opened 2022-01-21 20:17 UTC
Sacrificing a [[Hangarback Walker]] with [[Goblin Welder]] doesn't produce any tokens and sacrificing [[Solemn Simulacrum]] doesn't draw a card.

22:12, T8.M2: Jipsu activates: Choose target artifact a player controls and target artifact card in that player's graveyard. If both targets are still legal as this ability resolves, that player simultaneously sacrifices the artifact and returns the artifact card to the battlefield. from Goblin Welder [940] targeting Hangarback Walker [43f]Solemn Simulacrum [355]
22:12, T8.M2: Jipsu sacrificed Hangarback Walker [43f] (source: Goblin Welder [940])
22:12, T8.M2: Jipsu puts Solemn Simulacrum [355] from graveyard onto the Battlefield (source: Goblin Welder [940])
22:12, T8.M2: Jipsu - Ability triggers: Solemn Simulacrum [355] - When Solemn Simulacrum [355] enters the battlefield, you may search your library for a basic land card, put that card onto the battlefield tapped, then shuffle.
22:13, T8.M2: Jipsu searches their library (source: Solemn Simulacrum [355])
22:13, T8.M2: Jipsu puts Mountain [2b6] from library onto the Battlefield (source: Solemn Simulacrum [355])
22:13, T8.M2: Jipsu's library is shuffled (source: Solemn Simulacrum [355])

22:14, T10.M1: Jipsu activates: Choose target artifact a player controls and target artifact card in that player's graveyard. If both targets are still legal as this ability resolves, that player simultaneously sacrifices the artifact and returns the artifact card to the battlefield. from Goblin Welder [940] targeting Solemn Simulacrum [355]Hangarback Walker [43f]
22:14, T10.M1: Jipsu sacrificed Solemn Simulacrum [355] (source: Goblin Welder [940])
22:14, T10.M1: Jipsu puts Hangarback Walker [43f] from graveyard onto the Battlefield (source: Goblin Welder [940])
22:14, T10.M1: Jipsu - Ability triggers: Hangarback Walker [43f] - When Hangarback Walker [43f] dies, create a 1/1 colorless Thopter artifact creature token with flying for each +1/+1 counter on Hangarback Walker [43f].
22:14, T10.M1: Hangarback Walker [43f] is put into graveyard from battlefield

**Comment by Alex-Vasile** [comment] 2022-01-25 07:55
Duplicate of #7672

**Comment by jeffwadsworth** [comment] 2022-01-26 17:16
https://github.com/magefree/mage/commit/5dcbb49ba6ad3cba0d0b57dd5c763fecd05e2c85

**Closed by jeffwadsworth** 2022-01-26 17:16 UTC
