### ISSUE TITLE
Eureka uncastable during second game of match

### ISSUE THREAD

**Issue by rystan** [magefree/mage#4966] opened 2018-05-23 04:10 UTC
![2018-05-22 23_46_00-](https://user-images.githubusercontent.com/6609665/40403058-46e72ca4-5e1d-11e8-812d-cd7f69d5150d.png)

During the first game of the match, Eureka was castable and worked as expected.
During the second game of the match, I got Eureka again but was unable to cast the spell, despite having the mana available to cast it.  The card showed with a purple border regardless of how much mana I had available and when I attempted to cast it it popped up with a "choose spell or ability to play" dialog but did not cast the spell.

**Comment by rystan** [comment] 2018-05-28 05:13
The deck in question in the above scenario has a bunch of "play permanents without paying their mana cost" cards including things like: Genesis Wave, Primal Surge, Eureka, etc.  I don't have the game logs anymore to be certain what happened in game one exactly.  

Had a similar (but different and potentially related) situation happen in a game earlier where in the first game of the match, I played a Wave of Vitriol which swept up all of my opponent non-basic lands to be replaced with basic lands.  In game two, one of the "Enter the battlefield type lands", that was likely on the board during the Wave, got played to the battlefield untapped in turn 1.

![2018-05-27 22_35_45-greenshot](https://user-images.githubusercontent.com/6609665/40598075-9d52a420-6213-11e8-90dc-b48addb3dd12.png)

The way that I think they might be related is that there seems to be some sort of retention of state between games for individual cards in player decks.  Should/does the game/deck loading logic load brand new copies of the card classes every time you build an instance of the deck?

**Comment by LevelX2** [comment] 2018-05-28 09:58
> Should/does the game/deck loading logic load brand new copies of the card classes every time you build an instance of the deck?

That wouldn't solve the problems within one game, that also happen.

We have generally to prevent that card attributes are changed. Or to say it in onther way, all card states that can be changed have to be handeled in a way that they don't cause such problems.

**Comment by Zerrisx** [comment] 2020-07-07 18:17
Duplicate of #4600

**Closed by Zerrisx** 2020-07-07 18:17 UTC
