### ISSUE TITLE
Annoying Pop-up error everytime I scroll over a card. Please help!

### ISSUE THREAD

**Issue by tarmogyzzoyf** [magefree/mage#833] opened 2015-03-25 09:58 UTC
Hey guys, I'm new to xMage and very excited about finally being able to play with my friends abroad.

The only problem is that I have a recurring error pop-up whenever i scroll over a card in game. It says "nullpointerexception". Can anyone help me resolve this? I've tried Googling, but havent had success.

Here is a screenshot of said error: http://i.imgur.com/yk7hJro.jpg

thanks in advance!

**Comment by LevelX2** [comment] 2015-03-25 10:52
I presume a problem with Java 8 in some situations.

You can reset your client to java 7 (see link).
And please report if this solves the problem for you.
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16910&start=75#p175911

**Comment by tarmogyzzoyf** [comment] 2015-03-26 11:03
I tried what you suggested. The problem was fixed but the card images and mana symbols within the game stopped working. I reverted back to the previous xMage home and my nullpointexception error still persists.

**Comment by LevelX2** [comment] 2015-03-28 09:03
duplicate of #839

**Closed by LevelX2** 2015-03-28 09:03 UTC
