### ISSUE TITLE
Kaldheim Gods don't track commander damage. When hitting people with Toralf or Tergrid (And I imagine the other 2-sided Gods) there is no tracking of commander damage dealt so I assume people wouldn't die of commander damage either

### ISSUE THREAD

**Issue by kingbasofnl** [magefree/mage#9955] opened 2023-02-06 12:10 UTC

**Comment by PurpleCrowbar** [comment] 2023-02-06 14:28
Duplicate of #7637

**Closed by PurpleCrowbar** 2023-02-06 14:28 UTC
