### ISSUE TITLE
Fluctuator not reducing cycle cost

### ISSUE THREAD

**Issue by 1kelvin** [magefree/mage#3302] opened 2017-05-04 02:03 UTC
Cycling cost still requires the full mana cost when fluctuator is on the battlefield.

**Comment by ingmargoudt** [comment] 2017-05-04 08:06
We have unit tests confirming this. This issue will be looked into.

**Comment by Simown** [comment] 2017-05-05 08:13
Duplicate of #3148

**Closed** 2017-05-05 08:25 UTC
Labels: bug, duplicate
