### ISSUE TITLE
MIstbind Clique doesn't tap all lands

### ISSUE THREAD

**Issue by cosmokai2000** [magefree/mage#942] opened 2015-04-29 18:27 UTC
Mistbind Clique doesn't tap all lands when championing a faerie. I've been able to reproduce this

**Comment by ImperatorPrime** [comment] 2015-04-29 18:30
Duplicate of 938.

**Closed by ImperatorPrime** 2015-04-29 18:30 UTC

**Comment by cosmokai2000** [comment] 2015-04-29 18:34
938 was fixed yesterday, I was able to to this twice today

**Comment by ImperatorPrime** [comment] 2015-04-29 18:35
Using the regular launcher or checked out code? Because the fix hasn't been released yet.

**Comment by cosmokai2000** [comment] 2015-04-29 18:37
Launcher. Sorry then, my apologies
