### ISSUE TITLE
Denri Kiln, Editor in Chief entering with 128 counters

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10165] opened 2023-04-03 04:18 UTC
Rolled back, 64 vigilance counters.  Rolled back, tried first strike - 128 counters.  Did the same with +1/+1 counters, 128 counters again.

![image](https://user-images.githubusercontent.com/82664393/229410121-a1442d71-5232-4f03-9191-8df74d6bdc52.png)

**Comment by xenohedron** [comment] 2023-06-17 04:17
Duplicate of #9779

**Closed by xenohedron** 2023-06-17 04:17 UTC
Labels: bug
