### ISSUE TITLE
Dire Fleet Daredevil vs Catch Release [card]

### ISSUE THREAD

**Issue by pwn0r** [magefree/mage#4594] opened 2018-03-10 03:39 UTC
_exile target instant or sorcery card from an opponent's 
    graveyard. You may cast that card this turn and you may spend mana as 
    though it were mana of any color. If that card would be put into a 
    graveyard this turn, exile it instead._

I was unable to cast **Catch Release** catched [pun intended] with **Dire Fleet Devil** during same turn. It somehow still required blue mana to cast Catch part.

**Comment by LevelX2** [comment] 2018-03-10 07:38
Did you try to use mana from the mana pool?

Because that will work only with the next update not with 1.4.27V4b.

**Comment by pwn0r** [comment] 2018-03-10 19:08
I think I tried all the ways during that situation in order to cast it, but always asked for {U}. 
So is this problem with only this card or any card which allows to cast spells with any mana?

**Comment by JayDi85** [comment] 2018-03-10 19:21
`DireFleetDaredevilSpendAnyManaEffect` have that code:
```
    @Override
    public ManaType getAsThoughManaType(ManaType manaType, ManaPoolItem mana, UUID affectedControllerId, Ability source, Game game) {
        return mana.getFirstAvailable();
    }
```

It's return first available mana type from mana pool... Maybe the best way is return GENERIC mana type?

**Comment by pwn0r** [comment] 2018-03-10 19:42
update: I run some games against computer opponent -- it does appear to work OK on single cards, as I thought I used before. So for whatever reason that split card was the problem.

**Comment by Zerrisx** [comment] 2020-05-26 20:58
Duplicate of #6549

**Comment by JayDi85** [comment] 2020-06-03 08:51
It works fine in old and current dev version (Dire Fleet Daredevil with Catch Release).

**Closed by JayDi85** 2020-06-03 08:51 UTC
