### ISSUE TITLE
Nest of scarabs is not triggering with -1/-1 counters.

### ISSUE THREAD

**Issue by feltax** [magefree/mage#3307] opened 2017-05-04 18:56 UTC
Tested with souls-scar mage, channeler initiate and ruthless sniper. No trigger is created.
Seems to be a continuation of [Issue 3174](https://github.com/magefree/mage/issues/3174)

**Comment by drmDev** [comment] 2017-05-05 01:50
duplicate of #3174 resolved with the commit in there e73a2f5c58a1a91f70ddc140a4a33c8a81877fb6 . Test the interaction on the latest code from master, or wait until the next public release is out.

**Closed by drmDev** 2017-05-05 01:50 UTC
Labels: bug, duplicate, Not confirmed
