### ISSUE TITLE
K'rrik, Son of Yawgmoth bugged

### ISSUE THREAD

**Issue by Kwhorstkamp** [magefree/mage#6928] opened 2020-08-02 20:06 UTC
Tried to cast black spells with K'rrik, Son of Yawgmoth but unless i had enough mana untapped i couldnt pay life to use the phyrexian ability.

2 available mana, can't cast a 2B spell.
5 mana available, can't cast a 5BBB etc.

**Comment by Zerrisx** [comment] 2020-08-02 20:11
Duplicate of #6698

**Closed** 2020-08-03 17:17 UTC
Labels: bug
