### ISSUE TITLE
Latest server crushes by bugs or memory leaks

### ISSUE THREAD

**Issue by JohnPetfield** [magefree/mage#9818] opened 2022-12-19 20:19 UTC
Not sure if this is true, thought I'd raise just in case as I know #9815 addressed the guy trolling the other night:

![image](https://user-images.githubusercontent.com/64497504/208513501-6cb456ad-6cfa-42aa-8001-f1343508122a.png)

**Comment by Merlingilb** [comment] 2022-12-20 02:19
I am willing to help to find the bug but without server logs it is difficult to try to find anything.

**Comment by JayDi85** [comment] 2022-12-20 02:31
Server logs don't have any related errors. Are you sure about password related crash or it's just a joke from the troll?

**Comment by Merlingilb** [comment] 2022-12-20 02:34
Unfortunatly not sure... he kept saying it but the last two crashes he wasn't around...
If the server logs don't show any errors why does it crash then?

I really enjoy the game and just want to help fix such annoying problems. If you need any help with that I would be happy to help you.

(FYI I am a software engineer from germany)

**Comment by JayDi85** [comment] 2022-12-20 02:36
There are possible rare decks/use cases with too much tokens or effects, so server will catch memory limit/overflow and go to restart.

**Comment by Merlingilb** [comment] 2022-12-20 02:39
that's unfortunate... would we be able to just end the specific game if something like this happens to let the server live on and just end the problematic game?

**Comment by JayDi85** [comment] 2022-12-20 02:44
It's impossible to find the memory moment. But you can try to find a reproduceable use case, so it will be fixed.

**Comment by Merlingilb** [comment] 2022-12-20 03:41
but isn't there a token limit per player?

**Comment by JayDi85** [comment] 2022-12-20 03:52
There are possible infinite cycle with effects or other game objects, not only tokens. Also long and big games can eats the memory (the more cards/objects/effects on the table -- the more memory eating by its).

Crash moment example:
![shot_221220_075220](https://user-images.githubusercontent.com/8344157/208579799-f9de4c36-6bf3-43f7-b2b3-82795f7c8959.png)


Memory usage by games:
![shot_221220_074758](https://user-images.githubusercontent.com/8344157/208579435-73afb2c8-143b-456b-93dc-02ec274da750.png)

**Comment by Merlingilb** [comment] 2022-12-20 03:56
18 GB for 1 game???
Wow did not expect that much...

Why is is so much? The card data and game state cannot be so much... Is there a reason why a game can have several GB?

**Comment by JayDi85** [comment] 2022-12-20 03:56
Big game example (18 MB memory eats):
GAME started cfde72b1-dd7b-4b2d-81ae-2c6eb7b3bd85 [Casual EDH 6-8 3 mulls] Monolithic - Local Yandere - Heads I win - mentalblockage

**Comment by JayDi85** [comment] 2022-12-20 04:05
> 18 GB for 1 game

Well, it's a total memory usage, not real time. Real memory allocation for all game objects will be much less.

Big game example from screenshot:
GAME started cfde72b1-dd7b-4b2d-81ae-2c6eb7b3bd85 [Casual EDH 6-8 3 mulls] Monolithic - Local Yandere - Heads I win - mentalblockage

**Comment by Merlingilb** [comment] 2022-12-20 04:16
but doesn't it say "per thread allocated memory"?
for me that sounds like there is a lot of paging going on which would make everything very slow.... i did not yet host a xmage server so i do not have any experience in that but the memory usage seems quite high for a game server that only has to save text.

If that is the most common way the server crashes, maybe we should invest some time to reduce that?
Or is it more the problem that some card combinations trigger loops that never end? Then the focus should be on fixing those effects.

I am not sure what the best strategy here is but lately playing on the server became very annoying. We as a group can finish 1 out of 3 games at average. That is one reason why I thougt about helping with the development (and because we love the star wars extension and I wanted to implement the newest sets)

**Comment by JayDi85** [comment] 2022-12-20 04:24
Memory allocation is not a problem (it's works fast). The main problem -- memory leaks or freezed games. So server can't free memory for another games. Moreover it's a deck/cards specific problem, so each use case must be research and fixed each time.

If someone want to investigate actual memory leaks then here is a data (snapshots for one minute work, use VisualVM to view and compare):
* [xmage-memory-growing-per-minute.zip](https://github.com/magefree/mage/files/10265242/xmage-memory-growing-per-minute.zip)

<details>
<summary>Screenshots with new objects stats:</summary>

![shot_221220_081224](https://user-images.githubusercontent.com/8344157/208583112-69772724-9486-43dd-95f4-43b25d5ced30.png)
![shot_221220_081234](https://user-images.githubusercontent.com/8344157/208583120-c0140ca5-f287-460b-89b5-24f324b03ac9.png)
![shot_221220_081245](https://user-images.githubusercontent.com/8344157/208583127-feddb675-49da-425b-81ba-3beffc13625d.png)
![shot_221220_081254](https://user-images.githubusercontent.com/8344157/208583132-fc2ac2d2-222a-427c-b399-09f83333617e.png)

</details>

**Closed** 2023-05-08 16:30 UTC
Labels: server
