### ISSUE TITLE
Sealed game failing to start when 2nd player readies too slowly

### ISSUE THREAD

**Issue by Magicfanf** [magefree/mage#7781] opened 2021-04-28 22:48 UTC
I had several instances of a game when I completed my sealed pool more than 3 min after my opponent, and I don't even get to see the match window. The same happened today to my opponent. I can't explain why, nor where to get a log to track what happens?

**Comment by Alex-Vasile** [comment] 2022-09-28 03:08
Duplicate of #5555

**Closed by Alex-Vasile** 2022-09-28 03:08 UTC
