### ISSUE TITLE
Casting Expressive Iteration and Choosing Card to 'Bottom' Causes Session Rollback

### ISSUE THREAD

**Issue by lofiry** [magefree/mage#9250] opened 2022-07-11 02:00 UTC
Version running: 1.4.51-dev (2022-07-09 15-23)
Operation System: Windows 10

Steps to Reproduce:
1. Open XMage
2. Launch Client & Server
3. Log into local server
4. 5. Create a game, against the AI, game mode: modern.
6. Cast Expressive Iteration
7. Select a card to 'hand'
8. Select a card to 'bottom'
9. Crash report occurs
10. End 

It does not matter which card to select, it will cause the error message. Error message returned in system pop-up is below.

> An error has occurred on the MAGE server. Your last action will be rollbacked.
> Please post the following report here: https://github.com/magefree/mage/issues
> 
> Game exception occurred: java.lang.NullPointerException
> Server version: 1.4.51-V4-beta7 (build: 2022-07-09 15:21)
> mage.target.TargetImpl.tryToAutoChoose(TargetImpl.java:665)
> mage.player.human.HumanPlayer.choose(HumanPlayer.java:730)
> mage.cards.e.ExpressiveIterationEffect.apply(ExpressiveIteration.java:99)
> mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:201)
> mage.abilities.AbilityImpl.resolve(AbilityImpl.java:188)
> mage.game.stack.Spell.resolve(Spell.java:241)
> mage.game.GameImpl.resolve(GameImpl.java:1618)
> mage.game.GameImpl.playPriority(GameImpl.java:1544)
> mage.game.turn.Step.priority(Step.java:61)
> mage.game.turn.Phase.playStep(Phase.java:184)
> mage.game.turn.Phase.play(Phase.java:89)
> mage.game.turn.Turn.play(Turn.java:132)
> mage.game.GameImpl.playTurn(GameImpl.java:1042)
> mage.game.GameImpl.play(GameImpl.java:952)
> mage.game.GameImpl.start(GameImpl.java:928)
> mage.server.game.GameWorker.call(GameWorker.java:34)
> java.util.concurrent.FutureTask.run(FutureTask.java:266)
> java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> java.lang.Thread.run(Thread.java:748)

**Comment by Alex-Vasile** [comment] 2022-07-11 11:23
Duplicate of #9248.

Solve for next beta. See comment in that issue for what to do until then.

**Closed** 2022-07-11 11:24 UTC
