### ISSUE TITLE
Norn's annex still not working

### ISSUE THREAD

**Issue by harbingerofme** [magefree/mage#3530] opened 2017-06-24 23:37 UTC
Bug #3178 was never fixed.

**Comment by drmDev** [comment] 2017-06-25 00:56
It was marked as fixed on master, but a new release has not come out yet to make it publically available.

**Comment by harbingerofme** [comment] 2017-06-26 11:47
It is not an AI bug as the issue is labeled as.

**Comment by drmDev** [comment] 2017-06-26 11:49
removed that label. The commit that resolved the issue was irrelevant to AI anyways, was on the card and its effects itself:
https://github.com/magefree/mage/commit/884a3af503ff3e481ce42120e9a22fed39a24c15

**Comment by Zerrisx** [comment] 2020-06-28 01:47
Cannot reproduce; this appears to be fixed.

**Closed by Zerrisx** 2020-06-28 01:47 UTC
Labels: bug, not confirmed
