### ISSUE TITLE
Visions of Dominance accurately highlights as playable, but the actual flashback cost isn't discounted.

### ISSUE THREAD

**Issue by Grath** [magefree/mage#8499] opened 2021-12-03 19:50 UTC
I suspect the rest of the cycle might be similarly bugged, but I haven't confirmed yet.

**Comment by Grath** [comment] 2021-12-10 01:34
Can confirm, Visions of Glory has the same bug.

**Comment by jeffwadsworth** [comment] 2022-01-06 22:19
[[Visions of Dominance]]

**Comment by Alex-Vasile** [comment] 2022-05-11 14:36
Closing this as duplicate of #8454. See that issue for more info about problem. When that one is fixed, this and the other Visions of X will be fixed.

**Comment by Alex-Vasile** [comment] 2022-05-11 14:37
Closing this as a duplicate. See that issue for more info about problem. When that one is fixed, this and the other Visions of X will be fixed.

**Closed** 2022-05-11 14:36 UTC
