### ISSUE TITLE
C18 Varchild token creation *still* bugged.

### ISSUE THREAD

**Issue by Kerrus** [magefree/mage#5277] opened 2018-08-26 13:15 UTC
Varchild now creates tokens successfully when dealing damage to a player. She just creates them under her controller's control, rather than the damaged player's control as her card text states.

**Comment by kevinwshin** [comment] 2018-08-28 01:00
That was all my fault. I just misread the card. The new fix should be all functional. Hopefully it actually is.

**Comment by Kerrus** [comment] 2018-09-23 04:14
STILL BUGGED.

**Comment by kevinwshin** [comment] 2018-09-24 15:57
Could you give me more details? What situation are you experiencing that is incorrect and what should be happening instead?

**Comment by theelk801** [comment] 2018-09-24 17:02
It's already been fixed with cf67c27

**Comment by jeffwadsworth** [comment] 2019-04-15 14:41
This is still bugged.  The token's are created and controlled by the defender, but the token's are placed on the wrong battlefield.  I will add a picture soon.

**Comment by awjackson** [comment] 2022-04-05 11:08
I can't reproduce this.

**Closed by awjackson** 2022-04-05 11:08 UTC
Labels: bug
