### ISSUE TITLE
Blood Moon effects work in an outdated way with "as it enters" lands

### ISSUE THREAD

**Issue by Dunkoro** [magefree/mage#12698] opened 2024-08-21 18:14 UTC
The interaction between Blood Moon and "As it enters" lands (like shocklands, Cavern of Souls, Vesuva, etc) used to work the way it's implemented in XMage, but it was changed... 7 years ago?

https://gatherer.wizards.com/pages/Card/Details.aspx?multiverseid=509540
```If a nonbasic land has an ability that causes it to enter the battlefield tapped, it will lose that ability before it can apply. The same is also true of any other abilities that modify how a land enters the battlefield or apply "as" a land enters the battlefield, such as that of Vesuva or Cavern of Souls.```

**Comment by Grath** [comment] 2024-08-21 18:15
Duplicate of #4202

**Closed by Grath** 2024-08-21 18:15 UTC
