### ISSUE TITLE
Dress Down not stopping modular nor Walking Ballista, Hangarback Walker

### ISSUE THREAD

**Issue by NapoleonBorn2Party** [magefree/mage#10461] opened 2023-06-13 08:17 UTC
Playing [[Dress Down]] doesn't stop cards like [[Zabaz, the Glimmerwasp]] with modular entering the battlefield with counters. Same thing applies to [[Walking Ballista]] and [[Hangarback Walker]]. This shouldn't happen according to the rule 614.12:
"_Some replacement effects modify how a permanent enters the battlefield. (See rules 614.1c–d.) Such effects may come from the permanent itself if they affect only that permanent (as opposed to a general subset of permanents that includes it). They may also come from other sources. To determine which replacement effects apply and how they apply, check the characteristics of the permanent as it would exist on the battlefield, taking into account replacement effects that have already modified how it enters the battlefield (see rule 616.1), continuous effects from the permanent's own static abilities that would apply to it once it’s on the battlefield, and continuous effects that already exist and would apply to the permanent._" as explained [here](https://strategy.channelfireball.com/home/10-must-know-dress-down-interactions-in-modern-mtg/), [here](https://tappedout.net/mtg-questions/dress-down-interaction-1/) and [here](https://magic.wizards.com/en/articles/archive/news/ixalan-comprehensive-rules-changes-2017-09-28).
As hardened scales is getting popular once again in modern, this is affecting the outcome of some games.

**Comment by Grath** [comment] 2023-06-13 14:11
Duplicate of #4202

**Closed by Grath** 2023-06-13 14:11 UTC
