### ISSUE TITLE
Cross platform xmage to Android

### ISSUE THREAD

**Issue by ghost** [magefree/mage#5512] opened 2019-01-12 07:28 UTC
Hi, there. I saw lot of issues for android platform support, I have idea: Facebook came out a new mobile development engine: React Native, developers can use React Native to write android and iOS platforms app. How our developers think?

**Comment by JayDi85** [comment] 2019-01-12 07:32
It's about new client-server API support. See #5373

**Comment by c4dr01d** [comment] 2019-01-12 07:34
React Native can call java code using React Native Interface. so....

**Comment by Zerrisx** [comment] 2020-07-29 03:58
Duplicate of #5406

**Closed by Zerrisx** 2020-07-29 03:58 UTC
Labels: question
