### ISSUE TITLE
Exiled face-down should be hidden.

### ISSUE THREAD

**Issue by Chewbaklava** [magefree/mage#13069] opened 2024-11-19 03:13 UTC
Example: Bomat Courier. I imagine this issue extends to other cards as well.

![image](https://github.com/user-attachments/assets/0992a6ef-145f-44db-92c5-ea745b198eeb)

**Comment by Chewbaklava** [comment] 2024-11-19 03:16
[[Bomat Courier]]

**Comment by Grath** [comment] 2024-11-19 03:18
Duplicate of #11881

**Closed by Grath** 2024-11-19 03:18 UTC
