### ISSUE TITLE
Sacrificing Treacherous Blessing to Final Payment

### ISSUE THREAD

**Issue by DominusMaximus** [magefree/mage#6408] opened 2020-04-12 17:10 UTC
1.4.42.dev_2020-03-19_15-37

Treacherous Blessing's life loss trigger is incorrectly triggering when it is sacrificed to Final Payment's additional cost. Final Payment doesn't enter the stack until all costs have been paid, which means Treacherous Blessing is no longer on the battlefield by the time this occurs.

**Comment by Zerrisx** [comment] 2020-07-15 19:50
Duplicate of #6283

**Closed by Zerrisx** 2020-07-15 19:50 UTC
