### ISSUE TITLE
Marisi, Breaker of the Coil null error

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9161] opened 2022-06-26 19:20 UTC
When I hit the AI with [[Marisi, Breaker of the Coil]] this happens

Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.51-V4-beta6 (build: 2022-06-24 13:26)
mage.game.GameImpl.playPriority(GameImpl.java:1574)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment] 2022-06-27 15:33
What was on the battlefield when this happened?  It works in generic testing.

**Comment by catman123456** [comment] 2022-06-28 03:09
Before i could get a screen shot it booted me out

**Comment by catman123456** [comment] 2022-06-28 06:45
It seems that [[Kenrith, the Returned King]] is causing this to happen.

![image](https://user-images.githubusercontent.com/64045003/176111327-c8320729-a4f8-4ae9-b4a2-d0582d873e5d.png)

**Comment by catman123456** [comment] 2022-06-28 07:02
Now i got a error and a game lost

![image](https://user-images.githubusercontent.com/64045003/176114589-394f92da-5fd5-4fbb-a481-b2895cbb6655.png)

Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.51-V4-beta6 (build: 2022-06-24 13:26)
mage.game.GameImpl.playPriority(GameImpl.java:1574)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by jeffwadsworth** [comment] 2022-06-28 13:37
Ok, bug recreated.  As you pointed out, if the player that has their creatures goaded dies/leaves the game before the goaded creature(s) attack, the NPE occurs.

**Comment by rockydirtbag** [comment] 2022-06-28 13:41
I've noticed this issue as well, and I think the cause is in the GoadTargetEffect class. I've tweaked it as follows, and now the bug doesn't seem to show up anymore:

`

> public boolean apply(Game game, Ability source) {
>         for (UUID targetId : getTargetPointer().getTargets(game, source)) {
>             Permanent targetCreature = game.getPermanent(targetId);
> -->         if (targetCreature!=null && source!=null) {
>                 targetCreature.addGoadingPlayer(source.getControllerId());
>             }
>         }
>         return true;
>     }

`

I'm new to the project, so I'm not sure how I can post my fix, but maybe someone with experience can help out?

**Comment by Alex-Vasile** [comment] 2022-06-28 13:50
> I've noticed this issue as well, and I think the cause is in the GoadTargetEffect class. I've tweaked it as follows, and now the bug doesn't seem to show up anymore:
> 
> ```java
> public boolean apply(Game game, Ability source) {
>          for (UUID targetId : getTargetPointer().getTargets(game, source)) {
>              Permanent targetCreature = game.getPermanent(targetId);
>              if (targetCreature!=null && source!=null) { // This is the change
>                  targetCreature.addGoadingPlayer(source.getControllerId());
>              }
>          }
>          return true;
>      }
> ```
> 
> I'm new to the project, so I'm not sure how I can post my fix, but maybe someone with experience can help out?

Thank you for the contribution.

I've formatted your answer a bit to make it easier to read. You can use triple backslashes "```" instead of a single one to slow a block of formatted code, and you can do "```Java" at the beginning to show the code highlighting.

@jeffwadsworth assigned themselves this one already so I think they will address the issue.

But for future contributions:
1. Fork on GitHub
2. Download clone with GitHub into pycharm (or your idea of choice)
3. Make a new branch
4. Make you changes, make sure tests run, commit, and push.
5. Then open a PR and reference the GitHub issue (e.g. this issue is 9161) that you're fixing (or describe the change if an issue is not already opened).

If there are any issues you wish to work on, comment on them saying that you would like to be assigned to it, and someone will assign the issue to you so that everyone else knows what you're working on.

**Closed** 2022-06-28 15:26 UTC
Labels: bug
