### ISSUE TITLE
Possibility to choose an X value

### ISSUE THREAD

**Issue by dlucca1986** [magefree/mage#9257] opened 2022-07-12 08:51 UTC
Dear all,
it would be very useful to have the option to choose an X value in case of endless combos.
For example - Chain of Smog + Sedgemoore Witch ( endless Tokens ).
There would be a huge time saver when the opponent doesn't concede.
Best regards.

**Comment by Alex-Vasile** [comment] 2022-09-22 04:34
Duplicate of #2147

**Closed** 2022-09-22 04:34 UTC
Labels: enhancement
