### ISSUE TITLE
Mana Web doesn't tap City of Brass

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#4746] opened 2018-04-12 11:18 UTC
Opponent had City of Brass out with Underground Sea and Plateau.  When they tapped Plateau, City of Brass wasn't tapping.

**Comment by rystan** [comment] 2018-04-14 05:30
It seems like a possible fix for this particular issue might be to move the following line of code:
        this.netMana.add(Mana.ColorlessMana(1));
From: ColorlessManaAbility.java line 41 into the constructor for BasicManaAbility.java after line 42.

This would cause all colored sources to also add ColorlessMana type to the netMana array in addition to their normal color so that the netMana array should then include Red, White & Colorless in the list of types tapped by Mana Web, which should then pick up the City of Brass.

Not sure what other effect that change might have though.

**Comment by Zerrisx** [comment] 2020-07-07 20:29
Cannot reproduce; this appears to be fixed.

**Closed by Zerrisx** 2020-07-07 20:29 UTC
Labels: bug, cards
