### ISSUE TITLE
Paladin Class Level 3 Not Giving Doublestrike on solo attack

### ISSUE THREAD

**Issue by peter-thoenen** [magefree/mage#8453] opened 2021-11-13 08:22 UTC
Title sums it up, the gatherer explicitly say it still gets (just not the +1/+1 bonus):

https://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=527316

**Comment by awjackson** [comment] 2021-11-13 10:35
I strongly suspect this is yet another duplicate of #8228

**Closed** 2021-11-21 06:59 UTC
