### ISSUE TITLE
Ward Sliver Not Granting Protection to Changeling

### ISSUE THREAD

**Issue by Aeronomotron** [magefree/mage#9418] opened 2022-08-26 18:48 UTC
On the us.xmage.today server, client and server build 2021-09-05, Ward Sliver was in play naming white. The same player that controlled ward sliver also had a Morophon, the Boundless in play. As a changeling, Morophon should have protection from white. Morophon then got exiled with the white spell; Path to Exile.

**Comment by Alex-Vasile** [comment] 2022-08-26 19:10
> us.xmage.today server, client and server build 2021-09-05
The client and server build is for the stable release, but that address is for the beta server (2022-08-13).
Can you please verify if you are using the beta release or the stable release?

(I recommend you not use the stable release as its extremely old and switch to the beta).

**Comment by Aeronomotron** [comment] 2022-08-26 19:24
I am on the stable release.
I believe that the beta server is beta.xmage.today, not us.xmage.today.

I have had a few problems on the beta server that has made me hesitate to migrate there. The first one is the known issue with Astral Cornucopia, as it is working as intended on the stable release, but not working correctly on the Beta server. The modern deck I am testing plays this card, which means whenever I want to test that deck, I would have to close the beta client and load up the stable one. The second is a re-emergence of a visual issue that I encountered back in 2021, and is present on the beta server, but not the stable one. This visual glitch makes the game nearly unplayable, as you oftentimes can't see the stack, board state, or hand clearly. A visual example is attached. 
![image](https://user-images.githubusercontent.com/30334866/186976410-1b29a7fd-69aa-4275-b33e-92560d68ae97.png)

**Comment by Alex-Vasile** [comment] 2022-08-26 20:02
My bad, misread that.

1. Astral cornucopia was recently fixed in dca1b5e110aadead6b668293449481d0222dd9f3, so that fix will go out with the next beta update.
2. I will look into the Morophon issue and see if its still a problem in the beta or if it's already been fixed.
3. The GUI glitch i've seen issues opened on here with similar bugs before. I am having troubling finding them, but I know i've seen reports of this. Unfortunately, I don't know what the cause is (or if it was ever identified) or what the solution is.

**Closed** 2022-08-27 00:19 UTC

**Comment by Aeronomotron** [comment] 2022-08-27 02:00
Ok!
Yea, the visual glitch was never really solved back in 2021. I tried updating to a different version of java, increasing the ram allocation, and a few other technical things that I wasn't knowledgeable enough to know their purpose.  One of the updates seemed to fix it, for whatever reason. 
Thanks for all you do!

**Comment by Alex-Vasile** [comment] 2022-08-27 02:14
> Ok!
> 
> Yea, the visual glitch was never really solved back in 2021. I tried updating to a different version of java, increasing the ram allocation, and a few other technical things that I wasn't knowledgeable enough to know their purpose.  One of the updates seemed to fix it, for whatever reason. 
> 
> Thanks for all you do!

You don't happen to remember which update it was?

I've never experience this issue myself, so idk how to start on fixing it

**Comment by Alex-Vasile** [comment] 2022-09-01 14:12
@Aeronomotron, how much ram are you running the client with? Does adding more ram help?

**Comment by Aeronomotron** [comment] 2022-09-01 14:28
I don't remember what update it was. If you search my username in the discord channel #bugreports, you can see a troubleshooting session I had with JayDi back in 8/2021, which also involved another, now resolved, issue. In order to try to solve the issue, I updated to the most recent version of Java 8, and allocated an additional 1GB of RAM to the client while running on the beta server, for a total of 2 GB. After that change, I have never seen it breach 60% ram usage. I tried to dig around in the log files to see if I could find anything suggesting an error, but I found nothing. I started a game on the Beta server, now with the fixed Astral Cornucopia (thanks btw :)), and about half way through the game, that tearing issue started up again.

**Comment by Alex-Vasile** [comment] 2022-09-01 18:40
> I don't remember what update it was. If you search my username in the discord channel #bugreports, you can see a troubleshooting session I had with JayDi back in 8/2021, which also involved another, now resolved, issue. In order to try to solve the issue, I updated to the most recent version of Java 8, and allocated an additional 1GB of RAM to the client while running on the beta server, for a total of 2 GB. After that change, I have never seen it breach 60% ram usage. I tried to dig around in the log files to see if I could find anything suggesting an error, but I found nothing. I started a game on the Beta server, now with the fixed Astral Cornucopia (thanks btw :)), and about half way through the game, that tearing issue started up again.

Hmm. Do you run through the launcher? If so, try running the client directly (with one of the start scripts in the client folder) and see if a newer version of Java works better.

What OS are you using?

**Comment by Aeronomotron** [comment] 2022-09-01 20:48
Ok, I will give it a shot when I have the chance.

**Comment by Aeronomotron** [comment] 2022-09-02 02:45
I have been playing for about an hour, and it seems to be running fine now! I updated my GPU drivers like you recommended, and started the client using the script rather than just running the jar file. I also added the -Dsun.java2d.d3d=false to the client command line. I don't know which of those three things actually resolved it, but I am glad it did.

**Comment by Alex-Vasile** [comment] 2022-09-02 02:49
> I have been playing for about an hour, and it seems to be running fine now! I updated my GPU drivers like you recommended, and started the client using the script rather than just running the jar file. I also added the -Dsun.java2d.d3d=false to the client command line. I don't know which of those three things actually resolved it, but I am glad it did. 

I'm guessing it's the Java. If your client settings in the launcher have the same flag, then you can figure it out by booting through the launcher and playing for a bit.
