### ISSUE TITLE
Verdurous Gearhulk text bug

### ISSUE THREAD

**Issue by PurpleCrowbar** [magefree/mage#8791] opened 2022-03-27 03:19 UTC
When [[Verdurous Gearhulk]]'s triggered ability activates, the following message displays when choosing creatures to distribute +1/+1 counters to:
![image](https://user-images.githubusercontent.com/26198472/160265178-f3418646-3133-4ade-a215-4dc8ae78d765.png)

**Comment by awjackson** [comment] 2022-03-27 03:43
Duplicate of #8069

**Closed by awjackson** 2022-03-27 03:43 UTC
