### ISSUE TITLE
Offerings not working correctly for Patron commanders

### ISSUE THREAD

**Issue by squito7** [magefree/mage#6940] opened 2020-08-04 16:56 UTC
The offering commanders like Patron of the Orochi don't allow you to cast them from the command zone unless you have mana  available for their casting cost at minimum.
This is a bug, since you have to wait until you have 8 mana available to cast the patron from the command zone even though you should be able to cast him with his offering ability for much cheaper.

**Comment by Zerrisx** [comment] 2020-08-04 17:28
Duplicate of #6698

**Comment by Zerrisx** [comment] 2020-08-12 16:10
Fixed by 3e498e2

**Closed by Zerrisx** 2020-08-12 16:10 UTC
Labels: bug
