### ISSUE TITLE
Trigger ability stack blocked

### ISSUE THREAD

**Issue by dosfod** [magefree/mage#7638] opened 2021-03-01 18:07 UTC
Hey, 

As shown in the screenshot, the triggered ability stack was blocked when I attacked with [[Uro, Titan of Nature's Wrath]] and a couple of [[Elder Gargaroth]]

![image](https://user-images.githubusercontent.com/29545637/109538942-f3f28980-7ac0-11eb-9fd4-1bddd0c3c693.png)

It happened again with Uro and a single Gargaroth, so I guess that the issue is related with one of the cards. When it happens, I can click on the abilities of the Gargaroth but nothing happens. The triggered stack stays there and it just blocks the game, I can't click on the phases buttons or anything else...

Let me know if you need more info.

Kind regards.

**Comment by weirddan455** [comment] 2021-03-02 20:54
I was able to reproduce this.  The dialog that asks you to order the triggered ability takes focus and doesn't allow mouse clicks in the main UI window until it goes away (which it doesn't seem to do until all the triggers go on the stack.)  The bug happens when one of the abilities is modal (like Elder Gargaroth) because you need to choose a mode before it will go on the stack.

You can work around the bug by using the keyboard (press 1, 2, or 3 to choose a mode.)

**Comment by dosfod** [comment] 2021-03-02 21:55
Thanks for the reply! I'll try the workaround while the bug isn't fixed :)

**Comment by JayDi85** [comment] 2021-09-21 10:19
Fixed in 46081d9185c489eddea1ca78ef4851585e76ae9c

**Closed by JayDi85** 2021-09-21 10:19 UTC
Labels: bug, GUI
