### ISSUE TITLE
Condemn targeting a token causes error

### ISSUE THREAD

**Issue by DavidRagone** [magefree/mage#742] opened 2015-02-21 03:38 UTC
Condemn targeting a Sorin, Solemn Visitor token. Sorin +'d, then I tried targeting.
```
Game exception occurred: java.lang.NullPointerException
Server version: 1.3.0dev2015-02-07v6
mage.players.PlayerImpl.putCardsOnBottomOfLibrary(PlayerImpl.java:843)
mage.abilities.effects.common.PutOnLibraryTargetEffect.apply(PutOnLibraryTargetEffect.java:135)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:182)
mage.game.stack.Spell.resolve(Spell.java:198)
mage.game.GameImpl.resolve(GameImpl.java:1195)
mage.game.GameImpl.playPriority(GameImpl.java:1157)
mage.game.turn.Step.priority(Step.java:87)
mage.game.turn.Phase.playStep(Phase.java:203)
mage.game.turn.Phase.play(Phase.java:115)
mage.game.turn.Turn.play(Turn.java:140)
mage.game.GameImpl.playTurn(GameImpl.java:734)
mage.game.GameImpl.play(GameImpl.java:659)
mage.game.GameImpl.start(GameImpl.java:626)
mage.game.GameImpl.start(GameImpl.java:611)
mage.server.game.GameWorker.call(GameWorker.java:60)
java.util.concurrent.FutureTask.run(FutureTask.java:262)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java.lang.Thread.run(Thread.java:745)
```

**Comment by mnapoleon** [comment] 2015-03-06 17:59
I don't know much about the way this stuff is handled yet but I don't think that tokens should be moved to the bottom of the library.  They should just be destroyed.  
Technically the token is an 'attacking creature' so the Condemn can target it but I don't think the rest of the the rule applies.  I think if the target creature is a token it should just be destroyed.
So I guess that PutOnLibraryTargetEffect needs to determine if the target is a token and if it is just exile it.  (or whatever the equivalent action is on  token)

**Comment by emerald000** [comment] 2015-03-06 18:15
Tokens are actually moved to other zones before disappearing. Relevant rule:

704.5d If a token is phased out, or is in a zone other than the battlefield, it ceases to exist.

**Comment by mnapoleon** [comment] 2015-03-06 18:23
Ok that is probably handled correctly then since I imagine it is a common case.

**Comment by DavidRagone** [comment] 2015-03-07 00:31
Awesome. Thanks, @mnapoleon!

**Comment by drmDev** [comment] 2016-07-25 11:33
Sounds like this issue is resolved? @LevelX2 commit referenced above

**Comment by drmDev** [comment] 2016-07-29 08:12
confirmed resolved - closing

**Closed by drmDev** 2016-07-29 08:12 UTC
Labels: bug, Not confirmed
