### ISSUE TITLE
Ranar doesn't trigger when I exile permanents I don't control

### ISSUE THREAD

**Issue by johnmeat** [magefree/mage#7572] opened 2021-02-14 13:42 UTC
Using Curse of the Swine to exile an AI Bear:
![image](https://user-images.githubusercontent.com/64497504/107878349-e090cd00-6ec9-11eb-817d-cad0acb1144a.png)
![image](https://user-images.githubusercontent.com/64497504/107878374-23eb3b80-6eca-11eb-8867-2125f505c979.png)

The same is true for swords to plowshares:
![image](https://user-images.githubusercontent.com/64497504/107878386-3c5b5600-6eca-11eb-9ff5-566ad430d921.png)

![image](https://user-images.githubusercontent.com/64497504/107878400-539a4380-6eca-11eb-8928-caeb79b674f3.png)

gatherer entry:
![image](https://user-images.githubusercontent.com/64497504/107878411-61e85f80-6eca-11eb-9646-73c8a5b586c1.png)

**Comment by jeffwadsworth** [comment] 2021-02-14 16:40
Zone_Change_Group does not currently store the "source" ability/spell.

**Comment by Zechr** [comment] 2021-02-15 03:01
Addendum to this, Ranar also does trigger if a source an opponent controls exiles Ranar. An opponent's Astral Slide exiling Ranar created a spirit token.

**Comment by theelk801** [comment] 2021-02-19 15:11
This requires a large refactor, right now zone changes don't take into account which player is doing the zone change and many cards don't have it programmed in.

**Comment by JayDi85** [comment] 2021-02-19 15:25
@theelk801 can you show the example? `ZoneChangeGroupEvent` and `ZoneChangeEvent` -- all have `playerId`.

**Comment by theelk801** [comment] 2021-02-19 15:27
Sorry, I should rephrase. The events have `playerId` but the implementations don't take it into account correctly.

**Comment by JayDi85** [comment] 2021-02-19 15:39
Hmm, I see... `playerId` is a controller of the object, not controller of the source:
![shot_210219_193155](https://user-images.githubusercontent.com/8344157/108525080-2940ef80-72e9-11eb-8a5b-e0c7798612b8.png)

As @jeffwadsworth tell -- I think it can be fixed by `sourceId` in group event:
![shot_210219_193538](https://user-images.githubusercontent.com/8344157/108525646-c2700600-72e9-11eb-9c72-6fdc2d76f18d.png)

So you will have access to source id -> source object -> controller (`sourceId` is empty for state base actions, but non empty for other use cases e.g. player interactions or triggers).

**Comment by theelk801** [comment] 2021-02-19 15:42
But even more than that, a lot of cards aren't implemented with the correct player calling the `moveCards` method because it's never mattered before, like with [[Vorinclex, Monstrous Raider]] and counters. This is something I can do but it's big refactor and it'll take some time.

**Comment by JayDi85** [comment] 2021-02-19 16:36
Missing of `source` information and wrong command usage are different problems. Missing `source` was fixed last December in #7242 for most use cases.

I think you are talking about use cases like "target opponent exile card" (example: [[Chaos Wand]]):
```
opponent.moveCards(card, Zone.EXILED, source, game);
```
Inner code contains:
```
card.moveToExile(exileId, exileName, source, game))
```
The player information is lost after that. So that methods calls like `card.moveToExile` must be fixed to store player info (~110 places for exile moves).

**Comment by theelk801** [comment] 2021-02-19 17:16
There are also instances like `AshiokNightmareMuseToken` where a single player calls the exile method for all the cards even though each card is moved by its owner (which can be fixed with the `byOwner` argument) but the point is that there's a lot of refactoring needed.

**Comment by theelk801** [comment] 2021-02-19 17:18
Also, it's a separate issue but worth mentioning here that we should probably have a way to sacrifice/destroy permanents as a group to avoid concurrent issues like regenerate and totem armor

**Comment by jeffwadsworth** [comment] 2021-02-19 23:40
I will start going through the card base to fix the "card.move..." code bits; unless someone else is currently doing that.  I will start in the Z cards and move up.  I think it is okay to mention this here because it is somewhat related to this issue.

**Comment by jeffwadsworth** [comment] 2021-07-02 20:08
Getting back to this.

**Comment by Zechr** [comment] 2021-07-02 20:32
It's worth noting that Ranar has been errata'd. It now says if a spell or ability you control exiles a permanent or if a card is put into exile from your hand, create a spirit token. So now it shouldn't work with stuff like sac outlets and Rest in Peace.

**Comment by theelk801** [comment] 2021-07-02 20:33
yeah I already applied the errata to Ranar

**Comment by jeffwadsworth** [comment] 2021-07-07 16:25
Hmm.  Curse of the Swine works fine if you target only your creatures OR only another player's creatures.  Otherwise, separate events are created and added to the event list that triggers "ZoneChangeGroup" multiple times instead of just once.  All other cards that check for this type of trigger do so for only one player's cards (one or more cards from your graveyard, etc).  This seems to be a quirk of actually selecting targets and not using a filter like "Wrath of God".  Does anyone know why this is implemented this way?

**Comment by jeffwadsworth** [comment] 2021-07-07 22:14
Currently, if a group of cards are exiled from the battlefield, and they were controlled by 2 or more different players, multiple "ZoneChangeGroup" events take place.  It a group of cards are exiled from just one player's battlefield, just one "ZoneChangeGroup" event takes place.  I am looking for the root cause of this issue because it is supposed to fire just once per event.  This is incorrect behavior.

**Comment by jeffwadsworth** [comment] 2021-07-07 22:17
> 
> 
> It's worth noting that Ranar has been errata'd. It now says if a spell or ability you control exiles a permanent or if a card is put into exile from your hand, create a spirit token. So now it shouldn't work with stuff like sac outlets and Rest in Peace.

It seems to me it should work with RIP.  The replacement effect is part of the ability you control and exiles the card instead of it going to the graveyard.  Of course, their is a hefty number of debates on this very issue on Reddit.  For example, when used with Altar of Dementia.

**Comment by jeffwadsworth** [comment] 2021-07-12 20:00
On a side note, Curse of the Swine does not give a 2/2 Boar token if a permanent creature token is "exiled".  It should.  Fixing that as well.

**Closed** 2021-07-14 21:44 UTC
Labels: bug

**Comment by JayDi85** [comment] 2021-07-14 22:49
For ffe75f77edc86a5b6d8864ba34e8ea5dda8027c0:

1. Direct compare of `source` object (ability) is potentially buggy -- it's a java object and it copies all the time in game engine (same ability from the source object can have multiple instances like copy before activate and multiple permanents can have single ability object like singletons). That's why a `sourceId` must help here (to group events by source);
2. [[Hero of Bretagard]] -- it need group events by player, so new code (without events grouping by `playerId`) will not work with it.

P.S. Maybe there are another unsupported cards now (need to reseach all ZONE_CHANGE_GROUP usage). I think group event must be reworked to fix duplicated events. Possible solution:
- keep only to/from zones, cards/tokens lists (group by zones only -- but it can be bugged too if some cards looking for multiple zones);
- add original event info. So some cards can cycle and find player or another useful info. Example: `Map<Card, GameEvent> cards`

**Comment by JayDi85** [comment] 2021-07-14 22:55
It's a strange... As I can see -- group event introduced long ago for triggers like `whenever one or more cards` (e.g. you must catch only one event at the end). So I don't know why xmage splitting that events by zones/source/players (`ZoneChangeData`), e.g. creating multiple group events.

**Comment by jeffwadsworth** [comment] 2021-07-14 23:55
Now it groups the events by source ability.  The Hero has the same wording as Ranar.  How is it dependent on grouping the events by player?  I will change its code to match Ranar shortly.

**Comment by jeffwadsworth** [comment] 2021-07-14 23:58
As for multiple triggers/events, you just code the card for that instance and don’t use the group event.  Now, the group event takes into account the permanents and the tokens which were neglected before.

**Comment by JayDi85** [comment] 2021-07-27 10:26
@jeffwadsworth related bug report with [[Laelia, the Blade Reforged]] from discord -- it can triggers for both players somehow.

**Comment by jeffwadsworth** [comment] 2021-07-27 15:03
I will check the card out.

**Comment by jeffwadsworth** [comment] 2021-07-27 15:26
Yeah, the card code used the old method.  Fix incoming.

**Comment by JoeyVers** [comment] 2021-08-11 14:28
> > It's worth noting that Ranar has been errata'd. It now says if a spell or ability you control exiles a permanent or if a card is put into exile from your hand, create a spirit token. So now it shouldn't work with stuff like sac outlets and Rest in Peace.
> 
> It seems to me it should work with RIP. The replacement effect is part of the ability you control and exiles the card instead of it going to the graveyard. Of course, there is a hefty number of debates on this very issue on Reddit. For example, when used with Altar of Dementia.

Hi, is there any chance that the Ranar + RIP combo is going to be fixed in Xmage?

**Comment by JoeyVers** [comment] 2021-08-11 14:52
Below are the latest rulings on Ranar. So the first item says that if I control the ability (I would say that is the triggered ability of my RIP), it should trigger.

![image](https://user-images.githubusercontent.com/14837339/129051763-3108f7c8-605d-4b5e-a44c-e3c0e055c1cb.png)

**Comment by jeffwadsworth** [comment] 2021-08-11 14:55
That would be my interpretation as well.  Anyone else object?  As noted above; the discussions on this are pretty heated.

**Comment by jeffwadsworth** [comment] 2021-08-11 15:44
So, if it dies to SBAs and then gets exiled due to RIP, it doesn't trigger Ranar because it wasn't a spell or ability you control (replacement effects have no controller):
the only abilities that the comprehensive rules spoke of as having a controller were activated and triggered abilities on the stack (C.R. 113.8; see also C.R. 109.4), not static abilities such as foretell or Rest in Peace's second ability (C.R. 113.3d; compare C.R. 113.1c with C.R. 113.1).

**Comment by jeffwadsworth** [comment] 2021-08-11 16:22
I know the Foretell static ability causes it to trigger so I will fix that and anything else that doesn't fall under the "activated and triggered" ability scope.

**Comment by JoeyVers** [comment] 2021-08-11 16:25
Okay so I think someone on reddit posted a message 5 days ago with a clear explenation and I think he is right, see [here](https://www.reddit.com/r/mtgrules/comments/msspg7/ranar_the_everwatchfull/h7woc2e?utm_source=share&utm_medium=web2x&context=3). So in short: Ranar won't trigger when a creature is destroyed as an SBA due to lethal damage (C.R. 704.5g) and RIP is on the battlefield. Ranar will trigger when a permanent is destroyed or sacrificed when a ability you control resolves and RIP is on the battlefield.

It doesn't matter who is controlling RIP in this case because it is a replacement effect as we already cleared out.

This is a part of the guys post:
Under the current Oracle text, Ranar's triggered ability generally will trigger if you control Ranar and

- you would discard one or more cards by any means (including by a spell or ability you don't control), but those cards are exiled instead of going to the graveyard (e.g., because someone controls Rest in Peace).
- one or more cards are exiled from your hand by any means (including by a spell or ability you don't control such as Kitesail Freebooter's enters-the-battlefield ability).
- one or more permanents (even permanents you don't control) would be destroyed or sacrificed while a spell or ability you control is resolving, but those permanents are exiled instead of going to the graveyard (e.g., because someone controls Rest in Peace).
- one or more permanents (even permanents you don't control) are exiled while a spell or ability you control (such as [[Swords to Plowshares]] or [[Path to Exile]]) is resolving.

On the other hand, Ranar's triggered ability generally won't trigger if you control Ranar and a permanent is exiled
- while a spell or ability you don't control is resolving, or
- during a state-based action, or
- (in accordance with a statement by the rules manager) while you're paying the cost of a spell or ability,

even if you controlled that permanent and even if the permanent is exiled rather than going to a graveyard.

**Comment by JoeyVers** [comment] 2021-08-11 16:27
> I know the Foretell static ability causes it to trigger so I will fix that and anything else that doesn't fall under the "activated and triggered" ability scope.

See my last post. It is correct that Ranar triggers on foretelling a card. And that was also already confirmed by Jess Dunks, see his reaction to a tweet [here](https://twitter.com/Dunkatog/status/1385370021317156869?s=20).

**Comment by JoeyVers** [comment] 2021-08-29 09:25
Okay to bring this toppic up again (I'm sorry) I saw a tweet of Jess Dunks again where he clearly states that if I control RiP and Ranar, I will make tokens out of every dieing creature because it's my replacement effect that is exiling them. See [this](https://twitter.com/Dunkatog/status/1375227428704972809) tweet.
