### ISSUE TITLE
Can't prowl without mana for normal casting 

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#11891] opened 2024-03-02 23:47 UTC
![032 can't prowl wiout mana for normal cast](https://github.com/magefree/mage/assets/4504719/7a7cdb33-8157-4810-b020-4c1f5dd89693)

With a [[Hunting Velociraptor]] I give prowl to my dinosaurs, but can't use it unless I have mana to cast it normally

**Comment by xenohedron** [comment] 2024-03-03 01:02
duplicate of #11714

**Closed by xenohedron** 2024-03-03 01:02 UTC
