### ISSUE TITLE
Animate Dead Triggers

### ISSUE THREAD

**Issue by rexelallan** [magefree/mage#9572] opened 2022-09-25 21:06 UTC
Just checking if this is correct.

Upon blinking by aminatou, the animate dead will have 2 triggers on the stack shown by xmage.

* I resolve the ETB trigger 1st, therefore, targeting a new creature in graveyard.

* when I resolve the "when animate dead leaves, sac enchanted creature", the original creature is no longer enchanted right? because it is enchanting a new one.

Therefore, the original creature  will not be sacrificed anymore, sicne xmage treated the New animate Dead as new Object and the Old One fizzles in resolution.

I would just like to confirm if this is a legal play or not xmage bug?

Sorry but I don't have screenshot since the guy ragequit.

**Comment by awjackson** [comment] 2022-09-26 00:23
Sorry, but the interaction you're describing is indeed an xmage bug. The wording of Animate Dead in xmage does not match its Oracle wording.

In xmage, Animate Dead (and the very similar cards Dance of the Dead and Necromancy) have as a separate ability "When {this} leaves the battlefield, *enchanted creature's* controller sacrifices it". According to these cards' Oracle text, however, the sacrifice is not a separate ability but part of the wall-of-text ability that reanimates the creature, and it is worded "When {this} leaves the battlefield, *that creature's* controller sacrifices it". In other words it should be a delayed triggered ability created by the reanimation ability, and its target should be locked-in as the creature returned to the battlefield by the previous effects of that ability.

I did a bit of research and Animate Dead's current Oracle wording (other than terminology changes, like "in play -> on the battlefield") seems to date back to 2007, which is longer than xmage has been in development, or at least in public development on github.

**Comment by awjackson** [comment] 2022-09-26 00:40
Duplicate of #5250

**Closed** 2022-09-26 00:45 UTC
Labels: bug, duplicate, cards
