### ISSUE TITLE
Mana Vault doesn't untap, eats mana

### ISSUE THREAD

**Issue by ogier** [magefree/mage#750] opened 2015-02-25 02:33 UTC
Hi, I had trouble with the card Mana Vault. Its upkeep trigger happened, and I couldn't choose "Yes" and pay 4. Here's exactly what happened:

1. The upkeep trigger asked if I wanted to pay 4 to untap vault. I chose "Yes".
2. A prompt "Pay {4}" appeared with a "Cancel" button underneath (the mana symbol for 4 actually).
3. I tapped a signet. Prompt changed to "Pay {1}". I tapped another signet and prompt was still "Pay {1}". I tapped a land. No mana was in my pool and the prompt went back to "Pay {4}".
4. I tapped a land. No mana was in my pool and the prompt remained "Pay {4}".
5. I clicked the "Cancel" button and the trigger was finished with Mana Vault tapped, and no lands or signets were untapped (refunded) as they would be if I were casting a card.

Version:
```
XMage Launcher version installed:  0.3.1
XMage Launcher version available:  0.3.1
Java version installed:  1.7.0_71
Java version available:  1.7.0_71
XMage version installed:  1.3.0.dev2015-02-07v6 (2015-02-14)
XMage version available:  1.3.0.dev2015-02-07v6 (2015-02-14)
```

**Comment by LevelX2** [comment] 2015-02-26 11:19
This is no problem with Mana Vault. The problem is that in some constellations the mana cost to pay that's left is not updated to the prompt (#185).
You tap the first signet, you get the prompt to pay the {1} to activate the signet.
You tap the second signet, you get the prompt to pay the {1} to activate the second signet.
You tap a land. The man gets payed but you're still short for one mana. Because of bug #185 you get prompted again with the {4}. If you now pay the missing mana all works correctly.

It's not nice and not user friendly but no problem of Mana Vault, so I close this issue.

**Closed by LevelX2** 2015-02-26 11:19 UTC
