### ISSUE TITLE
Auras created by Orvar always etb then go to GY

### ISSUE THREAD

**Issue by ETALOS1** [magefree/mage#7536] opened 2021-02-09 21:37 UTC
When a token copy of an Aura is created by Orvar's triggered ability, players should be able to choose legal targets for the copies and then those Auras should enchant those targets.

Currently, however, the Auras simply enter the battlefield and then go immediately to the graveyard. No choice is even given to choose a target for the newly-created Auras.

**Comment by Zerrisx** [comment] 2021-02-09 22:03
Likely another duplicate of #6798

**Comment by jeffwadsworth** [comment] 2021-02-09 23:37
It is, I didn't notice the other bug.  I will check it out in the morning.  It is most probably related to using token.put.... vs controller.move....

**Closed** 2021-02-11 16:00 UTC
Labels: duplicate
