### ISSUE TITLE
AI should not buff opponent's creatures

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#5705] opened 2019-04-10 22:42 UTC
Cards like Aquastrand Spider can target opponent's cards with Graft. The AI shouldn't do that.

Update: This can probably be expanded to the AI should avoid giving opponent's creatures +#/+# if possible.

**Comment by Zerrisx** [comment] 2020-07-14 16:12
Duplicate of #6838

**Closed by Zerrisx** 2020-07-14 16:12 UTC
Labels: AI
