### ISSUE TITLE
New Blood does not change the creature type in the text.

### ISSUE THREAD

**Issue by Tharkon** [magefree/mage#13117] opened 2024-12-07 00:03 UTC
I played a [New Blood] targeting [Ocelot Pride], changing Cat to Vampire, then gained some life but at the end of turn Cat tokens were created instead of Vampire tokens.

I tried the same test on several other creatures:
[Elvish Archers] changing Elf to Vampire.
[Mikaeus, the Unhallowed] changing Human to Vampire.
[Urza, Prince of Kroog] changing Soldier to Vampire.
[Merfolk Sovereign] changing Merfolk to Vampire.
[Kudo, King Among Bears] changing Bear to Vampire.

None of these had the expected effect, Elvish Archer tapped for {0}, Mikaeus buffed all the Vampires, Urza created soldier tokens, Merfolk Sovereign was unable to target Vampires and Kudo was the only non-Bear.

**Comment by PurpleCrowbar** [comment] 2024-12-07 00:10
Duplicate of #2082

**Comment by PurpleCrowbar** [comment] 2024-12-07 00:11
See also #4331

**Closed by PurpleCrowbar** 2024-12-07 00:10 UTC
