### ISSUE TITLE
TempleOfPowerWatcher not found in watchers

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#11365] opened 2023-10-29 22:50 UTC
```
ERROR 2023-10-29 18:40:04,740 TempleOfPowerWatcher not found in watchers                                                 =>[GAME b7a1069f-cbfa-4474-9ccf-7dec0348bd47] Watchers.get 
java.lang.Throwable
	at mage.watchers.Watchers.get(Watchers.java:51)
	at mage.game.GameState.getWatcher(GameState.java:638)
	at mage.cards.t.TempleOfPowerHint.getText(TempleOfPower.java:93)
	at mage.util.CardUtil.getCardRulesWithAdditionalInfo(CardUtil.java:1200)
	at mage.cards.CardImpl.getRules(CardImpl.java:220)
	at mage.view.CardView.<init>(CardView.java:418)
	at mage.view.CardView.<init>(CardView.java:270)
	at mage.view.CardView.<init>(CardView.java:152)
	at mage.view.CardView.<init>(CardView.java:524)
	at mage.view.CardView.<init>(CardView.java:270)
	at mage.view.CardsView.<init>(CardsView.java:55)
	at mage.server.game.GameSessionPlayer.prepareGameView(GameSessionPlayer.java:214)
	at mage.server.game.GameSessionPlayer.getGameView(GameSessionPlayer.java:200)
	at mage.server.game.GameSessionPlayer.lambda$select$2(GameSessionPlayer.java:67)
	at java.util.Optional.ifPresent(Optional.java:159)
	at mage.server.game.GameSessionPlayer.select(GameSessionPlayer.java:67)
	at mage.server.game.GameController.lambda$select$20(GameController.java:862)
	at mage.server.game.GameController.perform(GameController.java:1001)
	at mage.server.game.GameController.perform(GameController.java:994)
	at mage.server.game.GameController.select(GameController.java:862)
	at mage.server.game.GameController.lambda$init$3aa0d15c$2(GameController.java:199)
	at mage.game.events.EventDispatcher.fireEvent(EventDispatcher.java:28)
	at mage.game.events.PlayerQueryEventSource.select(PlayerQueryEventSource.java:46)
	at mage.game.GameImpl.firePriorityEvent(GameImpl.java:2842)
	at mage.player.human.HumanPlayer.priority(HumanPlayer.java:1207)
	at mage.game.GameImpl.playPriority(GameImpl.java:1633)
	at mage.game.turn.Step.priority(Step.java:66)
	at mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
	at mage.game.turn.Phase.playStep(Phase.java:204)
	at mage.game.turn.Phase.play(Phase.java:90)
	at mage.game.turn.Turn.play(Turn.java:137)
	at mage.game.GameImpl.playTurn(GameImpl.java:1110)
	at mage.game.GameImpl.play(GameImpl.java:1017)
	at mage.game.GameImpl.start(GameImpl.java:993)
	at mage.server.game.GameWorker.call(GameWorker.java:34)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

I notice this in the server console, I have [[Ojer Axonil, Deepest Might]] in my hand...
other than that I didn't notice any problem with that card

version: 1.4.51-dev (2023-10-28 12-59)

**Comment by JayDi85** [comment] 2023-10-29 23:01
Duplicate of #11329

**Closed by JayDi85** 2023-10-29 23:01 UTC
Labels: duplicate
