### ISSUE TITLE
``Mighty Servant of Leuk-o``  draw cards issue

### ISSUE THREAD

**Issue by adoukimskywalk** [magefree/mage#9436] opened 2022-08-28 15:36 UTC
When I crew Mighty Servant of Leuk-o with exactly 2 creature and I deal damage to a players I don't draws any cards. No trigger hapen.

**Comment by Alex-Vasile** [comment] 2022-09-05 00:42
Duplicate of #9324

**Closed by Alex-Vasile** 2022-09-05 00:42 UTC
