### ISSUE TITLE
Card Issue: Undiscovered paradise don't works with Land Tax

### ISSUE THREAD

**Issue by gotoco** [magefree/mage#9537] opened 2022-09-18 05:28 UTC
During playing Xmage I realized the issue with the old-school combo: Undiscovered Paradise and Land Tax.

When both are in-game, and Undiscovered Paradise was tapped for mana, during my turn I should return "Undiscovered Paradise" during my untap, Then Land Tax should trigger during the Upkeep if the condition is satisfied.

Currently Undiscovered Paradise is returned to the hand, and Land Tax still counts it for its trigger.

**Comment by awjackson** [comment] 2022-09-18 07:59
The problem is that Undiscovered Paradise is implemented in xmage as a delayed triggered ability (based on the printed text of the card, which like many pre-6ED cards is significantly different from the Oracle text) This is both incorrect to the Oracle text and *doesn't work* under the rules of Magic (which is exactly why the Oracle text is different) because players never get priority during the untap step and therefore triggered abilities can never be put on the stack then. Undiscovered Paradise's triggered ability is checked in the untap step but it doesn't actually fire until the upkeep step, at the same time Land Tax's trigger fires, so when Land Tax's intervening if clause is checked the land hasn't been returned yet.

I think Undiscovered Paradise needs to be reimplemented using some kind of special snowflake code in `PlayerImpl.untap`.

**Comment by Alex-Vasile** [comment] 2022-09-18 22:48
Duplicate of #5321.

**Closed** 2022-09-18 22:49 UTC
Labels: bug
