### ISSUE TITLE
NPE in table waiting dialog chat id

### ISSUE THREAD

**Issue by Zangster90** [magefree/mage#12750] opened 2024-08-28 21:56 UTC
Error type: General error - NullPointerException
Client version: 1.4.53-V1 (build: 2024-08-16 15:36)

NullPointerException - look at server or client logs for more details

Stack trace:
java.util.Objects.requireNonNull(Objects.java:203)
java.util.Optional.<init>(Optional.java:96)
java.util.Optional.of(Optional.java:108)
mage.remote.SessionImpl.getTableChatId(SessionImpl.java:695)
mage.client.SessionHandler.getTableChatId(SessionHandler.java:180)
mage.client.dialog.TableWaitingDialog.showDialog(TableWaitingDialog.java:125)
mage.client.MageFrame.showTableWaitingDialog(MageFrame.java:876)
mage.client.remote.CallbackClientImpl.joinedTable(CallbackClientImpl.java:603)
mage.client.remote.CallbackClientImpl.lambda$onCallback$2(CallbackClientImpl.java:217)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
and other 13 lines

**Comment by JayDi85** [comment] 2024-09-04 06:54
duplicate of #12761

**Closed** 2024-09-04 06:55 UTC
Labels: bug, client
