### ISSUE TITLE
Dredge Popup Bug

### ISSUE THREAD

**Issue by synergize** [magefree/mage#1156] opened 2015-07-28 11:38 UTC
Graveyard State: Stinkweed Imp, Golgari Thug, and Life from The Loam. Upon upkeep I select to drege Stinkweed. Window goes away and reappears asking to select Life from the loam times two. Upon clicking cancel, okay or auto select the window continuously pops up. Unable to chat or move windows. Had to close out client to fix.

**Comment by LevelX2** [comment] 2015-07-28 11:51
Duplicate of #643

**Closed by LevelX2** 2015-07-28 11:51 UTC
