### ISSUE TITLE
Saheeli's Artistry clone and Subtle Strike  

### ISSUE THREAD

**Issue by dpsk** [magefree/mage#2564] opened 2016-11-05 19:08 UTC
I copied opponents creature with the Artistry, later he tried to put -1/-1 on my clone and +1/+1 counter on his creature with Sublte Strike only to see that both options were applied to his creature.

Creature in that example was Angel of Invention, but i'm not sure it playing any role in that case.

**Comment by LevelX2** [comment] 2016-12-21 14:57
Subtle Strike was fixed with 1.4.15v5 (2016-09-24)

**Comment by Zerrisx** [comment] 2020-06-26 22:38
Cannot reproduce; this appears to be fixed.

**Closed by Zerrisx** 2020-06-26 22:38 UTC
Labels: bug
