### ISSUE TITLE
Visions of Duplicity: Flashback cost not reduced

### ISSUE THREAD

**Issue by rockydirtbag** [magefree/mage#8921] opened 2022-05-07 21:48 UTC
[[Visions of Duplicity]] costs 8UU to cast from a graveyard, even with [[Octavia, Living Thesis]] as Commander.

**Comment by Alex-Vasile** [comment] 2022-05-07 22:20
Duplicate of #8454.

All of the Visions of X cards have this issue.

**Closed** 2022-05-11 14:35 UTC
