### ISSUE TITLE
Clones of animated artifacts handled incorrectly

### ISSUE THREAD

**Issue by Mekkiss** [magefree/mage#2644] opened 2016-11-30 13:09 UTC
Steps to reproduce:

Have Sol Ring on the battlefield
Use Tezzeret, Agent of Bolas to animate Sol Ring
Cast Clone, copying Sol Ring

Expected result: Clone enters the battlefield as an unanimated Sol ring.
Actual behaviour: Clone enters the battlefield as a 0/0 Sol Ring artifact creature that is put into the graveyard as an SBA.

This seems to have only started in 1.4.19V0.

**Comment by JRHerlehy** [comment] 2016-12-04 00:21
I am unable to reproduce this following the scenario you provided. Do you have further documentation of the issue?

**Comment by MTGfan** [comment] 2016-12-06 03:12
I'm also not able to reproduce using the scenario described.

**Comment by goesta** [comment] 2017-02-16 09:18
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.

**Closed by goesta** 2017-02-16 09:18 UTC
Labels: bug, Not confirmed
