### ISSUE TITLE
Magus of the moon causes tap lands to enter tapped

### ISSUE THREAD

**Issue by acabaca24** [magefree/mage#6900] opened 2020-07-27 15:06 UTC
I was playing a simic growth chamber and my opponent had a Magus of the moon on board.
My land didn't trigger(like it's suppose to) but it enter tapped. Mountains aren't supposed to enter tapped.

"**If a nonbasic land has an ability that causes it to enter the battlefield tapped, it will lose that ability before it applies.** The same is also true of any other abilities that modify how a land enters the battlefield or apply “as” a land enters the battlefield, such as the first ability of Cavern of Souls. This is a change from previous rulings."

My source: https://scryfall.com/card/ima/138/magus-of-the-moon

I don't know if this issue exists with the card blood moon too, but the person to fix this bug should test that too if possible.

This caused me to lose the game because I couldn't play my six drop on time :(

**Comment by Zerrisx** [comment] 2020-07-27 16:44
Duplicate of #4202; it's been this way for a while sadly.  These interactions are particularly difficult to fix.

**Comment by acabaca24** [comment] 2020-07-27 18:18
Oh thanks for the quick answer! Hope you guys can figure it out! Should I close the issue?

**Comment by Zerrisx** [comment] 2020-07-27 18:23
I'll close it for ya; just wanted to make sure there wasn't anything additional going on beyond what was already reported.  Thanks for submitting it anyway!

**Closed by Zerrisx** 2020-07-27 18:23 UTC
