### ISSUE TITLE
Sword of Fire and Ice and Memnarch

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#8089] opened 2021-08-01 21:45 UTC
It was reported that Sword of Fire and Ice attached to a creature is not providing correct color protection.  Example given: Memnarch.
[[Sword of Fire and Ice]]
[[Memnarch]]

**Comment by theelk801** [comment] 2021-08-02 01:29
the memnarch was also a commander, this is likely the same as #7987 and #7983

**Comment by Alex-Vasile** [comment] 2022-09-27 18:46
Closing as duplicate of #7983

**Closed by Alex-Vasile** 2022-09-27 18:46 UTC
