### ISSUE TITLE
Bouncing a crewed vehicle does not 'uncrew'

### ISSUE THREAD

**Issue by Roboreaper** [magefree/mage#2761] opened 2017-01-09 12:50 UTC
when bouncing a crewed vehicle to your hand and then recasting that vehicle, it's still a creature

**Comment by goesta** [comment] 2017-02-14 20:38
Added a test which confirms this bug.

**Comment by goesta** [comment] 2017-02-15 22:05
Could we use Ability.reset() for this? And call it on all Abilities in the ReturnToHand effects?

**Comment by ImperatorPrime** [comment] 2017-03-08 08:58
I think you're looking in the wrong place. The issue is that the effect AddCardTypeSourceEffect doesn't care that the card it's following has changed zones.

**Comment by ImperatorPrime** [comment] 2017-03-08 09:00
Fixed by 3bebdd65bc2ae3e6a64afe8ca53223d198fb1eb2.

**Closed by ImperatorPrime** 2017-03-08 09:00 UTC
Labels: bug
