### ISSUE TITLE
Avenging Hunter Autolose Error

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#9031] opened 2022-05-29 21:42 UTC
Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.51-V4-beta4 (build: 2022-05-27 05:58)
mage.game.GameImpl.playPriority(GameImpl.java:1602)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1070)
mage.game.GameImpl.play(GameImpl.java:980)
mage.game.GameImpl.start(GameImpl.java:956)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Alex-Vasile** [comment] 2022-05-29 22:07
Duplicate of #9010

**Closed by Alex-Vasile** 2022-05-29 22:07 UTC
