### ISSUE TITLE
Game Trail not working

### ISSUE THREAD

**Issue by Gottschkopf** [magefree/mage#8182] opened 2021-08-31 09:51 UTC
[Game Trail](https://scryfall.com/card/soi/276/game-trail) asks if you want to reveal a land from your hand, but clicking "Yes" doesn't let you pick a land and it enters tapped.

**Comment by jeffwadsworth** [comment] 2021-08-31 13:21
[[Game Trail]]

**Comment by jeffwadsworth** [comment] 2021-08-31 14:37
This worked fine for me.

**Comment by Gottschkopf** [comment] 2021-08-31 14:57
I could replicate the bug by having no basics in hand, tutoring one (via Cultivate, Renegade Map etc), then playing Game Trail (or any of the cycle (in my case Fortified Village and Game Trail) in the same turn.

**Comment by jeffwadsworth** [comment] 2021-08-31 15:56
It does help when you give a detailed explanation of what you did.  The query to reveal the land comes up, but it does not reveal the land when you use Cultivate before playing it.  If the land(s) are present in your hand beforehand, it does reveal the land correctly.  Checking it out.

**Comment by jeffwadsworth** [comment] 2021-08-31 16:38
The issue is related to this:  #6210
Long forgotten about refactor that I will now do.

**Comment by JayDi85** [comment] 2021-09-02 22:13
Real reason in game simulations: cost pay status shared between games, so AI pay it in simulation, but Game Trail thinks it was pay in real game. Fixed in 421cac0ce3cc03cc755dd341ff50d03e09c6a1f2.

**Closed by JayDi85** 2021-09-02 22:13 UTC
Labels: bug
