### ISSUE TITLE
Weird Replacement Effect (Llanowar Reborn that isn't even in game)

### ISSUE THREAD

**Issue by Blitkun** [magefree/mage#1144] opened 2015-07-24 17:51 UTC
This just happened, I'm pretty sure neither deck runs Llanowar Reborn, though the replacement effect window appeared on my draw step. Had 2 Life from the Loam on the graveyard.

No matter what I click, the window simply refreshes.

GAMELOG:

<html>
  <head>
    
  </head>
  <body>
    <font color="#CCCC33">19:32: </font><font color="#20B2AA">Blitkun</font><font color="Orange"> 
    has joined the game</font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">ramon</font><font color="Orange"> 
    has joined the game</font>
<font color="#CCCC33">: </font><font color="Orange"><br><b>Match score:</b><br></font><font color="#20B2AA">Blitkun</font><font color="Orange"> 
    - 0 wins<br>DeckHash: -2012613941515304885<br></font><font color="#20B2AA">ramon</font><font color="Orange"> 
    - 0 wins<br>DeckHash: 6818414649644248392<br><br>You have to win 2 games 
    to win the complete match<br><br>Game has started<br><br></font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">ramon</font><font color="White"> 
    shuffles his or her library.</font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    shuffles his or her library.</font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">ramon</font><font color="White"> 
    won the toss</font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">ramon</font><font color="White"> 
    chooses that he or she takes the first turn</font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">ramon</font><font color="White"> 
    draws seven cards</font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    draws seven cards</font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">ramon</font><font color="White"> 
    keeps hand</font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    keeps hand</font>
<font color="#CCCC33">19:32: </font><font color="Orange">Turn 1 </font><font color="#20B2AA">ramon</font><font color="Orange"> 
    (20 - 20)</font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">ramon</font><font color="White"> 
    plays </font><font color="#B0C4DE">Urza's Power Plant [938]</font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">ramon</font><font color="White"> 
    casts </font><font color="#B0C4DE">Chromatic Sphere [51b]</font>
<font color="#CCCC33">19:32: </font><font color="#20B2AA">ramon</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">19:32: </font><font color="Orange">Turn 2 </font><font color="#20B2AA">Blitkun</font><font color="Orange"> 
    (20 - 20)</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    plays </font><font color="#B0C4DE">Bloodstained Mire [fa1]</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">19:33: </font><font color="Orange">Turn 3 </font><font color="#20B2AA">ramon</font><font color="Orange"> 
    (20 - 20)</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    plays </font><font color="#B0C4DE">Urza's Mine [6b2]</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    sacrificed </font><font color="#B0C4DE">Chromatic Sphere [51b]</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    casts </font><font color="#90EE90">Ancient Stirrings [b63]</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    moves a card to hand</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    reveals </font><font color="#B0C4DE">Urza's Tower</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    puts a card from library to the bottom of his or her library</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    puts a card from library to the bottom of his or her library</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    puts a card from library to the bottom of his or her library</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    puts a card from library to the bottom of his or her library</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    puts </font><font color="#90EE90">Ancient Stirrings [b63]</font><font color="White"> 
    from stack into his or her graveyard</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    casts </font><font color="#B0C4DE">Chromatic Star [381]</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">ramon</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    loses 1 life</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    sacrificed </font><font color="#B0C4DE">Bloodstained Mire [fa1]</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    activates: search your library for a Swamp or Mountain and put it onto the 
    battlefield. Then shuffle your library. from </font><font color="#B0C4DE">Bloodstained 
    Mire [fa1]</font>
<font color="#CCCC33">19:33: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    searches his or her library</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    puts </font><font color="#B0C4DE">Stomping Ground [1a7]</font><font color="White"> 
    from library onto the Battlefield</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    shuffles his or her library.</font>
<font color="#CCCC33">19:34: </font><font color="Orange">Turn 4 </font><font color="#20B2AA">Blitkun</font><font color="Orange"> 
    (20 - 19)</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    plays </font><font color="#B0C4DE">Mountain [e92]</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    casts </font><font color="#90EE90">Tarmogoyf [417]</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">19:34: </font><font color="Orange">Turn 5 </font><font color="#20B2AA">ramon</font><font color="Orange"> 
    (20 - 19)</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">ramon</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">ramon</font><font color="White"> 
    plays </font><font color="#B0C4DE">Urza's Tower [c2c]</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">ramon</font><font color="White"> 
    casts </font><font color="#B0C4DE">Karn Liberated [b2c]</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">ramon</font><font color="White"> 
    activates: exile target permanent. from </font><font color="#B0C4DE">Karn 
    Liberated [b2c]</font><font color="White"> targeting </font><font color="#90EE90">Tarmogoyf 
    [417]</font><font color="White"> </font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">ramon</font><font color="White"> 
    moves </font><font color="#90EE90">Tarmogoyf [417]</font><font color="White"> 
    from battlefield to the exile zone</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">ramon</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">19:34: </font><font color="Orange">Turn 6 </font><font color="#20B2AA">Blitkun</font><font color="Orange"> 
    (20 - 19)</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    casts </font><font color="#FF6347">Lightning Bolt [b30]</font><font color="White"> 
    targeting </font><font color="#20B2AA">ramon</font><font color="White"> </font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    redirects 3 damage to </font><font color="#B0C4DE">Karn Liberated [b2c]</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    puts </font><font color="#FF6347">Lightning Bolt [b30]</font><font color="White"> 
    from stack into his or her graveyard</font>
<font color="#CCCC33">19:34: </font><font color="#B0C4DE">Karn Liberated [b2c]</font><font color="White"> 
    is put into graveyard from battlefield</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">19:34: </font><font color="Orange">Turn 7 </font><font color="#20B2AA">ramon</font><font color="Orange"> 
    (20 - 19)</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">ramon</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">ramon</font><font color="White"> 
    plays </font><font color="#B0C4DE">Grove of the Burnwillows [bc1]</font>
<font color="#CCCC33">19:34: </font><font color="#20B2AA">ramon</font><font color="White"> 
    casts </font><font color="#B0C4DE">Ugin, the Spirit Dragon [c4e]</font>
<font color="#CCCC33">19:35: </font><font color="#20B2AA">ramon</font><font color="White"> 
    activates: </font><font color="#B0C4DE">Ugin, the Spirit Dragon [c4e]</font><font color="White"> 
    deals 3 damage to target creature or player. from </font><font color="#B0C4DE">Ugin, 
    the Spirit Dragon [c4e]</font><font color="White"> targeting </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    </font>
<font color="#CCCC33">19:35: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    loses 3 life</font>
<font color="#CCCC33">19:35: </font><font color="#20B2AA">ramon</font><font color="White"> 
    attacks with 0 creatures</font>
<font color="#CCCC33">19:35: </font><font color="Orange">Turn 8 </font><font color="#20B2AA">Blitkun</font><font color="Orange"> 
    (20 - 16)</font>
<font color="#CCCC33">19:35: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    draws a card</font>
<font color="#CCCC33">19:35: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    has conceded.</font>
<font color="#CCCC33">19:35: </font><font color="#20B2AA">ramon</font><font color="White"> 
    has won the game</font>
<font color="#CCCC33">19:35: </font><font color="#20B2AA">Blitkun</font><font color="White"> 
    has lost the game.</font>
  </body>
</html>

![xmage issue1](https://cloud.githubusercontent.com/assets/9158612/8881059/d361508e-31f1-11e5-8f0c-a9bd4510f1b3.png)

**Comment by LevelX2** [comment] 2015-07-25 07:33
Duplicate of #643

**Closed by LevelX2** 2015-07-25 07:33 UTC
