### ISSUE TITLE
Casting Spectral Procession with RRR through Blood Moon

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#941] opened 2015-04-29 05:57 UTC
While Blood Moon is in play, you can cast Spectral Procession with 3 non-basic lands that would normally give white mana. For example, you can cast Spectral Procession with 3 Plateau.

**Comment by LevelX2** [comment] 2015-04-29 08:33
Fixed with 66499bd58f01a52491a7f73a09a773ec9ef1fcba
Caused by missing breaks in switch statement.

**Closed by LevelX2** 2015-04-29 08:33 UTC
Labels: bug
