### ISSUE TITLE
Prosper Null error

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9136] opened 2022-06-21 14:16 UTC
when i was playing [[Prosper, Tome-Bound]] the AI did nothing and then this happen.

Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.51-V4-beta5 (build: 2022-06-17 05:05)
mage.game.GameImpl.playPriority(GameImpl.java:1574)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/64045003/174824712-c05a3a3d-07ce-4163-9dea-94e8630fc0e8.png)

this seems to happen when i pick [[Kathril, Aspect Warper]] as the  AI commander

![image](https://user-images.githubusercontent.com/64045003/174829249-0a7befc2-aef9-476f-87b3-e683aade0a16.png)

**Comment by Alex-Vasile** [comment] 2022-07-01 00:55
Looking at the stack trace in the screenshot this is a duplicate of #9177.

**Closed by Alex-Vasile** 2022-07-01 00:55 UTC
Labels: bug
