### ISSUE TITLE
Suggestion: Adjustable Starting Life

### ISSUE THREAD

**Issue by Rewyn** [magefree/mage#5892] opened 2019-07-11 17:29 UTC
A gamemode (maybe as an addition to Freeform Commander?) that allows you to set custom variables for things like starting life etc.
For example some people have suggested we could have 30 starting life for commander instead of 40, and I'd like to test that and see how it plays out within my playgroup.

**Comment by Zerrisx** [comment] 2020-07-15 14:58
Duplicate of #4705

**Closed by Zerrisx** 2020-07-15 14:58 UTC
Labels: enhancement
