### ISSUE TITLE
Dread Return can't be played from hand

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#6606] opened 2020-06-04 19:46 UTC
There is some issue with Dread Return, sometimes even if I have the mana and creatures in the grave, I can't cast it for no apparent reason.

And today I found an even more weird issue: 
![dread return](https://user-images.githubusercontent.com/4504719/83800161-fd0b1300-a674-11ea-8c70-f9ffc5e3e608.PNG)
I flashback Dread Return and suddenly all my cards in exile, grave and hand go puff.

I have experience something somewhat similar to that with a previous version but in that occasion I lose altogether at the beginning of my turn and it was kind of a hopeless situation anyway, so I don't mind it much at the time. 

But this time it was different, it was in the middle of resolving the effects, I cast it, the Demon's effects go to the stack, all AI pass priority on the last one and puff... And in the console nothing appeared to be out of the ordinary either.

Maybe that I have to leave the game running not doing anything for a long time have some influence on it, but isn't like is the first time I do that...

Edit: I include the game log, is the json one, the other didn't get created, I suppose is because I kill the server soon after I took the picture...
[gamelogsJson 4-6-20.zip](https://github.com/magefree/mage/files/4732445/gamelogsJson.4-6-20.zip)

**Comment by jeffwadsworth** [comment] 2020-06-08 15:15
How did you sacrifice your 3 creatures?

**Comment by copperfield42** [comment] 2020-06-08 15:40
as normal I guess, previously I reanimated the Avenger of Zendikar from computer2 with the Demon of Dark Schemes, and use it along with the tokens for the Dread Return, and that was the first thing I did in that turn.

**Comment by jeffwadsworth** [comment] 2020-06-09 00:44
I have set up similar scenario's multiple times and the Dread Return always works fine.

**Comment by copperfield42** [comment] 2020-06-26 23:33
![banishing cards 1](https://user-images.githubusercontent.com/4504719/85907954-461c3600-b7e1-11ea-8fab-68c00ca22062.PNG)
It happens again, the part where it banishes my cards, funnily enough the next play that the computer does legit defeat me, so now I guess that while the computer check the possible plays if it find one where it defeat the human player, and that player is low on life this weird bug happens.

I attach the json log, as the normal one wasn't generated for some reason and this time I close the game normally 
[game log 26-6-2020.zip](https://github.com/magefree/mage/files/4839598/game.log.26-6-2020.zip)

**Comment by Zerrisx** [comment] 2020-07-17 21:26
> 
> There is some issue with Dread Return, sometimes even if I have the mana and creatures in the grave, I can't cast it for no apparent reason.
> 

Can you provide a screenshot of any board state in which this happens?  (The other issue is almost certainly a duplicate of #6738

**Comment by copperfield42** [comment] 2020-07-17 21:42
I don't have any at the moment.
I think that maybe it was that issue I saw the other day about Command Tower or something like that, if it happens again I would tell you.

**Comment by copperfield42** [comment] 2020-07-20 13:50
@Zerrisx I got the issue with Dread Return again
![dread return 1 1](https://user-images.githubusercontent.com/4504719/87944763-d0b52580-ca6d-11ea-9caa-20b444f6d1c5.PNG)
same as before to show the rest of my field
![dread return 1 2](https://user-images.githubusercontent.com/4504719/87944668-b1b69380-ca6d-11ea-82aa-8b6800e84224.PNG)

a little later
![dread return 1 3](https://user-images.githubusercontent.com/4504719/87944716-c2ffa000-ca6d-11ea-8c5e-12ffe3a3b442.PNG)

game log: [20200719_233610_Commander Free For All_1.txt](https://github.com/magefree/mage/files/4948034/20200719_233610_Commander.Free.For.All_1.txt)

**Comment by Zerrisx** [comment] 2020-07-29 04:22
Okay, interesting.  I can reproduce this with your board.

![image](https://user-images.githubusercontent.com/59861365/88756363-15eded00-d129-11ea-9b83-f4f8a06dc93c.png)

[Test]
battlefield:Human:Tainted Peak:1
battlefield:Human:Luxury Suite:1
battlefield:Human:Memorial to Folly:1
battlefield:Human:Mountain:1
battlefield:Human:Geier Reach Sanitarium:1
battlefield:Human:Barren Moor:1
battlefield:Human:Sol Ring:1
battlefield:Human:Rakdos Signet:1
battlefield:Human:Phyrexian Reclamation:1
battlefield:Human:Anje Falkenrath:1
battlefield:Human:Demon of Dark Schemes:1
battlefield:Human:Eater of Hope:1
hand:Human:Dread Return:1
hand:Human:Reanimate:1
graveyard:Human:Reassembling Skeleton:1
graveyard:Human:Lord of the Void:1
graveyard:Human:Rune-Scarred Demon:1
graveyard:Human:Anger:1
graveyard:Human:Dread Necromancer:1

I'll try removing cards one at a time to isolate the issue.

**Comment by copperfield42** [comment] 2021-09-09 01:34
![019 dread return](https://user-images.githubusercontent.com/4504719/132607484-a31c3019-352c-4ae3-adcf-6126b1182b61.PNG)
another sample

**Comment by awjackson** [comment] 2022-03-03 21:05
This is almost certainly the same issue as #8462 (Dread Return and Battle Screech are both cards with non-mana flashback costs) and as such is presumably fixed now.

**Closed by awjackson** 2022-03-03 21:05 UTC
Labels: bug
