### ISSUE TITLE
Vindictive Lich

### ISSUE THREAD

**Issue by MantaXIV** [magefree/mage#4279] opened 2017-12-24 17:30 UTC
Yesterday I was play Commander, and when my Vindictive Lich died, I put the ability in to the stack, but nothing happened. My opponent doesn't discard two cards. Please, what can I do now to fix this?

**Comment by derlhurgoyf** [comment] 2018-01-29 03:31
In a 4-way Commander game Vindictive Lich died and I select all three modes and all three opponents. However only one effect happened (sacrifice a creature). The other players were unaffected by discard and life loss.

**Comment by derlhurgoyf** [comment] 2018-02-18 01:41
probably duplicate of #3895

**Comment by Zerrisx** [comment] 2020-06-28 18:49
Duplicate of #4742

**Closed by Zerrisx** 2020-06-28 18:49 UTC
Labels: cards
