### ISSUE TITLE
Token Icons will randomly change between turns

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9468] opened 2022-09-04 23:08 UTC
e.g. create 3 Soldier tokens with [[Captain's Call]], they will switch between different cards as the turns continue.

**Comment by hidde-vb** [comment] 2022-09-29 21:09
@Alex-Vasile This seems to be fixed? the card [xxx] stays the same, only the initial token will be a random soldier token, but for each spell it will use the same 3 versions,

**Comment by PurpleCrowbar** [comment] 2022-09-29 21:34
> This seems to be fixed? the card [xxx] stays the same, only the initial token will be a random soldier token, but for each spell it will use the same 3 versions,

This issue is fixed in the case of DMU's Captain's Call specifically (because DMU token images were recently added to xmage), but the issue *generally* is not fixed. In xmage when a source from a set without an image for a token creates an instance of that token it will instead generate the token with a random image from a set which *does* have an image for that token. This is why prior to 47670266cd489871a46e5e8114536d22f73eba48 DMU cards would create tokens with images from random sets. The issue is that these token images will frequently switch to a different image whenever the battlefield "moves", i.e. permanents shrink or move to accommodate more / less permanents entering play, which seems to imply that the images for these tokens are being fetched each time the battlefield updates.

Also, thumbnail and "full" images for tokens are not synced, which is the reason that you can have a token in game displaying with a certain image on the battlefield, but displays a different full image at the top-right of the client when you hover your cursor over it.

**Comment by JayDi85** [comment] 2022-09-29 21:42
If true about images changes then it's regression from one of the commits.
Must be researched.

Token images and thunbnails (small images) work fine in old versions. Maybe
something lost (example: token cache key or set code from initialized token
permanent).

**Comment by JayDi85** [comment] 2023-05-09 07:41
> The issue is that these token images will frequently switch to a different image whenever the battlefield "moves", i.e. permanents shrink or move to accommodate more / less permanents entering play, which seems to imply that the images for these tokens are being fetched each time the battlefield updates.

I can't reproduce images switching on battlefield update in current version. So it must be fixed.

**Closed by JayDi85** 2023-05-09 07:41 UTC
Labels: bug, GUI
