### ISSUE TITLE
Issue popped up during a game. 

### ISSUE THREAD

**Issue by Gamefreak1476** [magefree/mage#9212] opened 2022-07-02 23:37 UTC
Used Hour of Devastation to try to wipe the board and the following occurred. 

An error has occurred on the MAGE server. Your last action will be rollbacked.
Please post the following report here: https://github.com/magefree/mage/issues

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.51-V4-beta6 (build: 2022-06-24 13:26)
mage.abilities.effects.common.combat.GoadTargetEffect.apply(GoadTargetEffect.java:60)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:115)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1176)
mage.game.GameState.applyEffects(GameState.java:663)
mage.game.GameImpl.applyEffects(GameImpl.java:1747)
mage.game.GameState.processAction(GameState.java:652)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:2009)
mage.game.GameImpl.playPriority(GameImpl.java:1513)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Alex-Vasile** [comment] 2022-07-02 23:39
Goad is top of trace. I assume there was a goaded creature on the board.

Looks like a duplicate of #9205.

**Comment by Alex-Vasile** [comment] 2022-07-03 20:57
Closed in da10b6397ccf36e0fe6f5e8630bb2f3499128196

**Closed by Alex-Vasile** 2022-07-03 20:57 UTC
