### ISSUE TITLE
Back side of Ore-Rich Stalactite allows player to choose spell

### ISSUE THREAD

**Issue by Cytocide** [magefree/mage#12001] opened 2024-03-25 00:20 UTC
The back side of ore-rich stalactite (cosmium catalyst), currently allows the player to select which spell to cast, but it should be randomly selected.

**Comment by xenohedron** [comment] 2024-03-25 00:23
Duplicate of #11933, will be fixed in next release

**Closed** 2024-03-25 00:23 UTC
