### ISSUE TITLE
Change to "tapped for mana" rule.

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#1122] opened 2015-07-17 04:16 UTC
New rule:

106.10a An ability that triggers whenever a permanent “is tapped for mana” or “is tapped for mana
[of a specified type]” triggers whenever such a mana ability resolves and produces mana or the
specified type of mana.

"This is a new rule that slightly changes how we resolve abilities that trigger whenever a permanent is tapped for mana or for mana of a specified type. Now, you look at what was actually produced after the activated mana ability resolves. So, tapping a Gaea's Cradle while you no control no creatures won't cause a Wild Growth attached to it to trigger. The good news is it's now clear if you named blue for Gauntlet of Power, tapping a Mountain that produces {U} because of a replacement effect will cause it to trigger."

**Comment by LevelX2** [comment] 2018-09-27 09:10
106.11. To “tap [a permanent] for mana” is to activate a mana ability of that permanent that includes the {T} symbol in its activation cost. See rule 605, “Mana Abilities.”

    106.11a An ability that triggers whenever a permanent “is tapped for mana” or is tapped for mana of a specified type triggers whenever such a mana ability resolves and produces mana or the specified type of mana.
    106.11b A replacement effect that applies if a permanent “is tapped for mana” or tapped for mana of a specific type and/or amount modifies the mana production event while such an ability is resolving and producing mana or the specified type and/or amount of mana.

**Comment by Zerrisx** [comment] 2020-05-18 00:36
Cannot reproduce; this appears to be fixed.

**Closed** 2020-06-24 20:09 UTC
Labels: enhancement
