### ISSUE TITLE
Cavern of Souls making creatures uncounterable when using "Add {1} to your mana pool."

### ISSUE THREAD

**Issue by Badaro** [magefree/mage#882] opened 2015-04-04 20:53 UTC
Using version 1.3.0dev2015-03-14v5.

* Have a Cavern of Souls in play, naming "Construct"
* Cast a Wurmcoil (Artifact Creature - Wurm) using the "Add {1} to your mana pool." ability of the Cavern
* Opponent attempts to counter it, counterspell fizzles due to the Cavern's ability

**Comment by Badaro** [comment] 2015-04-04 20:57
Gamelog: http://pastebin.com/gTHK3Ljj

**Comment by LevelX2** [comment] 2015-04-06 21:32
Duplicate of #798

**Closed by LevelX2** 2015-04-06 21:32 UTC
Labels: duplicate

**Comment by Badaro** [comment] 2015-04-07 14:44
Suspected it was a duplicate, but thought it would be better to let you confirm that. Hope the game log helps fixing it.
