### ISSUE TITLE
Spells that target other spells show themselves as valid targets

### ISSUE THREAD

**Issue by Alex-Vasile** [magefree/mage#9611] opened 2022-10-01 23:03 UTC
E.g. Here I am casting [[Negate]] and it's highlighted as a potential target.
![Target](https://user-images.githubusercontent.com/48962821/193431276-76276560-81f0-42ba-a915-1acf449e91c5.PNG)

The game won't actually let me click it, but it should not show up as targetable in the first place. Aside from not being technically correct, this also means that:
1. Auto-choosing targets cannot work for it since there are "2" potential targets of which we need to pick one.
2. The AI may potentially be spending time computing that possibility

**Comment by xenohedron** [comment] 2024-09-16 02:50
Fails to autochoose target creature spell with Essence Scatter, even though Essence Scatter isn't even a creature spell. It's not highlighted though.
![image](https://github.com/user-attachments/assets/b7099675-7b4b-4732-a100-be4a33d3cf7d)

**Comment by xenohedron** [comment] 2024-10-04 00:46
See https://github.com/magefree/mage/issues/12466#issuecomment-2392568025 for the root cause on not autochoosing.

Simple fix for cancel being highlighted above though, possibleTargets needs to exclude

**Comment by xenohedron** [comment] 2024-10-04 03:36
Fixed by 91c1d1d

**Closed by xenohedron** 2024-10-04 03:36 UTC
Labels: bug
