### ISSUE TITLE
Provoke not enforcing requiring block - player can undo the block to avoid

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3203] opened 2017-04-22 05:22 UTC
if you use the provoke effect the player has the ability to press undo and choose not to block.

-- from subreddit

**Comment by drmDev** [comment] 2017-04-22 05:22
Will not be able to UT this scenario (pretty sure)

**Comment by Zerrisx** [comment] 2020-06-27 17:43
Duplicate of #3729

**Closed by Zerrisx** 2020-06-27 17:43 UTC
Labels: GUI, bug, not confirmed
