### ISSUE TITLE
Rollback

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#7560] opened 2021-02-12 23:28 UTC
This happen when I was sacrificing things to Razaketh

![image](https://user-images.githubusercontent.com/64045003/107832850-81af4480-6d5f-11eb-9370-1c8801ffd62f.png)

Game exception occurred: java.util.ConcurrentModificationException
Server version: 1.4.48V0 (build: 2021-02-07 19:27)
java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
java.util.ArrayList$Itr.next(ArrayList.java:859)
mage.abilities.AbilitiesImpl.<init>(AbilitiesImpl.java:35)
mage.abilities.AbilitiesImpl.copy(AbilitiesImpl.java:42)
mage.abilities.AbilitiesImpl.copy(AbilitiesImpl.java:21)
mage.MageObjectImpl.<init>(MageObjectImpl.java:75)
mage.cards.CardImpl.<init>(CardImpl.java:114)
mage.game.permanent.PermanentImpl.<init>(PermanentImpl.java:123)
mage.game.permanent.PermanentCard.<init>(PermanentCard.java:82)
mage.game.permanent.PermanentCard.copy(PermanentCard.java:158)
mage.game.permanent.PermanentCard.copy(PermanentCard.java:27)
mage.game.GameImpl.getLastKnownInformation(GameImpl.java:2923)
mage.game.GameImpl.getLastKnownInformation(GameImpl.java:2950)
mage.abilities.TriggeredAbilities.checkTrigger(TriggeredAbilities.java:68)
mage.abilities.TriggeredAbilities.checkTriggers(TriggeredAbilities.java:51)
mage.game.GameState.handleEvent(GameState.java:758)
mage.game.GameState.handleSimultaneousEvent(GameState.java:731)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:211)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:170)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:81)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1447)
mage.game.GameImpl.playPriority(GameImpl.java:1393)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:128)
mage.game.GameImpl.playTurn(GameImpl.java:911)
mage.game.GameImpl.play(GameImpl.java:821)
mage.game.GameImpl.start(GameImpl.java:797)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment] 2021-02-13 11:46
Can be related to #7170

**Comment by JayDi85** [comment] 2021-02-13 11:50
Duplicate of #7170

**Closed by JayDi85** 2021-02-13 11:50 UTC
