### ISSUE TITLE
Fractal Harness not doubling properly

### ISSUE THREAD

**Issue by ThatBlueBunny** [magefree/mage#8997] opened 2022-05-25 15:57 UTC
I played Fractal Harness (from Commander 2021), attached it to a creature with 4 +1/+1 counters, attacked with it and it went up to 64 counters (so it doubled 4 times?).

**Comment by Alex-Vasile** [comment] 2022-05-25 17:27
Duplicate of #8377.

Fixed on the beta.

**Closed by Alex-Vasile** 2022-05-25 17:27 UTC
