### ISSUE TITLE
Suggestion: Context-sensitive "Done" button language

### ISSUE THREAD

**Issue by mezzoEmrys** [magefree/mage#5895] opened 2019-07-13 03:58 UTC
Currently when changing from the main phase to the combat phase, the button to do this is simply labeled "Done". This can lead to pressing "Done" expecting to finish the resolution of an effect or similar, but instead changing phases. In these cases, I suggest having the button say "Change phase" to make it clear what the button will do.

Similarly, when searching, "Done" should say something like "Fail to find" or, in the case of a card that allows you to search up to some number of cards, it should say "Accept selected card(s)" after the first card has been selected. Adding this language will make it easier for newer players using xmage to not make common mistakes with searching.

**Comment by Zerrisx** [comment] 2020-07-17 17:48
Duplicate of #1802

**Closed by Zerrisx** 2020-07-17 17:48 UTC
Labels: GUI, enhancement
