### ISSUE TITLE
Surprised it's missing

### ISSUE THREAD

**Issue by Mike405429** [magefree/mage#10571] opened 2023-07-06 05:54 UTC
Hello, I was trying to rebuild my Omnath deck which uses some cards from the Jared Precon commander deck. The specific card I could not find was Nethroi, Apex of Death. I don't know if it will be hard to get added but it would be greatly appreciated if it could be added. Thanks and have an amazing day!

**Comment by ssk97** [comment] 2023-07-06 06:33
Mutate as a mechanic is very complex and currently unimplemented. While we would very much like to add support for it and there are efforts to do so, it seems unlikely to be added in the near future.

**Comment by Grath** [comment] 2023-07-06 18:01
Duplicate of #7623

**Closed by Grath** 2023-07-06 18:01 UTC
