### ISSUE TITLE
AbilityPicker - using keyboard to select option

### ISSUE THREAD

**Issue by viroulep** [magefree/mage#4151] opened 2017-11-07 16:30 UTC
I find a bit frustrating that you can't use the up/down + enter keys to navigate through an AbilityPicker's options.
Eg: when playing LED I have to click both on the card and on the default action, where it would be more convenient to keep the mouse around the hand area and simply hit enter.

Although I could figure my way out writing java, I'm totally unfamiliar with the codebase and the specific framework used to build mage's UI.
I'd gladly contribute a fix if someone could point me to documentation about how to implement some keyboard listener on the list of options (or to some place in the code where something similar is implemented, if any).
As far as I could see, there is an [addMouseListener](https://github.com/magefree/mage/blob/68d398c6fbb4379602099e313fb12507344a0fde/Mage.Client/src/main/java/mage/client/components/ability/AbilityPicker.java#L168), but I couldn't find a similar "keyboard listener" on JList's doc.

**Comment by Zerrisx** [comment] 2020-06-27 16:38
Duplicate of #3010

**Closed by Zerrisx** 2020-06-27 16:38 UTC
Labels: GUI
