### ISSUE TITLE
[KHM] Haunting Voyage not working properly when foretold

### ISSUE THREAD

**Issue by J1ZZ0** [magefree/mage#7862] opened 2021-05-29 23:30 UTC
Just like Starnheim Unleashed and Poison the Cup, the alternate effect of the foretold condition of haunting voyage doesnt work and results in the standard effect when cast from exile

**Comment by xenohedron** [comment] 2024-03-19 03:19
duplicate of #8419

**Closed by xenohedron** 2024-03-19 03:19 UTC
Labels: bug
