### ISSUE TITLE
Catch unknown error while downloading java.lang.IllegalArgumentException: Wrong code usage: scryfall used unique card numbers, but found duplicated: Spike Feeder/tpr/196/en - IllegalArgumentException

### ISSUE THREAD

**Issue by kuruku44** [magefree/mage#12820] opened 2024-09-07 09:08 UTC
Error type: Catch unknown error while downloading java.lang.IllegalArgumentException: Wrong code usage: scryfall used unique card numbers, but found duplicated: Spike Feeder/tpr/196/en - IllegalArgumentException
Client version: 1.4.53-V1 (build: 2024-08-16 15:36)

Wrong code usage: scryfall used unique card numbers, but found duplicated: Spike Feeder/tpr/196/en

Stack trace:
org.mage.plugins.card.dl.sources.ScryfallImageSource.createBulkImagesIndex(ScryfallImageSource.java:609)
org.mage.plugins.card.dl.sources.ScryfallImageSource.analyseBulkData(ScryfallImageSource.java:503)
org.mage.plugins.card.dl.sources.ScryfallImageSource.prepareDownloadList(ScryfallImageSource.java:253)
org.mage.plugins.card.images.DownloadPicturesService.run(DownloadPicturesService.java:645)
java.lang.Thread.run(Thread.java:748)

Even if I deleted everything and re-downloaded it, it didn't cure it. I would be grateful if you could tell me what to do.

**Comment by JayDi85** [comment] 2024-09-07 09:14
duplicate of #12817

**Closed by JayDi85** 2024-09-07 09:14 UTC
