### ISSUE TITLE
Second level of attachments not shown on battlefield

### ISSUE THREAD

**Issue by Keifkeif** [magefree/mage#4539] opened 2018-02-20 02:14 UTC
I recently played a game on the xmage servers and in it I played a green monocolor deck against a green monocolor deck, I played quiet disrepair on either a utopia sprawl or a similar enchantment on a forest mana land card very early in the game, and the land card dissappeared for the remaining rounds.  Both enchantments were still visible, however the land was invisible and not interactable since you couldn't click on it in any way...  When I destroyed the quiet disrepair along with the enchantment a few rounds later in the game (for the sake of fairness with my friend I was versing and just to see what would happen) the forest land miraculously appeared again.

Just wanted to report this.  Thanks for the great game.

**Comment by LevelX2** [comment] 2018-02-20 14:32
Duplicate of:
https://github.com/magefree/mage/issues/892
https://github.com/magefree/mage/issues/785
https://github.com/magefree/mage/issues/258

**Closed** 2018-04-08 18:40 UTC
Labels: GUI, bug, duplicate
