### ISSUE TITLE
[Ragavan + Dragon's Rage Channeler+ Professional Face-Breaker] - Critical error

### ISSUE THREAD

**Issue by GallinaFina** [magefree/mage#9567] opened 2022-09-24 22:40 UTC
Super simple board state: I had a Ragavan, Dragon's Rage Channeler and Professional Face-Breaker on the field. Swung with Ragavan + the Dragon's Rage Channeler and got a critical error that kept looping, basically making it impossible to do anything else (couldn't type, concede, rollback or anything).
![ragcrash](https://user-images.githubusercontent.com/112827360/192121054-849ac06d-13d5-4ab3-816c-c5e14cf05ee2.png)

**Comment by awjackson** [comment] 2022-09-24 22:42
Duplicate of #9562

**Closed by awjackson** 2022-09-24 22:42 UTC
Labels: duplicate
