### ISSUE TITLE
Limited deck construction editor

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#2757] opened 2017-01-08 17:18 UTC
The divider bar separating the deck from the card pool defaults to be at the very bottom of the screen, hiding the cards in the pool. Users are confused because they don't see their cards. The default location of the divider bar needs to be higher.

**Comment by Zerrisx** [comment] 2020-06-27 03:44
Duplicate of #2134

**Closed by Zerrisx** 2020-06-27 03:44 UTC
Labels: enhancement
