### ISSUE TITLE
Player's permanents remain on the battlefield after they lose connection

### ISSUE THREAD

**Issue by ngenisis** [magefree/mage#1596] opened 2016-03-06 04:10 UTC
For example, a player controlled Stasis and then lost connection and timed out. Xmage skipped their turn and never gave them priority, but all of their permanents remained on the battlefield and continued affecting the game state. In this case, this meant that none of us ever received another untap step. The steps for removing a player from the game are as follows:
1. All objects owned by that player leave thegame and any effects which give that player control of any objects or players end.
2. If thatplayer controlled any objects on the stack not represented by cards, those objects cease to exist.
3. If there are any objects still controlled by that player, those objects are exiled. This is not
   a state-based action. It happens as soon as the player leaves the game. If the player who left the
   game had priority at the time he or she left, priority passes to the next player in turn order who’s
   still in the game.

**Comment by Zerrisx** [comment] 2020-07-01 21:59
Duplicate of #4472

**Closed by Zerrisx** 2020-07-01 21:59 UTC
Labels: bug
