### ISSUE TITLE
AI: Shielded by Faith is attached to any creature that enters the battlefield

### ISSUE THREAD

**Issue by Ebola16** [magefree/mage#6335] opened 2020-03-09 16:20 UTC
Shielded by Faith is attached to any creature that enters the battlefield (even opponent's creatures). Perhaps Shielded by Faith's AI code should be restricted to only the controller's creatures?

**Comment by Zerrisx** [comment] 2020-07-14 16:13
Duplicate of #6838

**Comment by Ebola16** [comment] 2024-01-13 00:28
Since the mass issue-closing has been partially undone and this issue still occurs, please re-open.

**Closed** 2024-01-16 23:12 UTC
Labels: AI
