### ISSUE TITLE
Cosima, God of Voyage doesn't return to command zone after dying.

### ISSUE THREAD

**Issue by AsterAether** [magefree/mage#8249] opened 2021-09-11 12:11 UTC
[[Cosima, God of Voyage]] player didn't have the option to return Cosima back to command zone after she was destroyed.
Of note should be that she was exiled with her ability beforehand and came back. Maybe doesn't get tagged as commander on return?

**Comment by Alex-Vasile** [comment] 2022-05-15 02:56
Duplicate of #8126

**Closed by Alex-Vasile** 2022-05-15 02:56 UTC
