### ISSUE TITLE
keep getting this error when trying to download card images

### ISSUE THREAD

**Issue by Groisnotdead** [magefree/mage#12822] opened 2024-09-07 10:16 UTC
Error type: Catch unknown error while downloading java.lang.IllegalArgumentException: Wrong code usage: scryfall used unique card numbers, but found duplicated: Spike Feeder/tpr/196/en - IllegalArgumentException
Client version: 1.4.53-V1 (build: 2024-08-16 15:36)

Wrong code usage: scryfall used unique card numbers, but found duplicated: Spike Feeder/tpr/196/en

Stack trace:
org.mage.plugins.card.dl.sources.ScryfallImageSource.createBulkImagesIndex(ScryfallImageSource.java:609)
org.mage.plugins.card.dl.sources.ScryfallImageSource.analyseBulkData(ScryfallImageSource.java:503)
org.mage.plugins.card.dl.sources.ScryfallImageSource.prepareDownloadList(ScryfallImageSource.java:253)
org.mage.plugins.card.images.DownloadPicturesService.run(DownloadPicturesService.java:645)
java.lang.Thread.run(Thread.java:748)

**Comment by JayDi85** [comment] 2024-09-07 10:34
duplicate of #12817, will be fixed with next release in 1 day

**Closed by JayDi85** 2024-09-07 10:34 UTC
