### ISSUE TITLE
Somehow AI attacked 2 players at once

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#9792] opened 2022-12-07 07:05 UTC
No idea how this happened.  AI managed to attack 2 players, was unblockable, and didn't have to pay for Propaganda.  He also got 2 triggers off of Elder Gargaroth.  Unsure of how this occurred.
![image](https://user-images.githubusercontent.com/82664393/206111184-a40eec95-c28a-493b-9042-66c819aa6c2b.png)

**Comment by LegionedintheDamned** [comment] 2022-12-07 07:05
![image](https://user-images.githubusercontent.com/82664393/206111256-dc8968e4-1a53-4156-80fb-c1baac2aeb03.png)
Battle log.

**Comment by PurpleCrowbar** [comment] 2022-12-07 15:56
Duplicate of #7434

Also, [[Propaganda]] doesn’t require payment for attacking planeswalkers, only players

**Closed by PurpleCrowbar** 2022-12-07 15:56 UTC
