### ISSUE TITLE
Bug: Commander is exiled for good after Unearth ability despite being sent to command zone

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#5789] opened 2019-05-08 12:16 UTC
In Freeform Commander (1v1), I had Sedraxis Specter as my commander. I let it die to my graveyard the first time. Then I used its Unearth ability to put it into play from my graveyard. When that turn ended, XMage asked to put it to the command zone or exile. I chose command zone, but it got exiled anyway.

**Comment by Zerrisx** [comment] 2020-07-14 15:36
Unearthed my commander with Sedris and returned it to the command zone without issue.  Cannot reproduce; closing as fixed.

**Closed by Zerrisx** 2020-07-14 15:36 UTC
