### ISSUE TITLE
Sideboarding timer issue

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#1981] opened 2016-06-08 18:12 UTC
I was sideboarding during a sealed deck, attempting to changing colors. I had moved all the main deck cards to sideboard and had almost finished getting my new main deck constructed when sideboarding ended and it took me to game 2 of the match. It surprised me because I had seen the timer show a minute left not long before. Since I had not finished sideboarding, my deck was 40 random cards, so I conceded the match. It then showed me the sideboarding screen, which still had ~20 seconds left on the clock, so it definitely took me to game 2 earlier than it should have. One thought is that the sync of the timer clocks gets off  a little bit because of the little lag each time you double-click a card to move it between main deck and sideboard.

**Comment by Zerrisx** [comment] 2020-07-17 20:58
Duplicate of #2173

**Closed by Zerrisx** 2020-07-17 20:58 UTC
Labels: bug
