### ISSUE TITLE
Unplayable on small screens

### ISSUE THREAD

**Issue by fenhl** [magefree/mage#2044] opened 2016-07-02 14:26 UTC
I want to play XMage on a display with a logical resolution of 1152×720, so I scaled everything down to the minimum in the GUI Size preferences, but the scrollbar below my hand is still not shown. It is not possible to resize the window vertically, and trying to resize horizontally immediately increases the vertical size so that part of the window is offscreen or hidden by the OS X Dock. Switching to fullscreen mode results in a similar effect.

**Comment by drmDev** [comment] 2016-07-02 14:29
Add a screenshot for a visual reference of what you're seeing

**Comment by fenhl** [comment] 2016-07-02 14:40
http://senf.fenhl.net/fs/H8mqS2Fnvh.png

**Comment by LevelX2** [comment] 2016-07-02 17:06
![small](https://cloud.githubusercontent.com/assets/2066790/16541639/fbd0bab4-4087-11e6-8f57-71d60e4d0213.jpg)
Should look like this.

**Comment by ochilly** [comment] 2016-07-05 05:14
I am running on a resolution of 1366x768 and I have the same issue. I cannot scale vertically so I have to move the window so it cuts off the top menu instead of the bottom area.

**Comment by AdamEternal** [comment] 2017-03-10 19:37
Same problem, also using Ubuntu 16.04. 32-bit. Resolution: 1280 x 800. Also can not scale vertically, but I can scale horizontally. I do have two Xubuntu panals though, one on top and one on bottom, and moving one panal gives enough room. I'll have to reconfigure my layout just for this application until this issue is fixed.

**Comment by pyested** [comment] 2017-11-27 21:48
Here is a provisional solution. I'm running xmage in Ubuntu 16.04 64bit with a resolution of 1366x768, as @ochilly. I've tried to scale the output resolution so xmage doesn't cut at the bottom of the window. First, you need to know the port that your monitor is currently using. In the terminal run:

`xrandr --query | grep connected` 

Obtaining the next output in my computer:

`VGA-0 disconnected (normal left inverted right x axis y axis)
LVDS-0 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 353mm x 198mm
HDMI-0 disconnected (normal left inverted right x axis y axis)`

As you see, LVDS-0 is the unique port showing a status of 'connected'. Knowing this, now run:

`xrandr --output LVDS-0 --scale 1.10x1.10` 

You have to modify _LVDS-0_ with the name of your port. By try and error, a scale of 1.10x1.10 leads to the desired result. The problem of this solution is that you need to run the above command every time you start Ubuntu. If you want to apply this scale automatically when you start Ubuntu, you have to modify your xprofile file by running:

 `sudo gedit ~/.xprofile`

The above command opens your xprofile file. There you must write _xrandr --output LVDS-0 --scale 1.10x1.10_, and save it. This will scale the output resolution next time you start Ubuntu, and so on.

In my case (again), applying the scale makes the output of the monitor seem a little bit dim, and I don't really like it. Therefore I've decided to write a sh script and run it only when needed (of course, before playing xmage).

I'm not a professional Ubuntu user/programmer, but after reading a lot of stuff doing with the issue this is the only solution that actually works for me.

Hope this is helpful for you!

**Comment by Zerrisx** [comment] 2020-05-26 23:38
Duplicate of #6081

Marking this as the duplicate, since the more recent one seems to have developer work being done on it.

**Closed** 2020-06-24 20:15 UTC
Labels: GUI
