### ISSUE TITLE
Java UI errors if the cleint uses Java 8

### ISSUE THREAD

**Issue by IttyBittyKittyCat** [magefree/mage#839] opened 2015-03-26 01:18 UTC
![screen shot 2015-03-25 at 6 12 21 pm](https://cloud.githubusercontent.com/assets/11656953/6838700/0cc0b008-d31b-11e4-878a-e56d50988214.png)

This has happened to me more than a few times but only in games or drafting. A massive number of error messages pop up usually saying something along the lines of java ui error null pointer exception (not too technologically knowledgeable). Forcing the client to re-update helped for a while but the error is back. It's sadly making xmage unplayable.

On OSX 10.9.4.

**Comment by IttyBittyKittyCat** [comment] 2015-03-26 03:06
Update on this, it's not just within games.
![screen shot 2015-03-25 at 8 05 08 pm](https://cloud.githubusercontent.com/assets/11656953/6839731/548dd136-d32a-11e4-812a-40265ca26c92.png)

**Comment by LevelX2** [comment] 2015-03-26 18:31
Try to revert back to java 7 with the launcher.
Described here:
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16910&start=45#p175524
And report if this solves the problem.

**Comment by IttyBittyKittyCat** [comment] 2015-03-26 20:37
I'm seeing nothing in that thread which helps me figure out how to revert back to java 7. Tried just downloading and installing java 7 but the computer won't let me due to having 8.

**Comment by fireshoes** [comment] 2015-03-26 22:20
He was referring to this: "You can change the XMage Home in Launcher settings to a java 7 configuration (http://xmage.info/xmagejava7) I created and update with the launcher back to java 7."

**Comment by LevelX2** [comment] 2015-03-28 08:48
Yeah, I linked to the wron post. The corect one is this.
http://www.slightlymagic.net/forum/viewtopic.php?f=70&t=16910&start=75#p175911

I assume a problem with java 8 and XMage on some systems.
You can change the XMage Home in Launcher settings to a java 7 configuration (http://xmage.info/xmagejava7) I created and update with the launcher back to java 7.

![laujava7](https://cloud.githubusercontent.com/assets/2066790/6880391/8fa69134-d52f-11e4-872e-3258b25dbf27.jpg)

And please report, if this fixes the problem.

**Comment by tkrajcar** [comment] 2015-03-29 00:27
Was seeing this, rolled back to Java 7 as described, no issues now. :+1:

**Comment by Malabarba** [comment] 2015-03-31 12:06
Same here. Was having frequent `indexOutOfBounds` exceptions. Downgrading java seems to have fixed it.

**Comment by LevelX2** [comment] 2015-03-31 23:14
Another problem maybe caused by Java 8
```
FATAL 2015-04-01 01:11:33,656                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.IndexOutOfBoundsException: Invalid index
	at javax.swing.DefaultRowSorter.convertRowIndexToModel(Unknown Source)
	at javax.swing.JTable.convertRowIndexToModel(Unknown Source)
	at javax.swing.JTable.setValueAt(Unknown Source)
	at javax.swing.JTable.editingStopped(Unknown Source)
	at javax.swing.AbstractCellEditor.fireEditingStopped(Unknown Source)
	at javax.swing.AbstractCellEditor.stopCellEditing(Unknown Source)
	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$300(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by LevelX2** [comment] 2015-04-25 17:01
```
FATAL 2015-04-25 18:56:40,185                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:56:40,200                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:56:40,216                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:56:40,231                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:56:40,247                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:56:40,247                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:56:40,263                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:56:40,263                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:56:40,278                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:56:40,341                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:57:06,294                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:57:08,928                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:57:11,147                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:59:37,639                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.ArrayIndexOutOfBoundsException
FATAL 2015-04-25 18:59:39,499                                                                                            =>[AWT-EventQueue-0] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at javax.swing.BoxLayout.minimumLayoutSize(BoxLayout.java:327)
	at java.awt.Container.minimumSize(Container.java:1846)
	at java.awt.Container.getMinimumSize(Container.java:1830)
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1746)
	at javax.swing.GroupLayout$ComponentSpring.calculateNonlinkedMinimumSize(GroupLayout.java:3008)
	at javax.swing.GroupLayout$ComponentSpring.calculateMinimumSize(GroupLayout.java:2972)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout$ComponentSpring.calculatePreferredSize(GroupLayout.java:2979)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1624)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1624)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1624)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$SequentialGroup.setValidSize(GroupLayout.java:2017)
	at javax.swing.GroupLayout$Group.setSize(GroupLayout.java:1587)
	at javax.swing.GroupLayout.layoutContainer(GroupLayout.java:924)
	at java.awt.Container.layout(Container.java:1508)
	at java.awt.Container.doLayout(Container.java:1497)
	at java.awt.Container.validateTree(Container.java:1693)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validateTree(Container.java:1702)
	at java.awt.Container.validate(Container.java:1628)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:704)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:702)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:701)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1719)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:869)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at mage.client.util.EDTExceptionHandler.handle(EDTExceptionHandler.java:51)
	at mage.client.util.EDTExceptionHandler.uncaughtException(EDTExceptionHandler.java:45)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1057)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1052)
	at java.awt.EventDispatchThread.processException(EventDispatchThread.java:223)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:215)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by goesta** [comment] 2017-02-28 22:14
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.

**Closed by goesta** 2017-02-28 22:14 UTC
Labels: bug
