### ISSUE TITLE
Sasaya's Essence generates too much mana

### ISSUE THREAD

**Issue by glitchkuh** [magefree/mage#8426] opened 2021-11-02 12:33 UTC
When you tap [[Sasaya's Essence]] for Mana (a flipped [[Sasaya, Orochi Ascendant]], it adds too much mana (it's seems to be a random amount). E.g. you have Sasaya's Essence with 5 Forests, when you tap 1 you could get 6 Mana (should be 5), when you tap the next Forest it could tap for 8 (should still be 5) etc.

**Comment by jeffwadsworth** [comment] 2021-11-04 14:23
[[Sasaya's Essence]]

**Comment by jeffwadsworth** [comment] 2021-11-04 15:29
This one is bizarre.  The count is correct, but goes awry from there in some cases.  Checking it out.
![interestingWeirdness](https://user-images.githubusercontent.com/1496996/140355592-467cad2c-2902-465c-981a-8b34f421bc04.jpg)

**Comment by Alex-Vasile** [comment] 2022-03-18 00:11
I haven't been able to reproduce this.

Though the card text is currently wrong.  Says:
"Whenever land you control for mana"
instead of 
"Whenever a land you control is tapped for mana"

**Comment by JayDi85** [comment] 2024-04-11 07:11
All my pain in one stack trace:

![shot_240411_092409](https://github.com/magefree/mage/assets/8344157/bf62500c-65f6-4f03-846b-06eee2952e65)

**Comment by Susucre** [comment] 2024-04-11 08:41
I have the feeling that the mana triggered ability being resolved instantly here is the problem:
![image](https://github.com/magefree/mage/assets/34709007/3c68d5ad-8f36-425f-8768-d40233713c34)

It should not resolve directly here, but be collected and resolved right after the TAPPED_FOR_MANA event has been handled. (fired by `ManaEffect::checkToFirePossibleEvents`)

**Comment by JayDi85** [comment] 2024-04-11 09:02
It’s not a problem in mana triggers - it must resolve immediately to apply additional manas/colors — it’s fine. The problem in ApplyEffects inside resolve - it restart game cycle and recreate triggers and other things — and it broke original triggers iterator so it continue to random trigger/item (e.g. can trigger same ability again). And it light on many other problems like wrong usage of stack and non stack triggered abilities. I’ll report more details about it.

**Comment by Susucre** [comment] 2024-04-11 09:08
Thanks for investigating it. Spent a couple hours on it a couple days ago and had more questions than answers.

**Comment by JayDi85** [comment] 2024-04-11 09:25
And another big problem: looks like mana calculation can raise user dialog for replacement choice. Only game cycle (game thread) can use dialogs. Any call of user dialog outside of the game cycle will reset/broke current active dialog and game will be freeze (user will not see a real dialog). It’s rare use case but still possible.

Maybe related test:

![IMG_0177](https://github.com/magefree/mage/assets/8344157/fa71893a-ba0b-4c16-a6a4-d5fcc2df3528)

**Comment by JayDi85** [comment] 2024-04-16 19:38
Must be fixed by e8e2f23284e9fbbbeb56697092052855bfce6fd5

**Closed by JayDi85** 2024-04-16 19:38 UTC
Labels: bug
