### ISSUE TITLE
 Itlimoc, Cradle of the Sun bug

### ISSUE THREAD

**Issue by DJKoVid** [magefree/mage#6584] opened 2020-05-28 16:04 UTC
1. Itlimoc, Cradle of the Sun doesn't tap for # creatures, it just taps for one. 
2. Emrakul, the Promised End can't access the opponents hand.

Thank you.

**Comment by jeffwadsworth** [comment] 2020-06-09 13:40
![WorksFine](https://user-images.githubusercontent.com/1496996/84154539-dbbb7580-aa2c-11ea-9682-a2dcb1c07766.jpg)

**Comment by DJKoVid** [comment] 2020-06-09 13:42
Thank you!

**Comment by jeffwadsworth** [comment] 2020-06-09 13:45
The target opponent's turn control ability works for me as well.
![WorksFine](https://user-images.githubusercontent.com/1496996/84155143-9a779580-aa2d-11ea-8a4e-07b3c3baa0d2.jpg)

**Comment by jeffwadsworth** [comment] 2020-06-09 13:47
![WorksFine](https://user-images.githubusercontent.com/1496996/84155342-dad71380-aa2d-11ea-9d38-dc976988e9ad.jpg)

**Comment by jeffwadsworth** [comment] 2020-06-09 13:48
I played the Swamp for the opponent, etc.

**Comment by DJKoVid** [comment] 2020-06-15 15:28
It still just taps for 1. am i missing an update?

**Comment by Zerrisx** [comment] 2020-06-26 01:21
Emrakul issue is a duplicate of #2088, and the Cradle issue is fixed.

**Closed by Zerrisx** 2020-06-26 01:21 UTC
Labels: not confirmed
