### ISSUE TITLE
Clone on Jeleva does not exile cards on ETB

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#3477] opened 2017-06-07 04:23 UTC
When casting Clone and having it ETB as Jeleva, Nephalia's Scourge, the Clone won't exile cards. It should be looking at how much mana was spent to cast Clone.

-- from forums

**Comment by Zerrisx** [comment] 2020-06-28 00:05
Clone works - *if you keep the Clone for the legendary rule*.  If you let it die, then it doesn't.  But that sounds like a duplicate of #3476, not anything new.

**Comment by Zerrisx** [comment] 2020-06-28 00:05
Duplicate of #3476

**Closed by Zerrisx** 2020-06-28 00:05 UTC
Labels: bug
