### ISSUE TITLE
Multiple new perspective bug

### ISSUE THREAD

**Issue by sl1** [magefree/mage#3213] opened 2017-04-22 21:29 UTC
if you have 2 new perspectives in play and more than 7 cards in hand Xmage get stuck asking which replacement effect to resolve first.

**Comment by drmDev** [comment] 2017-04-26 01:14
tested this out and though it's a little clunky and seems to unnecessarily ask which replacement effect to occur 3 times total, it never got stuck in a loop. Can also pick the "auto select" button for this card since it really does not matter.

From my testing, there is a minor bug - it asks you more than needed for which replacement effect to use.

**Comment by drmDev** [comment] 2017-05-11 18:43
was able to reproduce issue in  #3323

**Comment by drmDev** [comment] 2017-05-11 18:44
will make #3323 the parent issue for this and close this one out.

**Closed by drmDev** 2017-05-11 18:44 UTC
Labels: AKH, bug, enhancement, GUI Handling
