### ISSUE TITLE
Undying ability returning the card to controller's hand instead of owner

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#2148] opened 2016-08-05 02:59 UTC
From reddit post:

"I played a game of commander with [[Ezuri, Claw of Progress]] as my commander and a [[Simic Manipulator]] out with a lot of counters on him. One of my opponents had a [[Vorapede]] out.

I stole the Vorapede using Simic Manipulator and shortly after someone played [[Wrath of God]]. Instead of returning to my opponent's board, Vorapede came back under my control.

The rules text for Undying states that it should return under its owner's control, not its controller's.
"

**Comment by drmDev** [comment] 2016-08-06 01:55
added test confirming bug. Act of Treason was cast on Vorapede. Vorapede was killed by the original owner. Vorapede returns with undying under the control of the caster of Act of Treason instead of its original owner.

**Comment by LevelX2** [comment] 2016-08-06 17:21
The test asserted the wrong player. After chnaging this, not bug confirmation so far.

**Comment by drmDev** [comment] 2016-08-06 21:50
Sorry about that, I'll need to take more time to double check the test is
written correctly.

**Comment by goesta** [comment] 2017-02-28 21:02
I'll close this issue because it was not confirmed by the test.

**Closed by goesta** 2017-02-28 21:02 UTC
Labels: bug, Not confirmed
