### ISSUE TITLE
Denry Kiln still multiplying counters

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10454] opened 2023-06-10 04:41 UTC
As per the picture - AI played [[Denry Kiln, Editor in Chief]].  Entered with 4 counters for some odd reason, then added 4 more counters.

![image](https://github.com/magefree/mage/assets/82664393/7b206bc0-0953-455b-8f0a-0b86e170eb78)

**Comment by Grath** [comment] 2023-06-10 04:56
Duplicate of #9779

**Closed by Grath** 2023-06-10 04:56 UTC
