### ISSUE TITLE
Make cards that let you choose a creature type display only types from your deck

### ISSUE THREAD

**Issue by Svyatoslav28597** [magefree/mage#12577] opened 2024-07-13 15:27 UTC
Currently cards that let you choose a creature type (Herald's horn, Cavern of Souls) show you a list of all possible types.
I propose showing only those that are present in deck/sideboard on your cards, commanders and companions at the start of the game, since other types won't matter and this would simplify searching for a needed one.

**Comment by JayDi85** [comment] 2024-07-13 16:58
Duplicate of #8478

**Closed by JayDi85** 2024-07-13 16:58 UTC
