### ISSUE TITLE
Ability to close or forever minimize Exile / Suspend windows

### ISSUE THREAD

**Issue by drmDev** [magefree/mage#1803] opened 2016-04-07 03:42 UTC
From reddit post:
https://www.reddit.com/r/XMage/comments/4dnkeg/ways_to_permanently_close_the_exile_window/

"As per the title. Is there a way to close the Exile and Suspend windows that popup the moment something is sent to the Exile Zone? The windows can be minimized but not closed, so after a while almost half of my play area is taken up by minimized window bars. It's [annoying] considering there's an Exile Zone button on the player card."

---

(from XMage forum)
"Interacting with the graveyard or exile feels still clunky and awkward. We need a way to keep them open somehow without taking too much screen space and blocking interaction with other elements of the battlefield."

**Comment by JayDi85** [comment] 2017-11-24 15:08
Duplicate of #1115

**Closed by JayDi85** 2017-11-24 15:08 UTC
Labels: enhancement
