### ISSUE TITLE
Something is wrong with "Ponder"

### ISSUE THREAD

**Issue by frbattid** [magefree/mage#1408] opened 2015-12-05 22:07 UTC
I've experience this behaviour twice today:

1. I cast "Ponder".
2. I pay the mana and pass the priority.
3. The app shows me the top 3 cards, but the typical message encouraging you to put a card, then other one etc does not appear.
4. Nevertheless, it seems the cards can be put on top of the library.
5. Then the user is asked to suffle or not, and once answered the buttons disappear but the quesion remains forever.

**Comment by LevelX2** [comment] 2015-12-06 09:57
Can't reproduce this. Was it on a public server?
Any error messages in the client console?

**Comment by frbattid** [comment] 2015-12-06 16:03
This happened at xmage.de, 1.4.5v0 both client and server.

**Comment by hanasu** [comment] 2015-12-31 15:45
Closing, can be reopened if problem persists.

**Closed by hanasu** 2015-12-31 15:45 UTC
