### ISSUE TITLE
General error - ClassCastException

### ISSUE THREAD

**Issue by wadewils0n** [magefree/mage#12984] opened 2024-10-09 23:53 UTC
Error type: General error - ClassCastException
Client version: 1.4.54-V3 (build: 2024-09-25 12:58)

mage.view.CardView cannot be cast to mage.view.PermanentView

Stack trace:
org.mage.card.arcane.CardPanel.getOriginalPermanent(CardPanel.java:838)
mage.client.game.BattlefieldPanel.update(BattlefieldPanel.java:185)
mage.client.game.PlayAreaPanel.update(PlayAreaPanel.java:515)
mage.client.game.GamePanel.updateGame(GamePanel.java:1164)
mage.client.game.GamePanel.updateGame(GamePanel.java:1065)
mage.client.game.GamePanel.select(GamePanel.java:2069)
mage.client.remote.CallbackClientImpl.lambda$onCallback$2(CallbackClientImpl.java:302)
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
java.awt.EventQueue.access$500(EventQueue.java:97)
and other 11 lines

**Comment by xenohedron** [comment] 2024-10-11 23:25
duplicate of #12524

**Closed by xenohedron** 2024-10-11 23:25 UTC
