### ISSUE TITLE
Continuous effects do not discards after player left the game

### ISSUE THREAD

**Issue by JayDi85** [magefree/mage#5544] opened 2019-01-22 11:44 UTC
From discord, Stayfrosty310:
> When ever an opponent has an effect that applies to the board, such as stony silence, and they leave before the game is over with a d/c or a concession, the effects still continue. Ive only had it happen to enchanments so far.

**Comment by zeflap** [comment] 2019-02-04 00:51
Yeah, sounds like a case of "player's gone but board persists"
Easily spotted by the scrollbar that appears for such a player.

**Comment by Zerrisx** [comment] 2020-07-01 21:58
Duplicate of #4472

**Closed by Zerrisx** 2020-07-01 21:58 UTC
Labels: bug
