### ISSUE TITLE
Treasures and Clues go to the graveyard at end of turn when animated with The Antiquities War

### ISSUE THREAD

**Issue by theelk801** [magefree/mage#4899] opened 2018-05-05 01:47 UTC
This also happens with Tezzeret the Seeker's final ability.

**Comment by LevelX2** [comment] 2018-05-06 22:50
Probably fixed with this commit: bb15176a84f9790e8c450f7e9a686ef357e0214a
Maybe someone can check.

**Comment by Zerrisx** [comment] 2020-07-07 20:53
Cannot reproduce; this appears to be fixed.

**Closed by Zerrisx** 2020-07-07 20:53 UTC
Labels: bug
