### ISSUE TITLE
Of One Mind cost reduction ability does not effect castability calculation

### ISSUE THREAD

**Issue by soggypretzels** [magefree/mage#6717] opened 2020-06-24 20:01 UTC
Even if you meet the cost reduction requirement of controlling both a human and non-human creature, you can only cast Of One Mind if you have access to 3 mana. Once go to cast the spell, the mana cost is correctly calculated (costing just {U} if you meet the requirement), but this cost reduction does not factor into the calculation of if you can cast the spell.

Steps to reproduce:

1. Control a human and a non-human creature and 1 island
2. Have Of One Mind in hand
3. Try to cast Of One Mind

**Comment by Zerrisx** [comment] 2020-06-24 20:05
Duplicate of #6698

**Comment by JayDi85** [comment] 2020-06-27 01:47
Was fixed by a871b36bca46d5b259ee8815649954ada7a9b008

**Closed by JayDi85** 2020-06-27 01:47 UTC
