### ISSUE TITLE
Launch Client opens console, but nothing more

### ISSUE THREAD

**Issue by garythelobster** [magefree/mage#1088] opened 2015-07-05 09:35 UTC
It tells me I'm updated and everything but when I launch the client it simply opens the console and it stays blank

**Comment by derwerkself** [comment] 2015-07-05 15:46
For me it says "Could not find or load main class mage.client.MageFrame" in client console and "Could not find or load main class mage.server.Main" in server console
Already forced update, no improvement.

**Comment by Gatherix** [comment] 2015-07-05 17:18
Same error as derwerkself, began after updating

**Comment by LevelX2** [comment] 2015-07-05 18:34
I found this:
viewtopic.php?f=70&t=16358&p=169586&hilit=mage.client.MageFrame#p169579

**Comment by garythelobster** [comment] 2015-07-05 19:28
Tried that, doesn't work for me, same problem persists

**Comment by garythelobster** [comment] 2015-07-05 19:29
Also there is nothing in my xmage folder, if that helps

**Comment by LevelX2** [comment] 2015-07-05 19:50
Operating system?
Some mac OS users had problems in the past. There is a XMage home  
http://xmage.de/xmage_mac
that you can set in the launcher settings.
That uses still an old launcher version that seemed to work on macs.

**Comment by Gatherix** [comment] 2015-07-05 19:54
Deleting the installed.properties file had no effect. As far as I know, the launcher didn't change when this problem started; only started when I tried to update xMage to 1.4.2. Tried redownloading launcher. My xmage folder is populated, unlike garythelobster. Running Linux, Debian.

**Comment by garythelobster** [comment] 2015-07-05 19:57
Using Windows 7 64 bit so OS probably isn't a problem. Anyone know of any links to old versions of the launcher?

**Comment by LevelX2** [comment] 2015-07-05 20:19
You can set the xmage home in the launcher to:
http://xmage.de/xmagelauncher31
to get the old launcher and the current xmage release.

**Comment by Gatherix** [comment] 2015-07-05 20:50
Problem persists.

**Comment by garythelobster** [comment] 2015-07-06 00:23
Yep, still does the exact same thing for me

**Comment by LevelX2** [comment] 2015-07-06 07:48
I can imagine 2 possible reasons now:
1) Windows Firewall blocking (check in the setting of windows firewall that "Java(TM) Platform SE binary" is allowed to cross the firewall).
2) Problem with the file path you located the launcher.jar. Maybe it can help to use another directory, best with no blanks or special chars in the complete path.

**Comment by garythelobster** [comment] 2015-07-06 09:13
The firewall is what it was. Thank you very much!

**Comment by Gatherix** [comment] 2015-07-06 18:11
Firewall and path proved unrelated, however update to 1.4.2v1 from 1.4.2v0 fixed the problem. Thank you for the support.

**Comment by derwerkself** [comment] 2015-07-06 18:16
I can confirm that after updating to 1.4.2.v1 everything works fine again. Launcher "updated" itself to v0.3.1.
Thanks for the effort.

**Comment by LevelX2** [comment] 2015-07-06 18:28
> I can confirm that after updating to 1.4.2.v1 everything works fine again. Launcher "updated" itself to v0.3.1.

You're using a mac?
And the default launcher did not work?

**Comment by darkyndy** [comment] 2015-08-09 05:56
Using Windows 8.1 (64 bit).
Initially when running client nothing happened, checking logs:
~~~
ERROR 2015-08-08 19:04:27,072 Error staring process                                                                      =>[AWT-EventQueue-0] Utilities.launchProcess
java.io.IOException: Cannot run program "D:\java\jre1.7.0_75\bin\java" (in directory "D:\xmage\mage-client"): CreateProcess error=267, The directory name is invalid
	at java.lang.ProcessBuilder.start(Unknown Source)
	at com.xmage.launcher.Utilities.launchProcess(Utilities.java:142)
	at com.xmage.launcher.Utilities.launchClientProcess(Utilities.java:101)
	at com.xmage.launcher.XMageLauncher.handleClient(XMageLauncher.java:380)
	at com.xmage.launcher.XMageLauncher.access$300(XMageLauncher.java:58)
	at com.xmage.launcher.XMageLauncher$4.actionPerformed(XMageLauncher.java:223)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=267, The directory name is invalid
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 43 more

~~~
I created "mage-client" folder inside xmage folder, but now the error is:  "Error: Could not find or load main class mage.client.MageFrame".

Now I suppose maybe is something related to Java, doing java -version in console I get:
~~~
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
~~~
as this program requires other version maybe is something there...

I don't know, some help is appreciated.

**Comment by LevelX2** [comment] 2015-08-09 06:47
There was also for some people a problem with the launcher 34.
Please try if it helps to use the old launcher 31.

To test this you can switch the xmage home in the launcher settings to 
http://xmage.de/xmagelauncher31
update the launcher and reinstall java with the launcher if needed.

**Comment by darkyndy** [comment] 2015-08-09 11:50
I don't know if I did what is need, if you can be my explicit.

Exactly what I did:
- download launcher from http://xmage.de/xmage/XMageLauncher-0.3.1.jar
- edited from installed.properties part:
~~~
xmage.home=http\://xmage.de/xmagelauncher31
~~~
complete file after install:
~~~
#---XMage Properties---
#Sun Aug 09 14:36:25 EEST 2015
xmage.launcher.version=0.3.1
java.version=1.7.0_75
xmage.client.console=true
xmage.client.javaopts=-Xms256m -Xmx512m -XX\:MaxPermSize\=384m -XX\:+UseConcMarkSweepGC -XX\:+CMSClassUnloadingEnabled
xmage.home=http\://xmage.de/xmagelauncher31
xmage.version=1.4.3v0 (2015-08-06)
xmage.server.console=true
xmage.server.javaopts=-Xms256M -Xmx1G -XX\:MaxPermSize\=384m
xmage.torrent.uprate=50
xmage.torrent.downrate=0
xmage.torrent.use=false
~~~

Now log file is:
~~~
ERROR 2015-08-09 14:34:08,450 Invalid config from http://xmage.info/xmage/config.json                                    =>[AWT-EventQueue-0] XMageLauncher.getConfig
org.json.JSONException: A JSONObject text must begin with '{' at character 1
	at org.json.JSONTokener.syntaxError(JSONTokener.java:410)
	at org.json.JSONObject.<init>(JSONObject.java:179)
	at org.json.JSONObject.<init>(JSONObject.java:402)
	at com.xmage.launcher.Utilities.readJsonFromUrl(Utilities.java:83)
	at com.xmage.launcher.XMageLauncher.getConfig(XMageLauncher.java:492)
	at com.xmage.launcher.XMageLauncher.access$1000(XMageLauncher.java:58)
	at com.xmage.launcher.XMageLauncher$14.run(XMageLauncher.java:474)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
ERROR 2015-08-09 14:38:18,659 Error staring process                                                                      =>[AWT-EventQueue-0] Utilities.launchProcess
java.io.IOException: Cannot run program "D:\java\jre1.7.0_75\bin\java" (in directory "D:\xmage\mage-client"): CreateProcess error=267, The directory name is invalid
	at java.lang.ProcessBuilder.start(Unknown Source)
	at com.xmage.launcher.Utilities.launchProcess(Utilities.java:142)
	at com.xmage.launcher.Utilities.launchClientProcess(Utilities.java:101)
	at com.xmage.launcher.XMageLauncher.handleClient(XMageLauncher.java:380)
	at com.xmage.launcher.XMageLauncher.access$300(XMageLauncher.java:58)
	at com.xmage.launcher.XMageLauncher$4.actionPerformed(XMageLauncher.java:223)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=267, The directory name is invalid
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 43 more
ERROR 2015-08-09 14:49:32,059 Error staring process                                                                      =>[AWT-EventQueue-0] Utilities.launchProcess
java.io.IOException: Cannot run program "D:\java\jre1.7.0_75\bin\java" (in directory "D:\xmage\mage-client"): CreateProcess error=267, The directory name is invalid
	at java.lang.ProcessBuilder.start(Unknown Source)
	at com.xmage.launcher.Utilities.launchProcess(Utilities.java:142)
	at com.xmage.launcher.Utilities.launchClientProcess(Utilities.java:101)
	at com.xmage.launcher.XMageLauncher.handleClient(XMageLauncher.java:380)
	at com.xmage.launcher.XMageLauncher.access$300(XMageLauncher.java:58)
	at com.xmage.launcher.XMageLauncher$4.actionPerformed(XMageLauncher.java:223)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=267, The directory name is invalid
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 43 more

~~~

and yes, still nothing works,

**Comment by goesta** [comment] 2017-02-28 21:27
I'll close this issue because it seems to be outdated but feel free to create a new one if this problem still exists.

**Closed by goesta** 2017-02-28 21:27 UTC
Labels: Launcher / Installation

**Comment by jeffwadsworth** [comment] 2018-01-12 17:36
Specify this for the Mage Client Main Class:
mage.client.MageFrame
Sometimes, it doesn't automatically find it.
