### ISSUE TITLE
Protection from color looks at color identity

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#7987] opened 2021-07-08 01:02 UTC
![image](https://user-images.githubusercontent.com/11657716/124846395-8f9f7500-df4d-11eb-8ffe-8c3602e75867.png)

I can't block with Jadzi, even though she's blue and [[Sword of Feast and Famine]] only gives protection from green and black.

**Comment by Alex-Vasile** [comment] 2022-09-27 18:47
Closing as duplicate of #7983

**Closed by Alex-Vasile** 2022-09-27 18:47 UTC
