### ISSUE TITLE
Problem with Kroxa, autmated targeting and 1 card in hand.

### ISSUE THREAD

**Issue by Vuuyi** [magefree/mage#9261] opened 2022-07-12 20:24 UTC
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.51-V4-beta7 (build: 2022-07-09 15:21)
mage.target.TargetImpl.tryToAutoChoose(TargetImpl.java:665)
mage.player.human.HumanPlayer.choose(HumanPlayer.java:730)
mage.cards.k.KroxaTitanOfDeathsHungerDiscardEffect.lambda$apply$0(KroxaTitanOfDeathsHunger.java:121)
java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.forEachOrdered(ReferencePipeline.java:423)
mage.cards.k.KroxaTitanOfDeathsHungerDiscardEffect.apply(KroxaTitanOfDeathsHunger.java:116)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:201)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:185)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:149)
mage.game.stack.StackAbility.resolve(StackAbility.java:89)
mage.game.GameImpl.resolve(GameImpl.java:1618)
mage.game.GameImpl.playPriority(GameImpl.java:1544)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1042)
mage.game.GameImpl.play(GameImpl.java:952)
mage.game.GameImpl.start(GameImpl.java:928)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by Alex-Vasile** [comment] 2022-07-12 20:29
Duplicate of https://github.com/magefree/mage/issues/9248. Already solved for next beta.

Until next beta. Either :

Disable auto-choosing
Change auto-choose level to "All"

**Closed by Alex-Vasile** 2022-07-12 20:29 UTC
