### ISSUE TITLE
Hangerback Walker not producing tokens when sacked to Daretti, Scrap Savant

### ISSUE THREAD

**Issue by tylerFretz** [magefree/mage#7737] opened 2021-04-11 17:35 UTC
Hangerback Walker with three counters on it produced no thopter tokens when sacked to Daretti's -2.

![xmage-bug-dareti](https://user-images.githubusercontent.com/47012039/114314924-b2df9300-9aca-11eb-945a-cb7a20934ab7.png)

**Comment by ldeluigi** [comment] 2021-04-16 08:16
[[Hangerback Walker]] [[Daretti]]

**Comment by ldeluigi** [comment] 2021-04-16 08:20
[[Hangarback Walker]]

**Comment by Alex-Vasile** [comment] 2022-09-28 04:13
Duplicate of #8481

**Closed by Alex-Vasile** 2022-09-28 04:13 UTC
