### ISSUE TITLE
Damage Prevention Bug with Harm's Way (and possibly similar cards)

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#6100] opened 2019-12-17 21:24 UTC
I had two 3/1 creatures out, and my opponent cast Pyroclasm. I responded by casting Harm's Way targeting my opponent for the damage redirect. XMage prompted me correctly for choice of redirect target and damage source, but I never got a chance to pick which creature I wanted to "save" with the damage prevention. It appeared the client just "saved" the leftmost creature on the screen, the one that entered the battlefield first. Whereas I wanted to save the other creature.

I asked chat.magicjudges.org and multiple judges agreed that I should have been able to choose to save the other creature if I wanted to. So the XMage operation seems to be bugged.

**Comment by jeffwadsworth** [comment] 2019-12-17 22:00
Rule:
If the chosen source would simultaneously deal damage to multiple permanents you control (like Pyroclasm could) or to you and at least one permanent you control (like Earthquake could), Harm’s Way will redirect just 2 of that damage. It won’t redirect the next 2 damage that would be dealt to each recipient. You choose which 2 damage is redirected. If you like, you can choose to redirect 1 damage that would be dealt by the chosen source to each of two different recipients.

**Comment by duelcastermage** [comment] 2019-12-17 22:55
I realize that Harm's Way won't prevent two to each creature, but I never even got to choose which creature to prevent the 2 damage to.

**Comment by Zerrisx** [comment] 2020-07-15 18:15
Duplicate of #437

**Closed by Zerrisx** 2020-07-15 18:15 UTC
Labels: bug
