### ISSUE TITLE
Jace, Telepath Unbound won't let me cast split cards in GY for their chosen cost

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#10272] opened 2023-04-25 03:44 UTC
With the flipside planeswalker of [[Jace, Vryn's Prodigy]] (Jace, Telepath Unbound), I -3'd and targeted [[Fire // Ice]] in my graveyard with two mana open. I never got to cast either half of the card; I think XMage assumed its mana value was 4 and I couldn't cast anything(?)

**Comment by xenohedron** [comment] 2023-09-30 21:55
duplicate of #9607

**Closed by xenohedron** 2023-09-30 21:55 UTC
