### ISSUE TITLE
Trinisphere forces to pay {3} per half for a fused spell

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#2242] opened 2016-09-09 19:24 UTC
Wear // Tear should only cost {1}{R}{W}, but you are asked to pay {2}{R}{2}{W}.

(From reddit post)

**Comment by thechucklingatom** [comment] 2016-09-09 21:38
It does a similar thing with splice spells. Thorn is broken for splice as well, so I wouldn't be surprised if fuse has the same issue.

**Comment by Dilnu** [comment] 2016-09-09 23:48
Interesting, I'll investigate a bit, I'm not sure how easy it will be to fix at this point though.

**Comment by Dilnu** [comment] 2016-09-10 01:31
Well, that is a lot harder than I expected.

**Comment by thechucklingatom** [comment] 2016-09-10 15:10
so bear with me, but could it  be 
`@Override
    public boolean apply(Game game, Ability source, Ability abilityToModify) {
        int manaCost = abilityToModify.getManaCostsToPay().convertedManaCost();
        if(manaCost < 3){
            CardUtil.increaseCost(abilityToModify, 3 - manaCost);
        }
        return true;
    }`
not checking the type of the ability, so fuse and splice are getting increased because its trying to modify the ability?

**Comment by Dilnu** [comment] 2016-09-10 15:42
Honestly I tried to dig into it last night and I have no guesses as to why the code functions as it does.

**Comment by stravant** [comment] 2016-09-11 00:05
After taking a look at it, a TL;DR of the issue for anyone tackling it in the future: The core of the problem is that right now cost modification is applied to each SpellAbility separately when a spell is cast.... but the way that Fuse is implemented is by casting a Spell which has two different SpellAbilities, one for each half. So naturally the cost modification is applied to each half separately. Same problem for Splice onto Arcane (It also adds multiple SpellAbilities)

The most obvious way to fix the issue would be to change cost modification to apply to a given spell as a whole, rather than each SpellAbility... but that would be a significant change to the spell casting process.

The real solution would be to break up the activate method on abilities into separate pieces, and have the spell casting process call each piece individually, so that casting a spell with multiple SpellAbilities for instance, first calls all of the mode selections, then all of the target selections, then etc... rather than first calling the whole process for one SpellAbility and then the whole process for the next, etc.

**Comment by JayDi85** [comment] 2020-06-10 06:03
Fixed via b38ac2f575c3da161f98ac3fdc2048c9fc446169

**Closed by JayDi85** 2020-06-10 06:03 UTC
Labels: bug
