### ISSUE TITLE
K'rrik, Son of Yawgmoth bug

### ISSUE THREAD

**Issue by davidofthefunk** [magefree/mage#6696] opened 2020-06-21 23:26 UTC
So me and some friends were playing commander, and discovered that while K'rrik is on the battlefield, you can only use his ability to pay life instead of black mana if you already have enough mana open (via lands, etc.) to play the card normally.

**Comment by Zerrisx** [comment] 2020-06-22 02:57
Duplicate of #6698

**Comment by Zerrisx** [comment] 2020-08-03 18:37
Fixed by 244cf2a

**Closed by Zerrisx** 2020-08-03 18:37 UTC
Labels: bug
