### ISSUE TITLE
Fix "Mindslaver" like effects

### ISSUE THREAD

**Issue by Iwasrunningoutofnamesatthispoint** [magefree/mage#4687] opened 2018-03-30 14:50 UTC
I played a game where I was targeting a player with worst fears.
Another player flashed in dualcaster mage and did cast a copy of worst fears onto the same player.
His copy resolved first, then came mine.

The dualcaster player was able to get the other players turn, not me, eventhough my spell resolved after his.

The gatherer ruling on this is:

26.04.2014 | Multiple  player-controlling effects that affect the same player overwrite each  other. The last one to be created is the one that works.
-- | --

**Comment by Zerrisx** [comment] 2020-07-07 18:33
Duplicate of #2008

**Closed by Zerrisx** 2020-07-07 18:33 UTC
Labels: cards
