### ISSUE TITLE
Emrakul extra turn bug

### ISSUE THREAD

**Issue by albuzs** [magefree/mage#2168] opened 2016-08-15 19:51 UTC
Hello,

If you roll back once or twice during your opponent's controlled turn, the opponent will not get an extra turn for some reason. Has this been reported already?

**Comment by drmDev** [comment] 2016-08-15 19:57
There are many bugs related to the rollback feature. I'll find the parent
issue for that and add this information to it. This isn't a bug specific to
Emrakul.

**Comment by Zerrisx** [comment] 2020-06-26 01:10
Duplicate of #2088

**Closed by Zerrisx** 2020-06-26 01:10 UTC
Labels: bug
