### ISSUE TITLE
Hurl through Hell doesn't exile creatue.

### ISSUE THREAD

**Issue by AsterAether** [magefree/mage#8211] opened 2021-09-04 15:46 UTC
Hurl through Hell didn't exile the Gilded Drake, even though it resolved and showed the extra window for it.
![Unbenannt](https://user-images.githubusercontent.com/6317713/132100325-8b05b018-4a3a-411d-ba40-e0a6300631ea.PNG)

**Comment by jeffwadsworth** [comment] 2021-09-04 19:01
[[Hurl through Hell]]

**Comment by jeffwadsworth** [comment] 2021-09-04 19:08
This looks like a weird GUI issue.  Perhaps JayDi can figure it out.

**Comment by alexander-novo** [comment] 2021-09-05 01:14
I can confirm it is just a visual issue.

**Comment by JayDi85** [comment] 2021-09-05 09:31
It's not a visual bug. Game exiled a card, but not a permanent itself, so it was real. Fixed in e2098221909949c0ae6eabee1262df9491bbfe6c

**Closed by JayDi85** 2021-09-05 09:31 UTC
Labels: bug
