### ISSUE TITLE
Card image live fetch

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#11045] opened 2023-08-27 01:49 UTC
Someone on discord suggested this. Have a setting which auto-downloads card images as you see them in the deck editor or while you're playing a game. This would reduce the impact that downloading the entire image set has (many players get temp banned from scryfall for trying to download all of the images too quickly) and would also help when new sets come out - you won't have to check the images tab every update.

**Comment by xenohedron** [comment] 2023-09-30 22:37
duplicate of #4160

**Closed** 2023-09-30 22:38 UTC
Labels: enhancement, download
