### ISSUE TITLE
Mila, Crafty Companion token in Momir has Luka, Wayward Bonder's abilities

### ISSUE THREAD

**Issue by Taylor3621** [magefree/mage#9639] opened 2022-10-10 07:26 UTC
Pretty self explanatory. I was playing Momir Basic, and somehow, the token of [[Mila, Crafty Companion]] had [[Luka, Wayward Bonder]]'s loyalty abilities, which could be activated.

![image](https://user-images.githubusercontent.com/107843203/194816400-2b8468df-44c3-41d5-ace4-82c58bd739e6.png)

**Comment by awjackson** [comment] 2022-10-10 14:13
Duplicate of #8476

**Closed** 2022-10-10 15:22 UTC
Labels: bug, duplicate
