### ISSUE TITLE
Tenacious Underdog Still Gaining Multiple Blitz Draw Triggers

### ISSUE THREAD

**Issue by JelloPiranha** [magefree/mage#10457] opened 2023-06-11 16:35 UTC
Tenacious Underdog should lose its "When this creature dies, draw a card" ability when it dies, but it instead accumulates an additional instance of this ability every time you cast it for its Blitz cost leading to multiple draw triggers on every death. https://github.com/magefree/mage/issues/8885 references this issue, and https://github.com/magefree/mage/pull/9775 allegedly fixes it, but this bug still occurs as of build: 2023-06-09 03:03.

**Comment by PurpleCrowbar** [comment] 2023-06-11 17:22
Duplicate of #8885

**Closed by PurpleCrowbar** 2023-06-11 17:22 UTC
