### ISSUE TITLE
 Halvar god of battle Null Pointer Exception error

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#11797] opened 2024-02-16 04:39 UTC
When trying to move a aura to a token this happens. [[Halvar god of battle]]

![image](https://github.com/magefree/mage/assets/64045003/766ceec9-3421-49ce-8255-ad2a2ec4e0a5)

Game error occurred: 

java.lang.NullPointerException
Server version: 1.4.52-V7-beta7 (build: 2024-01-30 18:53)
Stack trace:
mage.cards.h.HalvarGodOfBattleEffect.apply(HalvarGodOfBattle.java:131)
mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:192)
mage.abilities.AbilityImpl.resolve(AbilityImpl.java:176)
mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:172)
mage.game.stack.StackAbility.resolve(StackAbility.java:84)
mage.game.GameImpl.resolve(GameImpl.java:1751)
mage.game.GameImpl.playPriority(GameImpl.java:1671)
mage.game.turn.Step.priority(Step.java:67)
mage.game.turn.Phase.playStep(Phase.java:204)
mage.game.turn.Phase.play(Phase.java:90)
mage.game.turn.Turn.play(Turn.java:137)
mage.game.GameImpl.playTurn(GameImpl.java:1117)
mage.game.GameImpl.play(GameImpl.java:1024)
mage.game.GameImpl.start(GameImpl.java:1000)
mage.server.game.GameWorker.call(GameWorker.java:34)
mage.server.game.GameWorker.call(GameWorker.java:15)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by xenohedron** [comment] 2024-03-23 06:14
This line trying to get the spell ability is suspicious:

```java
Target auraTarget = attachment.getSpellAbility().getTargets().get(0);
```

![image](https://github.com/magefree/mage/assets/12538125/21648c22-6386-42c3-94c4-a82a8d100aba)

Root cause would then be blind groping for aura target, related to #9583. (But I haven't tried to reproduce, so this is just speculation.)

**Comment by xenohedron** [comment] 2024-03-23 06:24
Ah, duplicate of #11328

**Closed by xenohedron** 2024-03-23 06:24 UTC
Labels: bug
