### ISSUE TITLE
Xmage UI tables/deck editor "click-through" bug

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4181] opened 2017-11-18 18:47 UTC
This is probably already a notorious quirk, but for the sake of clarity I'm posting it here anyways. Whenever I login and open the "Tables" tab, and then open "Deck Editor" afterwards, the buttons from the Tables tab (such as Create new match) are still clickable at the same spots as they would appear on the original tab (although graphically they're invisible), despite the fact that the Deck Editor tab should've covered them up both graphically and functionally.

Something similar happens when opening Deck Editor over a running game - you get tooltips popping up of cards from the game when you point the cursor over the spot the card is placed on - strangely this doesn't happen on the entire Deck Editor screen, but I see it most commonly in the top left portion (most likely since that spot is commonly occupied by opponent cards in both single and multiplayer, and Deck Editor has a lot of commonly used buttons there).

**Comment by JayDi85** [comment] 2017-11-27 18:10
Deck editor window do not hide all other like tables list window do:

![shot_171127_220843](https://user-images.githubusercontent.com/8344157/33281703-923238fe-d3bf-11e7-820f-280ceb2c3cea.png)

**Comment by Zerrisx** [comment] 2020-07-01 18:24
Duplicate of #3296

**Closed by Zerrisx** 2020-07-01 18:24 UTC
Labels: GUI, bug
