### ISSUE TITLE
Choosing the order to resolve of two replacement effects of Coldsteel Heart should work automatically

### ISSUE THREAD

**Issue by LevelX2** [magefree/mage#1548] opened 2016-02-21 22:52 UTC
Choosing the order to resolve of two replacement effects of Coldsteel Heart should work automatically

![coldsteelheart](https://cloud.githubusercontent.com/assets/2066790/13206015/089b0082-d8f6-11e5-8a7a-48cdbc19e369.jpg)

**Comment by emerald000** [comment] 2016-02-21 23:09
Technically, you have to choose the order you apply the replacement effects, since they are not a special case (616.1a-c).

**Comment by Zerrisx** [comment] 2020-07-17 17:42
Duplicate of #6676

**Closed by Zerrisx** 2020-07-17 17:42 UTC
Labels: enhancement, refactoring
