### ISSUE TITLE
yawgmoths will.

### ISSUE THREAD

**Issue by ignitaxiom** [magefree/mage#7490] opened 2021-02-03 02:57 UTC
i cast yawgmoths will, cast a card from my graveyard and my entire hand and gy get exiled.

**Comment by weirddan455** [comment] 2021-02-05 18:23
Not able to reproduce this.  Need more information about what was on the battlefield and what you were trying to cast.

**Comment by copperfield42** [comment] 2021-02-05 19:55
it might be related to #6738

**Comment by JayDi85** [comment] 2021-08-11 20:13
Cards disappear can be fixed in #6738

**Closed by JayDi85** 2021-08-11 20:13 UTC
Labels: not confirmed
