### ISSUE TITLE
A couple of bugs - DR Jublemorph, Baron von Count, Dire Fleet Daredevil and Lightning Storm

### ISSUE THREAD

**Issue by Iwasrunningoutofnamesatthispoint** [magefree/mage#4371] opened 2018-01-08 12:55 UTC
Here are a couple of bugs I came across:
Dr Julius Jumblemorph: When cast with the mana of Path of Ancestry you wont get the Srcy trigger
Baron von Count: When his Doom Counter moving trigger is on the stack, and he gets removed before it resolves the game will bug out and give an error message.
Dire Fleet Daredevil: He doesnt let you spent mana from your mana pool as if it was any color.
Lightning Storm: You can click the Triggers that are made by discarding lands to add multiple charge counters for free without having to discard anything.

And did you guys already fix the bug that permanets dont leave the battlefield if a player leaves a Commander Match?

PS: I would love to see some more Unstable cards before the 15th ;)

**Comment by Zzooouhh** [comment] 2018-01-08 17:26
Baron Von Count should be fixed now.
Dr. Julius Jumblemorph appears to a deeper issue concerning how the game handles Changeling, most (not all) of its interactions should be working properly now (casting any other creature from Path of Ancestry will scry except from Julius himself)

**Comment by emerald000** [comment] 2018-01-09 07:43
Path of Ancestry should use MageObject.shareSubtypes() instead of implementing it from scratch. This will fix the issue with Changelings.

**Comment by Zzooouhh** [comment] 2018-01-13 13:09
shareSubtypes doesn't discriminate between creature and noncreature subtypes though - it could cause some problems for commander planeswalkers and some cards in Freeform commander (legendary equipment in CZ -> all equipments paid for with POA will scry). A simple check for changelings in POA should be easy to do.

**Comment by Zerrisx** [comment] 2020-07-01 20:13
Cannot reproduce; these all appear to be fixed.

**Closed by Zerrisx** 2020-07-01 20:13 UTC
Labels: bug, cards
