### ISSUE TITLE
Soldevi Excavations goes straight to the graveyard (sometimes)

### ISSUE THREAD

**Issue by duelcastermage** [magefree/mage#9229] opened 2022-07-05 04:01 UTC
In a limited game, I had an untapped Island and untapped Mountain. I attempted to play [[Soldevi Excavations]] from my hand, choosing to sac the untapped Island on ETB. The Excavations went straight to my graveyard. Rollbacked and tried this several times, including clicking "no", and it always had the same result.

The oddest part is, in previous games I had played the Excavations at a later point in the game and it worked fine.

**Comment by Alex-Vasile** [comment] 2022-07-10 01:18
Duplicate of #8980

**Comment by Alex-Vasile** [comment] 2022-07-14 17:33
Was this the first game of the match?

**Closed** 2022-08-27 00:56 UTC
