### ISSUE TITLE
Macro Features for loops

### ISSUE THREAD

**Issue by CommanderMasterEDH** [magefree/mage#8392] opened 2021-10-17 21:54 UTC
I think we should try again with the Macro and heres what i got

1. number of times of the action you recorded
2. you have target options if you can change them and also tell how many times per target at least
3. ask if you got a infinite

**Comment by Alex-Vasile** [comment] 2022-09-22 04:33
Duplicate of #2147

**Closed** 2022-09-22 04:33 UTC
