### ISSUE TITLE
Issue with forced blocks from Nacatl-War Pride

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2845] opened 2017-02-08 13:23 UTC
3 way cube game and this occurred.  
![image](https://cloud.githubusercontent.com/assets/16917728/22738994/e64f3894-ee5d-11e6-84ad-a9cf2931458c.png)

**Comment by drmDev** [comment] 2017-03-04 23:26
writing a few tests for this

**Comment by drmDev** [comment] 2017-03-05 00:00
Unable to confirm with simple test you can see referenced in commit above. Some mix of interactions between other cards on the battlefield causing this - fairly difficult to duplicate. Can you find an easy way to duplicate this?

**Comment by drmDev** [comment] 2017-03-05 12:44
Need more details on possible interactions going on here and what exactly occurred. 
1) What steps did you take during declare blockers? 
2) Were there cards in play that altered which creatures are able to be blocked?
3) At what point did you see this message?
4) Was the game able to continue beyond this point?
5) Do you have the game log?

The message displayed is unclear but seems to be indicating Primeval Titan was blocking one of the tokens instead of the Nacatl required to be blocked.

**Comment by drmDev** [comment] 2017-03-05 12:58
Added and updated tests in commit
4bfa956368ad9d8625e7fbdb87183f2dc3de4ac1

**Comment by spjspj** [comment] 2017-03-05 13:01
Hi @drmDev  

I had 14 creatures (Consecrated Sphinx, Oracle of Mul Daya, 8x plant tokens, Bloom Tender, Deepglow Skate, Baleful Strix, Primeval Titan)
3 untapped - Deepglow Skate, Baleful Strix, Primeval Titan

Dude attacked - with normal Nacatl War-Pride - 14 tokens tapped and attacking
Each has 'Can't be blocked by more than one creature'
Each has 'Must be blocked if able this turn'

I was blocking one with Primeval Titan, *another* one with Deepglow Skate and *another one again* with Baleful Strix

After saying 'Done' on Select blockers, the popup box ending in: "which not has to be blocked as a requirement.  Existing block removed.  It's a requirement to block Nacatl War-Pride"

509.1c The defending player checks each creature he or she controls to see whether it's affected by any requirements (effects that say a creature must block, or that it must block if some condition is met). If the number of requirements that are being obeyed is fewer than the maximum possible number of requirements that could be obeyed without disobeying any restrictions, the declaration of blockers is illegal. 

I was fulfulling 3 requirements and not breaking 3 restrictions - 
  aka restriction - 3* blocking this turn if able
  aka requirements 3* blocking with not more than 1 creature

I think this was the most number of requirements I could address in the block and I wasn't disobeying any restrictions.

**Comment by drmDev** [comment] 2017-03-05 13:42
Welp I need to RTFC! The tokens are copies and also need to be blocked by one creature if able. Not sure if I'll be able to test this in the testing framework. Will likely need to be reproduced and debugged in game.

**Comment by jeffwadsworth** [comment] 2017-03-10 22:38
I will set this insane board up but I have run quite a few tests and never had any issues after the duration fix.  With all those permanents on the battlefield, who knows.

**Comment by drmDev** [comment] 2017-03-11 20:30
If you tested it and still unable to reproduce with similar or same conditions, sure we can close this.

**Closed** 2017-03-11 20:44 UTC
Labels: bug
