### ISSUE TITLE
Bronzehide Lion causing error on return to battlefield trigger causing rollback and other issues

### ISSUE THREAD

**Issue by DarkEmber7824** [magefree/mage#7912] opened 2021-06-15 23:21 UTC
When Bronzehide Lion dies, it seems to cause a soft crash and a large error code when either selecting a creature for it to return as an aura, OR when there's no creatures to target at all. It'll softlock rollback loop, until it randomly decides to not.

**Comment by Alex-Vasile** [comment] 2022-09-28 04:03
Duplicate of #7641

**Closed by Alex-Vasile** 2022-09-28 04:03 UTC
