### ISSUE TITLE
GUI: When no image, hint text in the big image section cut off

### ISSUE THREAD

**Issue by tiera3** [magefree/mage#12687] opened 2024-08-19 23:27 UTC
![image](https://github.com/user-attachments/assets/1b87e97c-0f2d-43f4-a7f1-e5e1cdd3741b)

Also the hint popup was cut off a little, but still understandable. The hint text replacing the big blowup image was cutoff so badly that it was missing key information.

**Comment by PurpleCrowbar** [comment] 2024-08-19 23:57
Duplicate of #11827

**Closed by PurpleCrowbar** 2024-08-19 23:57 UTC
