### ISSUE TITLE
Conduit of Worlds tap ability causes error and rollback

### ISSUE THREAD

**Issue by JohnPetfield** [magefree/mage#10449] opened 2023-06-09 14:27 UTC
Use [[Conduit of Worlds]] tap ability targeting a permanent in my graveyards so that I can cast it this turn. You get a null error and the game rolls back, in the beta game I played I had more 3+ permanents in GY I wasn't able to use it on any of the cards in graveyard

**Comment by alexander-novo** [comment] 2023-06-09 18:26
It would be helpful in the future if you include the error you get by copying it and pasting it into the bug report.

**Comment by JohnPetfield** [comment] 2023-06-09 18:39
I haven't been able to get to my pc and recreate in test mode yet, the
instructions to create the issue are very clear however.

**Comment by xenohedron** [comment] 2023-06-09 19:04
It was a null pointer exception caused by a missing watcher. Already fixed in #10414

**Closed** 2023-06-09 19:04 UTC
