### ISSUE TITLE
Theros gods enter tapped under Blind Obedience, even if they don't meet the devotion threshold

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#8098] opened 2021-08-04 17:43 UTC
I don't have a picture because the game ended shortly after, but I just saw a [[Purphoros, God of the Forge]] enter tapped under [[Blind Obedience]] with only 2 devotion to red.

Relevant ruling:

> **614.12.** Some replacement effects modify how a permanent enters the battlefield. (See rules 614.1c-d.) Such effects may come from the permanent itself if they affect only that permanent (as opposed to a general subset of permanents that includes it). They may also come from other sources. To determine which replacement effects apply and how they apply, check the characteristics of the permanent as it would exist on the battlefield, taking into account replacement effects that have already modified how it enters the battlefield (see rule 616.1), continuous effects generated by the resolution of spells or abilities that changed the permanent's characteristics on the stack (see rule 400.7a), and continuous effects from the permanent's own static abilities, but ignoring continuous effects from any other source that would affect it.

Notably, this should also mean that if the devotion to the color is not enough before the god enters but will be enough when it does, it should still enter untapped.

**Comment by ElchananHaas** [comment] 2021-08-05 14:39
This is a known and long lasting bug around continuous effects on ETB also affecting [[blood moon]]. XMage would need a large rework to fix all such issues, as such it will likely not be fixed anytime soon :(

**Comment by ElchananHaas** [comment] 2021-08-05 17:19
see #4202

**Comment by Alex-Vasile** [comment] 2022-09-28 03:59
Duplicate of #3515.

**Closed by Alex-Vasile** 2022-09-28 03:59 UTC
