### ISSUE TITLE
Deck builder does not show basic lands

### ISSUE THREAD

**Issue by ascherr** [magefree/mage#678] opened 2015-01-18 00:50 UTC
I am trying to piece together a deck and the basic lands are not showing up in search results. Any ideas?

**Comment by jeffwadsworth** [comment] 2015-01-18 02:47
Which version?  Works fine for me in latest build.


On Jan 17, 2015, at 6:50 PM, "ascherr" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am trying to piece together a deck and the basic lands are not showing up in search results. Any ideas?

**Comment by ascherr** [comment] 2015-01-18 04:23
The newest version. Just had the application update it. And no lands show in search results.

**Comment by LevelX2** [comment] 2015-01-18 09:24
I also can't reproduce this problem.
Did you set a filter in the set control at the top? If yes, which one?
Can you add a sreenshot here of the deck editor while the problem occurs.

**Comment by LevelX2** [comment] 2015-02-02 10:19
I close this. If the problem still there add more information (like screenshot).

**Closed by LevelX2** 2015-02-02 10:19 UTC
Labels: Not confirmed
