### ISSUE TITLE
Enslave aura does not take control of target opponent creature when played from graveyard

### ISSUE THREAD

**Issue by foryayfan** [magefree/mage#8557] opened 2022-01-14 22:55 UTC
I am running v1.4.51-v3-beta2

Enslave is an enchantment aura that is supposed to take control of target opponent creature.
In a game recently, Enslave was brought out of a graveyard and attached to an opponent creature but the opponent retained control of that creature.

**Comment by jeffwadsworth** [comment] 2022-01-19 15:32
[[Enslave]]

**Comment by jeffwadsworth** [comment] 2022-01-19 15:33
How was it "brought out of the graveyard"?

**Comment by Alex-Vasile** [comment] 2022-05-10 03:23
I have tried this with [[Brilliant Restoration]] to bring the enchantment out of the graveyard, but it seems to be working properly. So either not confirmed, or close this?

**Closed** 2022-09-28 02:22 UTC
Labels: not confirmed
