### ISSUE TITLE
Constant Error - "Unable to connect to server. Server likely offline."

### ISSUE THREAD

**Issue by ericsvince** [magefree/mage#3004] opened 2017-03-22 01:54 UTC
I get the error "Unable to connect to server. Server is likely offline." This happened after some update some time ago and I never got it to work again. I have no idea what to do. I get this error on my laptop (which is windows 10). Xmage works fine on my desktop (windows 7). Please someone, if you have any idea, I really want to play Xmage while at school haha. I have screenshots of all the errors and log from the client console if those need to be supplied. Here's what I have tried...

- Wifi (Tried on school and home network but doesn't work on either)
- Have tried reinstalling and didn't work.
- Disabled firewall and Xmage still did not work.
- Java is up to date.

**Comment by SolomonRude** [comment] 2017-03-22 18:42
i have the same issue...

**Comment by drmDev** [comment] 2017-03-27 04:10
Could you provide the screenshots and log?

**Comment by ericsvince** [comment] 2017-03-27 13:46
Here are screenshots of the error in Xmage...

<img width="960" alt="error1" src="https://cloud.githubusercontent.com/assets/26586572/24359341/11cf2dba-12d2-11e7-86d3-df731726dc2e.PNG">

<img width="960" alt="error2" src="https://cloud.githubusercontent.com/assets/26586572/24359355/1944f232-12d2-11e7-9559-59c34dfa7a3c.PNG">

<img width="960" alt="error3" src="https://cloud.githubusercontent.com/assets/26586572/24359363/1d1c70d8-12d2-11e7-86ed-c34c95b18a44.PNG">

**Comment by ericsvince** [comment] 2017-03-27 13:46
Here's the log...

Mar 17, 2017 8:08:04 PM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
INFO  2017-03-17 20:08:04,427 Starting MAGE client version 1.4.22V0                                                      =>[main] MageFrame.main 
INFO  2017-03-17 20:08:04,427 Logging level: INFO                                                                        =>[main] MageFrame.main 
Qt: Untested Windows version 10.0 detected!
Qt: Untested Windows version 10.0 detected!
Qt: Untested Windows version 10.0 detected!
Qt: Untested Windows version 10.0 detected!
ERROR 2017-03-17 20:08:05,717 Couldn't rename mana symbols!                                                              =>[AWT-EventQueue-0] ManaSymbols.renameSymbols 
ERROR 2017-03-17 20:08:05,719 Error for symbol:0                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,720 Error for symbol:1                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,720 Error for symbol:10                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,721 Error for symbol:11                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,721 Error for symbol:12                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,722 Error for symbol:15                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,722 Error for symbol:16                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,723 Error for symbol:2                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,723 Error for symbol:3                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,724 Error for symbol:4                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,724 Error for symbol:5                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,725 Error for symbol:6                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,726 Error for symbol:7                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,728 Error for symbol:8                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,730 Error for symbol:9                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,733 Error for symbol:B                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,734 Error for symbol:BG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,735 Error for symbol:BR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,736 Error for symbol:G                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,738 Error for symbol:GU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,739 Error for symbol:GW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,739 Error for symbol:R                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,740 Error for symbol:RG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,740 Error for symbol:RW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,740 Error for symbol:S                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,741 Error for symbol:T                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,741 Error for symbol:U                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,742 Error for symbol:UB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,742 Error for symbol:UR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,743 Error for symbol:W                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,743 Error for symbol:WB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,743 Error for symbol:WU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,744 Error for symbol:WP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,744 Error for symbol:UP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,745 Error for symbol:BP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,745 Error for symbol:RP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,746 Error for symbol:GP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,746 Error for symbol:X                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,746 Error for symbol:C                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,748 Error for symbol:E                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,749 Error for symbol:0                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,749 Error for symbol:1                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,750 Error for symbol:10                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,750 Error for symbol:11                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,751 Error for symbol:12                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,751 Error for symbol:15                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,752 Error for symbol:16                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,752 Error for symbol:2                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,753 Error for symbol:3                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,753 Error for symbol:4                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,754 Error for symbol:5                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,754 Error for symbol:6                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,755 Error for symbol:7                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,755 Error for symbol:8                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,755 Error for symbol:9                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,756 Error for symbol:B                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,756 Error for symbol:BG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,756 Error for symbol:BR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,756 Error for symbol:G                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,757 Error for symbol:GU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,757 Error for symbol:GW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,758 Error for symbol:R                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,758 Error for symbol:RG                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,758 Error for symbol:RW                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,759 Error for symbol:S                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,759 Error for symbol:T                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,759 Error for symbol:U                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,759 Error for symbol:UB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,760 Error for symbol:UR                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,760 Error for symbol:W                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,760 Error for symbol:WB                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,760 Error for symbol:WU                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,761 Error for symbol:WP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,761 Error for symbol:UP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,761 Error for symbol:BP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,762 Error for symbol:RP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,762 Error for symbol:GP                                                                        =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,762 Error for symbol:X                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,763 Error for symbol:C                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
ERROR 2017-03-17 20:08:05,763 Error for symbol:E                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadSymbolsImages 
INFO  2017-03-17 20:08:06,227 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2017-03-17 20:08:06,262 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2017-03-17 20:08:06,278 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2017-03-17 20:08:09,899 Card pool load time: 2 seconds                                                             =>[AWT-EventQueue-0] MageFrame.checkForNewImages 
INFO  2017-03-17 20:08:10,067 Card images checking time: 0 seconds                                                       =>[AWT-EventQueue-0] MageFrame.checkForNewImages 
INFO  2017-03-17 20:08:12,298 Client start up time: 7 seconds                                                            =>[AWT-EventQueue-0] MageFrame.lambda$new$2 
INFO  2017-03-17 20:08:12,298 Trying to connect to XMAGE server at xmage.woogerworks.info:17171                          =>[AWT-EventQueue-0] SessionImpl$5.run 
WARN  2017-03-17 20:08:33,411 Cannot connect                                                                             =>[AWT-EventQueue-0] SessionImpl.handleCannotConnectException 
org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
	at org.jboss.remoting.Client.connect(Client.java:1928)
	at org.jboss.remoting.Client.connect(Client.java:737)
	at mage.remote.SessionImpl$5.run(SessionImpl.java:390)
	at mage.remote.SessionImpl.handleRemotingTaskExceptions(SessionImpl.java:117)
	at mage.remote.SessionImpl.establishJBossRemotingConnection(SessionImpl.java:267)
	at mage.remote.SessionImpl.connect(SessionImpl.java:220)
	at mage.client.SessionHandler.connect(SessionHandler.java:49)
	at mage.client.MageFrame.connect(MageFrame.java:704)
	at mage.client.MageFrame.performConnect(MageFrame.java:750)
	at mage.client.MageFrame.autoConnect(MageFrame.java:717)
	at mage.client.MageFrame.lambda$new$2(MageFrame.java:317)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.Exception: Error setting up client lease
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:563)
	at org.jboss.remoting.Client.setupClientLease(Client.java:2070)
	at org.jboss.remoting.Client.connect(Client.java:1924)
	... 24 more
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://xmage.woogerworks.info:17171/?serializationtype=jboss]
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:855)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.transport(BisocketClientInvoker.java:470)
	at org.jboss.remoting.MicroRemoteClientInvoker.invoke(MicroRemoteClientInvoker.java:169)
	at org.jboss.remoting.MicroRemoteClientInvoker.establishLease(MicroRemoteClientInvoker.java:529)
	... 26 more
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.connect(SocketClientInvoker.java:293)
	at org.jboss.remoting.transport.socket.SocketClientInvoker.createSocket(SocketClientInvoker.java:210)
	at org.jboss.remoting.transport.bisocket.BisocketClientInvoker.createSocket(BisocketClientInvoker.java:477)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.getConnection(MicroSocketClientInvoker.java:1190)
	at org.jboss.remoting.transport.socket.MicroSocketClientInvoker.transport(MicroSocketClientInvoker.java:833)
	... 29 more
FATAL 2017-03-17 20:08:34,465 Error disconnecting ...                                                                    =>[AWT-EventQueue-0] SessionImpl.disconnect 
java.lang.Exception: Can not remove callback listener as remoting client is not connected to server.
	at org.jboss.remoting.Client.removeListener(Client.java:1466)
	at mage.remote.SessionImpl.disconnect(SessionImpl.java:488)
	at mage.remote.SessionImpl.establishJBossRemotingConnection(SessionImpl.java:415)
	at mage.remote.SessionImpl.connect(SessionImpl.java:220)
	at mage.client.SessionHandler.connect(SessionHandler.java:49)
	at mage.client.MageFrame.connect(MageFrame.java:704)
	at mage.client.MageFrame.performConnect(MageFrame.java:750)
	at mage.client.MageFrame.autoConnect(MageFrame.java:717)
	at mage.client.MageFrame.lambda$new$2(MageFrame.java:317)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
INFO  2017-03-17 20:08:34,465 Disconnected ...                                                                           =>[AWT-EventQueue-0] SessionImpl.disconnect 
INFO  2017-03-17 20:08:34,465 DISCONNECTED (Event Dispatch Thread)                                                       =>[AWT-EventQueue-0] MageFrame.disconnected

**Comment by drmDev** [comment] 2017-03-27 14:02
For resolving this part of it ("WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5."), try the advice followed here: http://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node

**Comment by drmDev** [comment] 2017-03-27 14:09
`Qt: Untested Windows version 10.0 detected!
Qt: Untested Windows version 10.0 detected!
Qt: Untested Windows version 10.0 detected!
Qt: Untested Windows version 10.0 detected!`

That part is only warnings and from everything I'm reading on it, nothing to be concerned with or that would cause these sorts of issues.

**Comment by drmDev** [comment] 2017-03-27 14:11
Do you have XMage installed it it's own directory? I recommend a new folder somewhere close to the root of the drive like c:\xmage or c:\games\xmage or whatever. I've heard of issues having it run from your user profile (i.e. C:\Users\YourUserName\....)

**Comment by ericsvince** [comment] 2017-03-27 14:50
I have it on my desktop right now. Should I move it somewhere else?

I tried the steps above but it still gives me the same error log. Could it be because I'm windows 10 and my registry folder is "HKEY_LOCAL_MACHINE\Software\WOW6432Node\JavaSoft" instead of "HKEY_LOCAL_MACHINE\Software\JavaSoft"? Because the error specifically says "Software\JavaSoft\Prefs"?

**Comment by drmDev** [comment] 2017-03-27 15:04
I'm running Windows 10 here and have the prefs key in HKEY_LOCAL_MACHINE\Software\JavaSoft. It can't do any harm to add the key to both paths I guess, just make sure there is a key for Prefs:

`Right click on the JavaSoft folder and click on New -> Key
Name the new Key Prefs and everything should work.`

Also, yes, move your xmage directory outside of desktop (which is in your user profile - Desktop on windows 10 is actually in Users\YourName\Desktop (part of the user profile). Similarly with Documents, Downloads, Pictures, etc. Assuming your OS hard drive is C, if you navigate to C:\Users\YourUserName you'll see all the folders related to your user profile there. It can cause permissions issues for some people trying to run applications directly from a folder there.

**Comment by ericsvince** [comment] 2017-03-27 15:27
I moved it directly to C:\ and it seemed to have no effect. Also, what I'm saying is that I don't have "HKEY_LOCAL_MACHINE\Software\JavaSoft" as a path in my registry. I have "HKEY_LOCAL_MACHINE\Software\WOW6432Node\JavaSoft" instead (as mentioned in the original solution you posted). I don't see any way to create a new path. I could try to rename it but I feel like that wouldn't work.

**Comment by drmDev** [comment] 2017-03-27 15:42
odd.. I have both paths on my Win 10. Not sure what that is about. I feel like something is not installed or configured correctly but not sure what this is indicating at this point frankly.

**Comment by drmDev** [comment] 2017-03-27 15:46
Not very familiar with the network component of this project either which uses JBoss. But these then seem to be the relevant messages from the log:

org.jboss.remoting.CannotConnectException: Error setting up client lease upon performing connect.
.....
Caused by: org.jboss.remoting.CannotConnectException: Can not get connection to server. Problem establishing socket connection for InvokerLocator [bisocket://xmage.woogerworks.info:17171/?serializationtype=jboss]
.....
Caused by: java.net.ConnectException: Connection timed out: connect
.....
FATAL 2017-03-17 20:08:34,465 Error disconnecting ... =>[AWT-EventQueue-0] SessionImpl.disconnect
java.lang.Exception: Can not remove callback listener as remoting client is not connected to server.

**Comment by ericsvince** [comment] 2017-03-27 17:15
Understood. I had Windows 8 on it and then updated to Windows 10 so maybe that did something. I'll keep looking for other solutions. Thank you for trying to help so much. I really appreciate it.

**Comment by Zerrisx** [comment] 2020-07-17 21:10
Three years later, this is either resolved or obsolete.

**Closed by Zerrisx** 2020-07-17 21:10 UTC
Labels: launcher / installation, network / connection, server

**Comment by phughk** [comment] 2021-06-25 19:01
Not re-opening the ticket, but for people who have come here due to launching `xmage/startMage.sh` - use the launcher in the parent directory, it will update your software and resolve the connection issues.
