### ISSUE TITLE
Downloading Symbols on a fresh installation does not work (tested on Linux & Windows)

### ISSUE THREAD

**Issue by dvmoritzschoefl** [magefree/mage#9135] opened 2022-06-21 11:15 UTC
I installed XMage using the supplied java installation (openjdk 11). After that I clicked away the "connect to server" dialog and pressed the "Symbols" tab on the top. However downloading the symbols does not work because java exceptions arise:

![image](https://user-images.githubusercontent.com/77104411/174786778-6f413efd-06fc-4078-aa59-84dbc5dd8c46.png)

I tested it on a fresh Ubuntu 22 and Windows 10 installation (Virtual Machine)

**Comment by Alex-Vasile** [comment] 2022-07-07 13:28
Issue is an expired certificate: `GeoTrust Global CA`

To see, `cd` into the JRE and then into `Contents/Home`. Then run `./bin/keytool -list -v -keystore lib/security/cacerts > output.txt` and open output.txt. Then search either by the name above or by "2022".

"Valid from: Tue May 21 00:00:00 EDT 2002 until: *Sat May 21 00:00:00 EDT 2022*"

**Comment by Alex-Vasile** [comment] 2022-07-07 13:28
Perhaps we can try similar solution to https://github.com/wultra/powerauth-push-server/pull/384

**Comment by jeffwadsworth** [comment] 2022-07-07 17:36
https://discord.com/channels/169970997389295616/169970997389295616/993981901217988718

**Comment by weirddan455** [comment] 2022-07-07 23:52
Interestingly, this works on my system (Arch Linux).  cacerts inside Java's folder is just a symlink to /etc/ssl/certs/java/cacerts which is managed by the global package manager (certs can be updated independently of the installed Java version).  I'd be surprised if this isn't also the case on Ubuntu.  Maybe you just need to update packages to pull down the new cert?

I am able to reproduce this bug by compiling OpenJDK from source.  It looks like it builds a default cacert file if you don't provide your own (or replace it with a symlink like the Arch build scripts do).  Outdated cert is here:  https://github.com/openjdk/jdk8u/blob/master/jdk/make/data/cacerts/geotrustglobalca

That said, I'm not sure this is really an XMage bug.  We can maybe do a workaround by providing this cert like that other project did but ideally this would be handled by the user's system or Java implementation.  I also don't know where to put in a bug report on OpenJDK to have them update that cert.  There's no issues on their GitHub page.  Maybe I'll look into that later.

**Comment by Alex-Vasile** [comment] 2022-07-07 23:59
> Interestingly, this works on my system (Arch Linux). cacerts inside Java's folder is just a symlink to /etc/ssl/certs/java/cacerts which is managed by the global package manager (certs can be updated independently of the installed Java version). I'd be surprised if this isn't also the case on Ubuntu. Maybe you just need to update packages to pull down the new cert?
> 
> I am able to reproduce this bug by compiling OpenJDK from source. It looks like it builds a default cacert file if you don't provide your own (or replace it with a symlink like the Arch build scripts do). Outdated cert is here: https://github.com/openjdk/jdk8u/blob/master/jdk/make/data/cacerts/geotrustglobalca
> 
> That said, I'm not sure this is really an XMage bug. We can maybe do a workaround by providing this cert like that other project did but ideally this would be handled by the user's system or Java implementation. I also don't know where to put in a bug report on OpenJDK to have them update that cert. There's no issues on their GitHub page. Maybe I'll look into that later.

Interesting. The cacert inside the JRE in my XMage folder is not a symlink (at least on my Mac) to anywhere else.

The client isn't using the user's system Java, only the launcher is. The client launches uses an ancient version of Java that is downloaded by the launcher. So I think we've made it our problem.

**Comment by weirddan455** [comment] 2022-07-08 00:14
Oh, I don't use the launcher.  I just launch XMage with my system's Java.  It's to be expected that an old version of Java will ship with outdated certs.  Do you have the problem if you use a system Java on Mac?  I assume that's the way you launch it for development inside IntelliJ or whatever you use?

**Comment by Alex-Vasile** [comment] 2022-07-08 00:24
> Oh, I don't use the launcher. I just launch XMage with my system's Java. It's to be expected that an old version of Java will ship with outdated certs. Do you have the problem if you use a system Java on Mac? I assume that's the way you launch it for development inside IntelliJ or whatever you use?

When playing with others I use the launcher. When doing dev I do IntelliJ, which also has this issue (I'm using BellSoft Liberica 1.8.0_333).

And it is to be expect. But that is still what the launcher is doing.

**Comment by weirddan455** [comment] 2022-07-08 00:44
Launcher is a whole other can of worms.  I just wrote my own because I don't like it using an old Oracle build of Java when I have a perfectly good version already installed (and in fact a system Java is required to launch the launcher):  https://github.com/weirddan455/xmage-launcher-qt

I'll see if I can reproduce this in Windows using the latest Oracle JRE and maybe figure out a workaround if Oracle is still shipping outdated certs in the latest version.

**Comment by Alex-Vasile** [comment] 2022-07-08 00:52
> Launcher is a whole other can of worms. I just wrote my own because I don't like it using an old Oracle build of Java when I have a perfectly good version already installed (and in fact a system Java is required to launch the launcher): https://github.com/weirddan455/xmage-launcher-qt
> 
> I'll see if I can reproduce this in Windows using the latest Oracle JRE and maybe figure out a workaround if Oracle is still shipping outdated certs in the latest version.

Agreed.

And yes they are, 1.8_333 was released early May of this year, only weeks before the cert expired.

**Comment by weirddan455** [comment] 2022-07-08 02:04
Confirmed not working on latest Oracle JRE on Windows.  As a quick and dirty fix, you can simply add the missing cert to Java's cacert file.  What I did was open https://gather.wizards.com in Firefox and look at the certificate.  I then clicked on the intermediate cert named "DigiCert TLS RSA SHA256 2020 CA1", scrolled down to Download PEM and saved that file.

Then you need to launch a command prompt as Administrator, cd into the Java directory (on my system C:\Program Files\Java\jre1.8.0_333) and run the following command:

`bin\keytool -import -alias digitcert -keystore lib\security\cacerts -file C:\path\to\digicert.pem`

Certificate is attached below as well.  If you download this, rename to .pem.  GitHub would only allow me to attach if I changed it to a .txt file.

[digitcert.txt](https://github.com/magefree/mage/files/9068328/digitcert.txt)

As far as what to do about this in XMage, I can see arguments for either shipping our own cert file or looking into a way to get certs from the system rather than from Java.  The latter may be tricky to do in a cross platform compatible way and there's no guarantee it will be more up to date than Java's certs (though probably more likely to be).

**Comment by jeffwadsworth** [comment] 2022-07-08 02:41
> > https://discord.com/channels/169970997389295616/169970997389295616/993981901217988718
> 
> What is it?
> 
> Link does not redirect to the discord app, and I aint logging in on a random link.

Shockingly, it is a link to the symbols that someone was gracious enough to share.

**Comment by weirddan455** [comment] 2022-07-08 04:05
> Does the company issuing this cert not host it somewhere on their website? We could store the hash in XMage, and have the client download and install it (checking the hash) using an approach similar to the approach in the GitHub link above. This way we don't have xmage installing a randomly saved certificate, anyone can see exactly where it's being downloaded from.

I don't think this should be something that happens at runtime.  Even if we could find it on Digicert's website, the site itself is likely to be signed by that same missing root cert leading us into a catch 22.

My thought was to ship something like this: https://src.fedoraproject.org/rpms/ca-certificates

It's a group of root certs chosen by Mozilla that is commonly used as the trusted root certs by Linux distros.  It should only be about 1MB of data.  I also don't think we would be installing any certs system wide.  It would just reside in the XMage folder for use with XMage only (we process it into a format Java can read and tell Java to use our file rather than looking in the Java folder).

**Comment by JayDi85** [comment] 2022-07-08 09:19
Is it related to linux version? There were some weird linux like debian -- it require to enable https certs for java, see https://github.com/magefree/mage/issues/4325#issuecomment-354706401

**Comment by weirddan455** [comment] 2022-07-08 09:36
> Is it related to linux version? There were some weird linux like debian -- it require to enable https certs for java, see [#4325 (comment)](https://github.com/magefree/mage/issues/4325#issuecomment-354706401)

It appears to more of a problem for Windows and Mac users.  At least for me, it works on Arch Linux but does not work on Windows 10.

Root problem is the certs that ship with Java are outdated.  Some Linux distros get around this by symlinking to system certs instead but Windows and Mac users are going to be using the certs that come with Java most of the time.

**Comment by Alex-Vasile** [comment] 2022-07-08 20:08
> > Does the company issuing this cert not host it somewhere on their website? We could store the hash in XMage, and have the client download and install it (checking the hash) using an approach similar to the approach in the GitHub link above. This way we don't have xmage installing a randomly saved certificate, anyone can see exactly where it's being downloaded from.
> 
> I don't think this should be something that happens at runtime. Even if we could find it on Digicert's website, the site itself is likely to be signed by that same missing root cert leading us into a catch 22.
> 
> My thought was to ship something like this: https://src.fedoraproject.org/rpms/ca-certificates
> 
> It's a group of root certs chosen by Mozilla that is commonly used as the trusted root certs by Linux distros. It should only be about 1MB of data. I also don't think we would be installing any certs system wide. It would just reside in the XMage folder for use with XMage only (we process it into a format Java can read and tell Java to use our file rather than looking in the Java folder).

Do you have the time to look into what it would take (either a different method or the one I linked above)?

All of them are not very big in terms of size, but I also don't think we need all them. Only one is expired. Might be easier to implement if only a single one is copied override, rather than the whole cacerts file. telling XMage to use our file would also have unintended consequences for anyone who is connecting to a server using a certificate that they added to their own version but would not be in ours.

**Comment by Alex-Vasile** [comment] 2022-07-08 20:27
> > Do you have the time to look into what it would take (either a different method or the one I linked above)?
> 
> From what I read it would be as easy as a `System.setProperty("javax.net.ssl.trustStore", "path/to/custom-certs");`

Do you have the time to test that solution and add it if it works?

> > All of them are not very big in terms of size, but I also don't think we need all them. Only one is expired. Might be easier to implement if only a single one is copied override, rather than the whole cacerts file.
> 
> Was just thinking we could avoid this problem again in the future if Java is going to be slow to update certs. Although this would mean, we would need to update our file in a timely manner instead.

It would be worth while to build the functionality in, but disable it after Java has update the certs.

> > telling XMage to use our file would also have unintended consequences for anyone who is connecting to a server using a certificate that they added to their own version but would not be in ours.
> 
> I don't believe XMage supports SSL for connecting to the game server (maybe someone will correct me if this is wrong). I think the only times it uses HTTPS would be for downloading images and the "What's new" page.

Okay

> I suppose another option for dealing with this would be to present a warning to the user like a web browser does and ask if they want to proceed with the connection anyway (insecure but is maybe fine for downloading images).

I like the approach of overriding the certs. This should be something XMage deals with rather than forces the user to decide.

**Comment by weirddan455** [comment] 2022-07-08 22:38
I'll look into it.  I don't know if conditionally disabling it makes much sense though.  People are going to have outdated Java versions (and we have a launcher encouraging them to do so).

**Comment by Alex-Vasile** [comment] 2022-07-13 18:07
> Is it works with updated JDK 8u332+?
> 
> https://bugs.openjdk.org/browse/JDK-8277488 ![shot_220713_215349](https://user-images.githubusercontent.com/8344157/178799068-293617a2-dbce-4d56-a865-c14c0ee801d2.png)

That PR appears to be adding a warning suppression for the certificate, and not an actual replacement for the expired certificate..

The certificate being shipping with the openJDK8
stable: https://github.com/openjdk/jdk8u/blob/master/jdk/make/data/cacerts/geotrustglobalca
Dev: https://github.com/openjdk/jdk8u-dev/blob/master/jdk/make/data/cacerts/geotrustglobalca
Are both outdated.

**Comment by Alex-Vasile** [comment] 2022-07-13 18:11
it's not just the repo, if you pick a distribution (e.g. 8u332-b09 from https://www.openlogic.com/openjdk-downloads?field_java_parent_version_target_id=416&field_operating_system_target_id=All&field_architecture_target_id=All&field_java_package_target_id=All) and inspect the cacerts you will find that it has this issue.

**Comment by JayDi85** [comment] 2022-07-13 18:21
What about JDK 11+?

**Comment by Alex-Vasile** [comment] 2022-07-13 18:31
> What about JDK 11+?

my local (macOS) 17.0.2 Java has the same issue.
As does the newest openJDK (11.0.15+10).

They will fix it at some point in a new update for all of the JREs. But that won't help us as long as the launcher continues to ship 1.8u202

**Comment by Alex-Vasile** [comment] 2022-07-21 16:24
Java 1.8u342 came out and I tested with on my Mac, it still doesn't work.

**Comment by gcaliber** [comment] 2022-07-25 20:14
I was able to manually add the new cert myself on arch, but this seems like a deal breaker for most people attempting new installs.

**Comment by Alex-Vasile** [comment] 2022-07-25 20:57
> I was able to manually add the new cert myself on arch, but this seems like a deal breaker for most people attempting new installs.

It is. There's a proposed solution in #9266, let me know if you know of a different approach

**Comment by Alex-Vasile** [comment] 2022-07-26 13:26
Finally found where to file a bug report. The issue is being tracked: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8291024

Supposedly fixed in newer versions of Java 11, 17, and 18.

The solution to this is to stop bundling the ancient version of Java with the launcher and instead have it download the newest java 1.8 which will eventually receive a patch for this.

**Comment by Alex-Vasile** [comment] 2022-08-14 21:08
#9266 fixes this issue in the dev environement, but the build and package scripts do not actually package the `caerts` file and provide it for release.

The location of the file will also need to be changed.

**Closed** 2022-09-01 03:44 UTC
Labels: bug, download
