### ISSUE TITLE
Battle for Zendikar set does not show all basic land printings

### ISSUE THREAD

**Issue by Ketsuban** [magefree/mage#1953] opened 2016-05-26 01:32 UTC
As a callback to the original Zendikar, Battle for Zendikar had full-art printings of each of its five different land artworks, for ten cards total. However unlike with the original Zendikar where Magiccards.info lists these all as separate printings, so 246 is the full-art counterpart of 266, Battle for Zendikar's printings are listed with each *artwork* being given a printing number, so 270b is the full-art counterpart of 270a.

XMage only lists five different cards for each basic land in BFZ rather than the ten I'd expect. I'm not sure how it picks the artworks to download—most are the normal-card-design variants, but one Forest, one Island and one Mountain are full-art. Possibly which artworks you actually get when downloading is random.

**Comment by fenhl** [comment] 2016-05-26 10:06
Can we close this as a duplicate of #1915 if we note that it does sometimes download the regular-frame version instead?

**Comment by LevelX2** [comment] 2016-10-29 22:35
Fixed.

**Closed by LevelX2** 2016-10-29 22:35 UTC
