### ISSUE TITLE
Server's error: offset out of bounds

### ISSUE THREAD

**Issue by dosfod** [magefree/mage#8836] opened 2022-04-12 10:16 UTC
Hi, 

since the last beta update, I am getting this error while launching a server in local: 

![image](https://user-images.githubusercontent.com/29545637/162938346-ef865869-873f-4a26-a977-b0134e863d5b.png)

I algo see this in the console: 

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/29545637/162938487-e9f8918f-4d66-4d00-a176-5a857579089c.png">

It is causing the server to lag a lot.

Can you take a look please?

Thanks!

**Comment by dosfod** [comment] 2022-04-12 11:50
It is happening with any UI changes, but it recovers eventually.

However, with these kind of menus: 

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/29545637/162953763-d3eea84c-0ff0-46ac-b448-67f102c199a5.png">

The game just freezes and won't recover again.

**Comment by JayDi85** [comment] 2022-04-12 15:11
[[Toxic Deluge]] works fine in latest version. Can't reproduce your error. What's your life here?

**Comment by dosfod** [comment] 2022-04-12 15:15
Hi, 

the problem was not with toxic deluge, it was with the GUI. Don't know what caused it, but I restarted the server and it is working properly now, without lag.

You can close the issue if you want, but that "offset out of bounds" error was popping whenever I touched GUI elements, such as seeing the graveyard, searching library or with the toxic deluge dialog.

In any case, it is all fine now.

Thanks a lot!

**Comment by Alex-Vasile** [comment] 2022-05-27 04:24
Still and issue.

Seen reports from others about it and experienced it myself.

I was seeing it when investigating #8968.

I would concede the game to let the AI play itself and would get one of these at the end of the match when the win screen showed up.

Was playing the Edgar Markov precon and the EHDREC average deck for The Scarab God.

The Scarab God deck card does have toxic deluge in it for what it's worth. Thought it would be strange for it to show up only at the end of the game.

**Comment by dosfod** [comment] 2022-06-22 08:19
Hi, 

just a reminder that this is still happening from time to time. Attached the console log screenshot (I can't copy it for some reason)

<img width="1282" alt="image" src="https://user-images.githubusercontent.com/29545637/174980066-8d66a6d5-9a6d-4aa8-b8c2-3a6155662b9a.png">

Thanks and regards

**Comment by Tharkon** [comment] 2022-06-30 21:50
It's still happening for me constantly as well. Even tried a game without AI just to be sure and while at first the error did not occur with Secluded Courtyard, later it appeared with Mother of Runes during the color selection dialogue. Though for me the error does not seem to appear in the console. But that could be because I start from command prompt and not from the Launcher.

**Comment by Alex-Vasile** [comment] 2022-06-30 23:56
Haven't figured out WHY it's happening, but I've tracked down to:
https://github.com/magefree/mage/blob/c328c71ef9715f8d2745a7955a3e44d62fa19af4/Mage.Client/src/main/java/mage/client/components/ColorPane.java#L156
called from:
https://github.com/magefree/mage/blob/c328c71ef9715f8d2745a7955a3e44d62fa19af4/Mage.Client/src/main/java/mage/client/chat/ChatPanelBasic.java#L274

It doesn't look like it's a choice dialog related. It's coming up from the game log window.

The actual code that raises the error is:
```Java
protected static final void checkOffset(int offset, CharacterIterator text) {
    if (offset < text.getBeginIndex() || offset > text.getEndIndex()) {
        throw new IllegalArgumentException("offset out of bounds");
    }
}
```

When it was throwing the exception for me it always because `offset > text.getEndIndex()`.

**Comment by Alex-Vasile** [comment] 2022-07-17 00:49
I believe this should be fixed by 420b6f1a74590b5126a5525fdb86d8e4f70916dd. It seems to have been introduced by a malformed string in Edgar Markov's ability description with an open "<" but no closing ">" which would causes random errors on the client as it tries to convert it to html.

**Comment by Alex-Vasile** [comment] 2022-07-17 02:16
<img alt="image" width="1042" src="https://user-images.githubusercontent.com/29545637/162953763-d3eea84c-0ff0-46ac-b448-67f102c199a5.png">

The AI on the top-left. with the Black-Red-White dual-lands. Is it playing Edgar Markov?

**Comment by Alex-Vasile** [comment] 2022-07-17 02:17
> It's still happening for me constantly as well. Even tried a game without AI just to be sure and while at first the error did not occur with Secluded Courtyard, later it appeared with Mother of Runes during the color selection dialogue. Though for me the error does not seem to appear in the console. But that could be because I start from command prompt and not from the Launcher.

Same question. Is anyone in the game playing Edgar Markov?

**Comment by dosfod** [comment] 2022-07-17 17:31
Yes, it was probably Edgar Markov

**Comment by Alex-Vasile** [comment] 2022-07-17 17:53
> https://github.com/magefree/mage/issues/8836#issuecomment-1186376133
> 
> 
> 
> Yes, it was probably Edgar Markov

Great. Then this should be solved in the new beta.

**Closed by Alex-Vasile** 2022-07-17 17:53 UTC
Labels: bug, GUI

**Comment by dosfod** [comment] 2022-07-18 08:10
> > [#8836 (comment)](https://github.com/magefree/mage/issues/8836#issuecomment-1186376133)
> > Yes, it was probably Edgar Markov
> 
> Great. Then this should be solved in the new beta.

Excellent, do you know when will the beta version be available?

**Comment by Alex-Vasile** [comment] 2022-07-18 10:52
> > > [#8836 (comment)](https://github.com/magefree/mage/issues/8836#issuecomment-1186376133)
> 
> > > Yes, it was probably Edgar Markov
> 
> > 
> 
> > Great. Then this should be solved in the new beta.
> 
> 
> 
> Excellent, do you know when will the beta version be available?

Zero knowledge or influence over that.
