### ISSUE TITLE
Blood artist and zulaport cutthroat bug

### ISSUE THREAD

**Issue by i4004** [magefree/mage#1451] opened 2016-01-10 08:10 UTC
When blood artist or zulaport cutthroat dies he is not triggering his triggered ability.

**Comment by fireshoes** [comment] 2016-01-10 15:14
There was a fix for this in 1.4.6v1. Have you updated in the last few days?

**Comment by LevelX2** [comment] 2016-01-10 15:17
This is not fixed yet. It's not that easy.

**Comment by LevelX2** [comment] 2016-01-10 21:19
Duplicate of #1426.

**Closed by LevelX2** 2016-01-10 21:19 UTC
Labels: bug, duplicate
