### ISSUE TITLE
SQLException: can't start server without removing all db files

### ISSUE THREAD

**Issue by magenoxx** [magefree/mage#504] opened 2014-08-12 13:41 UTC
Started happening after testing (didn't do anything special).
So now I restart server and when CardRepository is initialised NPE appears:
"java.lang.NullPointerException" [50000-178]
on code line (RepositoryUtil.java):

``` java
TableUtils.createTableIfNotExists(connectionSource, DatabaseVersion.class);
```

Stacktrace:

``` java
org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-178]
    at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
    at org.h2.message.DbException.get(DbException.java:167)
    at org.h2.message.DbException.convert(DbException.java:294)
    at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:337)
    at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
    at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
    at org.h2.Driver.connect(Driver.java:74)
    at java.sql.DriverManager.getConnection(DriverManager.java:571)
    at java.sql.DriverManager.getConnection(DriverManager.java:187)
    at com.j256.ormlite.jdbc.JdbcConnectionSource.makeConnection(JdbcConnectionSource.java:252)
    at com.j256.ormlite.jdbc.JdbcConnectionSource.getReadWriteConnection(JdbcConnectionSource.java:184)
    at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:440)
    at com.j256.ormlite.table.TableUtils.createTable(TableUtils.java:220)
    at com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:61)
    at mage.cards.repository.RepositoryUtil.isDatabaseObsolete(RepositoryUtil.java:19)
    at mage.cards.repository.CardRepository.<init>(CardRepository.java:71)
    at mage.cards.repository.CardRepository.<clinit>(CardRepository.java:54)
    at mage.server.MageServerImpl.getMissingCardsData(MageServerImpl.java:1123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.jboss.remoting.transporter.TransporterHandler.invoke(TransporterHandler.java:87)
    at org.jboss.remoting.ServerInvoker.invoke(ServerInvoker.java:967)
    at org.jboss.remoting.transport.socket.ServerThread.completeInvocation(ServerThread.java:791)
    at org.jboss.remoting.transport.socket.ServerThread.processInvocation(ServerThread.java:744)
    at org.jboss.remoting.transport.socket.ServerThread.dorun(ServerThread.java:586)
    at org.jboss.remoting.transport.socket.ServerThread.run(ServerThread.java:234)
Caused by: java.lang.NullPointerException
    at org.h2.mvstore.db.ValueDataType.compare(ValueDataType.java:98)
    at org.h2.mvstore.MVMap.compare(MVMap.java:724)
    at org.h2.mvstore.Page.binarySearch(Page.java:347)
    at org.h2.mvstore.MVMap.binarySearchPage(MVMap.java:497)
    at org.h2.mvstore.MVMap.getLiveKey(MVMap.java:476)
    at org.h2.mvstore.MVStore.copyLive(MVStore.java:1620)
    at org.h2.mvstore.MVStore.compact(MVStore.java:1565)
    at org.h2.mvstore.db.MVTableEngine$Store.close(MVTableEngine.java:326)
    at org.h2.engine.Database.closeOpenFilesAndUnlock(Database.java:1329)
    at org.h2.engine.Database.openDatabase(Database.java:292)
    at org.h2.engine.Database.<init>(Database.java:256)
    at org.h2.engine.Engine.openSession(Engine.java:57)
    at org.h2.engine.Engine.openSession(Engine.java:164)
    at org.h2.engine.Engine.createSessionAndValidate(Engine.java:142)
    at org.h2.engine.Engine.createSession(Engine.java:125)
    at org.h2.engine.Engine.createSession(Engine.java:27)
    at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:335)
    ... 24 more
```

**Comment by goesta** [comment] 2017-02-28 22:20
I'll close this issue because it seems to be outdated.

**Closed by goesta** 2017-02-28 22:20 UTC
Labels: bug

**Comment by LukeButtersFunnelback** [comment] 2018-09-27 23:47
This seems to be happening for me:
{code}
Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.NullPointerException" [50000-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.engine.Database.openDatabase(Database.java:301)
	at org.h2.engine.Database.<init>(Database.java:264)
	at org.h2.engine.Engine.openSession(Engine.java:64)
	at org.h2.engine.Engine.openSession(Engine.java:176)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:154)
	at org.h2.engine.Engine.createSession(Engine.java:137)
	at org.h2.engine.Engine.createSession(Engine.java:27)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:349)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:118)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:102)
	at org.h2.Driver.connect(Driver.java:72)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:270)
	at com.happy.admin.api.service.historicaldata.dao.LocalH2ServerHistoricalDataDataSourceFactory.lambda$0(LocalH2ServerHistoricalDataDataSourceFactory.java:78)
	at com.happy.admin.api.service.historicaldata.dao.LocalH2ServerHistoricalDataDataSourceFactory.getDatasource(LocalH2ServerHistoricalDataDataSourceFactory.java:94)
	... 54 more
Caused by: java.lang.NullPointerException
	at org.h2.mvstore.db.ValueDataType.compare(ValueDataType.java:103)
	at org.h2.mvstore.MVMap.compare(MVMap.java:708)
	at org.h2.mvstore.Page.binarySearch(Page.java:334)
	at org.h2.mvstore.MVMap.binarySearch(MVMap.java:461)
	at org.h2.mvstore.MVMap.get(MVMap.java:450)
	at org.h2.mvstore.MVMap.remove(MVMap.java:538)
	at org.h2.mvstore.db.TransactionStore.rollbackTo(TransactionStore.java:502)
	at org.h2.mvstore.db.TransactionStore$Transaction.rollback(TransactionStore.java:799)
	at org.h2.mvstore.db.MVTableEngine$Store.initTransactions(MVTableEngine.java:255)
	at org.h2.engine.Database.open(Database.java:762)
	at org.h2.engine.Database.openDatabase(Database.java:270)
	... 68 more
{code}

this is version 1.4.192
