### ISSUE TITLE
Quartzwood Crasher creates tokens too big when attacking multiple players 

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#12013] opened 2024-03-27 22:20 UTC
![033 quartzwood crasher 2](https://github.com/magefree/mage/assets/4504719/b244d32a-5512-4f85-af61-d907df432ce0)

If I attack multiple players with trample creatures, the second and onwards triggers of [[Quartzwood Crasher]] add the amount of the previous trigger to it which results in tokens bigger than it should.

In the example above it should result in two 1/1 and one 6/6

**Comment by xenohedron** [comment] 2024-03-31 17:21
@jimga150 this sounds related to the rework you're doing, curious if you can reproduce

**Comment by jimga150** [comment] 2024-04-01 03:46
Behaves correctly in master right now, it looks like the `OneOrMoreDealDamageTriggeredAbility` was fixed by #11841 when i discovered that `DAMAGED_BATCH_FOR_ONE_PLAYER` was getting more events batched into itself than it should have been.

**Closed** 2024-04-02 00:43 UTC
Labels: bug
