### ISSUE TITLE
Flashback not working with Split Cards.

### ISSUE THREAD

**Issue by jeffwadsworth** [magefree/mage#6327] opened 2020-03-02 23:20 UTC
Example:
Snapcaster Mage gives Fire // Ice flashback.  Fire // Ice can't be cast from the graveyard.

**Comment by Zerrisx** [comment] 2020-05-26 20:59
Duplicate of #6549

**Comment by JayDi85** [comment] 2020-06-03 08:49
Fixed via b94344341bf47968fcfa2018aa418547da25917e

**Closed by JayDi85** 2020-06-03 08:49 UTC
Labels: bug
