### ISSUE TITLE
past/cut/copy button not work and import too on MAC

### ISSUE THREAD

**Issue by Talek44** [magefree/mage#4208] opened 2017-11-28 14:33 UTC
Hi, I can't copy text on Import clipboard (past/cut/copy button not work on all windows of application).

I'm on Mac with High Sierra OS.

Moreover I can import .txt file or .dec. When I select my file (exported from deckstats website) and click on Open, nothing happens and in the java console I have this : INFO 2017-11-28 15:20:58,829 0

Thanks in advance

**Comment by JayDi85** [comment] 2017-12-07 17:25
1. Look here for [macOS fix](https://discussions.apple.com/message/32650419#32650419)
2. Can you attach sample import file or describe file's format for import? Give me not working deck. I try to import text format from deckstats and it works fine (with bugs, but it work and import some cards):
![shot_171207_210024](https://user-images.githubusercontent.com/8344157/33727529-c1d721ee-db91-11e7-9cb8-78564aa33715.png)

**Comment by spirius44** [comment] 2017-12-07 18:58
My copy/past function working perfectly except on Xmage.
To import function : it's the importation in Xmage program which don't work. And it's my files which are export from Deackstats.
Here is a video : https://youtu.be/3ApiBp-7a3U

**Comment by JayDi85** [comment] 2017-12-07 21:07
I can't help with macOS hotkeys. But I'm implemented deckstats format support (#4227). You can get it from next release or [download current developer version from here](https://yadi.sk/d/oLKb_rzG3PwE7n) (500 MB). That version have many fixed for deck editor such as new import messages/errors and checks. It may help with wrong deck lists.

**Comment by spirius44** [comment] 2017-12-07 21:15
Okay but it's normal if I also can't right click on each text box?

**Comment by JayDi85** [comment] 2017-12-07 21:24
No, it's a bug. [People on internet](https://www.google.com/search?q=High+Sierra+OS+cannot+type+site%3Adiscussions.apple.com&oq=High+Sierra+OS+cannot+type+site%3Adiscussions.apple.com) have same issues with other applications. Try to update your mac and restart it. Maybe you've installed another application or tool and it can't work with java app like xmage.

**Comment by spirius44** [comment] 2017-12-07 22:33
I downloaded the java app "Sweet Home 3D" and right click and hotkeys copy/cut/past works.

https://ibb.co/kGzkKb
https://ibb.co/bwwRQG

**Comment by spirius44** [comment] 2017-12-28 22:08
With the last update, right click is Ok but not on text box and cut/copy/past on it always don't work.

**Comment by hooptie45** [comment] 2018-05-17 22:45
I've experienced this, the xmage client seems to have windows bindings for copy/cut/paste; so try using the CTRL key instead of the CMD key. IE:
Cut becomes CTRL-x
Copy becomes CTRL-c
Paste becomes CTRL-v

**Comment by Zerrisx** [comment] 2020-07-01 19:18
Remaining issue appears to be a duplicate of #2994

**Closed by Zerrisx** 2020-07-01 19:18 UTC
Labels: linux / macos
