### ISSUE TITLE
Maskwood Nexus bugged/not working as intended

### ISSUE THREAD

**Issue by NimbleSlothMTG** [magefree/mage#7430] opened 2021-01-22 20:55 UTC
Maskwood Nexus currently just acts as a 4 cmc artifact that has (3), tap: Create a 2/2 blue Shapeshifter token with changeling.
 The whole first paragraph of text in which it's supposed to make all creatures you control every creature type as well as all your creatures you own that may or may not be on the battlefield. This currently just doesn't seem to work.
  I'm not sure how you'd fix this without a way of making it just essentially recognise all your creatures as having changeling but without adding that keyword and instead it just replaces the creature type with "this creature is every creature type".

**Comment by theelk801** [comment] 2021-01-22 21:10
duplicate of #7429

**Closed by theelk801** 2021-01-22 21:10 UTC
