### ISSUE TITLE
[VOW] Disturb-related bugs with Dawnhart Geist and Brine Comber

### ISSUE THREAD

**Issue by sprangg** [magefree/mage#9686] opened 2022-10-27 16:19 UTC
Tested [[Dawnhart Geist]] effect with a couple of disturb auras and it didn't trigger. It triggers ok from normally cast enchantments.

[[Brine Comber]] and its aura side don't trigger from disturb auras.

**Comment by awjackson** [comment] 2022-10-27 17:34
This is caused by the way we implement transforming spells partially as a continuous effect--it's split into `transformCardSpellStatic` which is not a continuous effect and which replaces the name, the supertypes and the abilities, and `transformCardSpellDynamic` which is a continuous effect and which replaces the color, types, subtypes, and replaces the abilities *again*. The problem is that the continuous effect is not created until the very end of the spell casting (after `super.activate()` returns) and that is too late for various trigger to see that the spell is an Enchantment Aura and not a creature.

@JayDi85 do you know why transforming spells is implemented in this strange half-and-half way? I don't see why it needs a continuous effect at all--if we can change the name and the supertype statically surely there's no problem with changing the other characteristics that way? The `Card` field of a Spell is a copy, so it's not like we're permanently modifying the original card.

**Comment by weirddan455** [comment] 2022-10-28 00:25
I'm not sure.  IIRC I put a PR in to implement Disturb but a lot of it got re-written by other devs before it got merged.  I believe the effects you mentioned have been around longer than that (before I started contributing to the project) and were used for cards like [[Delver of Secrets]].

It's possible we need to revisit how the Disturb mechanic is implemented since it gets transformed as it's cast rather than after it's already on the battlefield like the older transform cards were.  Maybe @theelk801 has some insight?

**Comment by awjackson** [comment] 2022-10-28 07:39
The methods I named are only used by Disturb. Transforming *permanents* use a completely different set of methods

**Comment by weirddan455** [comment] 2022-10-28 09:12
Oh I guess I'm mis-remembering.  It's been a while since I looked at that code.  I'll take a look later.

**Comment by weirddan455** [comment] 2022-10-28 20:13
There was discussion on this in #8201.  It sounds like the real solution to this is to refactor Disturb to work like MDFCs do.

**Comment by awjackson** [comment] 2022-10-28 20:28
We can't use the MDFC system as-is for TDFCs because the permanents would change UUIDs each time they transform and that really, really can't happen.

**Closed** 2023-09-15 21:56 UTC
Labels: bug
