### ISSUE TITLE
Spirit Mirror will only destroy its own tokens

### ISSUE THREAD

**Issue by WumpusEATSu** [magefree/mage#3436] opened 2017-05-25 20:35 UTC
Environment:
Local game - Constructed Freeform, Two Player Duel, Rated, Allow rollbacks, 1 Free Mulligan, 100% quit allow, Computer-mad opponent
Version 1.4.3
Decks attached

Repro:
1. Get Unnatural Selection and Spirit Mirror into play, with opponent's creatures on the battlefield, before Spirit Mirror has generated a token
2. Activate Unnatural Selection targeting an opponent's creature
3. Choose Reflection as the creature type
4. Try to activate the {0}: Destroy target Reflection ability of Spirit Mirror

Expected:
Should be able to activate it targeting any Reflection type creature

Actual:
Cannot activate the ability, and it will only be available to activate once a token is generated by Spirit Mirror, and then will only allow the player to target the token. This does not conform to the rules on the card.

**Comment by WumpusEATSu** [comment] 2017-05-25 20:37
To clarify, the deck with Spirit Mirror is "The Typist" and the opponent deck (could be any, but this is what I was using) was "Familiar Drums".
[Familiar Drums.dck.txt](https://github.com/magefree/mage/files/1030164/Familiar.Drums.dck.txt)
[The Typist.Deck.dck.txt](https://github.com/magefree/mage/files/1030165/The.Typist.Deck.dck.txt)

**Comment by drmDev** [comment] 2017-05-26 05:54
Think this is duplicate of https://github.com/magefree/mage/issues/3391

**Comment by drmDev** [comment] 2017-05-26 05:55
Confirmed it is duplicate. Fixed beyond 1.4.23v6 (in the next release, or test with latest from master on dev)

**Closed by drmDev** 2017-05-26 05:55 UTC
Labels: bug, duplicate

**Comment by WumpusEATSu** [comment] 2017-05-26 16:29
Yup, duplicate. LOL, #3391 was the issue I originally submitted to Reddit.
