### ISSUE TITLE
Can't cast Hogaak, Arisen Necropolis from the Command Zone

### ISSUE THREAD

**Issue by Kalosik00** [magefree/mage#6764] opened 2020-07-01 18:54 UTC
is:open Hello, can you fix BUG, i play Duel cmd and cant cast Hogaak from cmd zone. Thanks
<img width="1440" alt="Snímek obrazovky 2020-07-01 v 20 47 12" src="https://user-images.githubusercontent.com/67709059/86280925-fec8e780-bbdc-11ea-8484-73642c69482f.png">

**Comment by Zerrisx** [comment] 2020-07-01 19:11
Probable duplicate of #6698

**Comment by Zerrisx** [comment] 2020-07-05 04:25
I'm solidly convinced this is a duplicate, and this issue was fixed.

**Closed by Zerrisx** 2020-07-05 04:25 UTC

**Comment by Kalosik00** [comment] 2020-07-06 13:24
Hello, i tried today and isnt working yet - i dont think if is DELVE
mechanics, but i cant cast Hogaak. :-(

Regards

Miroslav

**Comment by Zerrisx** [comment] 2020-07-06 14:25
Yeah; the issue is fixed on beta servers but not yet on the release version.

**Comment by Kalosik00** [comment] 2020-07-06 14:34
Hi, how i can try it on BETA?
Regards

Miroslav

**Comment by Zerrisx** [comment] 2020-07-06 14:43
https://www.reddit.com/r/XMage/comments/a5mokm/new_testing_server_xmage_today_uma_cards_and/

Warning that the beta server has been a bit unstable lately; it goes down fairly regularly right now, so if your decks aren't loading properly, you can ask if anybody can restart it in the discord (https://discord.gg/PYpwTkc). But it should have all changes that have been coded, instead of just all changes up to the last time we commited a release version.

**Comment by Kalosik00** [comment] 2020-07-06 14:56
Perfect Thanks a lot

M
