### ISSUE TITLE
Hand and graveyard suddenly emptied

### ISSUE THREAD

**Issue by SpikesCafe-google** [magefree/mage#4586] opened 2018-03-08 16:57 UTC
![capture](https://user-images.githubusercontent.com/16656302/37164021-3a2ef0be-22c7-11e8-84ce-ecd78a56a6c6.PNG)

I had 2 cards in my hand and ~5 cards in my graveyard at the start of the computer opponent's turn. I resolved [Seance](https://magiccards.info/mm3/en/22.html) trigger on my upkeep and opted "no" on it. My opponent drew a card and cast Archwing Dragon, but as this happened my hand suddenly disappeared. The game lists my hand size as 2, though there are no cards. Also my graveyard now shows 0 cards and is empty.

This seems similar to another bug I've experienced where my library randomly disappears and I deck myself, though I don't have any screenshots of that.

**Comment by Zerrisx** [comment] 2020-07-02 21:32
Duplicate of #6738

**Closed by Zerrisx** 2020-07-02 21:32 UTC
Labels: bug
