### ISSUE TITLE
Rollback after tutoring causes infinite skipping for those who accept

### ISSUE THREAD

**Issue by zeflap** [magefree/mage#3866] opened 2017-08-20 23:51 UTC
Rollback after tutoring causes infinite skipping for those who accept

I had this happen a few times playing Commander

**Comment by zeflap** [comment] 2017-08-26 21:51
Just had this happen with a rollback after casting Fireball, so dialogs might be badness?

**Comment by LevelX2** [comment] 2017-08-26 23:46
I never was able to reproduce the problem. So the more detail how to reproduce the better.

**Comment by Zerrisx** [comment] 2020-07-17 22:20
Pretty sure this is a simple duplicate of #2072, specifically that rolling back in certain states results in the other players losing priority for the rest of the game.

**Closed by Zerrisx** 2020-07-17 22:20 UTC
Labels: not confirmed
