### ISSUE TITLE
Overloaded Cyclonic Rift - waiting for opponent whose session expired

### ISSUE THREAD

**Issue by spjspj** [magefree/mage#2423] opened 2016-10-04 14:06 UTC
![things21](https://cloud.githubusercontent.com/assets/16917728/19077207/631efd1c-8a97-11e6-8f60-4ae9584515c6.png)

**Comment by spjspj** [comment] 2016-10-04 14:16
I can attempt to look at :)

**Comment by spjspj** [comment] 2016-10-04 15:19
After the 10 minutes expired, there was the same thing (waiting).  Something about expired sessions vs just opponents who have conceded possibly.

**Comment by spjspj** [comment] 2016-10-07 14:09
Not having much luck with recreating this.  I changed the boot function from the 'Mage Server Console' to instead Expire a session, did so in a 3-way match for a human but the same behaviour didn't occur on overloading rift.

**Comment by fireshoes** [comment] 2016-10-07 15:10
I think it is something in general with a player leaving the game. I posted one in the forums about a conceded player's Confusion in the Ranks continuing to trigger.

**Comment by spjspj** [comment] 2016-10-16 12:53
Got this again
When the dude just leaves (doesn't concede) leads to the issue it seems like.

**Comment by Zerrisx** [comment] 2020-07-01 22:20
Duplicate of #4262

**Closed by Zerrisx** 2020-07-01 22:20 UTC
Labels: bug
