### ISSUE TITLE
Dread return doesnt flashback properly. 

### ISSUE THREAD

**Issue by Saigo1** [magefree/mage#3132] opened 2017-04-17 15:35 UTC
Was just playing on local server and tried to flashback Dread Return, it allowed me to sac the creatures but the spell did not resolve after the costs had been paid. It did not allow me to select a creature to return from yard to board.

**Comment by drmDev** [comment] 2017-04-17 15:39
Feel like this will be related to Battle Screech flashback issue #3125 . Creating test for Dread Return to duplicate issue.

**Comment by drmDev** [comment] 2017-04-17 15:53
Test added - same issue as Battle Screech. costs are paid, but card does not appear to be exiled nor does the flashback effect apply

**Comment by jeffwadsworth** [comment] 2017-04-17 23:01
So far, just Battle Screech and Dread Return are affected.  The other non-mana cost Flashback cards appear to work correctly.

**Comment by drmDev** [comment] 2017-04-18 01:43
Cabal Therapy has also been reported as affected as well. I presume anything like "Flashback: tap X" or "Flashback: sacrifice X" will be affected

**Comment by magenoxx** [comment] 2017-04-18 07:53
Could you please commit reproducing tests - probably I will be able to look into the issue

**Comment by magenoxx** [comment] 2017-04-18 09:02
Found root cause: the change that broke it was related to changes for Foretold: see AbilityImpl Line 296

**Comment by jeffwadsworth** [comment] 2017-04-18 10:04
https://github.com/magefree/mage/commit/2b08d5a101216f04efc0d89cd3a878513e7ebca5

**Comment by drmDev** [comment] 2017-04-18 11:53
@magenoxx Re: "Could you please commit reproducing tests - probably I will be able to look into the issue" did you see my commit here? `ut for #3132 confirming issue with dread return` there are two tests in one for Battle Screech and one for Dread Return

**Comment by jeffwadsworth** [comment] 2017-04-18 13:13
Ok, I used Stravant's suggested fix for this and it seems to work fine.  I am testing it a bit further to verify.

**Closed** 2017-04-18 17:09 UTC
Labels: bug
