### ISSUE TITLE
Skyhunter Strike Force 'Melee' is not function

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10098] opened 2023-03-05 23:47 UTC
As per the image below, melee is not triggering on either Skyhunter Strike Force or the creatures being granted melee.

![image](https://user-images.githubusercontent.com/82664393/222993010-1d115921-d82a-4dfc-ad6f-0836e8018333.png)

**Comment by Grath** [comment] 2023-03-20 03:26
Duplicate of #9848

**Closed** 2023-04-20 01:12 UTC
