### ISSUE TITLE
Myrkul, Lord of Bones

### ISSUE THREAD

**Issue by RyanTytka** [magefree/mage#9130] opened 2022-06-19 23:56 UTC
Myrkul, Lord of bones does not work. When a creature dies while he is on the battlefield, an error occurs and the game rolls back to the previous state with the effect being ignored.

**Comment by PurpleCrowbar** [comment] 2022-06-20 00:02
I believe this was fixed in 2cf3e0fd74f7b34c3fcffdf0cac2bca4db3196f6, can anyone confirm if the beta has been updated since then?

**Comment by PurpleCrowbar** [comment] 2022-06-20 00:16
Just confirmed that the fix above was committed a few hours after the beta was updated (i.e., is not live on xmage.today as of writing), and Myrkul is fixed on the most recent build. Closing as fixed

**Closed by PurpleCrowbar** 2022-06-20 00:16 UTC
