### ISSUE TITLE
Single creature attacking multiple planeswalkers

### ISSUE THREAD

**Issue by Perdogie** [magefree/mage#10275] opened 2023-04-25 15:45 UTC
Throughout match, singular creatures could target multiple planeswalkers during combat dealing damage equal to its power each instance. 
In this example, lone 2/1 token is attacking 4 planeswalkers attempting to deal 2 damage to each. Gideon had used first ability on previous turn to prevent all damage from that creature which successfully prevented all 4 instances of damage. Text states that the computer is attacking with 4 creatures although it's just 1, and yet Gideon is preventing all damage from the theoretical creatures that are attacking even though he can only prevent damage from 1. 
<img width="1920" alt="multiple attackers" src="https://user-images.githubusercontent.com/131274772/234330962-4aba3aa4-05d5-4095-8555-422c3b6293d6.PNG">
<img width="152" alt="1token" src="https://user-images.githubusercontent.com/131274772/234330985-2c4a25ef-0de3-4b30-a35f-8de6fdf80bdd.PNG">

**Comment by Grath** [comment] 2023-04-25 15:48
Duplicate of #7434

**Closed by Grath** 2023-04-25 15:48 UTC
