### ISSUE TITLE
Lotus Field + Blood Moon interaction bugged

### ISSUE THREAD

**Issue by D4RK0N3dev** [magefree/mage#10458] opened 2023-06-11 19:18 UTC
Hi, I spotted some bug. When Blood Moon is in the battlefield and Lotus Field enters it should enter untapped. Unfortunately I don't have logs from that siduation because Xmage crashed in the middle of the game.

**Comment by Grath** [comment] 2023-06-11 19:19
Duplicate of #4202

**Closed by Grath** 2023-06-11 19:19 UTC
