### ISSUE TITLE
Kaladesh booster generated without a rare

### ISSUE THREAD

**Issue by emerald000** [magefree/mage#2385] opened 2016-09-27 06:43 UTC
![Booster](http://i.imgur.com/kE3Ym5Z.jpg)

**Comment by LevelX2** [comment] 2016-10-02 23:29
Was not able to reproduce that problem yet.

**Comment by Simown** [comment] 2016-10-13 10:37
Can't reproduce it either. Generated ~10000 Kaladesh boosters and each had either a Mythic or a Rare. I'll look in to it a bit more this weekend.

**Comment by Zerrisx** [comment] 2020-07-01 22:47
Haven't seen or heard reports of this since in four years, closing as cannot reproduce.

**Closed by Zerrisx** 2020-07-01 22:47 UTC
Labels: not confirmed
