### ISSUE TITLE
Goad Effect NPE

### ISSUE THREAD

**Issue by alexander-novo** [magefree/mage#9891] opened 2023-01-20 19:20 UTC
```
Game exception occurred: java.lang.NullPointerException
Server version: 1.4.52-V2-beta3 (build: 2023-01-20 14:06)
mage.abilities.effects.common.combat.GoadAllEffect.apply(GoadAllEffect.java:68)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:115)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1167)
mage.game.GameState.applyEffects(GameState.java:659)
mage.game.GameImpl.applyEffects(GameImpl.java:1764)
mage.game.GameImpl.leave(GameImpl.java:3019)
mage.game.GameImpl.checkConcede(GameImpl.java:793)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:2026)
mage.game.GameImpl.playPriority(GameImpl.java:1530)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

Happened multiple times throughout the game after a player died after being targeted with the third mode on Maestros Confluence.

**Comment by alexander-novo** [comment] 2023-01-20 19:24
[[Maestros Confluence]]

**Comment by jdmagtibay** [comment] 2023-01-21 06:37
I have also a similar issue now on beta with [[Disrupt Decorum]]

`Game exception occurred: java.lang.NullPointerException
Server version: 1.4.52-V2-beta3 (build: 2023-01-20 14:06)
mage.abilities.effects.common.combat.GoadAllEffect.apply(GoadAllEffect.java:68)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:115)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1167)
mage.game.GameState.applyEffects(GameState.java:659)
mage.game.GameImpl.applyEffects(GameImpl.java:1764)
mage.game.GameState.processAction(GameState.java:648)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:2023)
mage.game.GameImpl.playPriority(GameImpl.java:1530)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
`

**Comment by PurpleCrowbar** [comment] 2023-01-23 21:30
Duplicate of #9604

**Closed by PurpleCrowbar** 2023-01-23 21:30 UTC
Labels: bug
