### ISSUE TITLE
[BUG] Public Enemy forces everyone to attack

### ISSUE THREAD

**Issue by NibiruMTG** [magefree/mage#9864] opened 2023-01-04 14:37 UTC
[[Public Enemy]] also forces the creature's controller to attack with everything. The bug occurred in 1v1 where it meant that that player attacked their opponent, haven't tested how it works in multiplayer.

**Comment by PurpleCrowbar** [comment] 2023-01-07 02:29
Duplicate of #9433

**Closed by PurpleCrowbar** 2023-01-07 02:29 UTC
