### ISSUE TITLE
Yuriko Commander ninjitsu still not working

### ISSUE THREAD

**Issue by GaleOfYork** [magefree/mage#5441] opened 2018-11-25 12:53 UTC
Yuriko's ninjitsu was somewhat patched back in August, but after the following updates, her ninjitsu is buggy and cannot be used again. You can get to the ability placement on the stack where mana is being paid for her ninjitsu, but it will fail to activate once the second mana is paid for.

**Comment by Zerrisx** [comment] 2020-06-26 22:27
Duplicate of #5237

**Closed by Zerrisx** 2020-06-26 22:27 UTC
