### ISSUE TITLE
The effect of Anger is sometimes applied to the wrong player

### ISSUE THREAD

**Issue by rockydirtbag** [magefree/mage#9352] opened 2022-08-04 21:12 UTC
[[Anger]] was in my graveyard and I had a Mountain on the battlefield, granting haste to my creatures. Then Anger was put onto the battlefield under an opponent's control (with [[Ghouls' Night Out]]) and later returned to my graveyard, but then my creatures didn't have haste anymore.

Some testing showed that the haste ability seems to be granted to the player under whose control Anger dies: If it is in my opponent's grave and I reanimate it and then sacrifice it, my creatures have haste (if I control a mountain), but not my opponent's. If it is in my grave and I do the same, my creatures have haste again.
Edit: If it leaves its owner's grave, no creatures have haste anymore.

This bug might also apply to the other incarnations of this cycle ([[Wonder]] etc). I haven't tried it though.

**Comment by Alex-Vasile** [comment] 2022-09-19 19:25
Duplicate of #5522

**Closed by Alex-Vasile** 2022-09-19 19:25 UTC
