### ISSUE TITLE
Blood sun and enters the battefield effects

### ISSUE THREAD

**Issue by Origraena** [magefree/mage#4440] opened 2018-01-24 11:36 UTC
Currently, if blood sun is on the battlefield, and a player puts a gemstone mine, it enters with counters, however, it should not.

**Comment by jeffwadsworth** [comment] 2018-01-25 02:25
The rule change from Sept 2017 affects more than just Blood Sun.  It has not been implemented yet.

https://magic.wizards.com/en/articles/archive/news/ixalan-comprehensive-rules-changes-2017-09-28

**Comment by GAMEster52** [comment] 2018-02-05 23:54
yeah i saw the same today. a land entered the battlefield tapped with blood moon on the battlefield. this needs an update.

**Comment by nstephenh** [comment] 2018-03-21 20:37
Any progress on this? It does seem like a lot of work, but its important to the game.

**Comment by Zerrisx** [comment] 2020-07-17 22:06
Duplicate of #4202

**Closed by Zerrisx** 2020-07-17 22:06 UTC
Labels: bug, cards
