### ISSUE TITLE
Blood Sun does not prevent lands from entering the battlefield tapped 

### ISSUE THREAD

**Issue by anguepa** [magefree/mage#10291] opened 2023-04-29 18:11 UTC
The rules of Blood Sun include the following:

_If a land has an ability that causes it to enter the battlefield tapped, it will lose that ability before it applies. The same is also true of any other abilities of a land that modify how it enters the battlefield or apply “as” it enters the battlefield, such as the first ability of Unclaimed Territory._

Nevertheless, lands like Rustvale Bridge and Lotus Field enter the battlefield tapped even when a Blood Sun is in play. This makes it essentially impossible to play any Blood Sun deck.

**Comment by xenohedron** [comment] 2023-04-29 18:14
Duplicate of longstanding issue #4202

**Comment by Grath** [comment] 2023-04-29 18:19
Duplicate of #4202 indeed.

**Comment by anguepa** [comment] 2023-04-29 18:22
Is this issue addressed on a card by card basis or is it simply something that is not expected to get fixed anytime soon due to its difficulty?

**Comment by anguepa** [comment] 2023-04-29 18:23
Is this issue something that is addressed on a card by card basis or is it a problem that is not expected to get fixed anytime soon?

**Comment by Grath** [comment] 2023-04-29 18:25
This is something that needs an engine-level fix (cards entering the battlefield can't "look ahead" to what they'll be like, for Blood Sun/Blood Moon, on the battlefield) that is not expected to get fixed anytime soon.

**Closed by Grath** 2023-04-29 18:25 UTC
