### ISSUE TITLE
Goblin Fire Fiend's "must block if able" ability sometimes doesn't work

### ISSUE THREAD

**Issue by goblin** [magefree/mage#2645] opened 2016-11-30 19:59 UTC
Hi,

I'm a noob player but it seems the Goblin Fire Fiend's "Defending player blocks Goblin Fire Fiend if able" ability didn't work.

Unfortunately the client has frozen before I could grab a screenshot so there's no log in it:
[http://i.imgur.com/dmimfIY.jpg](http://i.imgur.com/dmimfIY.jpg)

The Cytoplast Manipulator was put on the battlefield by the computer in his previous turn. I then cast Goblin Fire Fiend, it went in with Haste, the computer ('mad' with skill level 1) decided to put the counter on it (kinda crazy but it's level 1). I then attacked with the two creatures, and the computer took 2 damage from each, rather than having to block my Goblin.

**Comment by goblin** [comment] 2016-11-30 20:11
On my next attack, the Goblin Fire Fiend was blocked properly by a new, different creature with Summoning Sickness, so this is not trivially reproducible.

**Comment by goblin** [comment] 2016-11-30 21:12
That's on XMage 1.4.19V0 with Java 1.8.0_102

**Comment by goblin** [comment] 2016-12-02 19:51
I've reproduced this using a dummy 2-human-player game. During the declare blockers step, the blue player ('goblin') was able to select no blockers. Here's a better screenshot with a log:

[http://i.imgur.com/OyjK2yK.jpg](http://i.imgur.com/OyjK2yK.jpg)

**Comment by teagao** [comment] 2016-12-07 02:11
Can confirm, block is automatically selected, but if player clicks "undo", phases change w/o blockers assigned

**Comment by Zerrisx** [comment] 2020-06-26 22:40
Duplicate of #3729

**Closed by Zerrisx** 2020-06-26 22:40 UTC
Labels: bug

**Comment by goblin** [comment] 2020-06-27 10:16
But but but... I was first! ;-) #3729 is a duplicate of this, not the other way around ;-)
