### ISSUE TITLE
Copy/Paste does not work in XMage macOS

### ISSUE THREAD

**Issue by jborden** [magefree/mage#2993] opened 2017-03-19 21:13 UTC
I am unable copy a clipboard item to XMage in macOS. I cannot copy/paste a card name in the deck editor to search for cards, my password to login or a message to my opponent during a duel. 

```bash
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.3
BuildVersion:	16D32
```

**Comment by dalovar** [comment] 2018-03-11 05:19
This is should be reopened. I experienced the same problem and found out you need to use CTRL + C instead of CMD + C. However, ideally, all shortcuts to manipulate text should be using CMD instead of CTRL if xmage is running on OSX

**Comment by JayDi85** [comment] 2018-03-11 05:26
Java code example:
https://stackoverflow.com/questions/34767520/copy-paste-shortcuts-only-working-with-ctrl-key-in-osx-java-application

**Comment by Zerrisx** [comment] 2020-06-27 04:16
Duplicate of #2994

**Closed by Zerrisx** 2020-06-27 04:16 UTC
Labels: GUI, bug, linux / macos
