### ISSUE TITLE
trying to see the back of a meld card crash the game

### ISSUE THREAD

**Issue by copperfield42** [magefree/mage#9658] opened 2022-10-15 18:08 UTC
clicking the sun symbol
![image](https://user-images.githubusercontent.com/4504719/196000769-ada089e8-2730-4015-aca6-618c8a6008f2.png)

and then the moon symbol
![image](https://user-images.githubusercontent.com/4504719/196001099-32e07fd2-7fcc-4803-821e-ef89d34adb85.png)

crash the game
![image](https://user-images.githubusercontent.com/4504719/196001144-fa8f486e-49dd-4e18-b9bc-3d1982384aa0.png)

the client console show this

```
FATAL 2022-10-15 13:52:00,912 MAGE Client UI error                                                                       =>[Animation] EDTExceptionHandler.handle 
java.lang.NullPointerException
	at org.mage.card.arcane.CardPanel.toggleTransformed(CardPanel.java:869)
	at org.mage.card.arcane.MageLayer.toggleTransformed(MageLayer.java:367)
	at org.mage.card.arcane.Animation$3.update(Animation.java:179)
	at org.mage.card.arcane.Animation$1.run(Animation.java:52)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
FATAL 2022-10-15 13:52:08,232 Client error
                                                                              =>[AWT-EventQueue-0] CallbackClientImpl.handleException 
java.lang.ClassCastException: mage.view.CardView cannot be cast to mage.view.PermanentView
	at org.mage.card.arcane.CardPanel.getOriginalPermanent(CardPanel.java:832)
	at mage.client.game.BattlefieldPanel.update(BattlefieldPanel.java:159)
	at mage.client.game.PlayAreaPanel.update(PlayAreaPanel.java:522)
	at mage.client.game.GamePanel.updateGame(GamePanel.java:818)
	at mage.client.game.GamePanel.updateGame(GamePanel.java:713)
	at mage.client.game.GamePanel.pickAbility(GamePanel.java:1740)
	at mage.client.remote.CallbackClientImpl.lambda$processCallback$0(CallbackClientImpl.java:240)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

you can't do much more after, but you can concede but the screen remain in the game. 

You can return to the lobby(?) in the switch menu selecting "tables" 

![image](https://user-images.githubusercontent.com/4504719/196001614-b11cfe2f-11de-44e2-9229-9b21366b8f68.png)

and everything else seem to be normal, you can star a new game if you want, but the crashed game remains listed there and you can go and watch it if you want

**Comment by awjackson** [comment] 2022-10-15 18:12
Duplicate of https://github.com/magefree/mage/issues/9452

**Closed by awjackson** 2022-10-15 18:12 UTC
