### ISSUE TITLE
"All creatures must block {this} if able" is bugged

### ISSUE THREAD

**Issue by Zzooouhh** [magefree/mage#4496] opened 2018-02-07 11:47 UTC
I've attacked with Shinen of Life's Roar into an untapped Birds of Paradise, the opponent didn't tap it, and he could just cancel out of the block like no ability affected it.

**Comment by JayDi85** [comment] 2018-02-07 11:51
I've got likely error with computer -- it's not attacking, but must:

Trove of Temptation ability do not apply to computer and it do not attack, but must (AI have dino creature on battlefield)
5:50: Turn 17 computer (14 - 5)
5:50: computer draws a card
5:50: computer attacks with 0 creatures
5:50: Turn 18 JayDi (14 - 5)

**Comment by LevelX2** [comment] 2018-02-07 12:40
Maybe also related from forum:
https://www.slightlymagic.net/forum/viewtopic.php?f=70&t=21565&start=30#p222241

_Nature's Will triggers off combat damage, so you should have your lands untapped during End of Combat in case you wanted to do something to an attacking / blocking creature - but the trigger doesn't seem to be occurring until Main 2.

This was during a game of 6x CHK Sealed against a human opponent._

**Comment by JayDi85** [comment] 2019-04-28 05:25
`Trove of Temptation` AI problem related to `getApplicableRequirementEffects` -- computer code don't support `playerMustBeAttackedIfAble` restriction.

**Comment by JayDi85** [comment] 2019-04-28 06:02
@Zzooouhh 
Shinen of Life's Roar works fine with Birds of Paradise.

You attacked by Shinen of Life's Roar -- you can't cancel it, blockers is hardcoded:
![shot_190428_095349](https://user-images.githubusercontent.com/8344157/56859425-af18db80-699b-11e9-8042-55e307dbf609.png)

Opponent attacked by Shinen of Life's Roar -- you can't cancel blocks, opponent can't cancel it too:
![shot_190428_095703](https://user-images.githubusercontent.com/8344157/56859455-4716c500-699c-11e9-9248-246bf98653bd.png)

**Comment by jeffwadsworth** [comment] 2020-06-11 21:55
Is this fixed?  I tested many scenarios and it worked fine with mandatory blocking.  I will close this issue if no one responds.

**Comment by jeffwadsworth** [comment] 2020-06-11 21:56
![WorksFine](https://user-images.githubusercontent.com/1496996/84443057-7ae69580-ac04-11ea-9616-d53e585f72e0.jpg)

**Comment by Zerrisx** [comment] 2020-07-01 20:49
Is it possible this is a duplicate of #3729?

**Comment by Zerrisx** [comment] 2020-07-29 16:23
Cannot reproduce; this appears to be fixed.

**Closed by Zerrisx** 2020-07-29 16:23 UTC
Labels: bug, cards
