### ISSUE TITLE
Build error with Java 10.0: `com.sun.codemodel.CodeWriter` is missing

### ISSUE THREAD

**Issue by jthemphill** [magefree/mage#5345] opened 2018-09-28 04:30 UTC
I'm attempting to build Mage for the first time.

```
% java --version
java 10.0.1 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
% mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T11:33:14-07:00)
Maven home: /usr/local/Cellar/maven/3.5.4/libexec
Java version: 10.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
% mvn install > compile-output.txt
```

You can read the output [here](https://github.com/magefree/mage/files/2426756/compile-output.txt). Ultimately, it seems `com.sun.codemodel.CodeWriter` is missing.

**Comment by JayDi85** [comment] 2018-09-28 08:45
xmage support java 7 and 8

**Comment by allentiak** [comment] 2020-05-09 01:22
Is this still valid with Java 11+?

**Comment by Zerrisx** [comment] 2020-07-13 17:16
What's the state of this?  Is it no longer an issue, an FAQ, or a just a question that should be closed?

**Comment by JayDi85** [comment] 2020-07-13 17:26
Duplicate of #6197

**Closed by JayDi85** 2020-07-13 17:26 UTC
