### ISSUE TITLE
Infinite Loop prompt comes up too often at times not pertaining to a possible draw

### ISSUE THREAD

**Issue by MasN2** [magefree/mage#3397] opened 2017-05-19 22:27 UTC
https://snag.gy/sBlIYh.jpg

Heres the log:

6:07 PM: MasN has joined the game
:  Match score: omegaservo - 0 wins DeckHash: 5743927600810708457 MasN - 0 wins DeckHash: -1629653411785525923  Match is not rated You have to win 2 games to win the complete match  Game has started  
6:07 PM: MasN's library is shuffled
6:07 PM: omegaservo's library is shuffled
6:07 PM: omegaservo won the toss
6:07 PM: omegaservo chooses that he or she takes the first turn
6:07 PM: omegaservo draws seven cards
6:07 PM: MasN draws seven cards
6:07 PM: omegaservo keeps hand
6:07 PM: MasN keeps hand
6:07 PM: Turn 1 omegaservo (20 - 20)
6:07 PM: omegaservo puts Wandering Fumarole [8fe] from hand onto the Battlefield
6:07 PM: omegaservo plays Wandering Fumarole [8fe]
6:07 PM: omegaservo attacks with 0 creatures
6:07 PM: Turn 2 MasN (20 - 20)
6:07 PM: MasN draws a card
6:07 PM: MasN puts Blooming Marsh [6d9] from hand onto the Battlefield
6:07 PM: MasN plays Blooming Marsh [6d9]
6:07 PM: MasN casts Attune with Aether [037]
6:07 PM: MasN searches his or her library
6:07 PM: MasN puts a card from library into his or her hand
6:07 PM: MasN reveals Swamp
6:07 PM: MasN's library is shuffled
6:07 PM: MasN puts Attune with Aether [037] from stack into his or her graveyard
6:07 PM: MasN attacks with 0 creatures
6:07 PM: Turn 3 omegaservo (20 - 20)
6:07 PM: omegaservo draws a card
6:07 PM: omegaservo reveals Island
6:07 PM: omegaservo puts Port Town [3da] from hand onto the Battlefield
6:07 PM: omegaservo plays Port Town [3da]
6:07 PM: omegaservo attacks with 0 creatures
6:07 PM: Turn 4 MasN (20 - 20)
6:07 PM: MasN draws a card
6:08 PM: MasN casts Traverse the Ulvenwald [b82]
6:08 PM: omegaservo casts Anticipate [eac]
6:08 PM: omegaservo puts a card from library into his or her hand
6:08 PM: omegaservo puts a card from library to the bottom of his or her library
6:08 PM: omegaservo puts a card from library to the bottom of his or her library
6:08 PM: omegaservo puts Anticipate [eac] from stack into his or her graveyard
6:08 PM: MasN searches his or her library
6:08 PM: MasN puts a card from library into his or her hand
6:08 PM: MasN reveals Forest
6:08 PM: MasN puts Traverse the Ulvenwald [b82] from stack into his or her graveyard
6:08 PM: MasN's library is shuffled
6:08 PM: MasN puts Evolving Wilds [686] from hand onto the Battlefield
6:08 PM: MasN plays Evolving Wilds [686]
6:08 PM: MasN attacks with 0 creatures
6:08 PM: Turn 5 omegaservo (20 - 20)
6:08 PM: omegaservo draws a card
6:08 PM: omegaservo puts Inspiring Vantage [8fb] from hand onto the Battlefield
6:08 PM: omegaservo plays Inspiring Vantage [8fb]
6:08 PM: omegaservo attacks with 0 creatures
6:08 PM: MasN sacrificed Evolving Wilds [686]
6:08 PM: MasN activates: search your library for a basic land card and put it onto the battlefield tapped. Then shuffle your library. from Evolving Wilds [686]
6:08 PM: MasN searches his or her library
6:08 PM: MasN puts Mountain [bae] from library onto the Battlefield
6:08 PM: MasN's library is shuffled
6:08 PM: Turn 6 MasN (20 - 20)
6:08 PM: MasN draws a card
6:09 PM: MasN puts Blooming Marsh [b14] from hand onto the Battlefield
6:09 PM: MasN plays Blooming Marsh [b14]
6:09 PM: MasN casts Woodweaver's Puzzleknot [d0f]
6:09 PM: MasN puts Woodweaver's Puzzleknot [d0f] from stack onto the Battlefield
6:09 PM: Ability triggers: Woodweaver's Puzzleknot [d0f] - When Woodweaver's Puzzleknot [d0f] enters the battlefield, you gain 3 life and get    .
6:09 PM: MasN gains 3 life
6:09 PM: MasN attacks with 0 creatures
6:09 PM: Turn 7 omegaservo (23 - 20)
6:09 PM: omegaservo draws a card
6:09 PM: omegaservo puts Irrigated Farmland [8b6] from hand onto the Battlefield
6:09 PM: omegaservo plays Irrigated Farmland [8b6]
6:09 PM: omegaservo attacks with 0 creatures
6:09 PM: Turn 8 MasN (23 - 20)
6:09 PM: MasN draws a card
6:09 PM: MasN puts Swamp [0d1] from hand onto the Battlefield
6:09 PM: MasN plays Swamp [0d1]
6:09 PM: MasN attacks with 0 creatures
6:09 PM: Turn 9 omegaservo (23 - 20)
6:09 PM: omegaservo draws a card
6:09 PM: omegaservo plays Needle Spires [c48]
6:09 PM: omegaservo puts Needle Spires [c48] from hand onto the Battlefield
6:09 PM: omegaservo attacks with 0 creatures
6:10 PM: MasN sacrificed Woodweaver's Puzzleknot [d0f]
6:10 PM: MasN activates: you gain 3 life and get    . from Woodweaver's Puzzleknot [d0f]
6:10 PM: MasN gains 3 life
6:10 PM: Turn 10 MasN (26 - 20)
6:10 PM: MasN draws a card
6:10 PM: MasN puts Forest [c33] from hand onto the Battlefield
6:10 PM: MasN plays Forest [c33]
6:10 PM: MasN casts Aetherworks Marvel [7da]
6:10 PM: omegaservo casts Disallow [24d] targeting Aetherworks Marvel [7da] 
6:10 PM: Aetherworks Marvel [7da] is countered by Disallow [24d]
6:10 PM: MasN puts Aetherworks Marvel [7da] from stack into his or her graveyard
6:10 PM: omegaservo puts Disallow [24d] from stack into his or her graveyard
6:10 PM: MasN casts Attune with Aether [f6f]
6:10 PM: MasN searches his or her library
6:10 PM: MasN reveals Forest
6:10 PM: MasN puts a card from library into his or her hand
6:10 PM: MasN puts Attune with Aether [f6f] from stack into his or her graveyard
6:10 PM: MasN's library is shuffled
6:10 PM: MasN attacks with 0 creatures
6:10 PM: Turn 11 omegaservo (26 - 20)
6:10 PM: omegaservo draws a card
6:10 PM: omegaservo puts Wandering Fumarole [3e8] from hand onto the Battlefield
6:10 PM: omegaservo plays Wandering Fumarole [3e8]
6:10 PM: omegaservo attacks with 0 creatures
6:10 PM: Turn 12 MasN (26 - 20)
6:10 PM: MasN draws a card
6:10 PM: MasN puts Forest [673] from hand onto the Battlefield
6:10 PM: MasN plays Forest [673]
6:10 PM: MasN casts Liliana, Death's Majesty [7a8]
6:10 PM: omegaservo casts Negate [5c7] targeting Liliana, Death's Majesty [7a8] 
6:10 PM: Liliana, Death's Majesty [7a8] is countered by Negate [5c7]
6:10 PM: MasN puts Liliana, Death's Majesty [7a8] from stack into his or her graveyard
6:10 PM: omegaservo puts Negate [5c7] from stack into his or her graveyard
6:10 PM: MasN attacks with 0 creatures
6:11 PM: omegaservo activates: draw a card. from Censor [9ca]
6:11 PM: omegaservo discards Censor [9ca]
6:11 PM: omegaservo draws a card
6:11 PM: omegaservo casts Anticipate [eb8]
6:11 PM: omegaservo puts a card from library into his or her hand
6:11 PM: omegaservo puts a card from library to the bottom of his or her library
6:11 PM: omegaservo puts a card from library to the bottom of his or her library
6:11 PM: omegaservo puts Anticipate [eb8] from stack into his or her graveyard
6:11 PM: Turn 13 omegaservo (26 - 20)
6:11 PM: omegaservo draws a card
6:11 PM: omegaservo plays Island [7f2]
6:11 PM: omegaservo puts Island [7f2] from hand onto the Battlefield
6:11 PM: omegaservo attacks with 0 creatures
6:11 PM: Turn 14 MasN (26 - 20)
6:11 PM: MasN draws a card
6:11 PM: MasN casts Liliana, the Last Hope [357]
6:11 PM: omegaservo casts Glimmer of Genius [af4]
6:11 PM: omegaservo scries 2
6:12 PM: omegaservo puts a card from library to the top of his or her library
6:12 PM: omegaservo puts a card from library to the top of his or her library
6:12 PM: omegaservo draws two cards
6:12 PM: omegaservo puts Glimmer of Genius [af4] from stack into his or her graveyard
6:12 PM: MasN puts Liliana, the Last Hope [357] from stack onto the Battlefield
6:12 PM: MasN puts Hissing Quagmire [026] from hand onto the Battlefield
6:12 PM: MasN plays Hissing Quagmire [026]
6:12 PM: MasN activates: Up to one target creature gets -2/-1 until your next turn. from Liliana, the Last Hope [357]
6:12 PM: MasN attacks with 0 creatures
6:12 PM: Turn 15 omegaservo (26 - 20)
6:12 PM: omegaservo draws a card
6:12 PM: omegaservo puts Island [ba0] from hand onto the Battlefield
6:12 PM: omegaservo plays Island [ba0]
6:12 PM: omegaservo attacks with 0 creatures
6:12 PM: Turn 16 MasN (26 - 20)
6:12 PM: MasN draws a card
6:12 PM: MasN casts Bristling Hydra [54f]
6:13 PM: omegaservo casts Reduce [103] targeting Bristling Hydra [54f] 
6:13 PM: omegaservo puts Reduce [103] from hand into his or her graveyard
6:13 PM: MasN chooses to pay   to prevent the counter effect
6:13 PM: omegaservo casts Censor [46b] targeting Bristling Hydra [54f] 
6:13 PM: MasN puts Bristling Hydra [54f] from stack into his or her graveyard
6:13 PM: MasN chooses not to pay   to prevent the counter effect
6:13 PM: Bristling Hydra [54f] is countered by Censor [46b]
6:13 PM: omegaservo puts Censor [46b] from stack into his or her graveyard
6:13 PM: MasN activates: Up to one target creature gets -2/-1 until your next turn. from Liliana, the Last Hope [357]
6:13 PM: MasN attacks with 0 creatures
6:13 PM: Turn 17 omegaservo (26 - 20)
6:13 PM: omegaservo draws a card
6:13 PM: omegaservo attacks with 0 creatures
6:13 PM: Turn 18 MasN (26 - 20)
6:14 PM: MasN draws a card
6:14 PM: MasN activates: put the top two cards of your library into your graveyard, then you may return a creature card from your graveyard to your hand. from Liliana, the Last Hope [357]
6:14 PM: MasN puts Painful Truths [173] from library into his or her graveyard
6:14 PM: MasN puts Aether Hub [440] from library into his or her graveyard
6:14 PM: MasN puts Bristling Hydra [54f] from graveyard into his or her hand
6:14 PM: MasN casts Bristling Hydra [54f]
6:14 PM: omegaservo casts Torrential Gearhulk [471]
6:14 PM: omegaservo puts Torrential Gearhulk [471] from stack onto the Battlefield
6:14 PM: Ability triggers: Torrential Gearhulk [471] - When Torrential Gearhulk [471] enters the battlefield, you may cast target instant card from your graveyard without paying its mana cost. If that card would be put into your graveyard this turn, exile it instead. - targeting Disallow [24d] 
6:14 PM: omegaservo casts Disallow [24d] from graveyard targeting Bristling Hydra [54f] 
6:14 PM: MasN puts Bristling Hydra [54f] from stack into his or her graveyard
6:14 PM: Bristling Hydra [54f] is countered by Disallow [24d]
6:14 PM: omegaservo moves Disallow [24d] from stack to the exile zone
6:14 PM: MasN casts Vessel of Nascency [435]
6:14 PM: MasN puts Vessel of Nascency [435] from stack onto the Battlefield
6:14 PM: MasN activates: reveal the top four cards of your library. You may put artifact, creature, enchantment, land, or planeswalker card from among them into your hand. Put the rest into your graveyard. from Vessel of Nascency [435]
6:14 PM: MasN sacrificed Vessel of Nascency [435]
6:15 PM: MasN reveals Canyon Slough, Chandra, Flamecaller, Harnessed Lightning, Liliana, Death's Majesty
6:15 PM: MasN puts a card from library into his or her hand
6:15 PM: MasN puts Canyon Slough [60a] from library into his or her graveyard
6:15 PM: MasN puts Chandra, Flamecaller [c51] from library into his or her graveyard
6:15 PM: MasN puts Harnessed Lightning [bfc] from library into his or her graveyard
6:15 PM: MasN attacks with 0 creatures
6:15 PM: Turn 19 omegaservo (26 - 20)
6:15 PM: omegaservo draws a card
6:15 PM: omegaservo attacks with 1 creature
6:15 PM: Attacker: Torrential Gearhulk [471] (5/6) unblocked
6:15 PM: Torrential Gearhulk [471] deals 5 damage to Liliana, the Last Hope [357]
6:15 PM: Liliana, the Last Hope [357] is put into graveyard from battlefield
6:15 PM: Turn 20 MasN (26 - 20)
6:16 PM: MasN draws a card
6:16 PM: MasN casts Liliana, Death's Majesty [899]
6:16 PM: omegaservo casts Reduce [8ac] targeting Liliana, Death's Majesty [899] 
6:16 PM: MasN puts Liliana, Death's Majesty [899] from stack into his or her graveyard
6:16 PM: MasN chooses not to pay   to prevent the counter effect
6:16 PM: Liliana, Death's Majesty [899] is countered by Reduce [8ac]
6:16 PM: omegaservo puts Reduce [8ac] from hand into his or her graveyard
6:16 PM: MasN casts Servant of the Conduit [d95]
6:16 PM: MasN puts Servant of the Conduit [d95] from stack onto the Battlefield
6:16 PM: Ability triggers: Servant of the Conduit [d95] - When Servant of the Conduit [d95] enters the battlefield, you get    (two energy counters).
6:16 PM: MasN attacks with 0 creatures
6:16 PM: Turn 21 omegaservo (26 - 20)
6:16 PM: omegaservo draws a card
6:16 PM: omegaservo attacks with 1 creature
6:16 PM: Attacker: Torrential Gearhulk [471] (5/6) unblocked
6:16 PM: MasN loses 5 life
6:16 PM: Turn 22 MasN (21 - 20)
6:17 PM: MasN draws a card
6:17 PM: MasN plays Forest [00a]
6:17 PM: MasN puts Forest [00a] from hand onto the Battlefield
6:17 PM: MasN casts Noxious Gearhulk [e0c]
6:17 PM: omegaservo casts Torrential Gearhulk [a35]
6:17 PM: omegaservo puts Torrential Gearhulk [a35] from stack onto the Battlefield
6:17 PM: Ability triggers: Torrential Gearhulk [a35] - When Torrential Gearhulk [a35] enters the battlefield, you may cast target instant card from your graveyard without paying its mana cost. If that card would be put into your graveyard this turn, exile it instead. - targeting Reduce // Rubble [0d6] 
6:17 PM: omegaservo casts Reduce [103] from graveyard targeting Noxious Gearhulk [e0c] 
6:17 PM: omegaservo moves Reduce // Rubble [0d6] from stack to the exile zone
6:17 PM: MasN chooses to pay   to prevent the counter effect
6:18 PM: MasN puts Noxious Gearhulk [e0c] from stack onto the Battlefield
6:18 PM: Ability triggers: Noxious Gearhulk [e0c] - When Noxious Gearhulk [e0c] enters the battlefield, you may destroy another target creature. If a creature is destroyed this way, you gain life equal to its toughness. - targeting Torrential Gearhulk [a35] 
6:18 PM: MasN gains 6 life
6:18 PM: Torrential Gearhulk [a35] died
6:18 PM: MasN attacks with 0 creatures
6:18 PM: Turn 23 omegaservo (27 - 20)
6:18 PM: omegaservo draws a card
6:18 PM: omegaservo puts Plains [91a] from hand onto the Battlefield
6:18 PM: omegaservo plays Plains [91a]
6:18 PM: omegaservo casts Sphinx of the Final Word [97d]
6:18 PM: omegaservo puts Sphinx of the Final Word [97d] from stack onto the Battlefield
6:18 PM: omegaservo attacks with 1 creature
6:18 PM: Attacker: Torrential Gearhulk [471] (5/6) unblocked
6:18 PM: MasN loses 5 life
6:18 PM: Turn 24 MasN (22 - 20)
6:18 PM: MasN draws a card
6:18 PM: MasN casts Aetherworks Marvel [75d]
6:19 PM: MasN puts Aetherworks Marvel [75d] from stack onto the Battlefield
6:19 PM: MasN activates: Look at the top six cards of your library. You may cast a card from among them without paying its mana cost. Put the rest on the bottom of your library in a random order. from Aetherworks Marvel [75d]
6:20 PM: MasN puts a card from library to the bottom of his or her library
6:20 PM: MasN casts Arlinn Kord [33b]
6:20 PM: MasN puts a card from library to the bottom of his or her library
6:20 PM: MasN puts a card from library to the bottom of his or her library
6:20 PM: MasN puts a card from library to the bottom of his or her library
6:20 PM: MasN puts a card from library to the bottom of his or her library
6:20 PM: MasN puts Arlinn Kord [33b] from stack onto the Battlefield
6:20 PM: MasN casts Unlicensed Disintegration [0f3] targeting Torrential Gearhulk [471] 
6:20 PM: Torrential Gearhulk [471] died
6:20 PM: omegaservo loses 3 life
6:20 PM: MasN puts Unlicensed Disintegration [0f3] from stack into his or her graveyard
6:20 PM: MasN activates: create a 2/2 green Wolf creature token. Transform Arlinn Kord [33b]. from Arlinn Kord [33b]
6:20 PM: MasN creates a Wolf [dcb] token
6:20 PM: Arlinn Kord [33b] transforms into Arlinn, Embraced by the Moon [4ad]
6:20 PM: MasN attacks with 1 creature
6:20 PM: Attacker: Noxious Gearhulk [e0c] (5/4) unblocked
6:20 PM: omegaservo loses 5 life
6:20 PM: Turn 25 omegaservo (22 - 12)
6:20 PM: omegaservo draws a card
6:21 PM: omegaservo casts Pull from Tomorrow [12b]
6:21 PM: omegaservo announces a value of 4 for  
6:21 PM: omegaservo draws four cards
6:21 PM: omegaservo puts Pull from Tomorrow [12b] from stack into his or her graveyard
6:21 PM: omegaservo discards Inspiring Vantage [3cc]
6:21 PM: omegaservo casts Sweltering Suns [994]
6:22 PM: Sweltering Suns [994] deals 3 damage to Noxious Gearhulk [e0c]
6:22 PM: Sweltering Suns [994] deals 3 damage to Servant of the Conduit [d95]
6:22 PM: Sweltering Suns [994] deals 3 damage to Sphinx of the Final Word [97d]
6:22 PM: Sweltering Suns [994] deals 3 damage to Wolf [dcb]
6:22 PM: omegaservo puts Sweltering Suns [994] from stack into his or her graveyard
6:22 PM: Servant of the Conduit [d95] died
6:22 PM: Ability triggers: Aetherworks Marvel [75d] - Whenever a permanent you control is put into a graveyard from the battlefield, you get   (an energy counter).
6:22 PM: Wolf [dcb] died
6:22 PM: Ability triggers: Aetherworks Marvel [75d] - Whenever a permanent you control is put into a graveyard from the battlefield, you get   (an energy counter).
6:22 PM: omegaservo attacks with 0 creatures
6:22 PM: Turn 26 MasN (22 - 12)
6:22 PM: MasN draws a card
6:22 PM: MasN activates: Look at the top six cards of your library. You may cast a card from among them without paying its mana cost. Put the rest on the bottom of your library in a random order. from Aetherworks Marvel [75d]
6:23 PM: MasN casts Tireless Tracker [217]
6:23 PM: MasN puts a card from library to the bottom of his or her library
6:23 PM: MasN puts a card from library to the bottom of his or her library
6:23 PM: MasN puts a card from library to the bottom of his or her library
6:23 PM: MasN puts a card from library to the bottom of his or her library
6:23 PM: MasN puts a card from library to the bottom of his or her library
6:23 PM: MasN puts Tireless Tracker [217] from stack onto the Battlefield
6:23 PM: MasN casts Traverse the Ulvenwald [c08]
6:23 PM: MasN searches his or her library
6:23 PM: MasN reveals Evolving Wilds
6:23 PM: MasN puts a card from library into his or her hand
6:23 PM: MasN's library is shuffled
6:23 PM: MasN puts Traverse the Ulvenwald [c08] from stack into his or her graveyard
6:23 PM: MasN puts Evolving Wilds [067] from hand onto the Battlefield
6:23 PM: MasN plays Evolving Wilds [067]
6:23 PM: Ability triggers: Tireless Tracker [217] - Whenever a land enters the battlefield under your control, Investigate. (Create a colorless Clue artifact token onto the battlefield with " , Sacrifice this artifact: Draw a card.")
6:24 PM: MasN creates a Clue [444] token
6:24 PM: MasN sacrificed Evolving Wilds [067]
6:24 PM: Ability triggers: Aetherworks Marvel [75d] - Whenever a permanent you control is put into a graveyard from the battlefield, you get   (an energy counter).
6:24 PM: MasN activates: search your library for a basic land card and put it onto the battlefield tapped. Then shuffle your library. from Evolving Wilds [067]
6:24 PM: MasN searches his or her library
6:24 PM: MasN puts Forest [efd] from library onto the Battlefield
6:24 PM: MasN's library is shuffled
6:24 PM: Ability triggers: Tireless Tracker [217] - Whenever a land enters the battlefield under your control, Investigate. (Create a colorless Clue artifact token onto the battlefield with " , Sacrifice this artifact: Draw a card.")
6:24 PM: MasN creates a Clue [eee] token
6:24 PM: MasN sacrificed Clue [444]
6:24 PM: Ability triggers: Tireless Tracker [217] - Whenever you sacrifice a Clue, put a +1/+1 counter on Tireless Tracker [217].
6:24 PM: Ability triggers: Aetherworks Marvel [75d] - Whenever a permanent you control is put into a graveyard from the battlefield, you get   (an energy counter).
6:24 PM: MasN activates: draw a card. from Clue [444]
6:24 PM: MasN draws a card
6:24 PM: MasN sacrificed Clue [eee]
6:24 PM: Ability triggers: Tireless Tracker [217] - Whenever you sacrifice a Clue, put a +1/+1 counter on Tireless Tracker [217].
6:24 PM: Ability triggers: Aetherworks Marvel [75d] - Whenever a permanent you control is put into a graveyard from the battlefield, you get   (an energy counter).
6:24 PM: MasN activates: draw a card. from Clue [eee]
6:25 PM: MasN draws a card
6:25 PM: MasN casts Woodweaver's Puzzleknot [0b5]
6:25 PM: MasN puts Woodweaver's Puzzleknot [0b5] from stack onto the Battlefield
6:25 PM: Ability triggers: Woodweaver's Puzzleknot [0b5] - When Woodweaver's Puzzleknot [0b5] enters the battlefield, you gain 3 life and get    .
6:25 PM: MasN gains 3 life
6:25 PM: MasN activates: Arlinn, Embraced by the Moon [33b] deals 3 damage to target creature or player. Transform Arlinn, Embraced by the Moon [33b]. from Arlinn, Embraced by the Moon [33b] targeting omegaservo 
6:26 PM: omegaservo loses 3 life
6:26 PM: MasN has NOT confirmed that the game is a draw because of infinite looping.
6:26 PM: Arlinn, Embraced by the Moon [703] transforms into Arlinn Kord [33b]

**Comment by drmDev** [comment] 2017-05-20 02:12
Infinite loop handling is perhaps too liberal at this time. It would only be a draw if both players confirmed still.

**Comment by LevelX2** [comment] 2017-05-20 06:53
Is set to resolving >=15 stack abilities without ever having an empty stack in between. And never more than 3 on the stack at the same time.
We could add a check, that within this 15 last abilities no more than 3 different abilities are included. 
So the infinity loop counter would be reset, if an ability goes to stack, that was not one of the last 15 abilities.

**Comment by drmDev** [comment] 2017-05-21 15:35
Another report on this:
While playing against the computer, the game will randomly ask if i want to end the game because of an infinite loop. No, I don't want to end the game and I never know when the trigger comes up. I play a creature, Cloudstone curio trigger goes on the stack, I say "yes". Boom. Game over. Please don't.
-- from forums

Sounds like the computer automatically selects Yes to confirming draws as well. Makes sense, but we need better infinite loop -> draw detection in general.

Original issue was #3329 and commit 5ce813ad875b3d43e4c946c673c5a7b0fe9c61d5 was the initial handling for this detection.

**Comment by Zerrisx** [comment] 2020-06-28 01:07
Cannot reproduce; this appears to be fixed.

**Closed by Zerrisx** 2020-06-28 01:07 UTC
Labels: enhancement
