### ISSUE TITLE
Arna triggers causes a game error.

### ISSUE THREAD

**Issue by jdmagtibay** [magefree/mage#12517] opened 2024-06-24 04:44 UTC
Hi. So this game error occur. Possibly because of [[Arna Kennerüd, Skycaptain]] with [[Helm of the Host]] equipped to it and a bestowed creature. So there are two Arna triggers on attack because there were already two copies of Arna. But I think it gets a conflict with copying the bestowed Aura. Here's the game error report.

`Game error occurred: `

`java.lang.IndexOutOfBoundsException: Index: 0, Size: 0`
`Server version: 1.4.52-V8‐beta1 (build: 2024-06-06 19:44)`
`Stack trace:`
`java.util.ArrayList.rangeCheck(ArrayList.java:659)`
`java.util.ArrayList.get(ArrayList.java:435)`
`mage.game.permanent.token.TokenImpl.putOntoBattlefieldHelper(TokenImpl.java:435)`
`mage.game.permanent.token.TokenImpl.putOntoBattlefield(TokenImpl.java:254)`
`mage.game.permanent.token.TokenImpl.putOntoBattlefield(TokenImpl.java:218)`
`mage.abilities.effects.common.CreateTokenCopyTargetEffect.apply(CreateTokenCopyTargetEffect.java:273)`
`mage.cards.a.ArnaKennerudSkycaptainTargetEffect.apply(ArnaKennerudSkycaptain.java:114)`
`mage.abilities.AbilityImpl.resolveMode(AbilityImpl.java:218)`
`mage.abilities.AbilityImpl.resolve(AbilityImpl.java:202)`
`mage.abilities.TriggeredAbilityImpl.resolve(TriggeredAbilityImpl.java:205)`
`mage.game.stack.StackAbility.resolve(StackAbility.java:85)`
`mage.game.GameImpl.resolve(GameImpl.java:1766)`
`mage.game.GameImpl.playPriority(GameImpl.java:1689)`
`mage.game.turn.Step.priority(Step.java:67)`
`mage.game.turn.Phase.playStep(Phase.java:205)`
`mage.game.turn.Phase.play(Phase.java:91)`
`mage.game.turn.Turn.play(Turn.java:137)`
`mage.game.GameImpl.playTurn(GameImpl.java:1123)`
`mage.game.GameImpl.play(GameImpl.java:1030)`
`mage.game.GameImpl.start(GameImpl.java:1006)`
`mage.server.game.GameWorker.call(GameWorker.java:34)`
`mage.server.game.GameWorker.call(GameWorker.java:15)`
`java.util.concurrent.FutureTask.run(FutureTask.java:266)`
`java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)`
`java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)`
`java.lang.Thread.run(Thread.java:750)`

Thanks.

**Comment by JayDi85** [comment] 2024-06-24 05:15
Something wrong with miss aura’s targets:

![IMG_0555](https://github.com/magefree/mage/assets/8344157/0291cc61-74d6-40ad-a897-bf5edf9cad6e)

**Comment by xenohedron** [comment] 2024-08-27 03:36
duplicate of #12580

**Closed by xenohedron** 2024-08-27 03:36 UTC
Labels: bug
