### ISSUE TITLE
Skip to certain item on the stack

### ISSUE THREAD

**Issue by the-red-lily** [magefree/mage#9140] opened 2022-06-22 14:17 UTC
It would be nice to right click an item on the stack, and choose an option "Skip to this spell/ability/trigger". It would function the same as f10, but instead of skipping until stack is empty, it skips until the chosen item is on the top of the stack

**Comment by Alex-Vasile** [comment] 2022-06-22 16:26
Duplicate of #8672

**Closed by Alex-Vasile** 2022-06-22 16:26 UTC

**Comment by the-red-lily** [comment] 2022-06-22 16:50
Please re-open this suggestion, it is different from the mentioned one
