### ISSUE TITLE
Priority skipping - Turn ending 

### ISSUE THREAD

**Issue by SacnothXIII** [magefree/mage#6463] opened 2020-04-22 23:04 UTC
My turns are ending without me passing them. Whenever I cast a spell in second main phase, after it resolves, the turn ends. No matter I have skips cancelled.
I was using a mono Red deck with robber of the rich in play. I am not sure if that could have something to do.

**Comment by LevelX2** [comment] 2020-06-16 18:16
Did you use roll back function before the problem starts?

**Comment by Zerrisx** [comment] 2020-07-07 20:47
Duplicate of #4309

**Closed by Zerrisx** 2020-07-07 20:47 UTC
Labels: bug, not confirmed
