### ISSUE TITLE
Pauper deck legality check

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#1133] opened 2015-07-21 18:56 UTC
When joining a pauper match, your deck is flagged as not legal if you are using not common printings of a card, even though the card is legal for pauper (e.g. Darksteel Citadel@uncommon in M15, or Lotus Petal@mythic in From the Vault or uncommon in TPR). Having the deck check the rarity of any printing would allow users to select their preferred art and not have to swap card versions when the deck importer loads the wrong rarity.

**Comment by JayDi85** [comment] 2017-12-14 00:30
Duplicate of #4244

**Closed** 2020-06-24 20:14 UTC
Labels: enhancement
