### ISSUE TITLE
AI: Targets own creatures with Inevitable End

### ISSUE THREAD

**Issue by Meerkov** [magefree/mage#6363] opened 2020-03-22 06:31 UTC
Hi, I downloaded this today. Played a Sealed game vs AI, and it did this twice:
1) Play a creature
2) Play Inevitable End on it's own creature, even though I have a creature on the board.

This causes the AI to sacrifice it's own creature, when it actually could have targeted my creature. Playing this card on your own creature should only happen in very rare circumstances.

I'm assuming the card needs a flag set to mark it as bad to use on yourself, because the AI correctly doesn't use Mire Grasp (-3/-3) on it's own creatures.

**Comment by Zerrisx** [comment] 2020-07-14 16:13
Duplicate of #6838

**Closed by Zerrisx** 2020-07-14 16:13 UTC
Labels: AI
