### ISSUE TITLE
Gallia the Endless Dance isn't triggering card draw on attack

### ISSUE THREAD

**Issue by peter-thoenen** [magefree/mage#8746] opened 2022-03-06 22:15 UTC
Seen it a couple games now in my changeling deck (I only point that out in case it's the shapeshifter thing causing an issue).  The discard/draw not triggering on attack of 3 creatures (including Gallia, it's not three"other" creatures)

**Comment by awjackson** [comment] 2022-03-07 19:22
Duplicate of #8228

**Closed by awjackson** 2022-03-07 19:22 UTC
Labels: duplicate
