### ISSUE TITLE
Missing cards from "Exit from Exile" precon

### ISSUE THREAD

**Issue by drownik** [magefree/mage#11793] opened 2024-02-15 10:54 UTC
There are 2 missing cards for a basic precon: Exit from Exile.

The missing cards are:

Durnan of the Yawning Portal (https://www.moxfield.com/cards/dX69X-tlincalli-hunter)
Tlincalli Hunter (https://www.moxfield.com/cards/nay6x-durnan-of-the-yawning-portal)

Please, add them so I can test the deck properly.

**Comment by Grath** [comment] 2024-02-15 13:01
Duplicate of #8785

**Closed by Grath** 2024-02-15 13:01 UTC
