### ISSUE TITLE
Bestow: Automatically reattached to a Token creature after recast (attached to commander before)

### ISSUE THREAD

**Issue by dashosa** [magefree/mage#6592] opened 2020-05-30 20:52 UTC
Eidolon of Countless battles as a creature automatically reattached to my commander again after recast, but went under a token

![image](https://user-images.githubusercontent.com/63882410/83338803-c492c000-a295-11ea-9c6d-f42771699fde.png)

**Comment by LevelX2** [comment] 2020-06-16 13:09
How was the bestow card deattached from the commander (Oyobi, Who Split the Heavens I guess)?

**Comment by dashosa** [comment] 2020-06-21 04:56
T1. Oyobi Commander dies and returns to command zone. Eidolon detaches.
T3. Recast Oyobi, Eidolon reattaches itself to Oyobi but instead goes under one of Oyobi's tokens. However, it is Oyobi's P/T that are affected, not the token it is under. 

Thanks!

**Comment by Zerrisx** [comment] 2020-07-15 20:21
Duplicate of #5806

**Closed by Zerrisx** 2020-07-15 20:21 UTC
Labels: bug, not confirmed

**Comment by jeffwadsworth** [comment] 2022-01-11 20:44
#8157
