### ISSUE TITLE
Emrakul, the Promised End

### ISSUE THREAD

**Issue by FluxMaster** [magefree/mage#3763] opened 2017-07-30 22:41 UTC
So, I'm new to XMage, so I don't know if maybe I'm just unfamiliar with the interface, but I wan't able to play any of my opponent's cards after taking control of their next turn using Emrakul, The Promised End. I could look at their hand and advance through the phases, but it wouldn't let me cast their Call the Gatewatch. Any knowledge on what happened?

**Comment by emerald000** [comment] 2017-07-31 01:40
Were you playing against the AI? There are known issues with controlling an AI's turn. It should work correctly against a human player.

**Comment by Zerrisx** [comment] 2020-06-26 01:11
Duplicate of #2088

**Closed by Zerrisx** 2020-06-26 01:11 UTC
Labels: not confirmed
