### ISSUE TITLE
Firkraag, Cunning Instigator second ability doesn't work

### ISSUE THREAD

**Issue by EthanAlexanderAnderson** [magefree/mage#11457] opened 2023-11-23 23:14 UTC
(I'm a relatively new player so hopefully I'm not misunderstanding the ability)
Firkraag's second ability reads:
"Whenever a creature deals combat damage to one of your opponents, if that creature had to attack this combat, you put a +1/+1 counter on Firkraag, Cunning Instigator and you draw a card."
This doesn't seem to work whatsoever, regardless of the owner of the attacking creature.
[[Firkraag, Cunning Instigator]]

**Comment by permadeath** [comment] 2023-11-24 00:34
It depends on whether the effect that forced that creature to attack specifically pertained to that creature and not to its controller.  I definitely find it unclear the way it's written on the card, though.  Here's the additional rules text for this card:

> An ability that looks for whether a creature “had to attack” checks to see if there were any requirements to attack that were applying to that particular creature at the time it was declared as an attacker. If an ability required that creature's controller to attack rather than the creature itself (such as that of Trove of Temptation), that creature dealing combat damage won't cause Firkraag's last ability to trigger, even if it was the only creature that player could have attacked with to meet the requirement. 

The second ability only triggers if the creature that did damage to your opponent was itself specifically required to attack.  See, for example, [[Akoum Firebird]].  It has the ability, "Akoum Firebird attacks each combat if able."  So if it did damage to your opponent, Firkraag's ability would trigger.  However, if a creature did damage to your opponent because of [[Seeker of Slaanesh]], even if that creature was the only creature that could have attacked, that will not trigger the ability because it required that creature's controller to attack, not the creature itself.

**Comment by EthanAlexanderAnderson** [comment] 2023-11-24 00:45
Thanks for your reply permadeath 🙂
In this case the effect that is forcing the creatures to attack is Goad.
For context I'm playing the Draconic Dissent Precon deck

**Comment by permadeath** [comment] 2023-11-24 00:49
Ah, yes, I hadn't considered goad.  In that case, it sounds like a bug.

**Comment by xenohedron** [comment] 2023-11-24 05:04
Duplicate of #10606

**Closed by xenohedron** 2023-11-24 05:04 UTC
