### ISSUE TITLE
Goad rollback

### ISSUE THREAD

**Issue by catman123456** [magefree/mage#9847] opened 2023-01-01 01:00 UTC
attacked with [[Baeloth Barrityl, Entertainer]] and this happen.

Game exception occurred: java.lang.NullPointerException
Server version: 1.4.52-V2-beta2 (build: 2022-12-19 08:29)
mage.abilities.effects.common.combat.GoadAllEffect.apply(GoadAllEffect.java:68)
mage.abilities.effects.ContinuousEffectImpl.apply(ContinuousEffectImpl.java:115)
mage.abilities.effects.ContinuousEffects.apply(ContinuousEffects.java:1167)
mage.game.GameState.applyEffects(GameState.java:659)
mage.game.GameImpl.applyEffects(GameImpl.java:1764)
mage.game.GameImpl.leave(GameImpl.java:3019)
mage.game.GameImpl.checkConcede(GameImpl.java:793)
mage.game.GameImpl.checkStateAndTriggered(GameImpl.java:2026)
mage.game.GameImpl.playPriority(GameImpl.java:1530)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.CombatDamageStep.priority(CombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/64045003/210158442-53e480ca-1616-4a85-8ea6-c27d8fb09f60.png)

Got a game loss 

Game exception occurred: mage.MageException: Iterated player priority after game exception too often, game ends! Last error:
 null
Server version: 1.4.52-V2-beta2 (build: 2022-12-19 08:29)
mage.game.GameImpl.playPriority(GameImpl.java:1591)
mage.game.turn.Step.priority(Step.java:61)
mage.game.turn.FirstCombatDamageStep.priority(FirstCombatDamageStep.java:31)
mage.game.turn.Phase.playStep(Phase.java:184)
mage.game.turn.Phase.play(Phase.java:89)
mage.game.turn.Turn.play(Turn.java:132)
mage.game.GameImpl.playTurn(GameImpl.java:1056)
mage.game.GameImpl.play(GameImpl.java:966)
mage.game.GameImpl.start(GameImpl.java:942)
mage.server.game.GameWorker.call(GameWorker.java:34)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

**Comment by PurpleCrowbar** [comment] 2023-01-23 21:30
Duplicate of #9604

**Closed by PurpleCrowbar** 2023-01-23 21:30 UTC
Labels: bug
