### ISSUE TITLE
Monarch not lost

### ISSUE THREAD

**Issue by LegionedintheDamned** [magefree/mage#10344] opened 2023-05-10 03:36 UTC
As per the screenshot.  Faerie Vandal attacked me, and never actually gave DonJuba the Monarch.

![image](https://github.com/magefree/mage/assets/82664393/2bc43014-103b-4b28-a700-6dd63f0460b1)

**Comment by Grath** [comment] 2023-05-10 03:37
Duplicate of #10334

**Closed by Grath** 2023-05-10 03:37 UTC
