### ISSUE TITLE
Magus Lucea Kane copies spell for X=0 rather than X=same value

### ISSUE THREAD

**Issue by SmokinDice** [magefree/mage#11340] opened 2023-10-22 16:30 UTC
Magus Lucea Kane
as of the official ruling from wotc: 07.10.2022 | The copy has the same value of X.

This doesn't work on Xmage. in a game the copy always has a X value of 0 rather than X beeing the same value as you spent on the original spell.

**Comment by Susucre** [comment] 2023-10-22 16:38
duplicate of #9697

**Closed by Susucre** 2023-10-22 16:38 UTC
