### ISSUE TITLE
Bot uses Surgical Extraction wrong

### ISSUE THREAD

**Issue by m-terlinde** [magefree/mage#1227] opened 2015-08-27 03:05 UTC
Hello,

the bot "mad" uses the Surgical Extraction and most of the mil cards wrong.
The bot used the Extraction on his own graveyard, that's not the smartest way to cast it ;).
And he did some self-milling with some cards, witch I don't remember.

You can get some of the server logs here:
http://paste2.org/7zweK4cY
It's round about 10 %, it is a really huge log. I hope, that is enough (the original log is ~ 25 MB).

The bot used this deck:

```
4 [KTK:239] Polluted Delta
3 [ORI:257] Island
4 [M12:80] Visions of Beyond
4 [DKA:52] Thought Scour
1 [ORI:261] Swamp
3 [ISD:240] Ghost Quarter
4 [NPH:74] Surgical Extraction
3 [NPH:118] Noxious Revival
1 [SOK:164] Oboro, Palace in the Clouds
4 [ZEN:41] Archive Trap
4 [DGM:124] Breaking // Entering
4 [ZEN:47] Hedron Crab
4 [RAV:208] Glimpse the Unthinkable
4 [M14:75] Tome Scour
2 [SOM:226] Darkslick Shores
4 [ARB:26] Mind Funeral
3 [PLC:71] Extirpate
4 [GTC:249] Watery Grave
```

I hope, you can resolve that issue.

Do you need any further information?

Kind regards,
Matthias

**Comment by jeffwadsworth** [comment] 2015-08-27 03:34
Please do not expect brilliant play by the AI at this time.  It is essentially a test opponent until further notice.


________________________________

**Comment by m-terlinde** [comment] 2015-08-27 03:43
Okay, I'll remember that the next time. There were some smart actions in the play.
But to extract the own key cards could be fixed in future?

Am 27. August 2015 05:35:01 MESZ, schrieb Jeff Wadsworth <notifications@github.com>:

**Comment by Zerrisx** [comment] 2020-07-14 16:11
Duplicate of #6838

**Closed by Zerrisx** 2020-07-14 16:11 UTC
Labels: AI, bug
