### ISSUE TITLE
Crumbling Vestige hanging

### ISSUE THREAD

**Issue by fireshoes** [magefree/mage#2557] opened 2016-11-03 17:35 UTC
I played Crumbling Vestige, the etb trigger went on the stack but the Done button did not appear for me to pass priority to my opponent with the trigger on the stack. Rollbacked. Played again. Then Done button came up after the etb trigger, but did not appear for my opponent. Played another game against a different opponent and the second scenario occurred twice (with a rollback in between). No NPE or other error in my client log.

**Comment by LevelX2** [comment] 2016-11-06 22:07
Crumbling Vestige ETB effect is a triggered mana effect and does not go to the stack.
That was fixed with 1.4.18V0. Probably that also fixed that problem.
I was not able to reproduce a problem now.

**Comment by emerald000** [comment] 2016-11-06 23:16
Crumbling Vestige ETB is not a mana ability, since it doesn't trigger from a mana ability, but from the land entering the battlefield.

605.1b A triggered ability is a mana ability if it meets all of the following criteria: it doesn’t have a target, it triggers from the resolution of an activated mana ability (see rule 106.11a), and it could put mana into a player’s mana pool when it resolves.

**Comment by LevelX2** [comment] 2016-11-08 17:29
emerald000 thanks for pointing that out. 
Reverted the ability back to a non mana ability.

That problem sounds to me more than a network connection problem as a coding problem of the card.

**Closed** 2016-12-21 14:55 UTC
